charmverse/app.charmverse.io

components/common/Avatar.tsx, components/common/WorkspaceAvatar.tsx, components/common/page-layout/Sidebar.tsx, components/settings/Layout.tsx
You can actually click the workspace icons on the left and change the path now.
=> remove hard-coded workspace domain

components/common/RouteGuard.tsx, package-lock.json, package.json, pages/_app.tsx
I'm gonna merge this ASAP. Trying to figure out why production is throwing a javascript error (it's recursive so crashes the tab and is calling useState somewhere)
=> uninstall auth0 since we do not use it

components/editor/@bangle.io/extensions/inline-command-palette/InlineCommandPalette.tsx, components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx, components/editor/BangleEditor.tsx
Added two more items to be able to insert them from the inline palette.
=> Insert code and callout from inline palette

components/common/page-layout/PageLayout.tsx, components/common/page-layout/Sidebar.tsx, hooks/useUser.ts, hooks/useUser.tsx, lib/strings.ts, pages/[domain]/settings/account.tsx, pages/_app.tsx
Adding context to the useUser hook so that state can be picked up across the app.
@Devorein let me know if you have recommendations WRT organization. Should I put the context stuff in the /context folder? It seems like a lot of moving parts for a single feature.. but maybe it's easier to find things that way.
=> Allow setting username

components/common/page-layout/PageLayout.tsx, components/common/page-layout/Sidebar.tsx, hooks/usePages.ts
=> show page icon in sidebar and browser tab

components/editor/@bangle.io/extensions/inline-command-palette/InlineCommandPalette.tsx, components/editor/BangleEditor.tsx, components/editor/Editor.tsx, models/Page.ts, pages/[domain]/[pagePath].tsx, seedData.ts
The whole app might crash at first due to the page content being a markdown string rather than JSON schema. I would suggest removing the corresponding key from local storage completely.
=> Full support for json based content schema

components/common/page-layout/Sidebar.tsx
fixes https://github.com/charmverse/app.charmverse.io/issues/37
=> get rid of error from material ui modal

components/common/page-layout/PageNavigation.tsx, components/common/page-layout/Sidebar.tsx, theme/index.ts
=> Add ability to delete pages

components/common/Emoji.tsx, components/editor/@bangle.dev/react-emoji-suggest/emoji-suggest.ts, components/editor/Editor.tsx, theme/index.ts
Clicking on Add Icon inserts a random emoji, just like notion, and clicking on Add Cover inserts our wide logo
=> Button for adding icon and cover for a page

components/common/PopperPopup.tsx, components/editor/@bangle.dev/react-emoji-suggest/EmojiSuggest.tsx, components/editor/@bangle.dev/react-emoji-suggest/emoji-suggest.ts, components/editor/@bangle.dev/tooltip/suggest-tooltip.ts, components/editor/BangleEditor.tsx, components/editor/BlockQuote.tsx, components/editor/Editor.tsx, components/editor/Page/PageBanner.tsx
Hovering over the page cover control works fine now 😄
=> Fixed page cover controls now showing on hover

components/editor/@bangle.dev/react-menu/LinkSubMenu.tsx, components/editor/@bangle.dev/react-menu/MenuButtons.tsx, components/editor/FloatingMenu.tsx
=> Floating menu link added

components/editor/@bangle.dev/react-menu/Icon.tsx, components/editor/@bangle.dev/react-menu/LinkSubMenu.tsx, components/editor/FloatingMenu.tsx
=> Better floating menu

components/editor/@bangle.dev/base-components/image.ts, components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx, components/editor/BangleEditor.tsx, components/editor/BlockAligner.tsx, components/editor/ColumnBlock.tsx, components/editor/ColumnLayout.tsx, components/editor/FloatingMenu.tsx, components/editor/Image.tsx, components/editor/ImageSelector.tsx, components/editor/ResizeHandle.tsx, components/editor/Resizer.tsx, components/editor/Video.tsx, components/editor/VideoSelector.tsx, hooks/useResize.ts, package.json
There a quite a few commits for the multi-column feature in this PR. I've refactored quite a lot of things for that feature so it would not make much sense to discard those completely.
=> Full iframe video support 

components/editor/CharmEditor.tsx, components/editor/Editor.tsx
=> Added placeholder for empty editor

charmClient.ts, components/bounties_v2/Bounty.tsx, components/bounties_v2/BountyBadge.tsx, pages/[domain]/bounty/[bountyId].tsx, pages/api/bounties/[id]/index.ts
Provide a bounty component that can display details of a bounty, and link to it
=> Bounty badge

components/databases/focalboard/src/components/calculations/calculations.ts, components/databases/focalboard/src/components/cardDetail/comment.test.tsx, components/databases/focalboard/src/components/properties/dateRange/dateRange.tsx, components/databases/focalboard/src/utils.ts, components/databases/focalboard/src/widgets/editableDayPicker.tsx, package-lock.json, package.json
This was being used in Focalboard.. i didn't test but pretty sure this will decrease our file size a good amount
=> remove moment date library

.eslintrc.json, components/common/page-layout/Header.tsx, components/editor/Editor.tsx, lib/utilities/debounce.ts, lib/utilities/debouncePromise.ts, pages/[domain]/[pageId].tsx
I picked 500ms as an arbitrary number, open to suggestions
=> Debounce edits on the page editor

components/common/page-layout/Header.tsx, components/common/page-layout/ShareButton.tsx, theme/index.ts
=> Copy Share dropdown UI from Notion

components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx, components/editor/CharmEditor.tsx, components/editor/Quote.tsx, theme/index.ts
=> Block quote

.eslintrc.json, components/settings/TokenGates.tsx, pages/_app.tsx, pages/api/token-gates/[id]/verify.ts, theme/lit-modal/styles.scss, theme/lit-modal/theme.ts, theme/styles.scss
=> fix dark mode for Lit popup

charmClient.ts, components/common/page-layout/ShareButton.tsx, components/databases/DatabasePage.tsx, components/databases/focalboard/src/components/viewHeader/viewHeader.tsx, pages/[domain]/[pageId].tsx, pages/api/blocks/views/[pageId]/index.ts, pages/api/public/view/[id]/index.ts, pages/share/view/[sharedViewId].tsx
Share specific focalboard views
=> Enforce board view

components/common/page-layout/ShareButton.tsx, pages/[domain]/[pageId].tsx
Simplifies the sharing of a board
All links now take a viewId
=> Share board view

package-lock.json, package.json
=> update lit modal

components/bounties/ApplicationEditorForm.tsx, components/bounties/BountyPaymentButton.tsx, components/editor/CryptoPrice.tsx, pages/[domain]/bounty/[bountyId].tsx
-- Show errors from the payments butt on to user (see screenshot)
-- we were not passing the token for bounties.. only supported ETH!
=> display errors from bounty payment button

components/common/RouteGuard.tsx, components/common/page-layout/Sidebar.tsx, components/login/LoginPageContent.tsx, components/signup/SignupForm.tsx, hooks/useSpaces.tsx, hooks/useUser.tsx, lib/spaces/index.ts, next.config.js, pages/[domain]/index.tsx, pages/createWorkspace.tsx, pages/index.tsx, pages/join.tsx, pages/login.tsx
Test Cases to try:
Existing user:
- Log out of Metamask and back in. Should take you to the wallet connect screen and then automatically to your workspace
User with multiple accounts:
- Try switching accounts. Right now I think we'll take you to the /join page... i think we need some UI way of getting to your own workspaces (maybe a link at top left?), or maybe we should be smarter and check if the new address has its own spaces to go to?
New user
- Try using an address that's never had a profile, we should send you to the /signup page to either create or join a new workspace
=> simplify authentication

components/common/RouteGuard.tsx, pages/[domain]/[pageId].tsx
Fix the sharing of a public resource
=> Fix redirect for public pages

components/common/RouteGuard.tsx, components/common/errors/ErrorPage.tsx, pages/[domain]/[pageId].tsx
=> show 404 page when using an invalid url

connectors.ts, pages/[domain]/bounties/[bountyId].tsx
- Fixes the auto-generated blockchain explorer link
- Wraps the text for long error messages in bounty
=> Erc error display

components/bounties/BountyEditorForm.tsx
Display custom tokens in the bounty list again
=> Display custom tokens

components/settings/PaymentMethods/components/PaymentMethodList.tsx
=> make token symbols visible

components/common/Emoji.tsx, components/common/page-layout/PageNavigation.tsx, components/editor/Editor.tsx, lib/notion/importFromWorkspace.ts
=> add support for images as page icons

components/databases/focalboard/src/components/cardDialog.tsx, components/databases/focalboard/src/components/centerPanel.scss, components/databases/focalboard/src/components/gallery/galleryCard.tsx, components/databases/focalboard/src/components/kanban/kanbanCard.tsx, components/databases/focalboard/src/components/table/horizontalGrip.scss, components/databases/focalboard/src/components/table/horizontalGrip.tsx, components/databases/focalboard/src/components/table/table.scss, components/databases/focalboard/src/components/table/table.tsx, components/databases/focalboard/src/components/table/tableHeader.tsx, components/databases/focalboard/src/components/table/tableHeaders.tsx, components/databases/focalboard/src/components/table/tableRow.tsx, components/databases/focalboard/src/components/table/tableRows.tsx, components/editor/CharmEditor.tsx, hooks/useEffecientDragLayer.ts, package-lock.json, package.json
- make the rows go full-width
- be able to add new columns from table view
- performance improvement for resizing columns
- fix links when copying cards
=> UX improvement for focalboard

prisma/migrations/20220324212102_change_is_admin_flag/migration.sql, prisma/schema.prisma, scripts/setAdminStatus.ts
Script for adding isAdmin flag to workspace creators
=> Add script for updating isAdmin status

components/editor/CharmEditor.tsx, components/editor/NestedPage.tsx, components/editor/ResizableIframe.tsx, theme/@bangle.dev/styles.scss
- different bullets for nested list items
- fix max width for videos, and also saving the updated width
- added a few more pixels of vertical spacing around nested pages and code blocks - the height of a row should be 32px, with 3px padding on top and bottom. Nested pages was only 30px
=> Updates to styling

components/common/CreateSpaceForm.tsx, prisma/migrations/20220328205159_spacerole_id/migration.sql, prisma/migrations/20220328205241_spacerole_id/migration.sql, prisma/schema.prisma, scripts/assignDefaultSpaceRoleIDs.ts
=> Make space ID mandatory in spaceRoles

pages/[domain]/[pageId].tsx
Fix sharing of public pages now that we use permissions
=> Fix public page sharing

components/invite/InviteLinkPage.tsx, components/invite/InviteLinkPageError.tsx, components/invite/components/CenteredBox.tsx, pages/[domain]/settings/contributors.tsx, pages/invite/[inviteCode].tsx
**Session Exist**
1. We get the user from the session. So no matter which wallet address you switch to it won't have any effect on the invite flow. We use the user from the session
2. After a successful discord connect, we log you as that user so clicking on accept Invite would add that user to the workspace
**Session Doesn't Exist**
1. Changing the wallet address will have an impact as before accepting the invite we create the user with that account (it won't create one if a user with that wallet address already exists and log you as that user)
2. If you connect to discord we fallback to **Session Exist**
=> Connect discord for invite page

components/[pageId]/BoardPage/BoardPage.tsx, components/common/BoardEditor/focalboard/src/components/cardDialog.tsx, components/common/BoardEditor/focalboard/src/components/rootPortal.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButton.tsx, components/common/NewPageMenu.tsx, components/common/PageLayout/components/AddNewCard.tsx, components/common/PageLayout/components/PageNavigation.tsx
1. Database pages shouldn't have nested pages (Something that notion does)
2. Click on + Icon creates a card
3. After creating the card its shown on a dialog
=> Disable creating nested pages for boards

pages/api/spaces/[id]/pages.ts
Only show the pages a user has access to
=> Return only pages a user has access to

components/common/form/InputSearchContributor.tsx
fix for the default value not appearing in input
=> set controlled value for contributor input

components/common/BoardEditor/focalboard/src/components/cardDialog.tsx, components/common/PageLayout/components/PageNavigation.tsx
proposed fixes for the comments i left
=> Notion import v4 matt

components/common/PageLayout/components/Account/components/AccountModal/AccountModal.tsx, components/settings/roles/components/ImportDiscordRolesButton.tsx, components/settings/workspace/ImportNotionWorkspace.tsx, lib/middleware/onError.ts
i noticed the error log is not showing the proper error anymore. i didn't test this, it also looks like we are now sending "message" instead of "error" property to the front-end. but i dont think we have updated all our front-end to look for that?
=> fix error logging server-side

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/InlineCharmEditor.tsx, components/common/CharmEditor/components/@bangle.dev/react-menu/Menu.tsx, components/common/CharmEditor/components/PageThread.tsx, components/common/CharmEditor/components/inlineComment/InlineComment.components.tsx, components/common/PageLayout/components/Header/Header.tsx, components/common/form/InputSearchContributor.tsx, hooks/useThreads.tsx, theme/@bangle.dev/styles.scss
- mostly CSS changes
- put the comment actions under a popup menu
=> Inline comments matt

pages/[domain]/bounties/[bountyId].tsx
This PR makes a bounty deletable whatever the status.
It includes a context-dependant warning message if the bounty is not open.
=> Make bounty deletable in all cases

adapters/litProtocol/hooks/useLitProtocol.tsx, components/common/Modal/ErrorModal.tsx, components/common/Modal/Modal.tsx, components/common/Modal/SuccessModal.tsx, components/common/Modal/index.tsx, components/common/TokenGateForm.tsx, components/settings/token-gates/TestConnectionModal.tsx, components/settings/token-gates/TokenGates.tsx, components/settings/token-gates/TokenGatesTable.tsx, lib/token-gates/index.ts, lib/token-gates/token-gates.ts, lit-js-sdk.d.ts, pages/join.tsx
I thought we needed to use the correct chain when verifying Lit Protocol, but it looks we can just use the chain the user is connected to. This is way more use-friendly and is fixing an issue with POAP where we couldn't tell the chain.
=> Token gate fix

components/common/BoardEditor/focalboard/src/components/addViewMenu.tsx
Simple solution but was a lot hard to find. We just needed to add the cardOrder whenever a view is created, so unfortunately for the existing views, it won't work.
=> Fixed inserting table row at top

components/[pageId]/DocumentPage/components/PageDeleteBanner.tsx, components/common/Modal/Modal.tsx, components/common/PageLayout/components/TrashModal.tsx, theme/@bangle.dev/styles.scss
- more room for scrollable area
- used MenuItem + next/link components so you can click the whole row to navigate, and it highlights on hover
=> UI updates to trash modal

components/settings/token-gates/TokenGates.tsx
=> add copy to describe token gates

components/bounties/[bountyId]/BountyDetails.tsx, pages/[domain]/bounties/[bountyId].tsx
`ScrollabelWindow` needs to be at the top. All it does is set flex-grow to 1, so it needs ot be the direct child of PageLayout
We probably should make this part of Pagelayout, but i think some pages need to not have it.
=> make it so you can scroll the page on bounty pages

components/common/CharmEditor/components/CryptoPrice.tsx, components/common/CoinLogoAndTicker.tsx, lib/tokens/tokenData.ts
Added logo to the crypto price module.
=> Added crypto logo to price module

components/bounties/BountyList.tsx
When navigating to and from the bounty filter, the last state will be saved
=> Persist bounty filter state

lib/permissions/pages/__tests__/page-permission-compute.spec.ts, lib/permissions/pages/index.ts, lib/permissions/pages/page-permission-compute.ts, testing/setupDatabase.ts
This PR fixes the computeUserPage permissions function and restores their rights to administrators
=> Fix admin permissions

components/common/Avatar.tsx, components/common/AvatarWithIcons.tsx, components/common/CreateSpaceForm.tsx, components/settings/workspace/LargeAvatar.tsx, pages/[domain]/settings/workspace.tsx
Changes: 
- vertical align icons in overlay
- remove the outline for avatar image
=> Bugfixes for workspace avatar image

components/settings/roles/components/GuildsAutocomplete.tsx, components/settings/roles/components/ImportGuildRolesMenuItem.tsx, lib/guild-xyz/server/updateGuildRolesForUser.ts, lib/roles/createRoles.ts
1. Fixed auto guild imported roles un/assignment
2. Detailed Guild Autocomplete with more metadata (also virtualization added for improved performance)
=> Fixed auto guild imported roles un/assignment

components/bounties/components/BountyCard.tsx
Tried it out in all these combinations
1. Long title long description (truncated to 120 letters)
2. Long title short description
3. Long title No description
4. Short title No description
5. Short title long description
6. Short title short description
=> Uniform height bounty card

charmClient.ts, components/[pageId]/BoardPage/BoardPage.tsx, components/common/BoardEditor/focalboard/src/components/cardDialog.tsx, components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, hooks/usePages.tsx, lib/pages/addPage.ts, pages/api/pages/[id]/index.ts
I Also sped up creating a page. Deployed to staging for your convenience! https://pr-491-faster-cards.charmverse.co/login
=> speed up time to create a card

components/common/BoardEditor/focalboard/src/store/cards.ts
We should be deleting cards with their board... but this seems to work for now!
=> check that boardPage exists when loading cards

components/common/PageLayout/PageLayout.tsx, components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/PageTitleWithBreadcrumbs.tsx, components/profile/components/ProfileLayout.tsx, components/profile/tasks/GnosisTasksList.tsx, components/profile/tasks/IntegrationCard.tsx, components/profile/tasks/TasksPage.tsx
=> Nexus tasks layout matt

components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Sidebar/Workspaces.tsx, components/profile/components/NexusPageTitle.tsx, components/profile/integrations/IntegrationsPage.tsx, components/profile/tasks/GnosisTasksList.tsx, components/profile/tasks/TasksPage.tsx, components/profile/tasks/TasksPageHeader.tsx, pages/profile/public.tsx
- re-enable the link to nexus page
- add a consistent header/title on each nexus page to facilitate navigation
- Hide more information for the task header on mobile:
=> Clean up nexus header

components/common/PageLayout/components/Header/snapshot/PublishToSnapshot.tsx, components/common/PageLayout/components/Header/snapshot/PublishingForm.tsx, components/common/form/InputGeneratorText.tsx
Related [card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=c0659288-95de-451c-bc56-95a315e399fc)
=> Small changes for snapshot modal ui

.vscode/settings.json, components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailContentsUtility.test.ts, components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailContentsUtility.ts, lib/browser.ts, lib/middleware/requireKeys.ts, package-lock.json, package.json
Released May 24: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/
=> update typescript to 4.7

components/common/PageLayout/components/Header/PageTitleWithBreadcrumbs.tsx
forgot to update this when we moved the paths
=> hide page title for nexus

components/common/PageLayout/components/Account/Account.tsx, components/profile/components/UserDetails.tsx
The top right corner username should be correct.
=> Fix for displayed username consistency

background/cron.ts, lib/emails/templates/components/EmailWrapper.tsx, lib/emails/templates/theme/styles.ts, scripts/sendNotifications.ts, theme/index.ts
The button HTML was being sent correctly but it was not visible in Gmail. I guess this may be related to a broken 'font-family' produced by react-mjml. There seems to be a bug when defining it as a global attribute, but doing it in the CSS works fine (probably it is injected by MJML and not react-mjml)
=> Fix buttons not appearing in the email

pages/api/profile/details.ts
The information is now persisted when first saving on user details.
=> Add details when creating the user details

charmClient.ts, components/profile/components/PoapSection.tsx, components/profile/components/UserDetails.tsx, components/profile/components/UserPathModal.tsx, pages/api/profile/checkPathAvailability.ts
=> Validate your nexus path in realtime

pages/api/aws/s3-upload.ts
i figure the simplest solution is to strip out the "+", it turns out we're doing the same for whitespace
=> fix image upload with + character

components/common/BoardEditor/focalboard/src/mutator.ts
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=2040a53e-b85b-4337-b2d3-7c2f401a7bf5
=> Include page title and icon when duplicating a card

components/bounties/[bountyId]/components_v3/BountyHeader.tsx, components/bounties/[bountyId]/components_v3/BountySubmissions.tsx, components/bounties/components/BountyStatusBadge.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.scss, components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx, components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx, pages/_app.tsx, theme/cssVariables.ts
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=2db5f5fd-9596-4249-8b58-87f3d08a82e3
- there's some cleanup in the bounty code to remove React warnings
=> Clean up task UI

pages/api/telegram/connect.ts
Fix for when a telegram user does'nt hvae a photo on their profile
I didn't fix it because i don't know what to look for, but in the future we should not assume an error in try/catch is for a certain reason... in this case we're falsely telling the user another account is already connected, but it was due to the photo upload to s3 instead. it would be better to just say 'something went wrong'
=> handle telegram connect when user has no avatar

db.ts, jest.config-server.ts, jest.setup.js, jest.setup.ts, next.config.js, package-lock.json, package.json, testing/createJestConfig.ts, testing/setupDatabase.ts
Also fixes 'too many open connections' error from Prisma :)
=> fix memory issues when running tests

components/bounties/BountyList.tsx
Better UI for this [card](https://app.charmverse.io/charmverse/page-8094940378450526)
=> Add title for video, hide bounty filters when no bounties exist

charmClient.ts, components/bounties/[bountyId]/components_v3/BountySubmissions.tsx, components/bounties/[bountyId]/components_v3/SubmissionEditorForm.tsx, components/bounties/components/BountySubmissionContent.tsx, lib/applications/actions/__tests__/createSubmission.spec.ts, lib/applications/actions/__tests__/updateSubmission.spec.ts, lib/applications/actions/createSubmission.ts, lib/applications/actions/updateSubmission.ts, lib/applications/interfaces.ts, lib/transactions/__tests__/createTransaction.spec.ts, lib/utilities/types.ts, pages/api/bounties/[id]/index.ts, testing/generate-stubs.ts
turns out we were not passing back the wallet address from the form
=> require and save wallet address for bounty submissions

components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx, components/common/PageLayout/components/Account/components/NetworkModal/components/NetworkButton/NetworkButton.tsx, connectors.ts, lib/tokens/tokenData.ts
=> fix logos on network modal

components/profile/PublicProfile.tsx, components/profile/components/PoapSection.tsx, components/profile/components/UserDetails.tsx, lib/middleware/errors.ts, lib/session/config.ts, lib/utilities/errors/errors.ts, pages/api/profile/poaps.ts
- cleans up the code around useSWR 
- we should never rely on 'req.session.user' to be up-to-date. We really should just replace this with a userId
=> clean up swr + dont use user session for data

components/common/PageLayout/components/Header/PageTitleWithBreadcrumbs.tsx, components/nexus/components/NexusPageTitle.tsx, pages/integrations.tsx, pages/nexus.tsx, pages/profile.tsx
this is just to see how it look sif we use breadcrumbs for nav like we do for the rest of the site
=> Use breadcrumbs for nexus navigation

charmClient.ts, components/common/Snackbar.tsx, components/nexus/TasksPage.tsx, components/profile/PublicProfile.tsx, components/profile/components/AggregatedData.tsx, jest.config.ts, lib/applications/__tests__/getCompletedApplicationsOfUser.spec.ts, lib/applications/getCompletedApplicationsOfUser.ts, lib/deepdao/__tests__/getAggregatedData.spec.ts, lib/deepdao/getAggregatedData.ts, lib/deepdao/getParticipationScore.ts, lib/deepdao/interfaces.ts, pages/_app.tsx, pages/api/dashboard/[userId]/index.ts, pages/api/public/profile/[userPath]/aggregate.ts
Basic deepdao integration for fetching three aggregated data from their platform,
1. proposals
2. votes
3. daos
We also fetch the total number of completed applications. [Here](https://www.loom.com/share/3a14e963f1764a02adcaf91d0353ed9f) is a loom recording on how the UI looks
=> Basic deepdao integration to display aggregated data

lib/permissions/pages/actions/__tests__/upsert-permission.spec.ts, lib/permissions/pages/actions/upsert-permission.ts
Ensures that a page permission can only be assigned to:
- Space => Same space as the page
- Role => A role created in same space as page
- User => A user who is a member of the space
No changes to public page permissions.
=> Improve page permission security

background/tasks/sendNotifications/sendNotifications.ts, components/nexus/MentionedTasksList.tsx, lib/emails/emails.ts, lib/emails/templates/PendingTasks.tsx, lib/mentions/getMentionedTasks.ts, lib/prosemirror/extractMentions.ts, pages/api/email-templates/index.ts
1. Updated email title and subject to consider mentioned tasks
2. Show mentioned tasks along with correct data after multi-sig actions
=> Email for mentioned tasks

.github/workflows/test_and_deploy.yml, README.md, components/profile/components/UserDetails.tsx, components/profile/components/__tests__/UserDetails.test.tsx, jest.config-browser.ts, jest.config.ts, next.config.js, package-lock.json, package.json
Updated code for runninc react testing library tests. 
Test steps:
1. Run `npm ci`.
2. Go to `.vscode\settings.json` and set:
`"jestrunner.configPath": "jest.config-browser.ts",`
3. Go to UserDetails.test.tsx and run the tests there.
=> User details tests

components/settings/roles/RoleSettings.tsx, components/settings/roles/spacePermissions/SpacePermissions.tsx, lib/permissions/meta/__tests__/getTemplateExplanation.spec.ts, lib/permissions/meta/preset-templates.ts, pages/[domain]/settings/contributors.tsx, pages/[domain]/settings/roles.tsx, pages/api/spaces/index.ts
This PR sets new workspaces to a collaborative permissions mode
=> Default workspaces to collaborative

prisma/migrations/20220629110233_voting/migration.sql, prisma/migrations/20220629112936_voting/migration.sql, prisma/schema.prisma
Schema for voting functionality.
=> Vote schema

theme/cssVariables.ts, theme/lit-protocol/lit-protocol.scss
=> fix background of Lit Protocol dropdown

components/common/CharmEditor/components/ResizablePDF.tsx
Fixed the refreshing of PDF when writing text.
Increased the default PDF width.
=> Fix pdf refresh

components/settings/roles/components/TokenGates/TokenGates.tsx, components/settings/roles/components/TokenGates/components/TokenGatesTable.tsx
The issue was that I've removed a couple of ugly scrollbars and absolute positioning from the original CSS so that the modal can be dynamic height, but didn't test conditional rules :/
FYI for debugging Lit Protocl in the future, I have a repo that we can use to test a bare bones integration:  https://github.com/charmverse/charmverse-lit-protocol-example
=> fix disappearing multiple conditions in lit modal

components/common/CharmEditor/components/inlineVote/inlineVote.components.tsx, lib/votes/createVote.ts
=> Send threshold as number

components/common/CharmEditor/components/FloatingMenu.tsx, lib/permissions/meta/__tests__/getTemplateExplanation.spec.ts, lib/permissions/meta/preset-templates.ts, lib/permissions/spaces/availableSpacePermissions.ts, lib/permissions/spaces/mapping.ts, lib/votes/createVote.ts, lib/votes/deleteVote.ts, lib/votes/updateVote.ts, prisma/migrations/20220704101621_added_voting_space_operation/migration.sql, prisma/schema.prisma
Added the possibility to give vote creation permission to regular users.
=> Vote permissions

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/inlineVote/inlineVote.components.tsx, components/common/PageLayout/components/Header/components/NotificationsBadge/NotificationsBadge.tsx, hooks/useInlineVotes.tsx, lib/inline-votes/findTotalInlineVotes.ts
[ x ] Notification count to include in-progress votes
[ x ] Skip counting completed votes when showing the votes count in paragraph
[ x ] Automatically remove charmeditor vote mark when loading editor
=> Notification count to include in progress votes

pages/api/pages/index.ts
=> delete the new page if permissions fail after creating it

components/common/PageLayout/components/SearchInWorkspaceModal.tsx, components/common/PageLayout/components/Sidebar/Sidebar.tsx, components/common/PageLayout/components/TrashModal.tsx
Added search for pages and bounties by name.
=> Workspace search

components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx, components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
Update focalboard view record for the following cases:
[ x ] after deleting the board
[ x ] after duplicating the board
[ x ] if a non-existent view is being referenced
=> Update fb views in ls when referencing non nonexistent view

lib/emails/templates/PendingTasks.tsx
[ x ] Changed Vote to Vote now
[ x ] Remove View button for notifications
[ x ] Removed extra divider
=> email template small ui fix

lib/discord/handleDiscordResponse.ts, pages/api/discord/importRoles.ts
[ x ] Rate limit discord api call
[ x ] changed RateLimit rps from 35 to 30
[ x ] used log.info to log out discord API endpoint
=> Rate limit discord api call

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/PageThreadsList.tsx, components/[pageId]/DocumentPage/components/VotesSidebar.tsx, components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/InlineActionCounter.tsx, components/common/CharmEditor/components/inlineVote/components/InlineVoteList.tsx, components/common/CharmEditor/components/inlineVote/components/PageInlineVote.tsx, components/common/CharmEditor/components/inlineVote/components/VoteDetail.tsx, components/nexus/VoteTasksList.tsx, components/votes/components/Proposal/ProposalDialog.tsx, components/votes/components/VotesTable.tsx, hooks/usePageActionDisplay.tsx, hooks/useVotes.tsx, lib/votes/getVoteTasks.ts, lib/votes/getVotesBySpace.ts, lib/votes/interfaces.ts
[ x ] Vote from nexus page
[ x ] Vote from votes/proposals page
[ x ] Used slide transition for right sidebar
[ x ] Fixed right sidebar opening and closing when refocusing on editor
=> Cast votes from proposal and nexus page

components/common/BoardEditor/focalboard/src/components/cardDialog.tsx, components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx, components/common/BoardEditor/focalboard/src/utils.ts
[ x ] Copy card link from card modal, board, and gallery view
[ x ] Replaced focalboard snack bar with charmverse snackbar
=> Fixed copy card link functionality

components/common/RouteGuard.tsx, hooks/useLocalStorage.tsx, lib/spaces/index.ts, pages/[domain]/index.tsx, pages/[domain]/settings/workspace.tsx, pages/index.tsx
When accessing workspace, go to its last visited page. Go to last visited non-workspace page when accessing base url.
=> Remember last visited workspace pages and non-workspace page

components/common/BoardEditor/focalboard/src/components/properties/user/user.tsx
Don't display the user uuid on a card's user property.
=> Don't display user uuid on card when no username

__integration-tests__/server/pages/api/v1/bounties/index.spec.ts, pages/api-docs.tsx, pages/api/v1/bounties/index.ts, testing/setupDatabase.ts
This endpoint was requested by Gateway. It is only temporarily needed by them.. eventually the idea is for us to call their API to mint NFTs instead of them calling us.
=> add public api endpoint to retrieve bounties

scripts/makeAPIKey.ts, scripts/testApi.ts
just another way to generate keys. it was easier to just call the api directly since i have access to the production db. eventually we'll have a formal way to do it :P
=> add scripts to generate and test an api key

components/common/PageLayout/components/SearchInWorkspaceModal.tsx
Made the quick find UI to be closer to the Notion one.
=> Updated search UI

components/[pageId]/DocumentPage/components/PageBanner.tsx
just moved them to the right side but also fixed z-index so they will appear above other elements
=> fix banner buttons on mobile

components/share/PublicBountyList.tsx, components/share/PublicPage.tsx, hooks/usePages.tsx
Fixes visibility of public bounties by passing bounty page data to use pages hook
Fixes public pages to show an error if the public space does not exist
=> Fix visibility of public bounties

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/BountyProperties.tsx, components/bounties/[bountyId]/components_v3/SubmissionEditorForm.tsx, components/bounties/components/BountyCard.tsx, components/bounties/components/BountyHeader.tsx, components/bounties/components/BountySubmissionsTable.tsx, components/common/BoardEditor/focalboard/src/components/cardDetail/comment.tsx, components/common/BoardEditor/focalboard/src/components/cardDetail/commentsList.tsx
1. show "Untitled" on the card when there is no title
2. fix the avatar icon in comments
3. move the Lock Submissions icon to the top of the Submissions table
4. "Payment Details" to "Payment Address"
5. fix layout of action row
=> Small bounty UI fix

__integration-tests__/server/pages/api/bounties/[id]/index.spec.ts, components/bounties/BountiesPage.tsx, components/bounties/components/BountiesKanbanView.tsx, components/share/PublicBountiesPage.tsx, components/share/PublicPage.tsx, next.config.js, pages/[domain]/bounties/index.tsx
also renamed BountyList to BountyPage to make it more obvious it's a page component. we ought to add -Page to any page-level component, but we already do in most places
=> Add routing for bounty page and load bounty by URL query 'bountyId'

components/common/CharmEditor/components/ResizableImage.tsx, components/common/CharmEditor/components/ResizablePDF.tsx
it's possible for a user to copy/paste images, so there's no guarantee this image is unique. S3 storage is pretty cheap so I don't think we need to find an alternative for now
=> dont delete images from s3

components/bounties/BountiesPage.tsx, components/bounties/components/MultiPaymentModal.tsx, components/bounties/components/NewBountyButton.tsx, components/common/Page/PageDialog.tsx
1. Bounties kanban not vertically scrollable
2. Can only mark a bounty as complete if it's either in progress or open and not completed
3. Store the bounty page in state right after creating it
=> Bounty page bug fixes

theme/@bangle.dev/styles.scss
=> match the header font size with Notion

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx, components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx, components/common/BoardEditor/focalboard/src/components/cardDialog.tsx, components/common/Page/PageDialog.tsx, components/common/form/InputSearchBlockchain.tsx, hooks/useBounties.tsx
Rather than try to pass around an empty bounty, I added a new 'draftBounty' to the state inside useBounties hook which is used to populate the form inside BountyProperties.
See loom: https://www.loom.com/share/ca32b3ae9b7b4373a453fc3991e60645
=> Confirm card conversion to bounty

components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx, components/[pageId]/DocumentPage/components/BountyProperties/components/BountyReviewers.tsx
This must have broke in the last 1-2 days in one of the refactor PRs
=> hot fix for checking bounty permissions

lib/token-gates/evaluateEligibility.ts
This broke the token gate form when i updated lit protocol who provides conditions json column. I'm going to separately write a migration script.. i think it might be worth hoisting the chains to the top?
=> hot fix for token gates

__integration-tests__/server/pages/api/bounties/pool.spec.ts, __integration-tests__/server/pages/api/v1/bounties/index.spec.ts, lib/applications/actions/__tests__/createApplication.spec.ts, lib/applications/actions/__tests__/updateApplication.spec.ts, lib/bounties/__tests__/updateBountySettings.spec.ts, lib/votes/__tests__/utils.spec.ts, tsconfig.json
fix broken types in tests:
- disable typechecks for outdated focalboard test
- update types in bounties tests
- workaround incompatible types in v1 bounties server tests
=> Fix broken typechecks

components/bounties/components/BountyStatusBadge.tsx, lib/utilities/__tests__/numbers.spec.ts, lib/utilities/numbers.ts
=> Support display of small numbers inside the Bounty

components/common/CharmEditor/components/ResizableImage.tsx
Converts embedded base64 images to S3 uploads
=> Auto-upload the embedded image

components/bounties/components/BountyCard.tsx
=> Truncate bounty amount within the card

components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx, package-lock.json, package.json
@Devorein please test in Chrome. I tested this in Firefox, both on an inline database that needed scrollbar and one that didn't. It seems to work pretty well, if there is a little delay while resizing:
=> Inline database full width

.eslintrc.json, components/[pageId]/BoardPage/BoardPage.tsx, components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyApplicantTableRow.tsx, components/common/BoardEditor/focalboard/src/components/SourceSelection.tsx, components/common/BoardEditor/focalboard/src/components/addViewMenu.tsx, components/common/BoardEditor/focalboard/src/components/cardDetail/commentsList.tsx, components/common/BoardEditor/focalboard/src/components/centerPanel.scss, components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderSortMenu.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx, components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/PopoverMenu.tsx, components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx, components/common/CharmEditor/components/inlineDatabase/inlineDatabase.ts, components/common/CharmEditor/components/inlinePalette/editorItems/database.tsx, components/common/CharmEditor/components/rowActions/RowActionsMenu.tsx, components/common/Page/PageDialog.tsx
this moves all the view source selection to the centerPanel component, splits up the 'board' as the inline board and teh 'board' based on whichever view is active
=> move source selection to focalboard

components/profile/components/IdentityModal.tsx, components/profile/components/Integration.tsx
I noticed the "Manage integrations" button was hard to see and using custom styles. I. also made username more obvious and did some other cleanup. See below:
Before:
After:
=> Identity cleanup

background/tasks/updateVotesStatus/updateVoteStatus.ts, components/profile/components/AggregatedData.tsx, components/profile/components/DeepDaoOrganizationRow.tsx, lib/deepdao/__tests__/getAggregatedData.spec.ts, lib/deepdao/getAggregatedData.ts, lib/deepdao/interfaces.ts, lib/deepdao/sortDeepdaoOrgs.ts, lib/spaces/__tests__/getSpacesCount.spec.ts, lib/spaces/getSpacesOfUser.ts, lib/votes/getVotesBySpace.ts, lib/votes/getVotesByState.ts
The vote without the title is for a proposal page since there is no title for those sort of votes
=> Fetch charmverse spaces for nexus profile

.cdk/staging-stack.ts, .github/workflows/test_and_deploy.yml
PR will deploy to new app/environment stg-charmverse-<pr_name>
Production will dpeloy to prd-charmverse-webapp and prd-charmverse-worker
=> Changing ElasticBeanstalk environment names

charmClient/charmClient.ts, components/profile/PublicProfile.tsx, components/profile/components/AggregatedData.tsx, components/profile/components/CommunityRow.tsx, lib/deepdao/client.ts, lib/deepdao/interfaces.ts, lib/profile/__tests__/getAggregatedData.spec.ts, lib/profile/getAggregatedData.ts, lib/profile/index.ts, lib/profile/interfaces.ts, lib/profile/sortCommunities.ts, pages/api/public/profile/[userPath]/aggregate.ts, prisma/migrations/20220830034514_change_dao_type/migration.sql, prisma/schema.prisma
- renamed 'organizations' to 'communities'
- split out profile logic from deepdao client/api types into lib/profile folder
=> some cleanup for hide nfts PR

components/common/BoardEditor/focalboard/src/components/cardDetail/commentsList.tsx, components/common/BoardEditor/focalboard/src/store/boards.ts, components/common/CharmEditor/components/inlinePalette/useEditorItems.tsx, components/common/CharmEditor/components/nestedPage/hooks/useNestedPage.ts, lib/pages/addPage.ts, pages/api/pages/index.ts
Woops... we were using different ids for the page than the board/cards. Need to figure out how to fix for boards that have been created now..
=> fix creating nested databases

pages/[domain]/settings/workspace.tsx, pages/api/session/login.ts, pages/api/spaces/[id]/index.ts
- Fixes two errors on the server due to invalid input
- Display an error when someone is trying to use a domain that already exists:
=> Prevent server errors due to invalid input

lib/pages/__tests__/mapPageTree.spec.ts, lib/pages/interfaces.ts, lib/pages/mapPageTree.ts, lib/pages/server/resolvePageTree.ts
Fixes a bug where created a nested page inside proposals would fail
=> Fix tree resolution for creating nested proposal pages

components/login/Footer.tsx, components/login/LoginPageContent.tsx
=> make login page more mobile-friendly

lib/discord/loginByDiscord.ts, pages/api/discord/connect.ts, pages/api/discord/oauth.ts
for testing locally, this allows you to use your laptop's IP address instead of localhost to connect thru Discord
=> make it easier to use discord on alternate local ip addresses

components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, lib/pages/mapPageTree.ts, testing/generate-stubs.ts
while debugging, did some type cleanup using generics :)
=> simplify page types

components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx, components/share/PublicPage.tsx, hooks/useCurrentSpace.ts, hooks/usePages.tsx, lib/spaces/__tests__/getSpacePublicInfo.spec.ts, lib/spaces/getSpacePublicInfo.ts, pages/api/public/pages/[...pageId]/index.ts, pages/api/spaces/[id]/public.ts
This PR fixes the non-navigable breadcrumbs by relying less on explicit page URL structure
It also fixes the display of child pages of a public page
=> Public page breadcrumbs

components/[pageId]/DocumentPage/DocumentPage.tsx
=> Restore display of proposal properties in child pages

.github/actions/install/action.yml, .github/workflows/test_and_deploy.yml
One of my builds timed out waiting for playwright to install. But we should  be able to cache it
=> install playwright dependencies as part of cached dependencies step

background/tasks/sendNotifications/sendNotifications.ts, lib/tasks/markTasks.ts, prisma/migrations/20220909024646_notification_channel/migration.sql, prisma/schema.prisma
should help a bit with QA and possibly product analytics
=> save the channel that notifications are received

lib/pages/addPage.ts, pages/api/blocks/index.ts
Fix inline boards not displaying to the public. Turns out the inline card permissions weren't provisioned properly
=> Fix inline boards

components/[pageId]/EditorPage/EditorPage.tsx
=> revert check for workspace

components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/components/BountyShareButton/BountyShareButton.tsx, components/common/PageLayout/components/Header/components/BountyShareButton/ShareBountyBoard.tsx
Please double-check my work.. I had to remove some checks for the current page's permissions. mabe it was just copypasta from the other share button?
=> Show public bounty toggle

pages/api/public/pages/[...pageId]/index.ts
This is a temporary fix until we can change permissions properly
=> enable viewing public bounty pages on their own

lib/profile/isProfilePathAvailable.ts, lib/users/createUser.ts, pages/api/profile/checkPathAvailability.ts
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=25ac8182-5056-4b58-9902-8b2b06068146
Username as default user profile path (when available)
=> Use username as default profile path

lib/users/createUser.ts
Instead of using `...` from username, default path will have `-`
(request on discord)
=> Replace dots with hyphen in default user path

components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantForm/BountyApplicantForm.tsx
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=8ccc5ddd-1fea-435e-8872-84f79ceab3c3
Fixed refreshing bounty card page after applying
=> Refresh bounty application form

components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx, pages/api/blocks/[id]/index.ts
only check page permissions for blocks that have a page analog
=> re-enable deleting non-page blocks (bug fix for user that can't delete views)

components/settings/roles/components/TokenGates/components/TokenGatesTable.tsx
Loom of current user experience: https://www.loom.com/share/98b4541d752446149aafb1bd7c44ad09
=> disable token gate test if litClient is not initialized

package-lock.json, package.json
This contains a malicious library: https://github.com/charmverse/app.charmverse.io/security/dependabot/18
=> uninstall malware from harmony sdk

components/proposals/components/ProposalStepper.tsx
=> Fix stepper layout

__integration-tests__/server/pages/api/proposals/[id]/index.spec.ts, __integration-tests__/server/pages/api/proposals/[id]/status.spec.ts, components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx, components/proposals/components/ProposalStepper.tsx, pages/api/proposals/[id]/index.ts, pages/api/proposals/[id]/status.ts
Admin can now update proposal properties and move it across stages
=> Admin overrides

components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButton.tsx, components/common/TemplatesMenu/TemplatesMenu.tsx, components/votes/components/NewProposalButton.tsx
We now control whether to show the new templates button
=> Add logic for hiding new templates

package-lock.json, package.json
This fixes https://github.com/charmverse/app.charmverse.io/security/dependabot/14
=> Update dependencies for security vulns

.env.test.local, .github/actions/build/action.yml, .github/actions/install/action.yml, .github/workflows/test_and_deploy.yml, Dockerfile, scripts/configure-db.sh
Now's a good time to do it, since Node 16 will go into maintenance this year: https://github.com/nodejs/release#release-schedule
Node v18 announcement with 'whats new': https://nodejs.org/en/blog/announcements/v18-release-announce/
=> update to node 18

pages/_app.tsx
i notice sometimes the page title is "DEV | | Charmverse" but figured out the issue
=> make dev prefix more consistent

lib/proposal/proposalStatusTransition.ts
Reviewer can move a proposal back to discussion stage
=> Allow reviewer to move proposal to discussion

components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx, components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/components/Snapshot/PublishToSnapshot.tsx, components/votes/components/CreateVoteModal.tsx
Clickable area is now the button. Before it was just the text and icon.
=> Publish to snapshot -> Add onClick to the whole button

.env
=> Restore .env

components/common/CreateSpaceForm.tsx, components/common/PageLayout/components/Sidebar/Workspaces.tsx, hooks/useSpaces.tsx, pages/createWorkspace.tsx
FIx adding news space one more time
=> Add space from sidebar bugfix

components/common/CharmEditor/components/suggestions/schema/common/track.ts
I was not able to export to markdown or submit to snapshot, getting an exception inside the markdown serializer. It seems that we need to add markdown config for any custom marks..
=> fix markdown export with tracking marks

components/settings/invites/components/TokenGates/components/TokenGatesTable.tsx
@Devorein i think you mentioned this 'bug' in discord. users that don't have a connected walelt should not be able to 'test' a token gate
=> check that users wallet is connected before testing token gate

lib/metrics/mixpanel/interfaces/BountyEvents.ts, lib/metrics/mixpanel/interfaces/index.ts, pages/api/applications/[id]/approve.ts, pages/api/applications/index.ts, pages/api/bounties/index.ts, pages/api/submissions/[id]/review.ts
=> Mixpanel bounty events

components/settings/invites/components/InviteLinks/components/InviteActions.tsx
Adding a token gate without wallet connected shows a very long and cryptic error message
=> Disable adding token gate without wallet

theme/@bangle.dev/styles.scss
Toggle arrow was jumping to each line instead of staying on the first line when a toggle is created in a page.
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=86f54ac9-07fc-4d87-8452-1bdcca7e033c
=> Arrange toggle arrow on a page

components/settings/Layout.tsx, components/settings/roles/components/SpacePermissions/components/PermissionConfigurationMode.tsx
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=7177a12a-bb9c-49a0-8706-900faffaef48
=> Make Settings links responsive + Permissions responsive fix

components/common/PageLayout/components/Header/components/Snapshot/PublishToSnapshot.tsx, components/proposals/components/ProposalStepper.tsx, components/votes/components/CreateVoteModal.tsx, hooks/useKeydownPress.ts, lib/pages/generateMarkdown.ts
=> Fix publish to snapshot

components/settings/invites/components/TokenGates/components/TokenGatesTable.tsx
Ensures the test button for token gates works
=> Fix token gates

__e2e__/po/nexus.po.ts, __e2e__/sessions/logout.spec.ts, components/login/WalletSign.tsx, components/nexus/components/NexusPageTitle.tsx, hooks/useWeb3AuthSig.tsx
This still shows 'verify wallet' on the login page, but i think that's still better than what we have now (user can't log out).
=> Logout using web3

components/common/CharmEditor/components/inlineVote/components/SnapshotVoteDetails.tsx
Make sure not to show NaN for empty dataset
=> Handle empty state for a vote

components/bounties/BountiesPage.tsx, components/common/EmptyStateVideo.tsx, components/proposals/ProposalsPage.tsx
=> add empty state for proposals

components/proposals/components/ProposalStepper.tsx, theme/index.ts
I also did some clean-up to separate the desktop and mobile inputs to make it easier to follow the code
=> add hover effect on proposal status

pages/_app.tsx
=> enable dark mode by default

.cdk/staging-stack.ts, docker-compose.yml
So these resources wouldn't count as a datadog host in billing.
=> adding tags to every resource in staging

components/bounties/components/BountyStatusBadge.tsx, components/nexus/BountyTasksList.tsx, components/nexus/MentionedTasksList.tsx, components/nexus/TasksPage.tsx, components/nexus/VoteTasksList.tsx, lib/applications/actions/createApplication.ts, lib/applications/interfaces.ts, lib/bounties/__tests__/getBountyTasks.spec.ts, lib/bounties/getBountyAction.ts, lib/bounties/getBountyTasks.ts, lib/permissions/interfaces.ts, lib/proposal/getProposalTasks.ts, pages/api/tasks/list.ts, prisma/migrations/20221017155636_add_bounty_notification_type/migration.sql, prisma/schema.prisma
My Nexus -> Bounties will show a status and a review button for pending actions by a reviewer or an applicant.
I took Proposals as an example.
https://app.charmverse.io/charmverse/page-3878915513317769
I also fixed a bug where votes were doubled.
=> Added bounties table to My Nexus

components/common/UserDisplay.tsx, components/nexus/GnosisTasksList.tsx, components/nexus/MentionedTasksList.tsx, components/nexus/ProposalTasksList.tsx, components/nexus/VoteTasksList.tsx
After a discussion with Matt and Chris we decided to make some small UI improvements to Nexus.
Regarding the buttons, we discussed that we should have some buttons like View that are not that emphasised then an action button. I decided to make the View button outlined. A grey button looked like it is disabled and looks like it's not clickable.
https://app.charmverse.io/charmverse/page-13207403648557392
=> Small UI improvements for Nexus

components/nexus/MentionedTasksList.tsx, lib/profile/getAggregatedData.ts
In the past we weren't getting the number of proposals and votes from charmverse db in My profile page.
For proposals I am getting the number of proposals that:
- the user has to have permissions to a space
- the user has to be a reviewer or author
- the proposal should not be deleted
https://app.charmverse.io/charmverse/page-619845225519724
=> Add cv data in My profile page

pages/[domain]/index.tsx
Fixes an issue which caused black screen if no pages exist
=> Redirect to members directory if no pages found

components/common/PageLayout/components/Sidebar/Sidebar.tsx
=> fix warning of prop being passed to html element

charmClient/apis/trackApi.ts, charmClient/charmClient.ts, pages/api/events/index.ts, pages/api/profile/check-path-availability.ts, pages/api/profile/checkPathAvailability.ts, pages/api/track/index.ts
/track is blocked by browsers as a known analytics endpoint
=> Replace camelcase api endpoint with hyphenated version and rename track endpoint

.github/workflows/test_and_deploy.yml, __e2e__/po/login.po.ts, __e2e__/sessions/loginDiscord.spec.ts, __e2e__/utils/web3.ts, components/login/WalletSign.tsx, hooks/usePages.tsx, hooks/useUser.tsx, pages/[domain]/index.tsx, pages/api/discord/callback.ts, pages/index.tsx
There's some additional code related to fixing Discord login which I'm just choosing to leave in here because it is going to be used in a PR to fix discord login.. https://github.com/charmverse/app.charmverse.io/pull/1140
=> re-enable e2e tests

components/settings/roles/components/RoleRow.tsx
User story:
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=0b064948-b9d6-418b-983d-8ac1844fd2af&cardId=f814bd8e-e26a-4677-b213-d5dba289e4e8
The arrow indicator is right aligned instead of aligned to role count.
=> feat: make roles collapsable

jest.config-server.ts, package-lock.json
Restoring commented line of code which I changed while testing things locally
and additionally  I think someone did not pushed updated package-lock file
=> Disable lib tests in server tests

charmClient/apis/membersApi.ts, hooks/useMemberProperties.tsx
We had the incorrect types on the client side for the api endpoints, which don't always return a list of permissions.
=> Bug fix: adding member property breaks the UI

components/common/PageLayout/components/Header/components/ShareButton/ShareButton.tsx, components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/PagePermissions.tsx
In dev mode, I usually get an error that the ShareButton is trying to update state on an unmounted component. I replaced useState/useEffect pattern with useSWR to get rid of this message.
Please double-check I"m refreshing the page and permissions as needed!
=> fix errors from Share Button effect

connectors.ts, lib/gnosis/gnosis.ts
Fix for [this](https://discord.com/channels/894960387743698944/950861057398833212/1036220214964138004) bug reported by Alex
=> Fixed resyncing gnosis safes

__integration-tests__/server/pages/api/spaces/[id]/snapshot.spec.ts, components/common/PageLayout/components/Header/components/Snapshot/ConnectSnapshot.tsx, components/common/PageLayout/components/Header/components/Snapshot/PublishingForm.tsx, hooks/useKeydownPress.ts, lib/snapshot/getSpace.ts, pages/api/spaces/[id]/snapshot.ts
=> Admin only snapshot

background/tasks/sendNotifications/sendNotifications.ts
Checking logs in datadog for each type of notification.
The main idea is to see if we have a duplicate taskId
=> send notifications logs

components/common/CharmEditor/components/PopoverMenu.tsx, components/common/CharmEditor/components/inlinePalette/components/InlineCommandPalette.tsx, components/common/CharmEditor/components/inlinePalette/components/InlinePaletteRow.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/database.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/list.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/media.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/other.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/text.tsx
When you type / to see all the commands inside a page you will see the list of commands look like the Notion ones.
I discussed with Chris and he approved the design and how the icons look.
=> Make commands look more like notion

prisma/schema.prisma
Add prisma schema inline with latest migration
=> Commit prisma schema

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx, components/common/CharmEditor/components/tweet/components/Tweet.tsx, components/common/CharmEditor/components/tweet/components/TweetInput.tsx, components/common/CharmEditor/components/tweet/tweet.ts, components/common/CharmEditor/components/tweet/twitterJSUrl.ts, components/common/CharmEditor/specRegistry.ts, lib/prosemirror/insertNode.ts, pages/_app.tsx, theme/cssVariables.ts
=> add Twitter embed

components/settings/invites/components/InviteLinks/components/InviteLinksTable.tsx, components/settings/invites/components/TokenGates/components/TokenGatesTable.tsx
=> disable copy link when no token gates exist

components/common/CharmEditor/components/Resizable/ResizableBox.tsx, components/common/CharmEditor/components/Resizable/VerticalResizer.tsx
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=44c79006-57dd-4e78-808f-b21ae0323b8c&cardId=2a0266cd-2b92-4a87-ad7d-98e15fe38236
=> fix: add sw and se resizers

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/@bangle.dev/react-menu/Menu.tsx, components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx, components/common/CharmEditor/components/inlinePalette/components/InlineCommandPalette.tsx, components/common/CharmEditor/components/inlinePalette/components/InlinePaletteRow.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/database.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/text.tsx, components/common/CharmEditor/components/inlinePalette/useEditorItems.tsx, components/common/CharmEditor/utils.ts
Please ignore:
- the bug where sometimes the floating menu jump a few pixels below
- the bug where sometimes the toggle does not work
- the bug when the text is always highlighted because the InlinePalette does not know what type of text is selected
=> Text commands in floating menu

components/integrations/components/GnosisSafes.tsx, connectors.ts, lib/gnosis/gnosis.tasks.ts, pages/api/email-templates/index.ts
Update gnosis safe urls to new app link
Add support for prepending the correct chain prefix
=> Update gnosis urls

components/common/PageLayout/PageLayout.tsx
https://app.charmverse.io/charmverse/page-011425735096148859
=> Keep in storage the status of the left sidebar

components/common/BoardEditor/focalboard/src/components/centerPanel.scss
Padding was added for all boards and we don't need it for boards embedded in pages or other places.
https://app.charmverse.io/charmverse/page-16806054051346364
=> Remove padding for embedded boards

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/ResizableImage.tsx, components/common/CharmEditor/components/tweet/tweet.ts
Fixes the issue where image pasting did not work
=> Fix image pasting

hooks/usePages.tsx, pages/api/pages/[id]/index.ts
- dont re-query pages on updates
- dont send contents update to web sockets
=> Make page updates via web sockets more efficient

components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx, hooks/usePages.tsx
[Task Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=a479fff9-c4e4-4dc5-ad67-5cdd5ad0c37a)
=> Redirect user to new page after deleting page

components/members/components/MemberDirectoryGalleryView.tsx, components/members/components/MemberDirectoryProperties/MemberPropertyTextMultiline.tsx, components/members/components/MemberDirectoryTableView.tsx
[Add "Show More" for long text](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=b29383fb-f66a-412a-a5b7-0200c6914fd4)
=> Show more for multi-text property

background/tasks/sendNotifications/sendNotifications.ts, lib/gnosis/gnosis.tasks.ts, lib/proposal/getProposalTasksFromWorkspaceEvents.ts
some other minor cleanups, just making variables easier to understand
=> ignore deleted proposals for notifications

components/settings/invites/Invites.tsx, components/settings/invites/components/InviteLinks/components/InviteActions.tsx
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=44c79006-57dd-4e78-808f-b21ae0323b8c&cardId=9b2c6440-f5d5-4471-8b3b-eacd899e5803
=> fix: add wallet connect and admin tooltip

components/common/BoardEditor/components/properties/SelectProperty/SelectProperty.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx, components/common/form/fields/utils.ts
https://app.charmverse.io/charmverse/page-4931554630313224
=> Hide empty values from kanban cards

components/common/CharmEditor/components/inlineComment/inlineComment.plugins.tsx
[Bug: comments being created multiple times](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=bb05b58a-9883-4b7f-82f3-2071d665a297)
=> Bug: comments being created multiple times

charmClient/charmClient.ts, components/invite/InviteLinkPage.tsx, components/login/LoginPageContent.tsx, components/login/WalletConnect.tsx, components/login/WalletSign.tsx, components/share/PublicPage.tsx, hooks/useUser.tsx, hooks/useWeb3AuthSig.tsx, lib/blockchain/interfaces.ts, lib/profile/__tests__/getAggregatedData.spec.ts, lib/users/__tests__/createUser.spec.ts, lib/users/createUser.ts, lib/users/getUser.ts, pages/api/profile/add-wallets.ts, pages/api/profile/index.ts, scripts/lowercaseWallets.ts
Force Web3 accounts to be lowercase in the client and server to make things simpler
=> Lowercase accounts

components/settings/members/MemberList.tsx, components/settings/members/MemberListItem.tsx
https://app.charmverse.io/charmverse/page-3237912660905362
=> Members - responsive table

components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx, components/bounties/components/BountyStatusBadge.tsx
https://app.charmverse.io/charmverse/page-2145884290280191
https://app.charmverse.io/charmverse/page-8542828179605135
Fixed amount input + added validation
=> Bounty amount input handling

components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, components/common/PageLayout/components/PageNavigation/components/BoardViewTreeItem.tsx, components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx, components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx, components/common/PageLayout/components/Sidebar/Sidebar.tsx
When a sidebar link is clicked on mobile, it should auto close
=> Auto close sidebar on mobile

components/common/CharmEditor/components/iframe/IframeComponent.tsx, components/common/CharmEditor/components/tweet/components/Tweet.tsx, components/common/CharmEditor/components/tweet/tweet.ts
Steps to use:
1. Type /embed
2. enter a twitter URL such as https://twitter.com/Joi/status/1524309636236836864
=> convert iframe to tweet plugin when twitter is detected

components/common/CharmEditor/components/mention/components/MentionSuggest.tsx, hooks/useMembers.tsx, pages/api/spaces/[id]/members/index.ts, scripts/seedUsers.ts
Alphabetic sorting of members in a workspace.
Native JS allows us to do string comparison using < or > without worrying about casing.
Also added memoization for the search, as well as partial matching for member names (so we don't only look at names starting with a specific string)
=> Sort members

components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeader.spec.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeaderMenu.tsx, components/common/BoardEditor/focalboard/src/store/cards.ts, components/common/BoardEditor/focalboard/src/widgets/menu/menu.tsx, components/common/PageLayout/components/Header/components/DatabasePageOptions.tsx
We were relying on 'card.title' which is no longer ever set.
=> fix sorting table rows by title

components/common/Modal/Modal.tsx, components/members/components/MemberDirectoryGalleryView.tsx, components/members/components/MemberDirectoryTableView.tsx, components/members/components/MemberOnboardingForm.tsx, components/profile/components/SpacesMemberDetails/SpacesMemberDetails.tsx, components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopup.tsx
I used the 'fullScreen' option of the Dialog component... i'm thinking we should use this in our standard Modal component too?
Preview: https://www.loom.com/share/4ba70e433b0c46cbb3c8d68b1a6f6b22
https://discord.com/channels/894960387743698944/933026321683066991/1044984954741854210
Original report: https://discord.com/channels/894960387743698944/933026321683066991/1044984954741854210
=> make member editing fullscreen

components/common/PageLayout/components/Sidebar/Sidebar.tsx, pages/[domain]/forum/index.tsx
Quick fix for showing Forums for charmverse team
=> Show the forum for CharmVerse team

components/common/CharmEditor/components/mention/components/MentionSuggest.tsx, lib/members/interfaces.ts
https://app.charmverse.io/charmverse/page-05431114156542183
Search users to mention by more props than username only
=> feat: filter members by custom name, discord, path

lib/pages/__tests__/getPreviewImageFromContent.spec.ts, lib/pages/server/updatePage.ts, lib/websockets/documentEvents/documentEvents.ts, pages/api/pages/[id]/index.ts, pages/api/pages/index.ts
I also ran scripts/updateCardFallbackPreview to fix previous cards and fixed it so that we send updates when galleryImage/hasContent has changed
=> set galleryimage and has content when editing a page thru websockets

components/settings/roles/components/RoleRow.tsx, lib/metrics/mixpanel/interfaces/SettingEvent.ts, pages/api/invites/[id]/index.ts, pages/api/permissions/space/[spaceId]/add.ts, pages/api/roles/[id]/index.ts, pages/api/roles/assignment/index.ts, pages/api/roles/index.ts, pages/api/token-gates/[id]/roles.ts
The events:
Add A Role
Add Member to Role
Manage Role Permissions
Add Token Gate Role
Delete Invite Link
=> Mixpanel settings events

background/websockets.ts, components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx, components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx, components/common/CharmEditor/components/fiduswriter/collab/doc.ts, components/common/CharmEditor/components/fiduswriter/fiduseditor.ts, components/common/CharmEditor/components/fiduswriter/ws.ts, components/common/CharmEditor/components/pasteChecker/pasteChecker.ts, package.json
When we receive a 1009 status code (large payload error), we reset the document and show the user an error
=> handle payload size errors in web sockets

lib/discord/loginByDiscord.ts, pages/api/discord/connect.ts, pages/api/discord/updateUserDiscordSocial.ts, scripts/updateUsersDiscordSocial.ts
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=725604be-cc11-472b-99bd-51bf933cbb24
- auto filling discord username in social when user connects
- script to update current discord users
=> Filling user discord social + udpate script

components/common/CharmEditor/components/iframe/__tests__/utils.spec.ts, components/common/CharmEditor/components/iframe/config.ts, components/common/CharmEditor/components/iframe/config.tsx, components/common/CharmEditor/components/iframe/iframe.ts, components/common/CharmEditor/components/iframe/utils.ts, components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx
example url to embed: https://docs.google.com/forms/d/e/1FAIpQLSfHZjNU09tzdSUjr0AWdQc599GbHh8iyKXfRd1nOaraDXLDLw/viewform?usp=sf_link
I also made it so that we pick up the iframe if you use the embed code. Google sets it automatically which is kind of neat
=> add embed support for google forms

components/forum/ForumPage.tsx, components/forum/components/PostList/PostList.tsx, lib/forums/posts/__tests__/searchForumPosts.spec.ts, lib/forums/posts/searchForumPosts.ts, scripts/generatePosts.ts
The forum search now accounts for the current category
Also cleaned up forum posts list and simplified the logic
=> Account for category in the search

scripts/reopenProposal.ts, scripts/reopenVote.ts
I already ran this but wanted review, maybe we can use it in the future.. did we have a script already?
=> script to update proposal status

components/forum/ForumPage.tsx, components/forum/components/CategorySelect.tsx, components/forum/components/PostList/components/PostCard.tsx
- the category select was invalid when it should be 'all categories'
- there was. a DOM error for having nested 'button' tags
=> fix errors on forum page

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/InlineCharmEditor.tsx
https://app.charmverse.io/charmverse/page-25205641924054345
=> Fix code carot color in darkmode

components/login/Login.tsx, components/login/WalletSign.tsx
- Autosign when using modal in Connect
- Dont' show user an error when signature cancelled, inform them instead
todo on mobile:
- full width connect button
- fix auto sign showing on mobile
=> Autoverify wallet

__integration-tests__/server/pages/api/v1/spaces/index.spec.ts, lib/discord/loginByDiscord.ts, pages/api/discord/connect.ts, pages/api/discord/oauth.ts, pages/api/v1/spaces/index.ts
=> Enable Discord in staging

components/common/BoardEditor/focalboard/src/components/addViewMenu.tsx, lib/pages/addPage.ts
soon we want to provide the user with a list of options to start with, but for now a 'quick fix' is to default to table
=> change default database type to table

components/common/PageLayout/components/Header/components/utils/databasePageOptions.ts
I noticed that existing select and multiselect were not merging properly so I made a fix for that.
=> Fix import in case of existing select and multiselect

components/common/CharmEditor/CharmEditor.tsx, components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx, components/forum/components/PostDialog/PostDialog.tsx, components/forum/components/PostPage/PostPage.tsx, lib/forums/posts/getForumPost.ts, lib/forums/posts/interfaces.ts, pages/[domain]/forum/post/[pagePath].tsx, pages/[domain]/forum/post/[postId].tsx
[Task Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=876aa6ac-5a5f-4262-b5f9-730052f1a534)
=> Forum post standalone page

components/common/BoardEditor/components/properties/SelectProperty/SelectProperty.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx, components/common/form/fields/Select/SelectOptionItem.tsx
=> Ellipsis for overflow text in chips and headers

components/common/CharmEditor/components/markdownParser/ImportZippedMarkdown.tsx, pages/api/pages/import/[spaceId]/zipped.ts
Fixes issue of replaying old uploads
=> Import markdown fix

lib/session/config.ts
The fix is to include the library that we want to merge declarations with. Otherwise you get an error like the one below:
=> fix TS error when running code with ts-node that imports session config

components/common/BoardEditor/focalboard/src/components/table/calculation/calculationRow.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeaders.tsx, components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx, components/common/BoardEditor/focalboard/src/mutator.ts, components/common/BoardEditor/utils/updateVisibilePropertyIds.ts
[Loom Recording](https://www.loom.com/share/ad5675705e624e86b257a12a14052092)
=> Reorder table title column

background/tasks/sendNotifications/sendNotifications.ts, lib/metrics/mixpanel/updateTrackUserProfile.ts, lib/users/updateUserProfile.ts
Changes:
Fix for prisma limitation when a large array of queries are running.
Fix user profile email update.
=> Fix prisma limit for large parallel queries & more

components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx, components/_app/Web3ConnectionManager/hooks/useMetamaskConnect.ts, components/login/Login.tsx, components/login/LoginPageContent.tsx, components/login/WalletSign.tsx, hooks/useWeb3AuthSig.tsx
Fix wallet connect on mobile
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=c504ae97-4208-42da-8d13-892fff3dbf75
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=28599a1d-c3b3-4060-8759-2fb704412ff3
- fixed wallet connect login
- added MM app deep link for mobile devices
=> Fix walletconnect flow on mobile

components/members/MemberOnboardingModal.tsx
Stops onboarding modal from showing to non space members
=> Don't show onboarding modal to non members

__integration-tests__/server/pages/api/forums/posts/[postId]/index.spec.ts, components/forum/components/ForumVote.tsx, components/forum/components/PostList/components/PostCard.tsx, components/forum/components/PostPage/components/PostComment.tsx, lib/forums/posts/getPostMeta.ts
=> Fix display of forum votes

components/common/BoardEditor/focalboard/src/components/centerPanel.scss, components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx, lib/focalboard/board.ts, lib/google/forms/getFormAndResponses.ts, lib/google/forms/syncFormResponses.ts
TL;DR: We were always checking for responses from _now_, not the updated date from the block.
=> Fix google refresh

.github/workflows/deploy_staging.yml, .github/workflows/destroy_staging.yml, .github/workflows/test_and_deploy.yml, package.json
For updating the output:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix warnings inside Github Actions

.github/actions/build_docker_image/action.yml, .github/workflows/deploy_staging.yml, .github/workflows/destroy_staging.yml
https://github.com/aws-actions/configure-aws-credentials/issues/489
=> update aws action to use node 16

.github/workflows/test_and_deploy.yml, adapters/litProtocol/hooks/useLitProtocol.tsx, lib/token-gates/evaluateEligibility.ts
=> Catch lit client fail

.github/workflows/test_and_deploy.yml
Close the loop of today's debugging
=> Re-enable full CI process

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx, components/common/LoadingComponent.tsx, theme/@bangle.dev/styles.scss
Trying to address the jarring horizontal layout shift when page content is loading. I think the loading component is causing it..
https://www.loom.com/share/46fba873dcf04d95b63e73416f4ae3e1
=> Fix for layout shift 

components/common/ImageSelector/ImageSelector.tsx, db.ts, hooks/useFirebaseAuth.tsx, lib/log/log.ts, lib/notion/getPersistentImageUrl.ts, pages/api/pages/import/[spaceId]/zipped.ts
This causes serious bugs because Typescript tells you that prisma/log is always available without import
=> remove global typescript defs for prisma and log

components/forum/components/PostList/PostList.tsx, components/forum/components/PostList/components/PostCard.tsx
https://app.charmverse.io/charmverse/page-18247391138004954
=> Add category on the PostCard

components/forum/components/PostPage/PostPage.tsx
https://app.charmverse.io/charmverse/page-3353496760514145
=> Added member creator below the post title

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/inlinePalette/components/InlineCommandPalette.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/advancedBlocks.tsx, components/common/CharmEditor/components/inlinePalette/useEditorItems.ts, components/forum/components/PostPage/PostPage.tsx
This hides post polls from the forum post command palette until we provide proper support
=> Disable post polls

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/InlineCharmEditor.tsx, components/forum/components/PostPage/components/CommentReplyForm.tsx, components/forum/components/PostPage/components/PostComment.tsx, components/forum/components/PostPage/components/PostCommentForm.tsx, theme/@bangle.dev/styles.scss
=> fix placeholder text and avatars in forums

components/common/Modal/ConfirmDeleteModal.tsx, components/forum/components/PostDialog/PostDialog.tsx, components/forum/components/PostPage/PostPage.tsx, components/forum/components/PostPage/components/PostCategoryInput.tsx, components/forum/components/interfaces.ts, pages/[domain]/forum/post/[pagePath].tsx
=> Show confirmation before user closes post without saving

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx, components/forum/components/PostList/components/PostSummary.tsx
I added a background color to charmeditor to cover up the loading icon, but this is causing other issues.
=> Fix forum post summary background

components/forum/components/PostPage/PostPage.tsx
Desktop screen
Mobile screen
[Discord Discussion](https://discord.com/channels/894960387743698944/1045000180996526120/1064171426728378459)
=> Hide related posts on small screen

components/common/CharmEditor/components/mention/mention.specs.ts, components/common/CharmEditor/components/textColor/textColorSpec.ts, components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/components/Snapshot/PublishingForm.tsx, lib/pages/generateMarkdown.ts, pages/api/v1/databases/[id]/search.ts
- Fix broken text-color mark export
- Add support for exporting the username of a mentioned person
- Add UI error handling and notification
=> Fix snapshot publish

charmClient/apis/votesApi.ts, components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/CharmEditor/components/inlineVote/components/ConfirmDeadlinePopover.tsx, components/common/CharmEditor/components/inlineVote/components/VoteDetail.tsx, components/common/CharmEditor/components/poll/PollComponent.tsx, components/nexus/VoteTasksList.tsx, components/votes/components/CreateVoteModal.tsx, components/votes/components/VoteActionsMenu.tsx, hooks/useVotes.tsx, lib/votes/__tests__/updateVote.spec.ts, lib/votes/interfaces.ts, lib/votes/updateVote.ts, package-lock.json, package.json, pages/api/votes/[id]/index.ts
Main changes
- User can now change deadlines for the polls (inline and in proposals)
- If the user doesn't finish the process, the update will not be triggered. This behaviour is also the same when you create a poll.
- Removed all imports that were not used in some files
- In useVotes I changed the setState behaviour for all functions to update the state only once per action without mutating the state variable.
- If you check package-lock.json you will see more then 1 package update. That is because the last package.json committed update didn't include package-lock
=> Update poll deadline

components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
See video: https://www.loom.com/share/fff41253a1334a65b8deef28a3e2c9dd
=> fix flicker of scrollbar while loading charm editor

lib/utilities/strings.ts
currently you see a red background always on page load.
=> Hide avatar until the user/space name is loaded

lib/log/__tests__/logUtils.spec.ts, lib/log/logLevel.ts, lib/log/logUtils.ts
=> check if value is a primitive for metadata in logs

lib/middleware/requireSuperApiKey.ts, prisma/migrations/20230119233040_token_name_required/migration.sql, prisma/schema.prisma, scripts/makeSuperAPIKey.ts
- make name unique
- allow passing in an existing token value when creating tokens (for when staging is reset)
=> improve DX for super tokens

hooks/useWeb3AuthSig.tsx
This prevents a user who logged in via Discord from being auto-logged out when a wallet is detected
It also performs auto-relogin when there is no current user
=> Fix auto login and logout

components/common/CharmEditor/components/common/MediaUrlInput.tsx, components/common/PageActions.tsx, components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx, components/forum/ForumPage.tsx, components/forum/components/CategoryMenu.tsx, components/forum/components/PostDialog/PostDialog.tsx, components/forum/components/PostList/PostList.tsx, components/forum/components/PostList/components/PostSummary.tsx, components/forum/components/PostPage/PostPage.tsx, components/forum/components/PostPage/components/PostCommentSort.tsx, lib/websockets/interfaces.ts, pages/api/forums/posts/[postId]/index.ts
- adjusted feed widths to mirror Reddit
- standardize heights of sidebar links
- make sidebar wider and set max rows for embed code 
- remove sidebar on posts
- refresh feed when updating a post
- hide sort option when there are no comments
- added page actions menu so user can delete posts - we still need to add this to the full page view tho, as well as the post cateogry in breadcrumbs
=> Forum tweaks

components/[pageId]/DocumentPage/DocumentPage.tsx
I broke this in my update a few weeks ago. It was just part of a cleanup: 
https://github.com/charmverse/app.charmverse.io/commit/f4ca0438ffd7c7ba14229e6705a90c09f49bfcc8#diff-01a1ee8371ead9485c98f19c255c3bed348fb620809a0d10b3f81924e8671e4eR153
=> fix missing bounty comments

lib/permissions/pages/actions/replaceIllegalPermissions.ts
we're getting an error "id" of undefined, which is not helpful. Unfortunately the stack trace is minified so i can't see which place is failing... I also don't think things should pretend to work when they don't, but I'd rather either log a warning, or check existence but throw a more useful error so we can tell what's going on up-stream. Either way, I really dislike Type casting because of this specific reason
=> remove type casting from permissions logic

components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Sidebar/SidebarSubmenu.tsx
Added link to nexus + added bell icon for notifications
=> Add notifications for users

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/mention/components/Mention.tsx, components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx, components/common/PageLayout/components/PageIcon.tsx, theme/colors.ts, theme/cssVariables.ts
=> Linked page icon

scripts/getPageHistory.ts
=> add a script to review page history

components/common/BoardEditor/focalboard/src/components/addViewMenu.tsx, components/common/BoardEditor/focalboard/src/components/centerPanel.scss, components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/gallery/gallery.scss, components/common/BoardEditor/focalboard/src/components/viewHeader/filterComponent.scss, components/common/BoardEditor/focalboard/src/components/viewHeader/filterComponent.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.scss, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderSortMenu.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx, components/common/BoardEditor/focalboard/src/components/viewMenu.tsx, components/common/BoardEditor/focalboard/src/widgets/buttons/iconButton.tsx, components/common/BoardEditor/focalboard/src/widgets/icons/board.tsx, components/common/BoardEditor/focalboard/src/widgets/icons/calendar.tsx, components/common/BoardEditor/focalboard/src/widgets/icons/gallery.tsx, components/common/BoardEditor/focalboard/src/widgets/icons/table.tsx, components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/database.tsx, components/common/TemplatesMenu/TemplatesMenu.tsx, components/members/components/MemberDirectoryProperties/MemberPropertyVisibility.tsx, lib/pages/addPage.ts, lib/pages/createNewDataSource.ts, pages/_app.tsx, theme/cssVariables.ts, theme/index.ts
Clicking Filter or Sort ends up with dropdown being hidden:
=> Fix filter/sort on views, and a bunch of minor UI polish for views

hooks/usePages.tsx
i made a story for e2e test: https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=3da26509-b47f-4987-a839-afc8de0355bf
=> hot fix to show deleted pages

components/common/CharmEditor/components/inlinePalette/components/InlineCommandPalette.tsx, components/common/CharmEditor/components/inlinePalette/components/InlinePaletteRow.tsx
=> Polish CSS for component dropdown

components/common/PageLayout/PageLayout.tsx, hooks/useResize.ts
=> Fix sidebar in nexus

components/common/IntlProvider.tsx
this also seems to shave off 50KB of our build :)
=> Disable intl

components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeaders.tsx, components/common/BoardEditor/focalboard/src/widgets/TextInput.tsx, theme/index.ts
We were using useMemo which caused the click handlers to be using stale state
=> Fix editing table columns

components/members/MemberDirectoryPage.tsx
=> Restore member dir properties sidebar icon

components/settings/roles/components/RoleRow.tsx
we need to stop propagation of clicks to not expand/collapse the row, but also want to use bindTrigger so the anchor el is set properly
=> fix position of role edit menu

components/common/Modal/Modal.tsx, components/settings/invites/components/TokenGates/TokenGates.tsx, lit-share-modal-v3.d.ts, next.base.js, package-lock.json, package.json, pages/_app.tsx
This fixes a link at the end to find out more about conditions that leads to a 404. I also realized we're using the 'react 17' version, updating to regular version seems to work fine.
=> update Lit Protocol modal

components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx, components/common/PageLayout/components/PageNavigation/components/TreeRoot.tsx, lib/pages/mapPageTree.ts
fix for https://app.charmverse.io/charmverse/page-39935349937146336
and a bit of refactor
=> Fix dropping parent page onto child in nav tree

pages/api/profile/index.ts, pages/api/spaces/index.ts
https://discord.com/channels/894960387743698944/1070230124932370513
Fix weird case when profile was loaded from cache for logged-out user + remove cache from spaces
=> Do not cache profile and spaces endpoints

components/profile/components/UserDetails/hooks/useUpdateProfileAvatar.ts, components/settings/workspace/LargeAvatar.tsx, components/settings/workspace/ProgressOverlay.tsx, lib/deepdao/client.ts, pages/api/profile/avatar.ts
user was reporting they couldn't upload an avatar but also didn't see an error. This is some cleanup and made it so we show the reason it failed to the user
=> improve UX of selecting an avatar

pages/404.tsx
=> Custom 404 page

components/common/CharmEditor/components/callout/components/Callout.tsx
=> Wrap flex box for callout component

pages/[domain]/settings/space.tsx
We need to restrict the user from typing special characters into domain name.
=> Check strict rules for space domain name

components/common/CharmEditor/components/iframe/config.ts, components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx, components/common/CharmEditor/components/video/VideoNodeView.tsx, lib/utilities/__tests__/strings.spec.ts, lib/utilities/strings.ts
Example: https://odysee.com/@Coldfusion:f/google-panics-over-chatgpt-the-ai-wars:a
=> Add support for Odysee video

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/BlockAligner.tsx, components/common/CharmEditor/components/CryptoPrice.tsx, components/common/CharmEditor/components/Resizable/Resizable.tsx, components/common/CharmEditor/components/ResizableImage.tsx, components/common/CharmEditor/components/bookmark/BookmarkNodeView.tsx, components/common/CharmEditor/components/callout/components/Callout.tsx, components/common/CharmEditor/components/common/EmptyEmbed.tsx, components/common/CharmEditor/components/iframe/IframeComponent.tsx, components/common/CharmEditor/components/listItem/listItem.component.ts, components/common/CharmEditor/components/listItem/listItem.nodeViewPlugin.ts, components/common/CharmEditor/components/nft/NFTNodeView.tsx, components/common/CharmEditor/components/tweet/TweetNodeView.tsx, components/common/CharmEditor/components/video/VideoNodeView.tsx, components/common/PageLayout/components/Header/components/DatabasePageOptions.tsx
1. disable updating callout icon
2. disable deleting a bookmark
3. Undo for page actions (w/ view and comment permission)
4. Checking todo
=> FIxed readonly board and page issues

components/forum/components/CreateForumPost.tsx
- button inlined with input
- input not focusable
=> Update create post styling

components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/AddPagePermissionsForm.tsx
https://www.loom.com/share/ee9bfca9c8c74c7991fd186f777ab073
=> Fix alert + loader issue on Firefox/Arc

.eslintrc.json, components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx, components/common/PageLayout/components/Header/components/DatabasePageOptions.tsx, components/profile/components/IdentityModal.tsx, components/profile/components/Integration.tsx, package-lock.json, package.json
it's a no-brainer to check that hook are always applied in the same order.. unfortunately, this lint rule didn't catch what is crashing in production. (The issue I have is with no-exhaustive-deps, but I just disabled  that one for now)
The error in prod is:
```
console error: Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```
=> add lint rule for hook order

prisma/migrations/20230207221149_add_pagepermissions_indexc/migration.sql, prisma/schema.prisma
We have an issue deleting many permissions by ID. This should speed things up
=> Add page permissions index by id

prisma/migrations/20230206213934_add_postcategorypermission_indexes/migration.sql, prisma/schema.prisma
Add indexes for querying post category permissions
- By post category ID
- By postcategory ID + assignee type (space, role, public)
=> Add post category permission indexes

__e2e__/utils/mocks.ts
Fixes an e2e test throwing when merged to main.
I have't been able to reproduce the server integration test error yet
https://github.com/charmverse/app.charmverse.io/actions/runs/4123398723/jobs/7121631394
=> Fix broken CI

components/profile/components/MemberMiniProfile/BlockchainData/NftsList.tsx, components/profile/components/MemberMiniProfile/BlockchainData/OrgsList.tsx, components/profile/components/MemberMiniProfile/BlockchainData/PoapsList.tsx, components/profile/components/MemberMiniProfile/MemberMiniProfile.tsx
=> Hide empty poaps, nfts & orgs section in member mini-profile

components/profile/components/UserDetails/UserDetails.tsx
Safety check for user wallets
https://discord.com/channels/894960387743698944/1073589821777379338
=> Safety check for user wallets

lib/permissions/pages/triggers/page-permission-added.ts
First step in preventing the page permissions bug
=> Optimise deleteMany operation

lib/votes/aggregateVoteResult.ts, lib/votes/calculateVoteStatus.ts, lib/votes/getVote.ts, scripts/closeOutProposals.ts
Script for closing proposals in CharmVerse
=> Close out proposals

components/common/PageLayout/components/Header/components/DatabasePageOptions.tsx
Before, we were importing a csv table without showing the columns on a table view.
Now, the properties will be visible for table view, but not for other views.
Notion does the same.
=> After csv import -> show table columns

.ebextensions/00_env_vars.config, .env.example, .github/workflows/deploy_serverless_prod.yml, components/settings/api/Api.tsx, components/settings/api/utils.ts, lib/discord/upsertUserForDiscordId.ts, lib/public-api/createWorkspaceApi.ts, lib/public-api/interfaces.ts, lib/spaces/createWorkspace.ts, lib/users/createUser.ts, lib/webhook/interfaces.ts, lib/webhook/publisher.ts, lib/webhook/subscribeToEvents.ts, pages/api/spaces/[id]/set-webhook.ts, pages/api/v1/spaces/index.ts
- use env to know which queue to send events
- allow passing admin username and avatar
- allow passing a webhook URL, for which we'll generate a signing secret and return it in the response
=> Game7 updates

components/common/PageLayout/components/DocumentHistory/index.tsx, components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/components/DocumentHistory.tsx
some cleanup, i kept the tooltip though which shows when the doc was created. Notion has this in the dropdown as well
=> remove last edited from header

components/common/PageLayout/components/Sidebar/Sidebar.tsx
Just some tweaks from Chris's mockups that didn't make it
=> adjust order of static items in sidebar

__e2e__/forum/deletePostFromDialog.spec.ts, __e2e__/po/forumHome.po.ts, components/common/BoardEditor/focalboard/src/components/dialog.tsx, components/common/PageActions.tsx, components/common/PageActionsMenu.tsx, components/forum/ForumPage.tsx, components/forum/components/PostDialog/PostDialog.tsx, components/forum/components/PostDialog/PostDialogGlobal.tsx, components/forum/components/PostDialog/index.tsx
Consume permissions engine for posts inside the context menu
=> Fix delete button in the context menu

components/common/CharmEditor/components/inlinePalette/editorItems/text.tsx, components/common/CharmEditor/components/rowActions/RowActionsMenu.tsx
[Task card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=81340508-c586-4b77-ad96-5a76ce00bc73)
=> Fixed issues with disclosure block

components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderPropertiesMenu.tsx, components/common/BoardEditor/focalboard/src/widgets/propertyMenu.tsx
1. Renamed checkbox to toggle
2. Used outlined toggle icon for toggle property
=> Convert checkbox to toggle in focalboard

components/profile/components/SpacesMemberDetails/components/SpaceDetailsAccordion.tsx
https://app.charmverse.io/charmverse/page-02603375307007605
=> Fix space name spilling out of container

scripts/updateGettingStartedPage.ts, seedData/gettingStartedPage.ts
This provides a script to update the getting started page with no further manual input required from the developer.
=> Update getting started

components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
[Task Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=3d9358f6-a7da-4ccc-b62a-831204f3ca22)
Before
After
=> Fixed width layout for inline dbs

hooks/useSharedPage.ts, pages/_app.tsx
Failed API calls in public pages are being retried infinitely.
=> Fixed public pages (forums & bounties)

components/common/BoardEditor/focalboard/src/components/properties/user/user.tsx, components/common/BoardEditor/focalboard/src/components/table/table.scss, components/common/UserDisplay.tsx, components/common/form/InputSearchMember.tsx
=> Improving user property UX for focalboard

components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx, components/proposals/components/ProposalStepSummary.tsx, components/proposals/components/ProposalStepper.tsx, lib/proposal/canChangeProposalStatus.ts, lib/proposal/proposalStatusTransition.ts
https://app.charmverse.io/charmverse/page-17599231466415222?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=
https://user-images.githubusercontent.com/5198394/219355055-45e41fc7-640b-43f1-9c73-9c6d7ec695d1.mp4
=> Feat/proposal UI updates

components/integrations/components/IdentityProviders.tsx
=> fix google icon logo

components/common/BoardEditor/components/properties/SelectProperty/SelectProperty.tsx, components/common/BoardEditor/focalboard/src/components/calendar/fullCalendar.tsx, components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx, components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx, components/common/BoardEditor/focalboard/src/components/properties/dateRange/dateRange.tsx, components/common/BoardEditor/focalboard/src/components/properties/user/user.tsx, components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx, components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
Quick fix for showing empty placeholder in card view (notions shows them in card view), in table view they are not shown
=> Show empty placeholder in card view

components/common/Modal/SettingsDialog.tsx, components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
@valentinludu what do you think?
I made the sidebar width fixed and removed some extra padding that seemed unecessary:
It looks like Notion has added a little whitespace around menu items which I added too:
=> Save some space in Settings sidebar

__e2e__/publicBounties.spec.ts, __e2e__/publicPage.spec.ts, __e2e__/publicProposals.spec.ts, components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx, components/[pageId]/DocumentPage/components/BountyProperties/components/BountyPropertiesHeader.tsx, components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx, components/[pageId]/SharedPage/SharedPage.tsx, components/common/CharmEditor/components/inlineVote/components/VoteDetail.tsx, components/common/form/InputSearchRole.tsx, lib/bounties/interfaces.ts, lib/pages/interfaces.ts, lib/votes/getVotesByPage.ts, lib/votes/interfaces.ts, pages/api/bounties/[id]/permissions.ts, pages/api/pages/[id]/votes.ts, pages/api/proposals/[id]/index.ts, pages/api/public/pages/[...pageId]/index.ts, pages/api/roles/index.ts, pages/api/votes/[id]/user-votes.ts
[Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=a602d0ff-07e8-43af-bc4c-83e40dd98eb4)
Nested polls on public page
Proposal properties on public page
Bounty properties on public page
=> Public page details are not visible

components/profile/components/MemberMiniProfile/MemberMiniProfile.tsx, components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopup.tsx, components/profile/components/TimezoneAutocomplete.tsx
Edit name for each space in My Profile view was not updating the db.
The reason was a callback that was not refreshing the spaceId for each individual edit modal.
Also fixed a warning on AutoSelect.
=> Fix member profile edit

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx, components/bounties/BountiesPage.tsx, components/bounties/components/BountiesKanbanView.tsx, components/bounties/components/NewBountyButton.tsx, components/common/PageDialog/PageDialog.tsx, components/common/PageLayout/NexusLayout.tsx, components/common/PageLayout/PageLayout.tsx, components/proposals/ProposalsPage.tsx, components/proposals/components/ProposalStepSummary.tsx, components/proposals/components/ProposalsTable.tsx
The fix was basically to move the PageDialog component into the separate page components for bounties and proposals and not be global. I also updated the code to use the path as source of truth and not 'fake it'
=> close popup when navigating to another page

.github/actions/build_docker_image/action.yml, .github/workflows/deploy_staging.yml, .github/workflows/destroy_staging.yml, scripts/migrations/2023_02_23_migrateProposals.ts
Lets revert this change once lib is stable
=> Deploy hotfix for AWS lib

.vscode/settings.json, components/settings/workspace/ImportContent.tsx, hooks/useNotionImport.tsx, pages/_app.tsx
Currently you have to click on settings to trigger notion import, this PR addresses that issue.
=> Trigger notion import automatically

components/[pageId]/EditorPage/EditorPage.tsx, components/settings/workspace/Space.tsx, pages/_app.tsx
[Task item](https://app.charmverse.io/charmverse/page-4890602409201261?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565)
=> Fix page title not updating

.ebextensions/00_env_vars.config, background/cron.ts, lib/aws/config.ts, lib/aws/webhookSqs.ts
Updated config for collabland webhook
=> Prod config for collabland sqs

__e2e__/bounties/createEditBounty.spec.ts, components/bounties/BountiesPage.tsx, components/bounties/components/BountiesKanbanView.tsx, components/bounties/components/BountyGalleryCard.tsx, components/bounties/components/BountyGalleryView.tsx, components/bounties/components/BountyKanbanCard.tsx
[Task Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=bfde0976-1489-4911-830f-d6373d80a195)
=> Gallery and board view for bounties

components/nexus/BountyTasksList.tsx, components/nexus/DiscussionTasksList.tsx, components/nexus/TasksPage.tsx
Chris mentioned to have two separate sections one for bounty and the other for discussions and they should have a single scrollbar.
=> Move bounty related discussions inside bounty nexus task

components/common/SpaceAccessGate/SpaceAccessGateWithSearch.tsx, pages/join.tsx
Go to a URL like https://app.charmverse.io/join?domain=doesnotexist and there's currently no way to search for a different space
=> show search input when joining a page that doesnt exist

pages/api/blocks/[id]/subtree.ts
I can't say for sure but I think duplicating cards has never worked
=> fix duplicating cards

lib/metrics/mixpanel/interfaces/UserEvent.ts, lib/public-api/createWorkspaceApi.ts
Tracking of space creation "source" for spaces created via API. Used superApiKey name to keep it simple
=> Add tracking of api space creation

lib/emails/templates/PendingTasks.tsx, pages/api/email-templates/index.ts
=> Show bounty discussions in bounty section for emails

__e2e__/forum/editDescription.spec.ts, __e2e__/forum/updateCategoryPermissions.spec.ts, __e2e__/po/forumHome.po.ts, charmClient/apis/forumApi.ts, components/forum/ForumPage.tsx, components/forum/components/CategoryContextMenu.tsx, components/forum/components/CategoryDescriptionDialog.tsx, hooks/useForumCategories.ts, lib/forums/categories/__tests__/updatePostCategory.spec.ts, lib/forums/categories/generateDefaultPostCategories.ts, lib/forums/categories/updatePostCategory.ts, prisma/migrations/20230303001452_post_category_description/migration.sql, prisma/schema.prisma
Allows editing the description of a post category
=> Show a description in forum categories

.ebextensions/00_env_vars.config, lib/collabland/collablandClient.ts
- use collabland api url from env rather than hardcoded one
- add more logging for easier debugging
- small refactor
=> Use collabland api url from env var

.ebextensions_cron/00_env_vars.config
cron worker has its own set of env vars
=> add collab api key to cron job

lib/collabland/collablandClient.ts
this throttles our requests to one per second. We should ask what would be acceptable for them.
=> rate limit requests to collab land

components/nexus/components/NotifyMeModal.tsx
Card: https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=d7dedd2f-971e-4b78-8800-a510ed0e2bdc
=> copy change for email input

components/common/BoardEditor/focalboard/src/components/calendar/fullcalendar.scss, components/common/BoardEditor/focalboard/src/styles/shared-variables.scss, components/common/BoardEditor/focalboard/src/theme.ts, theme/cssVariables.ts
Card: https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=96ec5b81-51df-40dd-beca-a1dd9baac450
=> fix white color of calendar events on white background

components/forum/components/CategoryMenu.tsx, components/forum/components/ForumFilterListLink.tsx
card: https://app.charmverse.io/charmverse/page-49366552253645923?viewId=0eb701c2-a378-41ab-b7a8-b06693bb9487&cardId=b0ab311a-e073-4a4f-94e6-1964fa8e2a80
=> add highlight to forums category sidebar

components/proposals/components/ProposalStepper/DesktopStepper.tsx
=> fix width of proposal stepper

components/common/BoardEditor/focalboard/src/components/properties/user/user.tsx
https://www.loom.com/share/89d1dcfb928846ee984889a05924e58e
=> notion ux for multi person property

components/common/CharmEditor/components/common/BlockNodeContainer.tsx, components/common/CharmEditor/components/file/File.tsx, components/common/CharmEditor/components/file/FileUploadForm.tsx, hooks/useS3UploadInput.ts
Update Charm Editor File style according to feedback
=> Fix file input layout

connectors.ts
You can add Sepolia to Metamask on Chainlist: https://chainlist.org/?testnets=true&search=sepolia
Also if you have an Alchemy account, you can get 1 ETH by signing in to their faucet: https://sepoliafaucet.com/
=> add Sepolia testnet

components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx, scripts/migrations/2023_03_13_fix_calendarViews.ts, seedData/space/space-da74cab3-c2b6-40bb-8734-0de5375b0fce-pages-1657887621286/page-[Your DAO] Home-66f0739b-2c65-457f-bd42-c5acf02f7b68/children/board-Calendar-74f5829b-6cf0-4810-8c9b-d9415157b991/blocks/view-block-2a9746f1-6eac-4084-a082-39e549b8035f.json
running the migration script i noticed almost all calendars missing a date property were from seed data :)
=> fix seed data for calendars

charmClient/apis/googleApi.ts, components/common/Modal/index.tsx, components/integrations/components/IdentityProviders.tsx, components/integrations/components/NewIdentityModal.tsx, components/login/CollectEmail.tsx, components/login/Login.tsx, components/login/WalletSign.tsx, hooks/useFirebaseAuth.tsx, lib/google/__tests__/disconnectVerifiedEmail.spec.ts, lib/google/disconnectVerifiedEmail.ts, lib/users/updateUsedIdentity.ts, pages/api/google/disconnect-email-account.ts
Improve the modal UX when connecting via email
Allow user to disconnect email account
=> Email ux improvements

lib/metrics/mixpanel/updateTrackGroupProfile.ts, lib/public-api/createWorkspaceApi.ts
Tracking origin (super api key name) in mixpanel space profile
=> Tracking space Origin in mixpanel

lib/templates/exports/templateCreator.json, lib/templates/exports/templateHackathon.json
__title should be put only inside visiblePropertyIds if the view is a gellery type.
=> Fix space template columns

components/common/Modal/ConfirmDeleteModal.tsx, components/common/Modal/Modal.tsx, components/login/CollectEmail.tsx, components/login/LoginPageContent.tsx, hooks/useFirebaseAuth.tsx, pages/authenticate.tsx
Improvements to UI of authenticate page
=> Improve the UI of the email login page

components/common/BoardEditor/components/properties/SelectProperty/SelectProperty.tsx, components/common/form/fields/SelectField.tsx
https://app.charmverse.io/charmverse/page-9722105202508626
-  fixed visual lgitch
- improved overall looks to be more notion-like
=> Improved select property styles

components/common/form/fields/TextInputField.tsx, components/profile/components/MemberMiniProfile/MemberMiniProfile.tsx, components/profile/components/UserDescription.tsx, components/profile/components/UserDetails/UserDetailsMini.tsx
Hotfix: https://discord.com/channels/894960387743698944/1087125446363205712
=> Fix member profiles

components/common/BoardEditor/focalboard/src/components/viewSidebar/GoogleDataSource/GoogleDataSource.tsx
When connecting a 2nd account:
=> fix another google button

components/members/MemberEmailForm.tsx, components/members/MemberOnboardingModal.tsx, components/settings/AccountSettings.tsx
=> Show email settings checkboxes in onboarding modal

components/common/PageLayout/components/Header/components/ShareButton/components/ShareToWeb.tsx
Will fix issue where user could not update the proposal public status
=> Use page permissions hook in share to web logic

components/nexus/BountyTasksList.tsx, components/nexus/DiscussionTasksList.tsx, components/nexus/ProposalTasksList.tsx, components/nexus/TasksPage.tsx, lib/discussion/getDiscussionTasks.ts, lib/discussion/getPropertiesFromPage.ts, lib/discussion/interfaces.ts, lib/emails/templates/PendingTasks.tsx, lib/proposal/getAccessibleProposals.ts, lib/proposal/getProposalTasks.ts, lib/proposal/getProposalsBySpace.ts, lib/proposal/interface.ts, pages/api/spaces/[id]/proposals.ts, prisma/migrations/20230323153201_proposal_comment_notification/migration.sql, prisma/migrations/20230324035748_page_comment_notification_type/migration.sql, prisma/schema.prisma
- replies to comments
- mentions in comments
- new comments
=> Proposal comment notifications

components/common/CharmEditor/components/disclosure/disclosure.ts, theme/@bangle.dev/styles.scss
Here comes my nemesis. Changed toggle implementation to make multi-row selection work as expected.
https://user-images.githubusercontent.com/5198394/227182629-6b999ddd-1a0c-4e5b-8330-e6c3d4ae82c6.mp4
https://app.charmverse.io/charmverse/page-17411641296138258
=> Rework and fix toggle component

components/settings/invites/components/TokenGates/components/TokenGatesTable.tsx
[Task item](https://app.charmverse.io/charmverse/page-03452081624962089)
=> Fix token gate copy link not visible on mobile

components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/AddPagePermissionsForm.tsx, components/common/PageLayout/components/Header/components/ShareButton/components/PagePermissions/PagePermissions.tsx
=> update placeholder when searching for users

components/settings/invites/components/TokenGates/components/TokenGateRolesSelect.tsx, components/settings/invites/components/TokenGates/components/TokenGatesTable.tsx
Align dropdown icon with the text
Make space between title and copy button of Token gates
=> Fix invites alignment

components/common/PageLayout/components/Sidebar/Sidebar.tsx, components/members/MemberDirectoryPage.tsx, components/proposals/ProposalsPage.tsx, hooks/useHasMemberLevel.tsx, pages/[domain]/bounties/index.tsx
Fixes the visual glitch where user would temporarily see "Guests do not have access to X"
=> Fix usage and definition of hasMemberLevel hook

components/integrations/components/NewIdentityModal.tsx, hooks/useDiscordConnection.tsx
Ways to reproduce:
Refresh your page.
Go to My Account and be sure you have only the wallet connected.
Connect Discord
Connect Telegram
Connect Google
Disconnect Discord
You will see Google and Telegram disappear, but if you refresh and go back to My Account you will see them connected.
=> Fix disconnecting discord resets the user context

lib/permissions/pages/actions/upsert-permission.ts, lib/permissions/pages/triggers/page-created.ts
I am not able to create pages in my test space - this whole process is timing out. BUt it is because resolvePageTree takes up to 5 seconds when you have 8000 pages, and the subsequent queries are using the same transaction which times out.
I do'nt have a fix for that case, but while debugging I cleaned up some of the code
=> minor improvements to creating page

package-lock.json, package.json
=> update to Typescript 5

components/common/BoardEditor/focalboard/src/components/properties/lastModifiedBy/lastModifiedBy.tsx, components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
=> Fixed empty property values in readonly mode

components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Sidebar/NotificationsBadge.tsx
[Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=2c92aa14-8324-4511-9ede-da0a62e5dfda)
=> Open notification by clicking on counter

components/common/CharmEditor/components/@bangle.dev/tooltip/trigger-input-rule.ts
[Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=10ab0400-b4eb-48e8-a622-27b5870fce17)
=> Allow @mentions with ( and [ infront (notion ux)

components/bounties/BountiesPage.tsx
=> Show better no open bounty ui

components/profile/components/UserDescription.tsx, components/profile/components/UserDetails/UserDetails.tsx
Fix "about me" input in user popup. Inputs will not be rendered while data is being loaded. 
Added sskeleteon loader for a bit better ux
=> Fix user details form

lib/members/getMemberSearchValue.ts, lib/members/getSpaceMembers.ts
Remove wallet addresses from frontend data
=> Remove wallet addresses from member search data

components/integrations/components/IdentityProviders.tsx
[Task item](https://app.charmverse.io/charmverse/page-01870383324177327)
=> Disconnect wallet text update

lib/pages/server/convertJsonPagesToPrisma.ts
i realized pages are being given creation dates prior to space being created
=> reset date fields on pages being created via template

components/[pageId]/DatabasePage/DatabasePage.tsx, components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx, lib/google/forms/syncFormResponses.ts
- tested editing properties, adding new select options, and submitting new responses
- tested re-sync button, which now has a confirmation modal
=> Allow users to edit google forms

components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/ConnectorButton.tsx, components/invite/InviteLinkPage.tsx, components/login/Login.tsx, hooks/useFirebaseAuth.tsx
Previous
Current
Works with both discord and email
=> Connect button for invite links

components/proposals/ProposalsPage.tsx, components/proposals/components/ProposalsTable.tsx, components/proposals/components/ProposalsViewOptions.tsx, components/proposals/hooks/useProposals.ts, lib/proposal/getAccessibleProposals.ts, pages/api/spaces/[id]/proposals.ts
Clean up while investigating an issue where proposal sort is inconsistent. Not 100% confident this will solve the issue, and I am waiting to get access to the original space to see if it is a data issue.
=> clean up sorting for proposals

components/common/CharmEditor/components/mention/components/Mention.tsx, components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx, components/common/PageLayout/components/PageIcon.tsx
[Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=8bae196c-0542-407e-9393-23e99cc3df85)
=> Add no access for hidden mention and nested pages

lib/focalboard/board.ts, lib/pages/createFormResponseCard.ts
Added names instead of 'Question X' as a title in a database.
=> Typeform questions

components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/createLinkedView.tsx, components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSourceOptions.tsx, hooks/useApiPageKeys.tsx
[Task item](https://app.charmverse.io/charmverse/page-9393383813528715)
=> Fix page id linked to apiPageKey

components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyPaymentButton.tsx, components/bounties/BountiesPage.tsx, components/bounties/components/BountiesKanbanView.tsx, components/bounties/components/BountyGalleryView.tsx, components/bounties/components/MultiPaymentButton.tsx, components/common/PageLayout/components/Sidebar/Sidebar.tsx, components/common/form/InputSearchRole.tsx, components/settings/roles/hooks/useImportDiscordRoles.ts, connectors.ts, hooks/useGnosisPayment.ts, hooks/useSettingsDialog.tsx, lib/bounties/createBounty.ts, lib/payment-methods/defaultPaymentMethods.ts
- Fixed: closing a bounty popup on "Admin" tab redirects you back to "Open" tab
- Set "Require applications" to false by default (Alex request)
- Better error messages
- Use ETH as native currency for Optimsim but add OP as a default payment method
=> improve bounty UX

package-lock.json
original: https://github.com/charmverse/app.charmverse.io/pull/2197
=> Bump socket.io-parser from 4.2.2 to 4.2.3

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/PageDeleteBanner.tsx, components/_app/GlobalComponents.tsx, components/common/Banners/Banner.tsx, components/common/Banners/PaidAnnouncementBanner.tsx, components/common/PageLayout/PageLayout.tsx
Reverts charmverse/app.charmverse.io#2237 and brings back the paid announcement banner
=> Revert "Revert "Show paid announcement banner""

components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSourceOptions/useSourceOptions.tsx, components/common/BoardEditor/focalboard/src/store/cards.ts, components/common/PageActions/components/DatabasePageActionList.tsx, components/common/PageActions/utils/__tests__/databasePageOptions.spec.ts, components/common/PageActions/utils/databasePageOptions.ts, components/proposals/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts, components/proposals/components/ProposalsBoard/utils/boardData.ts, components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx, components/rewards/components/RewardApplicationPage/components/ApplicationComments.tsx, components/rewards/components/RewardProperties/hooks/useRewardsBoardAdapter.ts, components/rewards/components/RewardsBoard/utils/boardData.ts
- application comments always visible, even if it was rejected
- hide submission input if application was rejected
=> minor rewards fixes

__e2e__/charmEditor/dragAndDrop.spec.ts
=> Fix dragAndDrop e2e test

components/common/CharmEditor/components/link/link.ts
=> Better handling of URLs to convert to pages

components/common/BoardEditor/focalboard/src/store/cards.ts, lib/focalboard/card.ts
=> Fixed broken card property types

components/common/BaseLayout/components/Header.tsx, components/login/LoginPageContent.tsx, hooks/useBaseCurrentDomain.tsx
Login page cleanup:
- remove unnecessary flag (isCustomDomaiin)
- add loading state for custom domains
- fix flickering text
In total, a nicer user experience for custom domains.
=> Fix flicker on login page and add loading for custom domain

components/settings/space/components/ConnectCollabland.tsx, lib/collabland/__tests__/disconnectSpace.spec.ts, lib/collabland/disconnectSpace.ts
=> Skip deleting collabland roles after disconnecting

components/[pageId]/DocumentPage/DocumentPage.tsx, components/rewards/RewardsPage.tsx, components/rewards/components/NewInlineReward.tsx, components/rewards/components/RewardProperties/RewardProperties.tsx, components/rewards/components/RewardProperties/hooks/useRewardsBoardAdapter.ts, components/rewards/hooks/useRewardPage.ts, components/rewards/hooks/useRewards.tsx, pages/api/rewards/[id]/index.ts, pages/api/rewards/[id]/is-editable-by-applicants.ts, pages/api/rewards/index.ts, pages/api/spaces/[id]/reward-templates.ts
Fix card rewards adding and editing. Most of the issues related to this was caused by the fact that pageId !== rewardId in such case.
Additionally polished a few details.
=> Fix inline card rewards

components/[pageId]/DocumentPage/DocumentPage.tsx
[Card](https://app.charmverse.io/charmverse/card-properties-not-available-when-creating-a-template-3167342476071229)
=> Show card properties during template creation

components/forum/components/ForumFilterListLink.tsx, lib/forums/categories/deletePostCategory.ts
[Card](https://app.charmverse.io/charmverse/can-t-delete-forum-category-8151910955248065)
=> Delete forum category with archived posts

components/members/components/MemberDirectoryProperties/MemberPropertySidebarDetails.tsx, components/members/components/MemberDirectoryTableView.tsx, components/members/components/MemberProfile/components/ProfileWidgets/components/MemberPropertiesWidget/MemberProperties.tsx, components/members/components/MemberProfile/components/UserSpacesList/components/UserSpacesListItem.tsx
[Card](https://app.charmverse.io/charmverse/url-properties-in-member-profile-for-space-should-be-clickable-and-open-a-new-window-35388775503984515)
=> Clickable member directory url property

components/common/form/ColorSelectMenu.tsx, components/common/form/fields/Select/SelectOptionEdit.tsx, components/proposals/components/ProposalCategoriesList.tsx, components/proposals/components/ProposalViewOptions/components/ProposalCategoryContextMenu.tsx
=> Select and update proposal category color

serverless/webhooks/publisher.ts
[Card](https://app.charmverse.io/charmverse/take-messages-off-the-queue-when-a-webhook-endpoint-fails-7676935849524991)
=> Remove message from queue when webhook endpoint fails

components/settings/api/ApiSettings.tsx, components/settings/roles/components/RoleForm.tsx, components/settings/space/components/NotificationToggles.tsx
1. API Toggles
2. Notifications
3. Role select placeholder
=> Change more bounty copies to reward

components/common/CharmEditor/components/CryptoPrice.tsx, lib/middleware/requireUser.ts, pages/api/crypto-price/index.ts, theme/@bangle.dev/styles.scss
=> Fixed cryptoprice block not working in public pages

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx, components/[pageId]/DocumentPage/components/Sidebar/components/ProposalSidebar/ProposalSidebar.tsx, components/common/PageLayout/components/Header/components/ToggleEvaluationButton.tsx, components/proposals/components/ProposalProperties/ProposalPropertiesBase.tsx
Just some ideas i had, will send them to Chris for review
=> tweaks to Evaluation copy

scripts/migrations/2023_11_21_add_rewardColumns.ts
=>  write a script to add visible columns to rewards

components/[pageId]/DocumentPage/DocumentPage.tsx
[Card](https://app.charmverse.io/charmverse/card-ux-update-47568318855731984)
=> Add 5 lines of min editor height for card

components/settings/account/hooks/useLensProfile.ts
[Conversation](https://discord.com/channels/894960387743698944/1176899726117974036)
=> Use first wallet to fetch lens profile if no account is connected

scripts/migrations/2023_11_21_migrate_oldLists.ts
=> remove old list component nodes from docs

components/members/components/MemberProfile/components/ProfileWidgets/components/LensProfileWidget.tsx, lib/pages/comments/syncPageCommentsWithLensPost.ts
=> Fixed Lens profile avatar url

components/rewards/components/RewardApplicationPage/components/RewardSubmissionInput.tsx
[Card](https://app.charmverse.io/charmverse/users-can-not-submit-for-a-rewards-with-a-custom-rewards-4202910661164456)
=> Fixed issue with custom reward submission

components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx
=> Use checkbox for boolean filter

components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx, lib/rewards/blocks/constants.ts
=> Disable renaming, deleting and duplicating default reward properties

components/common/CharmEditor/components/linkedPage/components/LinkedPagesList.tsx
[Discussion](https://discord.com/channels/894960387743698944/1176914246081200179)
=> Add sidebar items to bottom of linked page menu list

components/[pageId]/DocumentPage/components/Sidebar/components/ProposalSidebar/RubricResults.tsx, components/common/BaseLayout/components/Header.tsx, components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx, components/common/BoardEditor/components/properties/UserSelect.tsx, components/common/BoardEditor/focalboard/src/components/properties/createdBy/createdBy.tsx, components/common/BoardEditor/focalboard/src/components/properties/lastModifiedBy/lastModifiedBy.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx, components/common/CharmEditor/components/mention/components/MentionSuggest.tsx, components/common/CharmEditor/components/suggestions/SuggestionCard.tsx, components/common/CharmEditor/components/thread/PageThread.tsx, components/common/PageLayout/components/Sidebar/components/SidebarSubmenu.tsx, components/common/UserDisplay.tsx, components/common/comments/Comment.tsx, components/common/comments/CommentForm.tsx, components/common/comments/CommentReply.tsx, components/common/form/InputSearchMember.tsx, components/forum/components/CreateForumPost.tsx, components/forum/components/PostList/components/PostCard.tsx, components/forum/components/PostPage/PostPage.tsx, components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx, components/rewards/components/RewardApplications/RewardApplicantTableRow.tsx
=> Consistent user display avatar and username

components/login/components/Footer.tsx
Feedback from Alex:
Make footer smaller + align the text to the right - for non logged in pages when user is on custom domain.
=> Improve layout footer

components/rewards/components/RewardProperties/RewardPropertiesForm.tsx, components/rewards/components/RewardProperties/components/RewardPropertiesHeader.tsx, scripts/migrateSpaceResources.ts
The banner was not disappearing
This ensures the permissions banner disappears properly when invoked
=> Refresh check to ensure banner disappears

components/common/Avatar.tsx, components/common/CharmEditor/components/ResizableImage.tsx, components/common/CharmEditor/components/file/File.tsx, lib/focalboard/board.ts, lib/members/getSpaceMembers.ts, lib/utilities/__tests__/url.spec.ts, lib/utilities/url.ts, pages/api/pages/[id]/index.ts, pages/api/spaces/[id]/index.ts, pages/api/spaces/[id]/pages.ts, pages/api/spaces/index.ts, pages/api/spaces/search-domain.ts, scripts/blacklistSpace.ts
=> rewrite s3 domain of user images

components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderDisplayByMenu.tsx, components/rewards/RewardsPage.tsx, hooks/useProposalBlocks.tsx, hooks/useRewardBlocks.tsx, lib/proposal/blocks/interfaces.ts, lib/rewards/blocks/interfaces.ts, lib/rewards/blocks/upsertDefaultRewardsBoard.ts, lib/rewards/blocks/views.ts, scripts/migrations/2023_11_22_migrateCustomBoardsBlocks.ts
- fix calendar view date property
- fix updating properties and data migration for table and caleendar views
=> Fix data migration

components/common/BoardEditor/focalboard/src/components/table/table.tsx, components/proposals/ProposalsPage.tsx, components/rewards/RewardsPage.tsx
Make values in rewards and proposals table views readonly
=> Readonly rewards and proposals rows

jest.setup.browser.ts, package.json
Fixes a subdependency https://github.com/charmverse/app.charmverse.io/security/dependabot/80
=> bump dev tools with security issue

components/proposals/components/ProposalProperties/components/ProposalRubricCriteriaInput.tsx, lib/proposal/getProposal.ts, lib/proposal/getProposalTemplates.ts, lib/proposal/rubric/__tests__/upsertRubricCriteria.spec.ts, lib/proposal/rubric/upsertRubricCriteria.ts, lib/proposal/updateProposalStatus.ts, package.json, pages/api/proposals/[id]/index.ts, stories/ProposalsPage/Proposals.stories.tsx
=> save changes when sorting rubric criteria

components/common/BoardEditor/components/kanban/KanbanGroupColumn.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanban.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx, components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx, components/common/BoardEditor/focalboard/src/components/table/table.tsx, components/common/BoardEditor/focalboard/src/components/table/tableGroup.tsx, components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx, components/common/BoardEditor/focalboard/src/components/table/tableRows.tsx, components/rewards/RewardsPage.tsx
=> Make reward application rows distinct with empty value

components/common/BoardEditor/focalboard/src/components/dialog.tsx, components/members/components/MemberProfile/components/ProfileWidgets/components/MemberPropertiesWidget/MemberPropertiesFormDialog.tsx
=> Fixed UserOnboardingModal footer action submit button padding

lib/notifications/cards/getCardNotifications.ts, lib/pages/__tests__/modifyChildPages.spec.ts, lib/pages/modifyChildPages.ts
Fix loading of notifications and cleanup of card notifications
Notifications list was failing because the linked page was deleted
=> Fix card notifications

components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/[pageId]/DocumentPage/hooks/usePageSidebar.tsx
=> remember if user closes the sidebar and only show sidebar if its time to review

components/members/components/MemberDirectoryProperties/MemberPropertiesSidebarItem.tsx, components/members/components/MemberDirectoryProperties/MemberPropertySidebarDetails.tsx
=> Fix toggling member property required field in free spaces

lib/permissions/bounties/__tests__/computeBountyPermissions.public.spec.ts, lib/permissions/bounties/computeBountyPermissions.public.ts
Fix ability to self-submit reward for free space
This wasn't done when we did rewards initially
=> Fix permissons for free space

hooks/useRewardBlocks.tsx
=> Fixed rewards db views gets replaced after updating custom reward property

components/rewards/components/NewInlineReward.tsx, components/rewards/components/NewRewardButton.tsx, components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
[Card](https://app.charmverse.io/charmverse/add-option-to-select-a-template-from-the-new-reward-form-like-we-have-in-proposals-5916909766067366)
=> Select reward template in rewards page create button & card

components/rewards/components/RewardApplicationPage/components/RewardSubmissionInput.tsx
Rich charmeditor in reward submission
=> CharmEditor in reward submission

components/rewards/components/RewardApplicationPage/components/RewardPaymentButton.tsx, components/settings/account/components/MultiSigList.tsx, connectors/chains.ts, hooks/useGnosisPayment.ts, hooks/useGnosisTransaction.tsx, hooks/useImportSafes.tsx, hooks/useMultiRewardPayment.ts, lib/blockchain/provider/ankr/client.ts, lib/gnosis/__tests__/getSafeTxStatus.spec.ts, lib/gnosis/getSafeTxStatus.ts, lib/gnosis/gnosis.ts, lib/gnosis/mantleClient.ts, lib/gnosis/safe/getSafeApiClient.ts
Fixed importing gnosis safes in account as well as mantle lookup
Gnosis safe imports in the account were failing, so was Mantle
=> Fix fetching Gnosis Safes

components/[pageId]/DatabasePage/DatabasePage.tsx, components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
https://app.charmverse.io/charmverse/filters-sort-broken-for-multiple-inline-dbs-on-same-page-23599280070275652
=> Fix filtering for inline databases

components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSidebar.tsx, components/common/form/InputEnumToOptions.tsx
=> Fix proposal cetegory permissions

components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx, components/forum/ForumFeedPage.tsx, components/forum/components/PostDialog/PostDialog.tsx, components/forum/components/PostPage/PostPage.tsx
Makes it easier to find other posts in the topic from full page view:
=> add category to forum breadcrumbs

__e2e__/proposals/proposalFlow.spec.ts, __e2e__/proposals/viewProposal.spec.ts, components/proposals/components/ProposalsBoard/utils/boardData.ts, pages/[domain]/[pageId].tsx
=> proposals page: full page layout by default

stories/Databases/CardDetails.stories.tsx, stories/Databases/Kanban.stories.tsx, stories/Databases/TableProperties.stories.tsx, stories/Members/MemberDirectory.stories.tsx, stories/ProposalsPage/Proposals.stories.tsx, stories/Rewards/Pages/NewRewardPage.stories.tsx, stories/Settings/Settings.stories.tsx, stories/lib/GlobalContext.tsx
Note: I added all the providers necessary in the GlobalContext component; that way we don't need to concern ourselves whether all the providers are being passed or not. Just wrap your component inside `GlobalContext` and you should be good to go. If we need to modify the initial state of a context provider, it should be passed via a prop.
=> Fixed storybook build issue

__integration-tests__/server/pages/api/v1/proposals/[proposalId]/comments/[commentId]/delete.spec.ts, pages/api/v1/proposals/[proposalId]/comments/[commentId]/index.ts
=> add endpoint to delete comments

components/proposals/components/ProposalProperties/ProposalPropertiesBase.tsx
[Card](https://app.charmverse.io/charmverse/category-empty-for-a-public-proposal-10713314848356204)
=> Show public proposal category in card and full page view

__integration-tests__/server/pages/api/v1/spaces/[spaceId]/members/index.spec.ts, lib/public-api/interfaces.ts, lib/summon/addUserToSpace.ts, pages/api/v1/spaces/[spaceId]/members/index.ts
Summon team agreed they will just send us the user's summon id instead.
Another change I made is that summonUserId is not required to use this endpoint
=> expect summonUserId to be provided when member is added

pages/api/v1/spaces/[spaceId]/members/index.ts
=> fix api docs for members endpoint

lib/focalboard/cardFilter.ts
[Card](https://app.charmverse.io/charmverse/should-create-new-cards-with-the-filtered-member-the-way-we-would-filtered-multiselect-6425044077588473)
=> Populate person property in a filter when creating a new card

components/common/CustomEmojiPicker.tsx, components/common/ImageSelector/ImageSelector.tsx, components/common/ImageSelector/ImageUploadButton.tsx, components/settings/space/components/LargeAvatar.tsx, hooks/useS3UploadInput.ts, lib/file/constants.ts, pages/api/image/resize.ts
[Card](https://app.charmverse.io/charmverse/resize-all-uploaded-images-7723593554479748)
=> Resize uploaded images to fixed dimension

components/members/components/MemberProfile/components/ProfileWidgets/components/SummonProfileWidget.tsx, components/members/hooks/useRequiredMemberProperties.ts, lib/summon/interfaces.ts
[Recording](https://www.loom.com/share/6ef62153189a4a4d8d68f70c564080bb)
Also fixed calculation of achievements and skills of summon profiles
=> Fixed disabled save button when no socials are provided

components/common/BaseLayout/components/Header.tsx, components/common/UserDisplay.tsx
[Discussion](https://discord.com/channels/894960387743698944/1184944927008903218)
=> Show avatar in header in non space pages

components/[pageId]/DocumentPage/DocumentPage.tsx
=> Hide db properties from reward

lib/websockets/spaceEvents.ts
[Discussion](https://discord.com/channels/894960387743698944/1185006361059274877)
=> Fixed deleting pages without position in parent document

components/common/BoardEditor/components/properties/TextInput.tsx, components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx, components/common/PopperPopup.tsx
=> Disable the popup for database titles on mobile

background/tasks/updateProposalStatus/task.ts, charmClient/hooks/proposals.ts, components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/hooks/useProposal.ts, components/common/PageActions/components/SnapshotAction/PublishToSnapshot.tsx, components/common/PageActions/components/SnapshotAction/PublishingForm.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/VoteSettings.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteSidebar.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/components/CompleteFeedbackButton.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/components/GoBackButton.tsx, lib/proposal/interface.ts, lib/proposal/updateProposalEvaluation.ts, pages/api/proposals/[id]/snapshot.ts
=> Add Snapshot voting to evaluations

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/EvaluationSettingsSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationSettings.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailSidebar.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/components/CompleteFeedbackButton.tsx, components/proposals/ProposalPage/components/WorkflowSelect.tsx, components/proposals/ProposalPage/hooks/useNewProposal.tsx, lib/proposal/createProposal.ts
https://discord.com/channels/894960387743698944/1161331165886697532/1186843783283875942
- fixed padding on mobile
- fixed the sidebar not reloading
- added a Configure button on mobile. Maybe the content should be inline on mobile? Maybe just when creating a proposal?
- bug fix: reviewers and workflow are readonly when using a template
- The button for feedback now just says "Complete <Evaluation title>' if there is no further step
=> fixes from Chris for proposals

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx, components/[pageId]/DocumentPage/hooks/useProposal.ts, components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/EvaluationSettingsSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationSettings.tsx, components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/components/OpenEvaluationButton.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/components/PublishRewardsButton.tsx, components/proposals/components/ProposalRewards/ProposalRewards.tsx
=> Polish in evaluation sidebar

components/common/Modal/ModalWithButtons.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricSidebar/RubricAnswersForm.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/components/GoBackButton.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/components/PublishRewardsButton.tsx, components/proposals/components/ProposalRewards/ProposalRewards.tsx, lib/proposal/updateProposalEvaluation.ts
=> Allow going back in proposal steps

components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationSettings.tsx, lib/proposal/createProposal.ts, scripts/migrations/2023_11_30_convertProposals.ts
=> update conversion script to support permissions

components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/components/OpenEvaluationButton.tsx, components/proposals/ProposalPage/hooks/useNewProposal.tsx
- sticky footer : change button to say "Vote" instead of "Evaluate"
- require content for free-form templates
=> UI tweaks from proposals QA

pages/api/votes/[id]/cast.ts
Fix permission we use
Evaluate is now the relevant one
=> Fix voting permissions

background/tasks/refreshBountyApplications/task.ts, background/tasks/verifyTokenGateMemberships/task.ts, lib/tokenGates/__tests__/verifyTokenGateMembership.spec.ts, lib/tokenGates/updateUserTokenGates.ts, lib/tokenGates/verifyTokenGateMembership.ts, lib/tokenGates/verifyTokenGates.ts, testing/utils/tokenGates.ts
Changes:
1. Fix cron for token gates.
2. Fixed logs.
=> Verify all types of token gates

__e2e__/memberOnboarding.spec.ts, __e2e__/proposals/proposalFlow.spec.ts, __e2e__/proposals/proposalTemplate.spec.ts, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/hooks/useNewProposal.tsx
=> send user to the new proposal instead of proposal pages

components/settings/proposals/SpaceProposalSettings.tsx, components/settings/proposals/components/ProposalWorkflow.tsx
=> dont let admin delete the last workflow

components/proposals/ProposalsPage.tsx
=> disable option to open proposals inside a dialog

lib/focalboard/__tests__/updateCardsFromProposals.spec.ts
=> Fix test flakiness by sorting cards

__integration-tests__/server/pages/api/proposals/[id]/rubric-criteria.spec.ts, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/EvaluationSettingsSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationSettings.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/RubricCriteriaSettings.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/OldProposalEvaluationSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricSidebar/RubricResults.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricSidebar/RubricSidebar.tsx, pages/api/proposals/[id]/rubric-criteria.ts
=> combine rubric results and decision tabs

lib/blockchain/updateLitDetails.ts, lib/tokenGates/__tests__/humanizeConditions.spec.ts, lib/tokenGates/humanizeConditions.ts
Show erc1155 name and image if possible.
=> Get nft image and name for ERC1155

components/common/BoardEditor/components/properties/ErrorWrapper.tsx, components/common/BoardEditor/components/properties/UserSelect.tsx, components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableRow.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/table/tableHeaders.tsx, components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu.tsx, components/proposals/ProposalsPage.tsx, components/proposals/hooks/useProposalsBoard.tsx
[Card](https://app.charmverse.io/charmverse/proposals-updated-column-5785901663768147)
[Card](https://app.charmverse.io/charmverse/multi-select-and-edit-rows-in-proposal-table-21506491975060316)
=> Drag and select + editable proposals card from table

components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu.tsx, hooks/useAreaSelection.ts, pages/api/spaces/[id]/proposals/blocks/index.ts
1. Disallow empty authors in proposals table
2. Fix background color of area selection for dark theme
3. Disable updating form field card properties
4. Fixed fetching proposal blocks for publicly available proposals
=> Disallow empty authors in proposals table

components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationStepSettings.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricEvaluation.tsx
=> some proposal polish

components/proposals/ProposalPage/NewProposalPage.tsx
=> fix e2e tests

components/[pageId]/DocumentPage/DocumentPage.tsx, scripts/migrations/2023_12_29_convertProposals.ts, scripts/query.ts
=> New migration script

components/common/BoardEditor/focalboard/src/utils.spec.ts, hooks/__tests__/useDateFormatter.spec.ts
=> Fixed broken browser tests

components/proposals/ProposalPage/components/EvaluationSidebar/components/EvaluationStepActions.tsx
Feedback doesn't have reviewer popup
No such thing as reviewers for feedback step
=> Hide feedback config

components/[pageId]/DocumentPage/components/Sidebar/components/CommentsSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation.tsx
Fix evaluation vote view alignment. Also added a more obvious "Create Vote" button
=> Fix vote sidebar

__e2e__/proposals/viewProposal.spec.ts, __integration-tests__/server/pages/api/proposals/[id]/rubric-criteria.spec.ts, __integration-tests__/server/pages/api/spaces/[id]/pages.spec.ts, lib/notifications/proposals/__tests__/createProposalNotifications.spec.ts, lib/permissions/api/overridenPermissionsApiClient.ts, lib/proposal/__tests__/getProposalTemplates.spec.ts, lib/proposal/getProposalTemplates.ts
Make sure we are using new model
An issue arose with the feature flag
=> Force usage of overriden permissions API

components/settings/proposals/components/EvaluationPermissions.tsx
=> replace description for vote permissions

lib/permissions/bounties/__tests__/computeBountyPermissions.spec.ts, lib/permissions/bounties/computeBountyPermissions.ts
https://app.charmverse.io/charmverse/milestones-reviewer-can-apply-to-assigned-reward-7642656749188084
=> Fix work permissions for assigned reward

components/proposals/components/ProposalRewards/AttachRewardButton.tsx, components/proposals/components/ProposalRewards/ProposalRewards.tsx
- remove  mimlesone reward banner
- fix milestone reward preview grid
=> Fix milestone rewards layout

components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/PageLayout/PageLayout.tsx, components/proposals/ProposalPage/NewProposalPage.tsx
=> add banner to announce proposals

components/settings/proposals/SpaceProposalSettings.tsx, components/settings/proposals/components/RequireTemplatesForm.tsx, components/settings/roles/components/RolePermissions/components/DefaultPagePermissions.tsx
Moves from Roles & Permissions to Proposals tab
=> move logic to require proposal templates

__integration-tests__/server/pages/api/proposals/[id]/index.public.spec.ts, __integration-tests__/server/pages/api/proposals/[id]/index.spec.ts, components/[pageId]/DocumentPage/components/ProposalProperties.tsx, lib/proposal/__tests__/updateProposal.spec.ts, lib/proposal/updateProposal.ts, pages/api/proposals/[id]/index.ts
=> fix editing proposal fields so they dont affect authors or reviewers

components/[pageId]/DocumentPage/DocumentPage.tsx, components/proposals/ProposalPage/components/ProposalFormFieldInputs.tsx, components/proposals/components/ProposalRewards/AttachRewardButton.tsx
Allow editing the structured form input
Was not hooked up to permissions
=> Use proposal permissions in structured proposal

__integration-tests__/server/pages/api/proposals/index.public.spec.ts, __integration-tests__/server/pages/api/proposals/index.spec.ts, charmClient/hooks/proposals.ts, components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx, components/[pageId]/DocumentPage/hooks/useProposal.ts, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/EvaluationSettingsSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationStepSettings.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/EvaluationStepActions.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/EvaluationStepSettingsModal.tsx, components/proposals/hooks/useProposalTemplates.tsx, lib/proposal/__tests__/createProposal.spec.ts, lib/proposal/createProposal.ts, pages/api/spaces/[id]/proposal-templates.ts
=> allow setting reviewers if not set in the template

lib/proposal/createDefaultProposal.ts, lib/proposal/createProposal.ts, lib/proposal/workflows/defaultWorkflows.ts, lib/spaces/createSpace.ts
Adds workflow to the default proposal
So it works well
=> Fix default proposal generation

components/common/form/FormField.tsx, components/common/form/FormFieldsEditor.tsx
https://app.charmverse.io/charmverse/bug-when-typing-in-proposal-title-cursor-jumps-to-form-field-897956050032948
focus form fields only on expand or add new
=> Proper focusing form fields

.github/actions/install/action.yml, .github/workflows/test_and_deploy.yml
Once core is merged in main, we should bump all downstream packages no matter what. Otherwise we can have apps out of sync
=> commit core right away before running tests

components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationStepSettings.tsx
=> allow admin to edit all settings even when using a template

scripts/migrations/2024_01_04_add_reviewers.ts
=> Script: Add reviewers to old proposal evaluations

lib/proposal/createDefaultProposal.ts
=> add vote settings to default proposal

components/rewards/components/RewardProperties/hooks/useRewardsBoardAdapter.ts
We can't/shouldn't mutate data that is returned by swr... i just fixed this exct issue in proposals yesterday (that one was my code :)
error in loom video: https://www.loom.com/share/4829d6e99d84450eb67421f4906bd8a3?sid=5b58bee1-2bd5-474a-a117-44eaa6ab6330
=> fix adapter for reward view blocks

components/common/PageActions/components/DuplicatePageAction.tsx, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/components/NewProposalButton.tsx, components/proposals/hooks/useProposalTemplates.tsx
=> allow duplicating a template

components/common/form/FormField.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailEvaluation.tsx, theme/index.ts
=> Feat/edit form field UI

lib/spaces/countSpaceBlocks/__tests__/countProposalBlocks.spec.ts, lib/spaces/countSpaceBlocks/countProposalBlocks.ts
Updated block counts
Don't count form settings, only the values
=> Count form field answers and rubric answers

components/common/form/FormFieldInputs.tsx, components/common/form/hooks/useFormFields.ts, hooks/useDebouncedValue.ts
=> Autosave form changes

charmClient/hooks/proposals.ts, components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx, components/[pageId]/DocumentPage/hooks/useProposal.ts, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/EvaluationSettingsSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx, components/proposals/ProposalPage/components/WorkflowSelect.tsx, lib/proposal/updateProposalWorkflow.ts, pages/api/proposals/[id]/workflow.ts
=> Allow updating workflow of templates and draft proposals

components/common/BoardEditor/focalboard/src/components/gallery/__snapshots__/galleryCard.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.tsx
customer request. also follow's Notion's UI
=> dont show a placeholder for gallery images

components/proposals/ProposalPage/hooks/useNewProposal.tsx
=> require rubric criteria title

pages/api/v1/proposals/[proposalId]/comments/[commentId]/index.ts
=> fix api docs for creting a comment

__integration-tests__/server/pages/api/proposals/[id]/index.public.spec.ts, __integration-tests__/server/pages/api/proposals/[id]/index.spec.ts, lib/proposal/mapDbProposalToProposal.ts, pages/api/proposals/[id]/index.ts
=> make sure to sort rubric criteria properly in result

testing/generateBoardStub.ts
=> try fixing test again

components/common/PageActions/components/DocumentPageActionList.tsx, components/common/PageActions/components/ForumPostActionList.tsx
=> temporarily remove convert to proposal button

components/proposals/ProposalPage/NewProposalPage.tsx, lib/focalboard/updateCardsFromProposals.ts, lib/proposal/__tests__/createProposal.spec.ts, lib/proposal/createProposal.ts, pages/api/proposals/index.ts
[Discussion](https://discord.com/channels/894960387743698944/1194473401931276298)
=> Create a new form and form fields when duplicating proposal templates

lib/focalboard/__tests__/createCardsFromProposals.spec.ts, lib/focalboard/__tests__/updateCardsFromProposals.spec.ts, lib/focalboard/createCardsFromProposals.ts, lib/focalboard/updateCardsFromProposals.ts, lib/pages/createCardPage.ts, testing/__tests__/generateBoard.spec.ts, testing/generateBoardStub.ts, testing/setupDatabase.ts
Fix proposal permission creation to inherit from parent board
We were defaulting the space-wide permission
=> Fix page permissions created with proposals

__e2e__/convertPageToProposal.spec.ts, __e2e__/forum/convertToProposal.spec.ts
=> disable e2e for convert to proposal

scripts/migrations/2024_01_10_removeDuplicateNotifications.ts
=> Remove duplicate notification migration script

lib/focalboard/updateCardsFromProposals.ts, scripts/resyncBoardPermissions.ts
Bring boards back in sync
Fix old permission creation
=> Script for resyncing boards with proposals as datasource

components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailEvaluation.tsx, pages/api/proposals/[id]/submit-result.ts, serverless/sqs/worker.ts
=> Create sqs message before processing notification

components/proposals/ProposalPage/NewProposalPage.tsx
=> Fix proposal form field title losing focus during typing

scripts/migrations/2024_01_10_splitStructuredProposalForms.ts.ts
=> Split structured proposal form migration script

components/[pageId]/DocumentPage/DocumentPage.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx
=> fix logic for proposal templates on mobile

components/common/BoardEditor/components/properties/TagSelect/TagSelect.tsx, components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/PersonPropertyTemplateMenu.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/PropertyTemplateMenu.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/SelectPropertyTemplateMenu.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/viewHeaderRowsMenu.tsx, components/common/CharmEditor/components/BlockAligner.tsx, components/common/TemplatesMenu/TemplatePageActionMenu.tsx, components/common/TemplatesMenu/TemplatesMenu.tsx, components/proposals/components/NewProposalButton.tsx
[Discussion](https://discord.com/channels/894960387743698944/1037760892965748827/threads/1192592148793655317)
=> Fix UI for select property in view headers menu

__e2e__/po/proposalPage.po.ts, __e2e__/po/proposalsList.po.ts, __e2e__/proposals/archiveProposal.spec.ts, components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/PropertyTemplateMenu.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderRowsMenu/viewHeaderRowsMenu.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/EvaluationStepActions.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/FeedbackEvaluation.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/GoBackButton.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailEvaluation.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricAnswersForm.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricEvaluation.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricResults.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/VoteEvaluation.tsx, components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx, components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts, components/proposals/components/ProposalRewards/AttachRewardButton.tsx, components/proposals/components/ProposalRewards/ProposalRewards.tsx, components/proposals/components/ProposalStatusSelect.tsx, components/proposals/components/ProposalStepSelect.tsx, lib/focalboard/card.ts, lib/focalboard/proposalDbProperties.ts, lib/proposal/getProposalEvaluationStatus.ts, lib/proposal/goBackToStep.ts, lib/proposal/interface.ts, pages/api/proposals/[id]/publish.ts, pages/api/proposals/[id]/submit-result.ts
[Discussion](https://discord.com/channels/894960387743698944/1194431225348239520)
=> Fix archive proposal action

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx, lib/websockets/spaceEvents.ts
1. Remove extra logic to detect linked page
2. Store applied page diffs to document
=> Remove extra logic to detect linked page

components/common/BoardEditor/focalboard/src/components/viewHeader/ToggleViewSidebarButton.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx, components/proposals/ProposalsPage.tsx, components/rewards/RewardsPage.tsx
=> fix toggling view sidebar

components/common/CustomEmojiPicker.tsx, lib/file/constants.ts, pages/api/image/resize.ts
=> increase max artwork width to 4k

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/[pageId]/DocumentPage/components/SyncedPageBanner.tsx, components/[pageId]/EditorPage/EditorPage.tsx, components/[pageId]/SharedPage/SharedPage.tsx, components/common/PageDialog/PageDialog.tsx, stories/ProposalsPage/Proposals.stories.tsx
Users dont know if they're looking a t the original or not
=> add an info alert when looking at a page that is synced elsewhere

components/common/BoardEditor/focalboard/src/components/__snapshots__/centerPanel.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/centerPanel.spec.tsx, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableHeader.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableHeaders.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/table/tableHeader.spec.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeaders.tsx
1. Fixed table columns drag selection
2. Toggle the table rows checkbox in the view header
=> Fixed table columns drag selection and toggle table rows checkbox

components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts, components/proposals/components/ProposalsBoard/utils/boardData.ts, scripts/migrations/2024_01_13_addDefaultProposalViewFilter.ts
=> Added migration for default proposal view filter

components/rewards/components/RewardsBoard/hooks/useRewardsBoardMutator.ts, lib/templates/exportWorkspacePages.ts
https://work.charmverse.fyi/duplicating-a-bounty-duplicates-its-status-541310372924958
https://work.charmverse.fyi/delete-reward-permissions-4710333159806315
=> Fix deleting and duplicating a bounty

charmClient/apis/proposalsApi.ts, components/_app/GlobalComponents.tsx, components/_app/components/ConfirmationModal.tsx, components/_app/components/Snackbar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/GoBackButton.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailEvaluation.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/PublishRewardsButton.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricAnswersForm.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricResults.tsx, components/proposals/ProposalPage/components/WorkflowSelect.tsx, components/proposals/hooks/useBatchUpdateProposalStatusOrStep.ts, hooks/useConfirmationModal.tsx, pages/_app.tsx
=> Add global confirmation modal

lib/spaces/createBotUser.ts, scripts/archiveSpaceProposals.ts
Archive all proposals for space reusable script
=> Archive proposals script

lib/proposal/createProposal.ts
This bug was broken for 2 weeks i think since tht's the last commit here? People probably are not assigning roles in workflows really yet to notice. I'll write a test as a followup today, and some validation that all permissions have a roleId, systemRole, or userId
=> copy over all fields in permissions from the workflow

components/[pageId]/DocumentPage/DocumentPage.tsx
enable comments for archived proposals
=> Enable archived proposals comments

scripts/makeAPIKey.ts, scripts/query.ts, scripts/restoreProposals.ts
=> add script for restoring proposals

__e2e__/database/databaseProposalsAsSource.spec.ts, components/common/BoardEditor/components/cardProperties/CardDetailProperty.tsx, components/common/BoardEditor/focalboard/csvExporter/__tests__/csvExporter.spec.ts, components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableHeader.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/table/tableHeader.spec.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx, components/common/BoardEditor/focalboard/src/components/table/tableHeaders.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderSortMenu.tsx, components/common/BoardEditor/focalboard/src/components/viewSidebar/viewPropertyOptions.tsx, lib/focalboard/__tests__/createCardsFromProposals.spec.ts, lib/focalboard/__tests__/extractCardProposalProperties.spec.ts, lib/focalboard/__tests__/extractDatabaseProposalProperties.spec.ts, lib/focalboard/__tests__/updateCardsFromProposals.spec.ts, lib/focalboard/createCardsFromProposals.ts, lib/focalboard/extractCardProposalProperties.ts, lib/focalboard/extractDatabaseProposalProperties.ts, lib/focalboard/generateResyncedProposalEvaluationForCard.ts, lib/focalboard/getPropertyName.ts, lib/focalboard/setDatabaseProposalProperties.ts, lib/focalboard/updateCardsFromProposals.ts, lib/proposal/createRewardsForProposal.ts, scripts/migrations/2024_01_16_deleteProposalEvaluationProperties.ts
=> Update proposal as a source board evaluation properties

lib/focalboard/createCardsFromProposals.ts, lib/focalboard/updateCardsFromProposals.ts
Fixes lots of mixed block ids, proposal and page ids and optimized the initial queries
=> Proposal source update

components/[pageId]/DocumentPage/components/CommentsFooter/PageComments.tsx, components/common/comments/Comment.tsx, components/common/comments/CommentForm.tsx, components/common/comments/CommentReply.tsx
Removed 'Publish to lens' on proposal comment's UI
=> Removed lens integration from proposal comments in UI

components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButton.spec.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButton.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.spec.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx, components/common/PageActions/components/ArchiveProposalAction.tsx, components/common/PageActions/components/DocumentPageActionList.tsx, components/common/PageActions/components/ExportMarkdownAction.tsx, components/common/PageActions/components/ExportToPDFAction.tsx, components/common/PageActions/components/UndoAction.tsx, components/common/TemplatesMenu/TemplatePageActionMenu.tsx, components/common/TemplatesMenu/TemplatesMenu.tsx, components/common/TemplatesMenu/index.ts, components/proposals/components/NewProposalButton.tsx, components/proposals/hooks/useProposalTemplates.tsx, components/proposals/hooks/useProposals.tsx, components/rewards/components/NewRewardButton.tsx, lib/proposal/getProposalTemplates.ts
The main purpose of this PR is just to show them in the dropdown, since they won't appear in the table
=> Archive proposal templates

components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx, components/settings/proposals/components/EvaluationPermissions.tsx
=> Warn admin if a user or role has permission but not view permission

components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx, components/common/BoardEditor/focalboard/src/components/properties/createdAt/createdAt.tsx, components/common/BoardEditor/focalboard/src/components/properties/dateRange/dateRange.tsx, components/common/BoardEditor/focalboard/src/components/properties/lastModifiedAt/__snapshots__/lastModifiedAt.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/properties/lastModifiedAt/lastModifiedAt.tsx, components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap
=> Fix wrapping db columns

components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
=> fix editing dates in databases

.ebstalk.apps.env/cron.env, package.json
Pass credentials config to worker
So it doesn't crash when issuing credentials
=> Pass credentials config to worker

components/[pageId]/DocumentPage/components/ProposalArchivedBanner.tsx, components/common/TemplatesMenu/TemplatesMenu.tsx
=> simplify copy for archive banner

lib/proposal/createProposal.ts
=> create vote if it iss the first step

components/settings/space/SpaceSettings.tsx, components/settings/space/components/NotificationToggles.tsx
=> update event settings for proposals

components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx
https://app.charmverse.io/charmverse/mobile-share-icon-is-too-high-5415566767761191
=> Space between divider and share button

lib/credentials/queriesAndMutations.ts
=> only create credentials wallet when we need it

lib/proposal/__tests__/getProposalTemplates.spec.ts, lib/proposal/getProposalTemplates.ts
=> hide deleted templates from proposal list

components/[pageId]/DocumentPage/components/ProposalArchivedBanner.tsx, components/common/CharmEditor/components/linkedPage/components/LinkedPagesList.tsx, components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx, lib/utilities/__tests__/strings.spec.ts, lib/utilities/strings.ts
when u link to a template, it will inject a link to create a proposal using that template
=> Support linking to proposal templates

components/common/CharmEditor/components/mention/components/Mention.tsx
…ntions
[Card](https://discord.com/channels/894960387743698944/1199718355268018247)
=> Open new proposal template page when clicking on template mentions

lib/proposal/__tests__/updateProposal.spec.ts, lib/proposal/updateProposal.ts
=> allow clearing out authors for proposal templates

components/common/BoardEditor/focalboard/src/store/cards.ts, scripts/generateProposals.ts
Fix evaluation sorting for total and average in database with proposals as source
=> Fix sorting

components/common/CharmEditor/InlineCharmEditor.tsx, components/common/CharmEditor/components/link/link.plugins.ts, components/common/CharmEditor/plugins.ts
[Card](https://discord.com/channels/894960387743698944/1200039439867588628)
=> Fixed clicking on links opening two tabs on readonly editor

components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
=> ensure reviewers on rewards are unique

__e2e__/proposals/proposalTemplates.spec.ts, __e2e__/publicProposals.spec.ts, __integration-tests__/server/pages/api/v1/proposals/index.spec.ts, lib/focalboard/__tests__/createCardsFromProposals.spec.ts, lib/focalboard/__tests__/updateCardsFromProposals.spec.ts, lib/spaces/countSpaceBlocks/__tests__/countProposalBlocks.spec.ts, lib/templates/__tests__/exportWorkspacePages.spec.ts, stories/ProposalsPage/Proposals.stories.tsx, stories/ProposalsPage/ProposalsPageStory.tsx, testing/setupDatabase.ts
Unblocks https://github.com/charmverse/core/pull/219
=> require evaluation Ids in tests

components/common/BoardEditor/components/properties/UserSelect.tsx
=> Fix displaying users in details view

package.json
Cleanup, and don't start with cron
=> Fix ceramic scripts

components/credentials/CredentialsSelect.tsx, lib/credentials/issueProposalCredentialsIfNecessary.ts
=> Show proposal credential placeholder in author property

components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
=> assign a uuid when creating a new reward

components/proposals/ProposalPage/NewProposalPage.tsx
=> fix convert to propoosal

components/proposals/ProposalPage/components/EvaluationSidebar/EvaluationSidebar.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/VoteEvaluation.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/PublishToSnapshot/PublishToSnapshot.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/PublishToSnapshot/components/PublishingForm.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/VoteEvaluation/components/SnapshotVotingForm/SnapshotVotingForm.tsx
=> fix snapshot voting

components/common/CharmEditor/components/linkedPage/components/LinkedPagesList.tsx, components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx
Regression from https://github.com/charmverse/app.charmverse.io/commit/06b6ffaf6a00bf737afa9278a429b0bc3c1c2351#diff-bf63a7f49e8a2bdc5c43a7d1bea6b14fe2fdf1281fc3faf57c14630996144df6
=> fix capitalization of features in page nodes

__integration-tests__/server/middleware.spec.ts, lib/spaces/config.ts, middleware.ts
Any page that starts with "u" in the title or any other page will not work on custom domains, because we think it's a public page.
=> fix for custom domain logic

__integration-tests__/server/pages/api/proposals/[id]/rubric-answers.spec.ts, __integration-tests__/server/pages/api/v1/proposals/[proposalId]/index.spec.ts, charmClient/hooks/proposals.ts, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/VoteSettings.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/RubricEvaluation/RubricAnswersForm.tsx, pages/api/proposals/[id]/rubric-answers.ts
=> hide vote settings if snapshot is selected

.github/workflows/deploy_staging.yml, __integration-tests__/server/pages/api/spaces/[id]/set-public-proposal-templates.spec.ts, charmClient/apis/spacesApi.ts, components/common/PageLayout/components/Header/components/ProposalsShareButton/ShareProposals.tsx, components/common/PageLayout/components/Header/components/ProposalsShareButton/TogglePublicProposalTemplates.tsx, lib/spaces/__tests__/togglePublicProposalTemplates.spec.ts, lib/spaces/toggleSpacePublicProposalTemplates.ts, package.json, pages/api/spaces/[id]/set-public-proposal-templates.ts
=> Public templates

components/common/BoardEditor/focalboard/csvExporter/__tests__/csvExporter.spec.ts, components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx, lib/focalboard/cardFilter.ts, lib/focalboard/createCardsFromProposals.ts, lib/focalboard/extractCardProposalProperties.ts, lib/focalboard/extractDatabaseProposalProperties.ts, lib/focalboard/setDatabaseProposalProperties.ts, lib/focalboard/updateCardsFromProposals.ts, scripts/migrations/2024_01_30_addProposalAuthorColumn.ts
[Card](https://app.charmverse.io/charmverse/add-author-to-proposal-as-a-source-8947340033327871)
=> Proposal author column in proposal as a source boards

components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/VoteSettings.tsx
Fix bug where custom options in vote settings were reset
=> Don't accidentally reset voting options

components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/VoteSettings.tsx
This should address the voting e2e test. Was probably an actual bug caught by e2e
=> Fix initial state so CI works

__e2e__/po/formField.po.ts, __e2e__/proposals/proposalTemplate.spec.ts, components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/form/FormField.tsx, components/common/form/FormFieldsEditor.tsx, components/common/form/FormFieldsInput.tsx, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/ProposalFormFieldsInput.tsx, components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/AttachRewardButton.tsx, stories/FormFields/FormFields.stories.tsx
=> fix Save button not allowing user to remove form fields questions

pages/api/v1/forum/comments/[commentId]/upvote.ts, pages/api/v1/forum/posts/[postId]/index.ts
=> Forum api documentation fixes

charmClient/hooks/spaces.ts, components/common/PageActions/components/DatabasePageActionList.tsx, components/common/PageActions/components/DocumentPageActionList.tsx, components/common/PageActions/components/SetAsHomePageAction.tsx, components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx, lib/session/__tests__/getDefaultPageForSpace.spec.ts, lib/session/getDefaultPageForSpace.ts, lib/spaces/updateSpace.ts
=> Add option to set Home page

lib/session/getDefaultPageForSpace.ts, pages/[domain]/index.tsx
=> Fix redirect for non logged in users

components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
=> make more fields readonly when using a reward template

charmClient/hooks/profile.ts, components/login/components/VerifyLoginOtpModal.tsx, components/settings/account/components/otp/components/ConfirmRecoveryCode.tsx, lib/metrics/mixpanel/interfaces/UserEvent.ts, lib/profile/otp/__tests__/verifyOtpToken.spec.ts, lib/profile/otp/__tests__/verifyRecoveryCode.spec.ts, lib/profile/otp/createRecoveryCode.ts, lib/profile/otp/createUserOtp.ts, lib/profile/otp/verifyRecoveryCode.ts, pages/api/profile/otp/recovery-code.ts, testing/userOtp.ts
Use backup codes when the user doesn't have his authenticator code
=> Backup codes

components/common/BoardEditor/components/properties/PagesAutocomplete.tsx
=> Use 'Untitled' for undefined page titles

components/proposals/ProposalPage/NewProposalPage.tsx, lib/proposal/workflows/__tests__/upsertWorkflowTemplate.spec.ts, lib/proposal/workflows/controller.ts, pages/api/spaces/[id]/proposals/workflows/index.ts
Try to keep proposal templates in sync with workflow configurations.
Card: https://work.charmverse.fyi/work.charmverse.fyi/tech-task-list-49366552253645923?cardId=3d77790f-7d89-4fe8-b1b7-2ec2fc50b892
=> Sync proposal templates when updating workflow settings

__integration-tests__/server/pages/api/spaces/[id]/members/index.spec.ts, pages/api/spaces/[id]/members/index.ts
Don't anonymise users in public setting
Confusing UX
=> Don't anonymise users

lib/blockchain/provider/alchemy/client.ts
Alchemy is now charging for SPAM filters
=> remove Paid SPAM filter feature from alchemy requests

components/common/CharmEditor/components/inlineVote/components/VoteDetail.tsx, components/common/CharmEditor/components/poll/PollComponent.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/VoteEvaluation/VoteEvaluation.tsx
=> fix view context for vote details

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/ProposalProperties.tsx
=> Readonly proposal rewards

lib/profile/getSummonProfile.ts
=> ignore default summon user id

lib/proposal/createRewardsForProposal.ts, lib/templates/exportWorkspacePages.ts, package.json, scripts/exportProposalScores.ts, scripts/migrations/2023_12_04_createDefaultRewardsAndProposals.ts, scripts/migrations/2024_01_03_transferProposalCategories.ts
=> remove use of proposal category

components/[pageId]/EditorPage/EditorPage.tsx, hooks/usePage.ts
=> Don't show page not found when the server is failing

.github/workflows/test_and_deploy.yml
=> undo changes to CI

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/DocumentPageWithSidebars.tsx, components/[pageId]/DocumentPage/components/CommentsFooter/PageComments.tsx, components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx, components/[pageId]/DocumentPage/components/Sidebar/components/CommentsSidebar.tsx, components/common/CharmEditor/components/inlineComment/components/InlineCommentThread.tsx, components/common/CharmEditor/components/thread/PageThread.tsx, components/common/form/FormFieldAnswerComment.tsx, components/common/form/FormFieldsInput.tsx, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/ProposalEvaluations.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/RubricEvaluation.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/EvaluationStepSettings.tsx, components/proposals/ProposalPage/components/ProposalFormFieldsInput.tsx, stories/FormFields/FormFields.stories.tsx
!!! got rid of all "isReviewer" props as well :)
=> fix commenting permissions on structured proposals

docker-compose.yml
=> use local permissions in staging socket server

components/common/ContextMenu.tsx, components/common/PageLayout/SharedPageLayout.tsx, components/common/PageLayout/components/LoggedOutButtons.tsx
=> Replace Try charmverse with "Built with..." and fix the link for custom domains

lib/forums/comments/createPostComment.ts, lib/forums/comments/deletePostComment.ts, lib/forums/posts/voteForumComment.ts, lib/metrics/mixpanel/interfaces/ProposalEvent.ts, pages/api/v1/forum/comments/[commentId]/index.ts, pages/api/v1/forum/comments/[commentId]/upvote.ts, pages/api/v1/forum/posts/[postId]/comments/index.ts, pages/api/v1/forum/posts/[postId]/upvote.ts, pages/api/v1/forum/posts/index.ts, pages/api/v1/proposals/[proposalId]/comments/[commentId]/vote.ts, pages/api/v1/proposals/[proposalId]/comments/index.ts
=> track forum and proposal events in the public api

.github/actions/build/action.yml, .github/actions/build_docker_image/action.yml, .github/actions/install/action.yml, .github/workflows/chromatic.yml, .github/workflows/deploy_serverless_prod.yml, .github/workflows/deploy_serverless_staging.yml, .github/workflows/deploy_staging.yml, .github/workflows/destroy_staging.yml, .github/workflows/test_and_deploy.yml, .github/workflows/test_new_core_pkg.yml, .github/workflows/update_core_pkg.yml
=> fix warnings about node 16 in github ci

components/common/RouteGuard.tsx, pages/[domain]/proposals/new.tsx
Handle case where user is already logged in but not yet a space member
=> Fix joining spaces from proposal template for logged in users

components/common/CharmEditor/components/BlockAligner.tsx, components/common/CharmEditor/components/farcasterFrame/components/FarcasterFrameNodeView.tsx, components/common/CharmEditor/components/farcasterFrame/components/FarcasterMiniProfile.tsx, components/settings/account/hooks/useIdentityTypes.tsx, hooks/useFarcasterFrame.ts, hooks/useFarcasterProfile.ts, hooks/useFarcasterUser.tsx, lib/farcaster/getFarcasterProfile.ts
=> Readonly public interaction with farcaster frame

lib/farcaster/getFarcasterProfile.ts
=> Only fetch farcaster profile if fid is preset

components/rewards/components/RewardProperties/components/RewardTokenProperty.tsx
https://app.charmverse.io/charmverse/adding-custom-token-as-reward-second-modal-defaults-to-ethereum-2959176801682517
=> Fix default chain for custom token form

components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButton.spec.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButton.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx, components/common/BoardEditor/focalboard/src/store/boards.ts, components/common/BoardEditor/focalboard/src/store/cards.ts
Use the local boardId instead of "current" when retrieving templates, which is almost never right. In this case, a user was linking one inline DB to another inline DB. 
[](https://work.charmverse.fyi/work.charmverse.fyi/tech-task-list-49366552253645923?viewId=50d940bb-fdbd-40ba-9816-616d6138a663&cardId=a616aa1c-b8d3-4396-89c5-69aa84cfaf2c)
=> Board templates

components/common/CharmEditor/components/farcasterFrame/components/FarcasterFrameNodeView.tsx, components/common/CharmEditor/components/farcasterFrame/components/FarcasterMiniProfile.tsx, components/common/CharmEditor/components/farcasterFrame/components/FarcasterSigner.tsx, hooks/useFarcasterFrame.ts, hooks/useFarcasterUser.tsx, lib/farcaster/interfaces.ts, lib/metrics/mixpanel/interfaces/UserEvent.ts, pages/api/farcaster/frame-action.ts, pages/api/farcaster/signer.ts
=> Improve farcaster frames security mechanisms

.github/actions/build_docker_image/action.yml, .github/workflows/destroy_staging.yml, .github/workflows/test_and_deploy.yml, .github/workflows/test_new_core_pkg.yml
=> update github actions that use node 16

components/common/CharmEditor/components/farcasterFrame/components/FarcasterFrameNodeView.tsx, hooks/useFarcasterFrame.ts, package.json, pages/api/farcaster/frame-action.ts, pages/api/farcaster/frame.ts
=> Handle latest farcaster frames specifications

components/members/components/MemberProfile/components/ProfileWidgets/components/CredentialsWidget.tsx, components/members/components/MemberProfile/components/UserCredentials/UserCredentialsList.tsx
Removes the empty state for Favorites and cleans up some logic
=> hide favorite section of credentials if none exist

hooks/useS3UploadInput.ts
Calling resize on them ends up rasterizing and reducing the quality
=> dont resize svg images

components/common/CharmEditor/components/farcasterFrame/components/FarcasterFrameNodeView.tsx, hooks/useFarcasterFrame.ts, lib/focalboard/__tests__/setDatabaseProposalProperties.spec.ts, lib/focalboard/setDatabaseProposalProperties.ts
[Card](https://app.charmverse.io/charmverse/proposals-column-for-databases-from-proposal-source-should-be-ordered-by-form-appearance-in-form-template-5808922713835902)
=> Create form field columns based on index for proposal source boards

__e2e__/proposals/proposalTemplate.spec.ts
Flaky example: https://github.com/charmverse/app.charmverse.io/actions/runs/7845360310/job/21410423938
=> disable flaky test

components/members/components/MemberProfile/components/UserCredentials/UserCredentialRow.tsx, components/settings/credentials/components/CredentialEventToggle.tsx, components/settings/credentials/components/CredentialTemplateRow.tsx, components/settings/credentials/components/ProposalCredentialPreview.tsx, lib/credentials/constants.ts, lib/credentials/issueProposalCredentialsIfNecessary.ts, lib/credentials/queriesAndMutations.ts, lib/credentials/schemas.ts
=> Credential schema update

lib/credentials/apolloClientWithRedisCache.ts, lib/credentials/queriesAndMutations.ts
=> Add option to skip caching

connectors/chains.ts, lib/blockchain/updateLitDetails.ts, lib/tokenGates/chains.ts, lib/tokenGates/humanizeConditions.ts, lib/tokenGates/utils.ts, package.json, stories/Common/TokenGate.stories.tsx
=> add Sepolia testnet to production blockchain list

components/common/PageDialog/components/NewDocumentPage.tsx, components/credentials/CredentialsSelect.tsx, components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/AttachRewardButton.tsx, components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx, components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
=> make rewards visible for space members

__integration-tests__/server/pages/api/v1/proposals/[proposalId]/index.spec.ts, __integration-tests__/server/pages/api/v1/proposals/index.spec.ts, pages/api/v1/proposals/[proposalId]/index.ts, pages/api/v1/proposals/index.ts
=> add startedAt date for current evaluation step in public api

components/[pageId]/DocumentPage/DocumentPageWithSidebars.tsx
[Discussion](https://discord.com/channels/894960387743698944/1206576778446114816)
=> Allow updating the reward templates for proposal templates while editing

lib/features/__tests__/getFeatureTitle.spec.ts, lib/features/getFeatureTitle.ts
=> Handle custom feature names that end in ies

__e2e__/deletePage.spec.ts
[### WHAT
](https://github.com/charmverse/app.charmverse.io/actions/runs/7875557832/job/21488031319)
=> disable test that fails sometimes in e2e

components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts, lib/proposal/__tests__/getProposalTemplates.spec.ts, lib/proposal/getProposalTemplates.ts
=> return private fields when creating a proposal

components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
=> rename rewards in placeholder for title

lib/credentials/issueProposalCredentialsIfNecessary.ts, lib/metrics/mixpanel/interfaces/CredentialEvent.ts, lib/metrics/mixpanel/interfaces/index.ts, pages/api/credentials/templates.ts
Track event, userId and spaceId
=> Track events when credentials are issued

__e2e__/proposals/freeFormProposalTemplate.spec.ts, __e2e__/proposals/proposalTemplate.spec.ts, __e2e__/proposals/publicProposals.spec.ts
=> Comment out failing e2e tests

charmClient/hooks/proposals.ts, components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/ConnectionErrorBanner.tsx, components/[pageId]/DocumentPage/components/ProposalNotesBanner.tsx, components/[pageId]/DocumentPage/components/Sidebar/ProposalSidebar.tsx, components/common/BoardEditor/focalboard/src/components/__snapshots__/centerPanel.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/gallery/__snapshots__/galleryCard.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/kanban/__snapshots__/kanban.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableRow.spec.tsx.snap, components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx, components/common/PageDialog/PageDialog.tsx, components/common/PageIcon.tsx, components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/components/DocumentHeaderElements.tsx, components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx, components/common/PageLayout/components/Sidebar/NavigationSidebar.tsx, components/common/PageLayout/components/Sidebar/components/PageNavigation/components/PageTreeItem.tsx, components/common/PageLayout/components/Sidebar/components/SidebarButton.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/ProposalNotesLink.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/ProposalNotesLink.tsx, components/proposals/ProposalPage/components/WorkflowSelect.tsx, hooks/useSnackbar.tsx, lib/proposal/getOrCreateReviewerNotes.ts, pages/api/proposals/[id]/reviewer-notes.ts
=> Allow reviewers to create and edit notes

components/[pageId]/DocumentPage/components/Sidebar/ProposalSidebar.tsx, lib/proposal/__tests__/getProposalTemplates.spec.ts, lib/proposal/interface.ts, lib/proposal/mapDbProposalToProposal.ts, stories/ProposalsPage/ProposalsPageStory.tsx, testing/mocks/proposal.ts
Also cleaned up the proposal type a bit
=> check permission to show proposal notes

pages/api/v1/forum/posts/[postId]/index.ts, pages/api/v1/forum/posts/[postId]/upvote.ts, pages/api/v1/forum/posts/index.ts
=> fix schema declaration for posts apis

scripts/fixProposalRubricCriteria.ts, scripts/syncTemplateRubricCriteria.ts
=> Proposal scripts

__e2e__/po/formField.po.ts, charmClient/hooks/proposals.ts, components/common/BoardEditor/components/properties/ProposalNotesLink.tsx, components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx, lib/focalboard/proposalDbProperties.ts, pages/api/proposals/reviewer-notes.ts
The new inputs were breaking the layout of the table. I tried to reuse the ProposalNotesLink component but the wrapping element is what's breaking things, so it was easier to copy/paste
=> Proposal note prop

__e2e__/proposals/publicProposals.spec.ts, pages/api/proposals/reviewer-notes.ts
=> Fix bug for reviewer notes

components/settings/space/SpaceSettings.tsx, components/settings/space/components/SpacePrimaryIdentity.tsx, lib/spaces/__tests__/updateSpace.spec.ts, lib/spaces/updateSpace.ts, pages/api/spaces/[id]/index.ts, testing/setupDatabase.ts
[Discussion](https://discord.com/channels/894960387743698944/1209126547420876831)
=> Reset required value for previous identity member property

__e2e__/po/databasePage.po.ts, __e2e__/po/proposalPage.po.ts, __e2e__/proposals/proposalCustomProperties.spec.ts, __e2e__/proposals/voteOnProposal.spec.ts, components/common/CharmEditor/components/inlineVote/components/SingleChoiceForm.tsx, components/proposals/ProposalPage/NewProposalPage.tsx
=> Add custom properties and proposal voting test coverage

components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx, components/rewards/components/NewRewardButton.tsx
=> Calculate reward type when using templates

__e2e__/proposals/proposalCustomProperties.spec.ts, __e2e__/proposals/structuredProposalTemplate.spec.ts, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/table.spec.tsx.snap, components/common/BoardEditor/focalboard/src/components/table/__snapshots__/tableRow.spec.tsx.snap, components/common/form/fields/Select/SelectPreview.tsx, components/members/components/MemberDirectoryGalleryView.tsx, components/members/components/__tests__/MemberDirectoryGalleryView.spec.tsx
Don't show props in member card if they're empty
=> Fix member card and add browser tests

lib/pages/restoreDocument.ts, lib/prosemirror/applyStepsToNode.ts, scripts/exportData/importPageToDev.ts, scripts/getPageHistory.ts, scripts/restorePageVersion.ts
=> add script to restore page

background/cron.ts
=> Disable token gate cron temporarily

lib/utilities/types.ts
=> fix type errors

components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx
=> fix opening milestones

pages/api/v1/forum/comments/[commentId]/index.ts, pages/api/v1/forum/posts/[postId]/index.ts, pages/api/v1/forum/posts/[postId]/upvote.ts
=> Allow Delete forum post from public api

components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx
=> show status column for published rewards

lib/focalboard/__tests__/updateCardsFromProposals.spec.ts, lib/focalboard/updateCardsFromProposals.ts
=> Optimized query to update cards from proposals

background/tasks/countAllSpacesBlocksTask.ts, lib/charms/getSpacesCharmsStatus.ts, lib/spaces/__tests__/deleteArchivalBlockCounts.spec.ts, lib/spaces/deleteArchivalBlockCounts.ts
https://app.charmverse.io/charmverse/slow-queries-for-charms-7597386042394729
=> Delete archival space block counts

background/cron.ts, connectors/chains.ts, lib/middleware/requireValidation.ts, lib/tokenGates/abis/abis.ts, lib/tokenGates/evaluateEligibility.ts, lib/tokenGates/validateTokenGate.ts, lib/tokenGates/validateTokenGateCondition.ts, lib/tokenGates/validateTokenGateConditionsObject.ts, lib/tokenGates/verifyTokenGateMembership.ts, lib/tokenGates/verifyTokenGates.ts, scripts/litTokenGateAdaptor.ts
Changes:
- fixes for readContract method
- Better logging when a condition fails
- Revert alchemy API's. Sometimes they were failing. Better to rely on Ankr or the public rpcs
- On error we return true (validation) so we don't kick out the user just because an API call failed.
=> Token Gate Cron job fix

components/proposals/ProposalsPage.tsx, components/rewards/RewardsPage.tsx
=> dont hardcode proposals in the empty state video
