charmverse/app.charmverse.io

components/common/PageDialog/NewPageDialog.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx

ad a way to delete rewards

---

components/common/BoardEditor/focalboard/src/components/viewHeader/ViewHeaderRowsMenu/ViewHeaderRowsMenu.tsx
components/common/BoardEditor/focalboard/src/components/viewHeader/ViewHeaderRowsMenu/components/BatchPaymentRewards.tsx
components/rewards/components/RewardsHeaderRowsMenu.tsx

Better tooltip for rewards batch actions

---

components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx
lib/proposal/getProposalErrors.ts

Fix saving draft proposal

---

lib/form/upsertProposalFormAnswers.ts
lib/form/validateAnswers.ts
lib/proposal/getProposalErrors.ts
pages/api/proposals/[id]/publish.ts

Fix proposal validation

---

charmClient/hooks/rewards.ts
components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/RewardSettings.tsx
components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
components/rewards/hooks/useNewReward.tsx
components/settings/proposals/components/EvaluationPermissions.tsx

[Card](https://app.charmverse.io/charmverse/create-reward-templates-from-proposal-page-7711943658318645)

Create reward templates from proposal page

---

__integration-tests__/server/pages/api/v1/forum/posts/[postId]/index.spec.ts
__integration-tests__/server/pages/api/v1/forum/posts/index.spec.ts
lib/forums/posts/__tests__/listForumPosts.spec.ts
lib/middleware/requireApiKey.ts
lib/middleware/requireSuperApiKey.ts
pages/api/v1/forum/posts/[postId]/index.ts
pages/api/v1/forum/posts/index.ts

fix and add tests for forums api

---

components/settings/roles/components/MemberActions.tsx

[Card](https://app.charmverse.io/charmverse/add-description-text-to-remove-user-48294331479438224)

Add description text in remove user from space option

---

components/common/TokenGateModal/components/TokenGateBlockchainSelect.tsx
components/common/TokenGateModal/components/TokenGateCollectableFields.tsx
components/common/TokenGateModal/components/TokenGateCollectables.tsx
components/common/TokenGateModal/components/TokenGateCommunities.tsx
components/common/TokenGateModal/components/TokenGateContent.tsx
components/common/TokenGateModal/components/TokenGateCredentials.tsx
components/common/TokenGateModal/components/TokenGateHome.tsx
components/common/TokenGateModal/hooks/useCollectablesForm.tsx
components/common/TokenGateModal/hooks/useCommunitiesForm.tsx
components/common/TokenGateModal/hooks/useCredentialsForm.ts
components/common/TokenGateModal/hooks/useTokenGateModalContext.tsx
components/common/TokenGateModal/utils/getCollectablesAccessControlConditions.ts
components/common/TokenGateModal/utils/getCommunitiesAccessControlConditions.ts
components/common/TokenGateModal/utils/getCredentialsAccessControlConditions.ts
components/common/TokenGateModal/utils/helpers.ts
components/common/TokenGateModal/utils/utils.ts
connectors/chains.ts
lib/blockchain/provider/ankr/config.ts
lib/metrics/mixpanel/constants.ts
lib/tokenGates/__tests__/humanizeConditions.spec.ts
lib/tokenGates/abis/abis.ts
lib/tokenGates/humanizeConditions.ts
lib/tokenGates/interfaces.ts

Changes:
- Rename DAO -> Communities
- Rename Gitcoin -> Credentials
- Rename Guild -> Guild.xyz
- Fix hypersub and unlock protocol validation and multiple conditions 
- Fix moloch dao validation
- Add gnosis to moloch dao chains
- Add Ankr chains for ERC20, 1155, 20.

Token Gate improvements

---

pages/api/proposals/index.ts

sort evaluations from templates when validating

---

components/common/PageActions/components/DuplicatePageAction.tsx
components/common/PageLayout/components/TrashModal.tsx
lib/websockets/__tests__/spaceEvents.spec.ts
lib/websockets/interfaces.ts
lib/websockets/spaceEvents.ts

[Card](https://app.charmverse.io/charmverse/duplicated-page-doesn-t-show-in-parent-page-869352925746254)

Duplicated page doesn't show in parent page

---

.github/workflows/deploy_staging.yml
.github/workflows/destroy_staging.yml

fix config for staging deploys

---

.github/workflows/test_and_deploy.yml

This originally had all the steps, but I cleaned it up 2 weeks ago thinking we didn't need them: https://github.com/charmverse/app.charmverse.io/commit/a1718f65f42b5328daa8ce4912de50e2f7ff8137#diff-26f81082456d6a7a3832ccb6bcacb1560e1db2f552e3d57a4da90097aacba804R339

alert discord if any step fails in CI

---

components/proposals/ProposalsPage.tsx

[Card](https://app.charmverse.io/charmverse/allow-admin-to-create-a-description-text-on-the-proposal-page-46447968952894225)

Add description to proposal board

---

lib/notifications/mailer/sendNotificationEmail.ts

[Card](https://app.charmverse.io/charmverse/email-notification-is-showing-my-image-with-the-reporter-s-name-024839051944065327)

Fixed notification email target user

---

hooks/useWeb3Account.tsx
lib/blockchain/provider/alchemy/client.ts
lib/blockchain/provider/ankr/client.ts
lib/blockchain/publicClient.ts
lib/blockchain/signAndVerify.ts
lib/middleware/requireWalletSignature.ts

This reverts commit f24b12212048bae3c157cda6907f61a489f6e3b8.

Revert "Fix wallet connect / gnosis (#3535)"

---

components/rewards/components/RewardsBoard/utils/boardData.ts
components/rewards/hooks/useRewardsBoardAdapter.ts
lib/rewards/blocks/__tests__/upsertDefaultRewardsBoard.spec.ts
lib/rewards/blocks/upsertDefaultRewardsBoard.ts
scripts/migrations/2024_03_04_addDefaultRewardBoardViews.ts

[Discussion](https://discord.com/channels/894960387743698944/1214188710556471326)

Fixed proposal board block field viewIds being empty value

---

components/common/CharmEditor/components/nft/NFTNodeView.tsx
connectors/chains.ts
lib/blockchain/getNFTs.ts
lib/blockchain/provider/ankr/config.ts
lib/blockchain/publicClient.ts

Switch ZKEVM from Alchemy to Ankr.
Simplified Ankr chains list
Move Polygon from Alchemy to Ankr

Fix polygon_zkevm - GET metadata

---

scripts/verifyTokenGates.ts

add a script to verify token gates against a wallet address

---

components/[pageId]/DocumentPage/DocumentPage.tsx

fix missing details for google form responses

---

components/settings/proposals/components/EvaluationPermissions.tsx

[Conversation](https://discord.com/channels/894960387743698944/1213107168207962122/1213156387413168159)

Use person icon for proposal system roles

---

components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
components/proposals/ProposalsPage.tsx

[Conversation](https://discord.com/channels/894960387743698944/1213099680108650556)
Before
Now

Whitespace for proposal board with description

---

components/common/CharmEditor/components/@bangle.dev/core/node-view.ts
components/common/CharmEditor/components/@bangle.dev/react/node-view-helpers.tsx
components/common/CharmEditor/components/rowActions/RowActionsMenu.tsx
components/common/CharmEditor/components/rowActions/__tests__/deleteRowNode.spec.ts
components/common/CharmEditor/components/rowActions/rowActions.ts
testing/prosemirror/renderTestEditor.ts

[Card](https://app.charmverse.io/charmverse/page-1550658364736237)

Fixed deleting page node in a column deletes whole column node

---

lib/profile/getUserNFTs.ts

[Discussion](https://discord.com/channels/894960387743698944/1214204343893360710)

Fixed getting pinned nfts

---

.vscode/settings.json
components/forum/components/CreateForumPost.tsx

[### WHAT
](https://work.charmverse.fyi/work.charmverse.fyi/tech-task-list-49366552253645923?cardId=020e4a33-7a08-461e-a4ce-25718495c300)

rename Create post so it fits on mobile

---

.github/workflows/test_and_deploy.yml
.vscode/settings.json
__integration-tests__/server/pages/api/spaces/[id]/pages.spec.ts
charmClient/apis/pagesApi.ts
charmClient/hooks/pages.ts
components/[pageId]/DocumentPage/components/PageDeleteBanner.tsx
components/[pageId]/DocumentPage/components/PageParentChip.tsx
components/common/BoardEditor/components/properties/ProposalNotesLink.tsx
components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
components/common/BoardEditor/focalboard/src/store/cards.ts
components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx
components/common/PageActions/KanbanPageActionButton.tsx
components/common/PageActions/components/PageActionsMenu.tsx
components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
components/common/PageLayout/components/TrashModal.tsx
components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/CustomPropertiesAdapter.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx
components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
components/proposals/ProposalsPage.tsx
components/proposals/components/ProposalsHeaderRowsMenu.tsx
components/proposals/hooks/useProposals.tsx
components/proposals/hooks/useProposalsBoard.tsx
components/rewards/hooks/useRewardsBoardAdapter.ts
lib/focalboard/card.ts
lib/proposals/getProposals.ts
pages/api/pages/[id]/index.ts
pages/api/proposals/reviewer-notes.ts
pages/api/spaces/[id]/pages.ts

grab page data along with proposals

---

components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSourceOptions/useSourceOptions.tsx
components/common/PageActions/components/DatabasePageActionList.tsx
components/common/PageActions/utils/databasePageOptions.ts

retrieve api keys only when needed

---

components/common/comments/CommentForm.tsx

[Discussion](https://discord.com/channels/894960387743698944/933026321683066991/1214970536380334151)

Remove auto focusing on page comment form

---

components/settings/Legend.tsx
components/settings/account/AccountSettings.tsx
components/settings/account/components/AccountPreferences.tsx
components/settings/account/hooks/useIdentityTypes.tsx
components/settings/profile/components/IdentityIcon.tsx
components/settings/profile/components/IdentityModal.tsx
components/settings/profile/components/Integration.tsx

Improved layout for user identities section

---

__integration-tests__/server/pages/api/proposals/[id]/evaluation.spec.ts
__integration-tests__/server/pages/api/proposals/[id]/rubric-answers.spec.ts
__integration-tests__/server/pages/api/proposals/[id]/rubric-criteria.spec.ts
charmClient/hooks/proposals.ts
components/proposals/ProposalPage/NewProposalPage.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/RubricTemplatesButton.tsx
lib/focalboard/createCardsFromProposals.ts
lib/focalboard/updateCardsFromProposals.ts
lib/proposals/interfaces.ts
lib/proposals/rubric/__tests__/upsertRubricAnswers.spec.ts
lib/proposals/rubric/__tests__/upsertRubricCriteria.spec.ts
lib/proposals/rubric/getRubricTemplates.ts
lib/proposals/rubric/interfaces.ts
lib/proposals/rubric/upsertRubricAnswers.ts
lib/proposals/rubric/upsertRubricCriteria.ts
pages/api/proposals/[id]/rubric-criteria.ts
pages/api/proposals/rubric-templates.ts

Allow copying rubric criteria from templates

---

lib/blockchain/provider/zora/client.ts
lib/blockchain/provider/zora/getNFTs.ts

Zora error in our logs was about wallets array being empty

Fix get nfts from Zora

---

components/[pageId]/DatabasePage/DatabasePage.tsx
components/[pageId]/DocumentPage/DocumentPage.tsx
components/common/BoardEditor/components/properties/PagesAutocomplete.tsx
components/common/PageDialog/PageDialog.tsx

[Card](https://app.charmverse.io/charmverse/show-database-board-on-top-for-related-cards-in-modal-8563132487863299)

Show database board on top for related cards in modal

---

lib/credentials/external/getOnchainCredentials.ts
lib/credentials/queriesAndMutations.ts

Fixed ceramic query, and onchain credentials mapper

Fix fetching credentials

---

components/rewards/components/RewardProperties/RewardPropertiesForm.tsx

Fix reward credentials label

---

components/settings/charms/components/CharmsHistoryTab.tsx
lib/charms/constants.ts
scripts/addCharmsToWallets.ts

[Discussion](https://discord.com/channels/894960387743698944/1215843718867980358)

Script to add charm transactions to user charm wallets

---

components/proposals/ProposalsPage.tsx
components/rewards/RewardsPage.tsx

Rewards board description

---

components/common/CharmEditor/components/fiduswriter/collab/merge/recreate_transform.ts
package.json

bump typescript

---

components/common/BaseLayout/components/Header.tsx

Users can check and add identities in Join Page

Manage identities in Join Page

---

lib/charms/__tests__/addCharms.spec.ts
lib/charms/addCharms.ts

We need to track total user balance (even if he gives charms to space) for leaderboard purposes

Charms tracking total balance

---

components/members/components/MemberProfile/components/ProfileWidgets/ProfileWidgets.tsx

User that owns the member profile should see his NFTs widget even tho he hasn't any pinned or otherwise.

Fix NFTs not visible

---

scripts/addMissingRubricQuestion.ts

Add script for populating rubric criteria

---

connectors/chains.ts
lib/blockchain/provider/alchemy/client.ts
lib/blockchain/provider/ankr/config.ts

Changes:
- Move back Polygon from ANKR to Alchemy
- Use Alchemy V3 API
- Get Unstoppable Domains metadata API and return the name and image

Get NFTS - use alchemy V3

---

lib/utils/url.ts

Fix url query util

---

.github/workflows/test_and_deploy.yml
playwright.config.ts

one playwright worker for ci

---

components/common/BoardEditor/focalboard/src/components/properties/tokenAmount/tokenAmount.tsx
connectors/chains.ts
lib/tokens/tokenData.ts

Fix goerli

---

.ebextensions_ceramic/04_autoscaling.config

Ceramic autorestart

---

components/settings/charms/components/CharmsHistoryTab.tsx
lib/charms/__tests__/rewardCharmsFormProposal.spec.ts
lib/charms/constants.ts
lib/charms/triggers/rewardCharmsForProposal.ts
lib/proposals/createProposal.ts

Charms proposal trigger

---

components/members/components/MemberProfile/components/ProfileWidgets/components/CollectionWidget/NftAvatarGallery/NftGalleryItem.tsx
lib/blockchain/getNFTs.ts
lib/blockchain/provider/alchemy/client.ts
lib/blockchain/provider/ankr/client.ts
lib/blockchain/provider/zksync/client.ts
lib/blockchain/provider/zora/getNFT.ts

[Discussion](https://discord.com/channels/894960387743698944/1217815145296957533)

Use BigInt to convert token id to decimal string

---

.cdk/staging-stack.ts

use TLS1.3 on load balancer in staging

---

__e2e__/proposals/structuredProposalTemplate.spec.ts

[### WHAT
https://github.com/charmverse/app.charmverse.io/actions/runs/8333970135/job/22808396199?pr=3770

disable flaky e2e

---

components/settings/profile/components/Integration.tsx

[Card](https://app.charmverse.io/charmverse/align-and-make-the-same-size-the-identity-properties-9708133746643683)
Before:
Now:

Fixed user accounts layout

---

components/rewards/components/RewardApplicationPage/components/GnosisSafesList.tsx
hooks/useCreateSafes.ts
hooks/useMultiGnosisPayment.ts
hooks/useMultiRewardPayment.ts

[Discussion](https://discord.com/channels/894960387743698944/1218670805861531750)
[Log](https://app.datadoghq.com/logs?query=%40spaceId%3A2d8f34f9-01f2-4136-94ae-39fc48ac6534%20%22InvalidAddressError%3A%20Address%20%5C%22eoa.agoraea.eth%5C%22%20is%20invalid.%22%20&cols=host%2Cservice&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&sp=&storage=hot&stream_sort=desc&viz=stream&from_ts=1710481848866&to_ts=1710654648866&live=true)

Fixed gnosis payment via custom erc 20 token

---

.github/workflows/test_and_deploy.yml

require e2e to pass before deploying to production

---

lib/databases/__tests__/relationProperty/syncRelationProperty.spec.ts

Fix flaky test: assumes sorting of query result

---

components/proposals/ProposalPage/components/ProposalProperties/components/CustomPropertiesAdapter.tsx

add default created time for new proposals

---

components/proposals/ProposalPage/NewProposalPage.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/RubricAnswersForm.tsx
lib/proposals/rubric/upsertRubricAnswers.ts
lib/proposals/updateProposalWorkflow.ts

User was accidentally putting their score into the comment box

Dont allow user to save rubric comments with no score

---

components/members/components/MemberProfile/components/UserCredentials/UserCredentialRow.tsx
lib/credentials/external/getOnchainCredentials.ts
lib/credentials/getAllUserCredentials.ts

Fixed getting onchain credentials

---

components/common/CreateSpaceForm/TemplateIcon.tsx
lib/spaces/config.ts
lib/templates/exports/templateGaming.json
lib/templates/importSpaceSettings.ts
scripts/exportData/exportEntireSpace.ts
scripts/exportData/exportNewTemplate.ts

add Gaming Template

---

components/[pageId]/DocumentPage/components/RewardProperties.tsx

remove uncessary api call

---

components/common/CreateSpaceForm/TemplateIcon.tsx

Replace icon for gaming template

---

components/common/DatabaseEditor/store/cards.ts
lib/databases/card.ts

fix db templates not appearing

---

lib/databases/generateCsv.ts
lib/permissions/api/overridenPermissionsApiClient.ts

App was erroring out when too many pageIds were sent over the wire

Paginate bulk page permissions requests

---

charmClient/hooks/pages.ts
components/[pageId]/DocumentPage/DocumentPage.tsx
components/common/DatabaseEditor/components/properties/PagesAutocomplete.tsx
components/common/DatabaseEditor/components/properties/RelationPropertyPagesAutocomplete.tsx
components/common/DatabaseEditor/store/cards.ts
hooks/usePages.tsx

- improve performance when looking at card type pages.
- fixes updating card templates
- includes some cleanup for relation pages UI

fix selectors in DocumentPage

---

lib/rewards/__tests__/rollupRewardStatus.spec.ts
lib/rewards/rollupRewardStatus.ts

Rewards were moved to complete status, even though they still had open slots

Fix rewards rollup

---

components/common/DatabaseEditor/components/table/tableRow.tsx

fix frozen rewards page

---

components/common/DatabaseEditor/components/table/__snapshots__/tableRow.spec.tsx.snap
components/common/DatabaseEditor/components/table/tableRow.spec.tsx

Before the fix, this test never would have finished

add test for recursive table rows

---

components/settings/credentials/components/CredentialEventsForm.tsx
components/settings/credentials/components/CredentialTemplateDialog.tsx
lib/credentials/schemas/external.ts
lib/credentials/schemas/index.ts

Fix types for external projects

---

__e2e__/proposals/joinSpaceViaProposals.spec.ts
components/common/CharmEditor/CharmEditor.tsx
components/common/CharmEditor/InlineCharmEditor.tsx
components/common/CharmEditor/components/emojiSuggest/EmojiPopup.tsx
components/common/CharmEditor/components/inlinePalette/InlinePalletteFloatingMenu.tsx
components/common/CharmEditor/components/inlinePalette/components/InlineCommandPalette.tsx
components/common/CharmEditor/components/inlinePalette/useEditorItems.ts
components/common/CharmEditor/components/linkedPage/components/LinkedPage.tsx
components/common/CharmEditor/components/linkedPage/components/LinkedPagesPopup.tsx
components/common/CharmEditor/components/linkedPage/linkedPage.specs.ts
components/common/CharmEditor/components/mention/components/Mention.tsx
components/common/CharmEditor/components/mention/components/MentionsPopup.tsx
components/common/CharmEditor/components/mention/components/index.ts
components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx
components/common/CharmEditor/components/nestedPage/hooks/useAddNestedPage.ts
components/common/CharmEditor/components/nestedPage/index.ts
components/common/CharmEditor/hooks/useGetPageDetails.ts
components/common/CharmEditor/hooks/useGetPageMetaFromCache.ts
components/common/CharmEditor/plugins.ts
components/common/CharmEditor/specRegistry.ts
lib/prosemirror/markdown/generateMarkdown.ts

This is a cleanup + fix so that mentions query page details just like page links

retrieve pages for mentions like we do for nested pages and linked pages

---

__integration-tests__/server/pages/api/blocks/[id]/index.spec.ts
__integration-tests__/server/pages/api/blocks/[id]/subtree.spec.ts
lib/databases/__tests__/getRelatedBlocks.spec.ts
lib/databases/block.ts
lib/databases/getRelatedBlocks.ts

dont return deleted blocks for subtree

---

charmClient/apis/pagesApi.ts
charmClient/hooks/pages.ts
components/common/CharmEditor/CharmEditor.tsx
components/common/CharmEditor/components/linkedPage/components/LinkedPagesPopup.tsx
components/common/CharmEditor/components/mention/components/Mention.tsx
components/common/CharmEditor/components/mention/components/MentionsPopup.tsx
components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx
components/common/CharmEditor/hooks/useGetPageMetaFromCache.ts
components/common/PageIcon.tsx
components/common/PageLayout/components/Sidebar/NavigationSidebar.tsx
components/common/PageLayout/components/Sidebar/components/PageNavigation/components/AddNewCard.tsx
components/common/PageLayout/components/Sidebar/components/PageNavigation/components/PageTreeItem.tsx
components/common/PageLayout/components/Sidebar/components/SearchInWorkspaceModal.tsx
components/common/PagesList.tsx
hooks/useRootPages.ts
hooks/useSearchPages.ts

cleanup page search and add it to link components

---

components/common/CharmEditor/components/linkedPage/components/LinkedPagesPopup.tsx
hooks/useRootPages.ts
hooks/useSearchPages.ts

better sorting of page results

---

hooks/__tests__/useRootPages.spec.ts
hooks/useRootPages.ts

use proper sorting for root pages and add tests

---

charmClient/hooks/helpers.ts
charmClient/hooks/pages.ts
components/common/CharmEditor/components/linkedPage/components/LinkedPagesPopup.tsx
components/common/DatabaseEditor/components/centerPanel.tsx
components/common/PageLayout/components/Sidebar/components/SearchInWorkspaceModal.tsx
hooks/useSearchPages.ts
lib/pages/__tests__/getRecentHistory.spec.ts
lib/pages/getPageMetaLite.ts
lib/pages/getRecentHistory.ts
lib/pages/interfaces.ts
lib/utils/dates.ts
pages/api/pages/recent-history.ts
scripts/exportProposalScores.ts

Show recent pages when using search and update the UI

---

lib/utils/__tests__/dates.spec.ts
lib/utils/dates.ts

fix relative date util + test

---

__e2e__/po/proposalPage.po.ts
__e2e__/proposals/freeFormProposalTemplate.spec.ts
components/_app/GlobalComponents.tsx
components/proposals/ProposalPage/NewProposalPage.tsx
components/proposals/ProposalPage/components/TemplateSelect.tsx
components/rewards/components/RewardProperties/RewardPropertiesForm.tsx

We were relying on usePages to grab the template, this was code based on an old implementation

Fix view of proposal template

---

lib/proposals/__tests__/getProposalErrors.spec.ts
lib/proposals/getProposalErrors.ts

Ignore whitespace when checking proposal title

---

scripts/migrations/2024_03_28_cleanupPageOrphans.ts
scripts/query.ts

there were about 450 pages with a parentId that no longer exists

save migration script used to fix orphan pages

---

lib/utils/__tests__/dates.spec.ts
lib/utils/dates.ts

fix flaky date util test

---

__e2e__/database/relationProperty.spec.ts
__e2e__/proposals/freeFormProposalTemplate.spec.ts
__e2e__/proposals/joinSpaceViaProposals.spec.ts
__e2e__/proposals/proposalCustomProperties.spec.ts
__e2e__/proposals/proposalEvaluations.spec.ts
__e2e__/sidebarAddNewSpace.spec.ts

improve how we check for text in e2e

---

lib/blockchain/refreshENSName.ts
lib/users/createUser.ts

We are being rate-limited by Alchemy and I can't even use my dev env right now, which has our production alchemy key

dont fail user login/creation if alchemy returns an error

---

hooks/usePages.tsx
pages/api/pages/[id]/duplicate.ts

When a page was duplicated, it wouldn't show up

Notify UI about newly duplicated pages

---

package.json

remove bangle.dev markdown lib

---

charmClient/apis/pagesApi.ts
components/common/PageActions/components/DatabasePageActionList.tsx
lib/databases/__tests__/generateCsv.spec.ts
lib/databases/generateCsv.ts
pages/api/pages/[id]/export-database.ts

[Card](https://discord.com/channels/894960387743698944/1222177843283492916)

Skip hidden columns during database export

---

__e2e__/charmEditor/rangeDeleteBlocks.spec.ts
__e2e__/utils/mocks.ts
components/common/CharmEditor/components/rowActions/RowActionsMenu.tsx

[Card](https://discord.com/channels/894960387743698944/1225077704865484810)

Fix issue deleting multiple blocks in document

---

components/common/DatabaseEditor/components/propertyValueElement.tsx

[Card](https://discord.com/channels/894960387743698944/1225441163188637706)

Show numeric values for proposal as a source boards

---

lib/forms/upsertProposalFormAnswers.ts
scripts/applicationImport/checkSelectFields.ts
scripts/applicationImport/exportFormState.ts
scripts/applicationImport/importApplications.ts
scripts/applicationImport/restoreFormFromLogs.ts

Scripts for importing applications from a CSV into an existing form

Import application data

---

scripts/migrations/2024_04_04_declineAndArchiveProposals.ts

[Discussion](https://discord.com/channels/894960387743698944/1224740821191098559)

Script to decline and archive proposals in space

---

components/common/DatabaseEditor/components/__snapshots__/centerPanel.spec.tsx.snap
components/common/DatabaseEditor/components/viewHeader/__snapshots__/viewHeader.spec.tsx.snap
components/common/DatabaseEditor/components/viewHeader/viewTabs.tsx

[Discussion](https://discord.com/channels/894960387743698944/1226891414458335293)

Fixed database view tabs bug

---

.cdk/staging-stack.ts

disable autoscaling alerts for staging

---

__e2e__/charmEditor/inlineComments.spec.ts
__e2e__/po/document.po.ts
components/[pageId]/DocumentPage/components/Sidebar/components/TogglePageButton.tsx
components/common/CharmEditor/components/inlineComment/components/InlineCommentThread.tsx
components/common/CharmEditor/components/inlineComment/inlineComment.plugins.tsx
lib/prosemirror/highlightMarkedElement.ts

Comments popover was not showing.
Task: https://app.charmverse.io/charmverse/comments-not-working-as-expected-16890573874310988

Fix comments popover not showing on icon click

---

.ebstalk.apps.env/cron.env

Added github webhook secret to cron.env

---

components/settings/integrations/components/SpaceIntegrations.tsx

Separate save button for snapshot domain in integrations

---

components/common/form/fields/ProjectProfileInputField.tsx
components/settings/projects/ProjectsSettings.tsx
components/settings/projects/hooks/useProjectForm.ts
components/settings/projects/hooks/useProjectUpdates.ts

Check for team lead based on flag

---

lib/databases/__tests__/cardFilter.spec.ts
lib/databases/cardFilter.ts

Fix proposal filter for PRoposal Status

---

__e2e__/pagesSidebar.spec.ts
__e2e__/publicPage.spec.ts
__e2e__/publicPageLink.spec.ts
__e2e__/sessions/login.spec.ts
__e2e__/sidebarAddNewSpace.spec.ts
__e2e__/utils/mocks.ts
components/common/PageLayout/PageLayout.tsx
components/common/PageLayout/SharedPageLayout.tsx
components/common/PageLayout/components/Header/Header.tsx
components/common/PageLayout/components/LayoutProviders.tsx
components/common/PageLayout/components/Sidebar/NavigationSidebar.tsx
components/common/PageLayout/components/Sidebar/NavigationSidebarDrawer.tsx
components/common/PageLayout/components/Sidebar/components/SidebarSubmenu.tsx
components/common/PageLayout/components/Sidebar/hooks/useNavigationSidebar.ts
components/settings/subscription/loadStripe.ts
hooks/useSharedPage.ts

Now when you visit a free tier space's public page, we will show the sidebar nav also. Includes some cleanup for e2e
Request for CharmVerse Community

Add a sidebar on shared page for free tiered spaces

---

lib/databases/relationProperty/__tests__/syncRelatedCardsValues.spec.ts

[Card](https://app.charmverse.io/charmverse/tech-task-list-49366552253645923?viewId=50d940bb-fdbd-40ba-9816-616d6138a663&cardId=9a8de404-f3ab-4c4a-b3b7-ddd3da1882b7)

Fixed unit test for sync related card values

---

lib/prosemirror/__tests__/updateEntityIds.spec.ts
lib/prosemirror/updateEntityIds.ts
lib/templates/importWorkspacePages.ts

No change in logic, jsut a cleanup + tests

extract and add tests on code for replacing ids in prosemirror nodes

---

components/common/DatabaseEditor/components/propertyValueElement.tsx

dont log error when value is undefined

---

components/common/CharmEditor/components/nft/NFTNodeView.tsx
components/common/form/CustomERCTokenForm.tsx
components/common/form/FormField.tsx
components/common/form/FormFieldAnswers.tsx
components/common/form/InputSearchBlockchain.tsx
components/common/form/fields/FieldTypeRenderer.tsx
components/common/form/fields/TextInputField.tsx
components/common/form/fields/utils.ts
components/common/form/interfaces.ts

[Card](https://app.charmverse.io/charmverse/extend-wallet-input-to-allow-a-blockchain-requirement-9395122206771407)

Added chain select for wallet address form field

---

components/common/PageActions/components/CopyPageLinkAction.tsx
components/common/PageLayout/components/Header/components/ShareButton/ShareButton.tsx
components/common/PageLayout/components/Header/components/ShareButton/components/FreePagePermissions/FreePagePermissions.tsx
components/common/PageLayout/components/Header/components/ShareButton/components/PaidPagePermissions/PagePermissionRow.tsx
components/common/PageLayout/components/Header/components/ShareButton/components/PaidPagePermissions/PaidPagePermissions.tsx
components/common/PageLayout/components/Header/components/ShareButton/components/ShareModal.tsx
components/common/PageLayout/components/Header/components/ShareButton/components/common/CopyLinkFooter.tsx
components/common/form/InputEnumToOptions.tsx
lib/permissions/pages/labels.ts

1. add a Copy link icon to the footer
2. Show "No access" instead of "Remove" for default permissions:

Share modal UX

---

charmClient/charmClient.ts
hooks/useNotionImport.tsx
lib/notion/NotionImporter/CharmverseDatabasePage.ts
lib/notion/NotionImporter/CharmversePage.ts
lib/notion/NotionImporter/NotionBlock.ts
lib/notion/NotionImporter/NotionCache.ts
lib/notion/NotionImporter/NotionImporter.ts
lib/notion/NotionImporter/NotionPage.ts
lib/notion/createPrismaPage.ts
lib/notion/interfaces.ts
lib/websockets/interfaces.ts
package.json
pages/api/notion/import.ts

Better handling of linked database when importing from Notion

---

components/credentials/CredentialsSelect.tsx
lib/credentials/templates.ts

Fix the UI to show correct shape in rewards and filter out the events

---

scripts/copyRubricCriterias.ts

I was accidentally assigning all new rubric criteria to the source proposal :(

Fix script for ocpying rubric criteria

---

components/common/DatabaseEditor/DatabaseProvider.tsx

When I added the listener to page update, i was assuming that title would exist all the time. But if the icon fo a page was changing, we ended up passing in `undefined` for `title`  and removing the page title inside of card state

Fix titles disappearing in kanban boards

---

lib/github/createRewardFromIssue.ts

[Datadog](https://app.datadoghq.com/logs?query=%40logger%3Asqs&cols=host%2Cservice&fromUser=true&index=*&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1713788335767&to_ts=1713791935767&live=true)

Fixed non issue related events from throwing error in github sqs

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx

Fix publish rewards not working

---

__integration-tests__/server/pages/api/pages/[id]/proposal-source.spec.ts
lib/databases/board.ts
lib/databases/proposalsSource/__tests__/getBoardProperties.spec.ts
lib/databases/proposalsSource/__tests__/getCardProperties.spec.ts
lib/databases/proposalsSource/getBoardProperties.ts

An improper setting was applied when using custom properties in proposal db

Fix proposal properties db

---

components/rewards/components/RewardChip.tsx
lib/pages/server/pageMetaSelect.ts
pages/api/spaces/[id]/pages.ts
stories/Databases/CardDetails.stories.tsx
stories/Databases/Kanban.stories.tsx
stories/Databases/TableProperties.stories.tsx
testing/mocks/page.ts

fix types from core

---

package.json
scripts/migrations/2024_04_23_transferLensPostLinkToPages.ts
testing/mocks/proposal.ts

Fixed broken type issues for proposal lensPostLink removal

---

components/common/DatabaseEditor/components/propertyValueElement.tsx
components/rewards/components/RewardsBoard/utils/boardData.ts
components/rewards/components/RewardsBoard/utils/getDefaultRewardProperties.ts
components/rewards/hooks/useRewardsBoardAdapter.ts
lib/rewards/getReward.ts
lib/rewards/interfaces.ts
lib/rewards/mapDbRewardToReward.ts
pages/api/public/pages/[...pageId]/index.ts

re-enabling a feature that got lost during refactors... i also removed a bunch of unecessary logic to check if milestones exist or not, which chris was OK with

add proposal link column back to rewards

---

__integration-tests__/server/pages/api/rewards/[id]/index.spec.ts
lib/rewards/interfaces.ts
lib/templates/exports/templateCreator.json
lib/templates/exports/templateGaming.json
lib/templates/exports/templateGrantRecipient.json
lib/templates/exports/templateGrantor.json
lib/templates/exports/templateHackathon.json
lib/templates/exports/templateImpactCommunity.json
lib/templates/exports/templateNftCommunity.json
lib/templates/exports/templateNounishDAO.json
testing/setupDatabase.ts

Removed lensPostLink from space templates

---

components/[pageId]/DocumentPage/components/PageTemplateBanner.tsx
components/rewards/components/RewardsBoard/utils/boardData.ts
components/rewards/components/RewardsBoard/utils/getDefaultRewardProperties.ts
components/rewards/hooks/useRewardsBoard.ts

use custom name for Proposal column in rewards page

---

__integration-tests__/server/pages/api/proposals/[id]/index.spec.ts
__integration-tests__/server/pages/api/proposals/index.spec.ts
components/common/DatabaseEditor/components/viewHeader/ViewHeaderRowsMenu/components/IssueProposalCredentials.tsx
components/common/DatabaseEditor/components/viewHeader/ViewHeaderRowsMenu/components/IssueRewardCredentials.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/ProposalCredentials/CredentialRow.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx
components/settings/credentials/SpaceCredentialSettings.tsx
lib/credentials/findIssuableProposalCredentials.ts
lib/credentials/findIssuableRewardCredentials.ts
lib/credentials/issueOffchainProposalCredentialsIfNecessary.ts
lib/credentials/issueOffchainRewardCredentialsIfNecessary.ts
pages/api/proposals/[id]/index.ts
pages/api/proposals/index.ts

Cover UI improvements mentioned in this [card](https://app.charmverse.io/charmverse/followup-proposal-credential-ux-improvements-5037151388683558)

Onchain proposal creds improvements

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/RubricAnswersForm.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/RubricEvaluation.tsx

Fix for:
https://www.loom.com/share/43bc0fa965e9481fb9155d7509b319a2?sid=81f9a7be-553d-4b0c-b48b-3aaf17750a23

Refresh proposal data after saving rubric draft scores

---

components/common/DatabaseEditor/octoUtils.tsx
lib/databases/__tests__/generateCsv.spec.ts
lib/databases/generateCsv.ts

I needed to update a standard util to support templates with 'dynamicOptions'

fix export of project member information

---

components/common/CharmEditor/components/floatingMenu/LinkSubMenu.tsx
components/common/CharmEditor/components/link/LinksPopup.tsx
components/common/DatabaseEditor/components/table/tableHeader.tsx
components/common/DatabaseEditor/components/viewSidebar/viewPropertyOption.tsx
components/common/DatabaseEditor/mutator.ts
components/common/form/fields/Select/SelectOptionEdit.tsx
components/members/components/MemberDirectorySidebar/AddMemberPropertyButton.tsx
components/members/components/MemberDirectorySidebar/MemberPropertiesSidebarItem.tsx
components/proposals/components/ProposalsBoard/hooks/useProposalsBoardMutator.ts
components/proposals/components/ProposalsBoard/utils/boardData.ts
components/rewards/components/RewardsBoard/hooks/useRewardsBoardMutator.ts
lib/utils/react.ts

Allow renaming title column for Rewards and Proposals page

---

components/[pageId]/DocumentPage/DocumentPage.tsx
components/[pageId]/DocumentPage/DocumentPageWithSidebars.tsx
components/common/workflows/SocialShare/LensSocialShare.tsx
components/rewards/components/NewRewardButton.tsx
components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
components/rewards/components/RewardApplicationPage/RewardApplicationPageV2.tsx
components/rewards/components/RewardApplicationPage/components/RewardApplicationInput.tsx
components/rewards/components/RewardApplicationPage/components/RewardPaymentButton.tsx
components/rewards/components/RewardApplicationPage/components/RewardSubmissionInput.tsx
components/rewards/components/RewardEvaluations/RewardEvaluations.tsx
components/rewards/components/RewardEvaluations/components/Review/EvaluationsReview.tsx
components/rewards/components/RewardEvaluations/components/Review/components/PaymentStepReview.tsx
components/rewards/hooks/useRewardTemplates.ts
lib/rewards/getReward.ts
lib/rewards/getRewardTemplates.ts
lib/rewards/interfaces.ts
lib/rewards/mapDbRewardToReward.ts
lib/rewards/work.ts
package.json
scripts/migrations/2024_04_26_convertCharmEditorApplicationInput.ts

Reward workflow updates

---

__e2e__/bounties/rewardWorkflow.spec.ts
components/[pageId]/DocumentPage/components/RewardProperties.tsx
components/common/DatabaseEditor/components/viewHeader/ViewHeaderRowsMenu/components/BatchPaymentRewards.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx
components/rewards/NewRewardPage.tsx
components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
components/rewards/components/RewardEvaluations/components/Review/components/PaymentStepReview.tsx
components/rewards/components/RewardEvaluations/components/Settings/components/PaymentSettings.tsx
components/rewards/components/RewardStickyFooter.tsx
components/rewards/components/RewardsHeaderRowsMenu.tsx
components/rewards/hooks/useRewardsBoardAdapter.ts
lib/github/createRewardFromIssue.ts
lib/rewards/createReward.ts
lib/rewards/getRewardErrors.ts
lib/rewards/getRewardType.ts
lib/rewards/publishReward.ts
lib/rewards/updateRewardSettings.ts
package.json
scripts/createNestedPage.ts
scripts/generators/createNestedPage.ts
scripts/migrations/2024_04_26_rewardTypes.ts

fix for reward types

---

__e2e__/bounties/rewardWorkflow.spec.ts
__e2e__/po/rewardPage.po.ts
components/[pageId]/DocumentPage/hooks/useReward.ts
components/rewards/components/RewardEvaluations/components/Review/components/PaymentStepReview.tsx
components/rewards/components/RewardEvaluations/components/Settings/components/PaymentSettings.tsx
components/rewards/components/RewardProperties/components/RewardTypeSelect.tsx
lib/rewards/createReward.ts

fix e2e for reward type

---

components/rewards/components/RewardEvaluations/components/Settings/components/SubmitStepSettings.tsx
lib/rewards/setRewardUsers.ts

Fixed reward workflows reverting to direct submission after editing step

---

components/_app/components/ConfirmationModal.tsx
components/rewards/NewRewardPage.tsx
components/rewards/components/RewardEvaluations/components/Settings/EvaluationsSettings.tsx
components/rewards/components/RewardEvaluations/components/Settings/components/EvaluationStepSettings.tsx
components/rewards/components/RewardEvaluations/components/Settings/components/PaymentStepSettings/PaymentStepSettings.tsx
components/rewards/components/RewardEvaluations/components/Settings/components/PaymentStepSettings/components/RewardTokenForm.tsx
hooks/useConfirmationModal.tsx

Fix reward templates

---

pages/api/spaces/[id]/reward-templates.ts

return a response if user is not logged in for reward templates

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RewardReviewStep.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsForm.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/RewardTokenProperty.tsx
components/rewards/components/RewardEvaluations/components/Settings/components/PaymentStepSettings/components/RewardTokenForm.tsx
components/rewards/components/RewardStatusBadge.tsx

show placeholder when user needs to enter token amount

---

components/common/DatabaseEditor/components/kanban/kanbanCard.tsx
components/common/DatabaseEditor/components/kanban/kanbanCardReward.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RewardReviewStep.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/RewardTokenProperty.tsx
components/rewards/components/RewardAmount.tsx
components/rewards/components/RewardEvaluations/components/Review/components/PaymentStepReview.tsx
components/rewards/components/RewardProperties/components/RewardPropertiesHeader.tsx

In addition to feature changes i analyzed how we're using the token components and simplified them further

simplify token amount component and remove badge from rewards

---

components/common/form/fields/FieldWrapper.tsx
package.json

add a div around descriptions to fix printing

---

components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx

Find coinbase wallet connector correctly

---

seedData/gettingStartedPage.ts

[Discussion](https://discord.com/channels/894960387743698944/1234888944865251482)

Updated getting started page

---

lib/blockchain/publicClient.ts

Make sure viem http request fails before our ALB timeouts.

Viem http improvement

---

components/common/CharmEditor/CharmEditor.tsx
components/common/CharmEditor/InlineCharmEditor.tsx
components/common/CharmEditor/components/@bangle.dev/core/bangle-editor.ts
components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
components/common/DatabaseEditor/components/__snapshots__/viewTitle.spec.tsx.snap
testing/prosemirror/renderTestEditor.ts

Request from CIT to translate into Japanese
Demo: https://www.loom.com/share/cd89f499b1284f5ca3e371681884d85f

allow editor content to be translated in read only mode

---

components/common/form/InputSearchMember.tsx
components/settings/integrations/components/Github/GithubSettings.tsx
components/settings/integrations/components/Github/GithubSettingsForm.tsx
hooks/useSettingsDialog.tsx
pages/api/spaces/[id]/github/connect.ts
pages/api/spaces/[id]/github/index.ts

improve connect flow for Github Apps

---

lib/forms/upsertProposalFormAnswers.ts

[Discussion](https://discord.com/channels/894960387743698944/1161331165886697532/1235872712132530237)

Remove milestone form field answers

---

__e2e__/database/addAndShowNewProperty.spec.ts
__e2e__/po/databasePage.po.ts
components/[pageId]/DocumentPage/DocumentPage.tsx
components/common/DatabaseEditor/components/__snapshots__/centerPanel.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/table.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/tableHeader.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/tableHeaders.spec.tsx.snap
components/common/DatabaseEditor/components/table/tableHeader.tsx
components/common/DatabaseEditor/components/table/tableHeaders.tsx

Fix new props not showing on table

---

lib/databases/proposalsSource/__tests__/createMissingCards.spec.ts
lib/databases/proposalsSource/createMissingCards.ts

make sure we create proposals for drafts that were published later

---

components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsForm.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/RewardTokenProperty.tsx
components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalRewards.ts
components/rewards/NewRewardPage.tsx
components/rewards/components/RewardEvaluations/components/Review/components/EvaluationStepSettingsModal.tsx
components/rewards/components/RewardEvaluations/components/Review/components/PaymentStepReview.tsx
components/rewards/components/RewardEvaluations/components/Settings/components/EvaluationStepSettings.tsx
components/rewards/components/RewardEvaluations/components/Settings/components/PaymentStepSettings/PaymentStepSettings.tsx
components/rewards/components/RewardEvaluations/components/Settings/components/PaymentStepSettings/components/RewardTokenForm.tsx
components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
components/rewards/components/RewardProperties/components/RewardTokenDialog.tsx

[Card](https://app.charmverse.io/charmverse/disable-token-chain-and-token-inputs-when-using-a-reward-template-8641440715535329)

Disable token chain and token inputs when using a reward template

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
components/settings/proposals/components/EvaluationContextMenu.tsx
components/settings/proposals/components/EvaluationDialog.tsx
components/settings/proposals/components/EvaluationPermissions.tsx
components/settings/proposals/components/EvaluationRow.tsx
components/settings/proposals/components/ProposalWorkflow.tsx
lib/proposals/getProposal.ts
lib/proposals/getProposalTemplate.ts
lib/proposals/getProposals.ts
lib/proposals/interfaces.ts
lib/proposals/mapDbProposalToProposal.ts
lib/proposals/submitEvaluationResult.ts
package.json
pages/api/proposals/[id]/submit-result.ts
testing/mocks/proposal.ts

Require reason for Fail on Pass/Fail steps

---

pages/[domain]/proposals/new.tsx

prevent creating proposals when they are turned off

---

__e2e__/proposals/joinSpaceViaProposals.spec.ts
components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
components/proposals/components/ProposalsBoard/utils/boardData.ts
lib/databases/proposalDbProperties.ts

Fix step column

---

components/[pageId]/DocumentPage/DocumentPage.tsx
components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx
lib/proposals/validateProposalProject.ts

[Card](https://discord.com/channels/894960387743698944/929085788598177792/1238351461755129877)

Fixed issue with project field not found

---

lib/websockets/spaceEvents.ts

[Card](https://discord.com/channels/894960387743698944/1237812265651015951)

Fixed issue when deleting nested page inside column

---

lib/blockchain/provider/alchemy/client.ts

[Discussion](https://discord.com/channels/894960387743698944/1235705281925742753)

Refetch nft metadata again if it was not retrieved on initial request

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx
components/settings/proposals/components/ProposalWorkflow.tsx
lib/proposals/concealProposalSteps.ts

Lift feature flag for hidden evaluations

---

components/common/DatabaseEditor/components/properties/UserAndRoleSelect.tsx
components/rewards/components/RewardEvaluations/components/Review/components/SubmitStepReview.tsx

Reward applicant roles UI improvement

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/EvaluationStepSettings.tsx
components/proposals/components/ProposalStepSelect.tsx
components/settings/proposals/components/EvaluationDialog.tsx
lib/credentials/issueOffchainProposalCredentialsIfNecessary.ts
lib/notifications/proposals/createProposalNotifications.ts
lib/proposals/getCurrentStep.ts
lib/proposals/getProposalAction.ts
lib/proposals/updateProposalEvaluation.ts
lib/webhookPublisher/publishEvent.ts
pages/api/proposals/[id]/evaluation.ts

Workflow appeal & priority steps UI improvements

---

lib/proposals/workflows/controller.ts

Sync proposal template and workflow appeal & final step settings

---

components/common/DatabaseEditor/components/viewHeader/RelatedPagesSelect.tsx
components/common/DatabaseEditor/components/viewHeader/filterEntry.tsx

Change request from our Friday demo

Make relational field full width

---

components/common/DatabaseEditor/components/centerPanel.tsx
components/common/DatabaseEditor/components/table/table.tsx
components/common/DatabaseEditor/components/table/tableRow.tsx
components/common/DatabaseEditor/components/table/tableRows.tsx
components/common/DatabaseEditor/mutator.ts
components/rewards/components/RewardsBoard/hooks/useRewardsBoardMutator.ts
components/rewards/hooks/useRewardsBoardAdapter.ts
hooks/useAreaSelection.ts
scripts/optimisms/getProjects.ts

We were watching things in a couple places that we didn't need to be and generating methods on the fly, causing unecessary re-renders. This doesn't fully solve the issue  the customer was having, but should help.

optimize React rendering on Rewards page

---

components/common/DatabaseEditor/components/propertyValueElement.tsx
components/proposals/components/ProposalStatusSelect.tsx
lib/databases/proposalDbProperties.ts
lib/proposals/getProposalEvaluationStatus.ts
lib/proposals/interfaces.ts

[Card](https://app.charmverse.io/charmverse/milestone-passed-should-be-passed-7855221366550453)

Fixed passed status for rewards and credentials step

---

components/common/DatabaseEditor/components/table/tableRow.tsx
components/rewards/components/RewardApplicationStatusChip.tsx
components/rewards/hooks/useRewardsBoardAdapter.ts

[Card](https://app.charmverse.io/charmverse/milestone-submission-icons-should-be-yellow-not-red-47321787883119715)

Fixed application and submission label for rewards table

---

components/common/DatabaseEditor/components/kanban/KanbanGroupColumn.tsx
components/common/DatabaseEditor/components/table/PaginatedRows.tsx
components/common/DatabaseEditor/components/table/PaginationShowMore.tsx
components/common/DatabaseEditor/components/table/table.tsx
components/common/DatabaseEditor/components/table/tableRows.tsx
hooks/usePaginatedData.ts

Add the pagination to grouped rows that we built for regualr rows

Paginate grouped tables

---

package.json
scripts/migrations/2024_05_21_createProposalEvaluationAppealReviews.ts

Drop appeal column from proposal evaluation review table

---

__e2e__/bounties/rewardApplication.spec.ts
__e2e__/po/rewardPage.po.ts
components/common/DatabaseEditor/components/table/tableRow.tsx

1. Click on the open button of any of the applications in a rewards table
2. It will show the Error lightning bolt as the redirected url is not correct

Fixed rewards application open button showing error page

---

components/rewards/components/RewardEvaluations/components/Settings/EvaluationsSettings.tsx

[Discussion](https://discord.com/channels/894960387743698944/1242560786799399013)

Show credentials step for rewards templates

---

components/common/PageLayout/components/Sidebar/NavigationSidebar.tsx
config/constants.ts

link Feedback to User Manual

---

lib/utils/domains/__tests__/isValidDomainName.spec.ts
lib/utils/domains/isValidDomainName.ts

[Discussion](https://discord.com/channels/894960387743698944/1242812921000624228)

Better logic for validating domain names

---

components/_app/OpenGraphData.tsx
lib/utils/browser.ts
lib/utils/domains/__tests__/getCanonicalURL.spec.ts
lib/utils/domains/getCanonicalURL.ts
lib/utils/domains/getPagePath.ts
package.json
pages/[domain]/[pageId].tsx

Set canonical URLs to help with SEO. Make sure to consider custom domains

Add Canonical url to document pages

---

components/common/CharmEditor/components/mention/mention.specs.ts

card https://work.charmverse.fyi/work.charmverse.fyi/tech-task-list-49366552253645923?viewId=50d940bb-fdbd-40ba-9816-616d6138a663&cardId=50200331-837b-4c89-9b4d-7f24f0e298d8

fix data loss when copying mentions

---

components/settings/proposals/constants.tsx
lib/databases/proposalDbProperties.ts

Fix types so new core versions can deploy without blocking

Fix type for deploy

---

components/common/CharmEditor/components/markdown/__tests__/markdown.plugin.spec.ts
components/common/CharmEditor/components/markdown/markdown.plugins.ts

[Card](https://app.charmverse.io/charmverse/pasting-code-into-code-block-breaks-the-block-9259967878949904)

Fixed pasting text inside code block

---

lib/templates/__tests__/importWorkspacePages.spec.ts

fix types in test file

---

scripts/testNotion.ts

add a script to test notion search

---

components/_app/OpenGraphData.tsx

add meta for login pages and other default pages

---

components/common/DatabaseEditor/components/propertyValueElement.tsx
components/common/DatabaseEditor/components/table/tableHeader.tsx
lib/databases/board.ts
lib/databases/proposalsSource/__tests__/getBoardProperties.spec.ts
lib/databases/proposalsSource/getBoardProperties.ts
lib/databases/proposalsSource/updateBoardProperties.ts

Added custom tooltip based on description for rubric criteria columns

---

components/common/DatabaseEditor/components/propertyValueElement.tsx
components/common/DatabaseEditor/store/cards.ts
components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
lib/databases/cardFilter.ts
lib/databases/proposalsSource/getBoardProperties.ts
lib/databases/proposalsSource/getCardProperties.ts
lib/databases/proposalsSource/getCardPropertiesFromRubric.ts
lib/databases/proposalsSource/updateBoardProperties.ts
lib/proposals/blocks/interfaces.ts
lib/proposals/createDefaultProposal.ts

use proposalReviewer type for column

---

components/login/LoginPage.tsx
components/login/LoginPageContent.tsx
pages/_app.tsx

update copy for login page and page titles

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluationContainer.tsx

Use outlined pan icon for appeal step

---

lib/notion/NotionImporter/NotionPage.ts

catch errors when retrieving child ids in notion

---

lib/blockchain/getENSName.ts

Fix:
- Issue when an ens avatar is hosted on ipfs

Fix ens avatar timeout

---

scripts/exportData/exportCandidates.ts

add script to export Orange DAO candidates

---

components/settings/space/components/NotificationToggles.tsx
lib/notifications/constants.ts
lib/notifications/getNotificationMetadata.tsx
lib/notifications/proposals/createProposalNotifications.ts
lib/webhookPublisher/interfaces.ts
lib/webhookPublisher/publishEvent.ts
pages/api/proposals/[id]/publish.ts
pages/api/proposals/evaluations/[id]/appeal/index.ts
scripts/migrations/2024_06_06_uncheckProposalPublishedNotification.ts
serverless/sqs/worker.ts

Send notification & email for proposal publish event

---

__e2e__/proposals/structuredProposalTemplate.spec.ts
__e2e__/proposals/structuredProposalWithProject.spec.ts
background/cron.ts
background/tasks/__tests__/sendDraftProposalNotificationTask.spec.ts
background/tasks/sendDraftProposalNotificationTask.ts
components/settings/proposals/SpaceProposalSettings.tsx
components/settings/proposals/components/EvaluationNotifications.tsx
components/settings/proposals/components/ProposalWorkflow.tsx
lib/notifications/constants.ts
lib/notifications/getNotificationMetadata.tsx
lib/proposals/createDraftProposal.ts
lib/proposals/workflows/__tests__/upsertWorkflowTemplate.spec.ts
lib/proposals/workflows/defaultWorkflows.ts
lib/templates/__tests__/importSpaceSettings.spec.ts
package.json
serverless/sqs/worker.ts

[Card](https://app.charmverse.io/charmverse/tech-task-list-49366552253645923?viewId=50d940bb-fdbd-40ba-9816-616d6138a663&cardId=fe606744-5af8-4e29-984f-7846f2c33817)

Send draft proposal publish reminder notification

---

charmClient/apis/blockchainApi.ts
charmClient/hooks/email.ts
components/settings/SettingsContent.tsx
components/settings/notifications/NotificationSettings.tsx
components/settings/notifications/components/SpaceEmailBrandingSettings.tsx
components/settings/notifications/components/SpaceNotificationSettings.tsx
pages/api/email/send-test.ts

UI to send test notification email

---

scripts/addOrangeDaoMembersAndCreateNotifications.ts

Fix:
- Update custom notification id to be the same with notification metadata id
- Update create script to add the same id for both tables

Fix orange dao notifications

---

charmClient/hooks/proposals.ts
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluationContainer.tsx
components/settings/notifications/components/SpaceEmailBrandingSettings.tsx
lib/proposals/submitEvaluationAppealResult.ts
lib/proposals/submitEvaluationResult.ts
package.json
pages/api/proposals/[id]/submit-result.ts
pages/api/proposals/evaluations/[id]/appeal/submit-result.ts

[Card](https://app.charmverse.io/charmverse/allow-optional-multiline-input-when-selecting-disabledreason-6569399269466205)

Multiline input for declining proposal evaluation review

---

pages/api/email/send-test.ts

Fixed test notification email sent to user's email

---

.ebstalk.apps.env/serverless.env
lib/mailer/mailer.ts

Fixed incorrect mailgun api key for serverless env

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/FeedbackEvaluation.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
components/rewards/components/RewardEvaluations/components/Review/components/ReviewStepReview.tsx
components/rewards/components/RewardEvaluations/components/Review/components/SubmitStepReview.tsx

Wrap list of reviewers in workflow steps

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/FeedbackEvaluation.tsx

Fixed duplicate wrapColumn prop issue

---

lib/databases/proposalsSource/__tests__/filterBoardProperties.spec.ts
lib/databases/proposalsSource/filterBoardProperties.ts
lib/projects/formField.ts
scripts/migrations/2024_06_11_exportCustomProposalSourceBoardProperties.ts

Fixed custom proposal source board properties not showing

---

lib/mailer/emails/templates/components/Header.tsx

Max height for custom email logo

---

pages/_app.tsx

fix for <!-- --> appearing in page titles

---

components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProposalSourcePropertiesDialog.tsx
components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/RubricEvaluationPropertiesList.tsx
components/common/DatabaseEditor/store/cards.ts
components/common/DatabaseEditor/widgets/iconForPropertyType.tsx
components/common/DatabaseEditor/widgets/typeDisplayName.ts
lib/databases/board.ts
lib/databases/filterClause.ts
lib/databases/generateCsv.ts
lib/databases/proposalDbProperties.ts
lib/databases/proposalsSource/__tests__/filterBoardProperties.spec.ts
lib/databases/proposalsSource/__tests__/getBoardProperties.spec.ts
lib/databases/proposalsSource/__tests__/getCardProperties.spec.ts
lib/databases/proposalsSource/__tests__/updateBoardProperties.spec.ts
lib/databases/proposalsSource/createSelectedPropertiesFromBoardProperties.ts
lib/databases/proposalsSource/filterBoardProperties.ts
lib/databases/proposalsSource/getBoardProperties.ts
lib/databases/proposalsSource/getCardProperties.ts
lib/databases/proposalsSource/getCardPropertiesFromRubric.ts

[Card](https://app.charmverse.io/charmverse/add-average-score-of-rubric-criteria-to-database-with-proposal-source-32041564643626375)

Rubric criteria average score in proposal source board properties

---

components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProposalSourcePropertiesDialog.tsx
components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/RubricEvaluationPropertiesList.tsx
lib/databases/board.ts
lib/databases/proposalDbProperties.ts
lib/databases/proposalsSource/__tests__/filterBoardProperties.spec.ts
lib/databases/proposalsSource/__tests__/getBoardProperties.spec.ts
lib/databases/proposalsSource/__tests__/getCardProperties.spec.ts
lib/databases/proposalsSource/createSelectedPropertiesFromBoardProperties.ts
lib/databases/proposalsSource/filterBoardProperties.ts
lib/databases/proposalsSource/getBoardProperties.ts
lib/databases/proposalsSource/getCardPropertiesFromRubric.ts
lib/databases/proposalsSource/updateBoardProperties.ts
package.json
scripts/generateProposals.ts

Proposal source board rubric evaluation criteria reviewer comment and score properties

---

lib/github/getMergedPullRequests.ts
lib/github/summariseDeveloperActivity.ts
lib/github/summarisePullRequest.ts
scripts/exportData/exportDevCandidates.ts

Fixed some parts of the query to github graphql API
Return first 5 pull requests

GitHub graphql query fix

---

pages/_app.tsx

I fixed this in prod but it was happening in dev mode:

fix page title in DEV mode

---

__e2e__/proposals/freeFormProposalTemplate.spec.ts
components/proposals/ProposalPage/components/ProposalEvaluations/ProposalEvaluations.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/EvaluationStepSettingsRow.tsx

[Card](https://app.charmverse.io/charmverse/proposals-collapse-the-step-sections-when-you-are-editing-a-template-and-using-a-proposal-template-7553013986177897)

Collapse evaluation section for creating proposal with template

---

background/tasks/__tests__/sendDraftProposalNotificationTask.spec.ts
background/tasks/sendDraftProposalNotificationTask.ts
testing/utils/proposals.ts

delete empty proposal drafts instead of sending notifications

---

.gitignore
__e2e__/rewards/filterRewards.spec.ts
components/rewards/hooks/useRewardsBoardAdapter.ts
lib/databases/cardFilter.ts

Fix array map filter to prevent errors on non extensible objects

Fix array map

---

__integration-tests__/server/pages/api/proposals/evaluations/[id]/appeal/index.spec.ts
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluationContainer.tsx
pages/api/proposals/evaluations/[id]/appeal/index.ts

Allow admin to appeal failed step

---

components/rewards/components/RewardAmount.tsx
components/rewards/components/RewardEvaluations/components/Review/components/PaymentStepReview.tsx
components/rewards/components/RewardEvaluations/components/Settings/components/PaymentStepSettings/PaymentStepSettings.tsx

Fix usage of space character and show full custom reward in sidebar

---

components/common/DatabaseEditor/widgets/propertyMenu.tsx
components/common/form/fields/SelectField.tsx

Add guard when checking existing options

---

components/common/form/fields/FieldTypeRenderer.tsx
components/common/form/fields/TextInputField.tsx

add a link icon to URL inputs

---

scripts/optimism/updateAppealReviewers.ts

Update appeal reviewer script

---

components/common/form/hooks/formFieldSchema.ts
components/common/form/hooks/useFormFields.ts

i needed this for a script but it would be useful for other things in the future

extract form field schema

---

components/common/form/fields/FieldTypeRenderer.tsx
components/common/form/fields/TextInputField.tsx

this works for project fields too, which are just 'text' type but should be a URL

show URL link whenever a link is present in a text input

---

pages/api/farcaster/signer.ts

TODO
- Select final Fid for connecting
- Clean up types for the signer request

Fix generating a signer

---

lib/databases/proposalDbProperties.ts
lib/databases/proposalsSource/filterBoardProperties.ts

Fixed proposal step value

---

.ebstalk.apps.env/connect-api.env
.ebstalk.apps.env/connect.env
apps/connect-api/src/api/image/upload.ts
apps/connect-api/src/routes.ts
apps/connect/apiClient/apiClient.ts
apps/connect/app/create-project/page.tsx
apps/connect/app/profile/page.tsx
apps/connect/components/common/FarcasterCard.tsx
apps/connect/components/farcaster/SearchFarcasterUser.tsx
apps/connect/components/home/HomePage.tsx
apps/connect/components/projects/AddProjectMembersForm.tsx
apps/connect/components/projects/CreateProject.tsx
apps/connect/components/projects/CreateProjectForm.tsx
apps/connect/components/projects/ProjectItem.tsx
apps/connect/components/projects/ProjectsList.tsx
apps/connect/components/welcome/WelcomePage.tsx
apps/connect/hooks/useFilePicker.ts
apps/connect/hooks/useS3UploadInput.ts
apps/connect/lib/actions/createProject.ts
apps/connect/lib/projects/form.ts
apps/connect/lib/projects/getRecentProjectsWithMembers.ts
components/common/CharmEditor/components/image/ResizableImage.tsx
components/common/PdfSelector/PdfSelector.tsx
hooks/useS3UploadInput.ts
lib/aws/uploadToS3Browser.ts
lib/farcaster/__tests__/loginWithFarcaster.spec.ts
lib/farcaster/getFarcasterProfile.ts
lib/farcaster/loginWithFarcaster.ts
package.json

Connect project form

---

.github/workflows/test_and_deploy.yml
apps/connect-api/src/server.ts
apps/connect/apiClient/HttpClient.ts
apps/connect/apiClient/apiClient.ts

Fix connect api

---

.ebstalk.apps.env/connect-api.env
.ebstalk.apps.env/connect.env
.github/workflows/deploy_staging.yml
.github/workflows/test_and_deploy.yml
apps/connect-api/package.json
apps/connect-api/src/lib/pathBasedRouter.ts
apps/connect-api/src/logRoutes.ts
apps/connect-api/src/main.ts
apps/connect-api/src/server.ts
apps/connect/apiClient/HttpClient.ts

CI performance: dont create a changeset to change cloudformation, just change directly
[](https://pgrzesik.com/posts/speed-up-cdk-deploments/)

Fix connect api, add logging and speed up CI a little

---

.github/workflows/destroy_staging.yml

fix destroy staging envs

---

components/common/form/fields/OptimismProjectSelector.tsx

Display op project details in tabs

---

apps/connect-api/src/server.ts
docker-compose.yml

fix cookie config for staging

---

components/common/PageLayout/components/Header/components/ShareButton/components/FreePagePermissions/FreeShareToWeb.tsx
components/common/PageLayout/components/Header/components/ShareButton/components/PaidPagePermissions/PaidShareToWeb.tsx
components/common/PageLayout/components/Header/components/ShareButton/components/common/ShareToWeb.tsx

Hide allowDiscovery for proposals

---

hooks/useFarcasterUser.tsx

Fix farcaster user crash

---

__e2e__/po/formField.po.ts
__e2e__/proposals/structuredProposalWithProject.spec.ts
components/proposals/hooks/useProjectForm.ts

fix update of project schema

---

lib/rewards/__tests__/createReward.spec.ts
lib/rewards/createReward.ts

save gallery image when creating new rewards

---

pages/api/farcaster/signer.ts

Use CharmConnect fid

---

components/common/DatabaseEditor/components/propertyValueElement.tsx

handle wrong errors in database elements

---

__e2e__/proposals/structuredProposalWithProject.spec.ts

re-establish e2e tests for proposal projects

---

__e2e__/po/proposalPage.po.ts
__e2e__/proposals/convertPageToProposal.spec.ts
components/common/PageActions/components/DocumentPageActionList.tsx
pages/[domain]/proposals/new.tsx
scripts/query.ts

Only authors can convert a page to proposal

---

scripts/exportData/exportCITRewards.ts

Script to export the applciation status of all users

---

components/settings/notifications/components/SpaceNotificationSettings.tsx
lib/notifications/createNotificationsFromEvent.ts
lib/notifications/documents/getDocumentNotifications.ts

allow admins to toggle forum post events

---

components/common/form/hooks/formFieldSchema.ts
connectors/chains.ts
hooks/useENSName.tsx
lib/gitcoin/createProjectCredentials.ts
lib/gitcoin/getProjectDetails.ts
lib/projects/createProjectYupSchema.ts
lib/questbook/createProjectCredentials.ts
package.json

update taiko mainnet

---

apps/connect/app/layout.tsx
apps/connect/app/p/[path]/page.tsx
apps/connect/components/common/WarpcastLogin/WarpcastLogin.tsx
apps/connect/components/home/HomePage.tsx

Connect app UI - Update 3

---

__e2e__/proposals/structuredProposalWithProject.spec.ts
components/settings/projects/components/ProjectForm.tsx
lib/projects/__tests__/createProject.spec.ts
lib/projects/__tests__/updateProject.spec.ts
lib/projects/constants.ts
lib/projects/createProject.ts
lib/projects/getDefaultProjectValues.ts
lib/projects/updateProjectAndMembers.ts
lib/proposals/__tests__/validateProposalProject.spec.ts
lib/proposals/form/__tests__/getProposalProjectFormAnswers.spec.ts
lib/proposals/getProposalErrors.ts

Fix tests again for proposal project - skip-tests

---

apps/connect/app/p/[path]/not-found.tsx
apps/connect/app/p/[path]/page.tsx
apps/connect/app/u/[username]/not-found.tsx
apps/connect/app/u/[username]/page.tsx
apps/connect/components/common/NotFoundPage.tsx
apps/connect/components/profile/[username]/ProfileDetailsPage.tsx
apps/connect/components/projects/[id]/ProjectDetailsPage.tsx

[Card](https://app.charmverse.io/charmverse/clean-up-404-page-for-projects-02436801675030642)

Project & user not found page layout

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/RubricAnswersForm.tsx
lib/proposals/rubric/upsertRubricAnswers.ts

[Card](are-required-to-answer-every-rubric-question-before-submitting-answers-8175577279861856)

Required reviewer answer for each rubric criteria

---

.ebstalk.apps.env/connect.env
.github/workflows/deploy_staging.yml
apps/connect/apiClient/apiClient.ts

test connect

---

components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/ProposalSourcePropertiesDialog.tsx
components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/RubricEvaluationPropertiesList.tsx
components/common/DatabaseEditor/store/cards.ts
components/common/DatabaseEditor/widgets/iconForPropertyType.tsx
components/common/DatabaseEditor/widgets/typeDisplayName.ts
lib/databases/board.ts
lib/databases/filterClause.ts
lib/databases/generateCsv.ts
lib/databases/proposalDbProperties.ts
lib/databases/proposalsSource/createSelectedPropertiesFromBoardProperties.ts
lib/databases/proposalsSource/filterBoardProperties.ts
lib/databases/proposalsSource/getBoardProperties.ts
lib/databases/proposalsSource/getCardPropertiesFromRubric.ts

Rubric reviewer score average proposal db property

---

.ebextensions_connect/07_http-to-https.config
.ebextensions_sunnyawards/07_http-to-https.config

so going to http:// redirects to https://

add https redirect for connect apps

---

apps/connect/components/projects/components/AddProjectMembersForm.tsx
apps/connect/components/projects/components/SearchFarcasterUser.tsx
apps/connect/components/projects/edit/EditProjectPage.tsx
apps/connect/lib/projects/form.ts
apps/sunnyawards/components/projects/components/AddProjectMembersForm.tsx
apps/sunnyawards/components/projects/components/SearchFarcasterUser.tsx
apps/sunnyawards/components/projects/edit/EditProjectPage.tsx
apps/sunnyawards/lib/projects/form.ts
lib/farcaster/getFarcasterUsers.ts

Fixed connect project edit issue

---

apps/sunnyawards/apiClient/apiClient.ts
apps/sunnyawards/app/api/aws/upload-token/route.ts
apps/sunnyawards/components/projects/components/ProjectImageField.tsx
apps/sunnyawards/hooks/useS3UploadInput.ts
lib/aws/uploadToS3Browser.ts

Fix image upload

---

components/common/DatabaseEditor/components/properties/UserAndRoleSelect.tsx
components/common/DatabaseEditor/components/propertyValueElement.tsx
lib/databases/generateCsv.ts

Fixed filtering properties correctly.
Bug was that if properties were filtered out from visible properties, they were ignored from the filter

Fix filtered properties

---

components/proposals/components/NewProposalButton.tsx

Handle edge case where no workflows exist

---

scripts/proposals/exportProposalTemplate.ts
scripts/proposals/restoreProposalFromSnapshot.ts

Add script for exporting and restoring template

---

components/proposals/components/NewProposalButton.tsx
pages/[domain]/proposals/new.tsx

Add protection for creating pages without a template if required

---

.github/actions/build/action.yml

fix cache key in github actions

---

.cdk/ProductionStack.ts
.cdk/StagingStack.ts
.github/workflows/deploy_staging.yml

testing wth a really long title https://github.com/charmverse/app.charmverse.io/pull/4312

Fix staging env for PRs with long names

---

lib/metrics/mixpanel/opEvents.ts
lib/rewards/closeOutReward.ts
lib/rewards/createReward.ts
lib/rewards/rollupRewardStatus.ts
lib/webhookPublisher/publishEvent.ts
pages/api/reward-applications/mark-paid.ts

Rewards and proposal status op events

---

components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/RubricEvaluationPropertiesList.tsx
components/common/DatabaseEditor/components/viewSidebar/viewSourceOptions/components/ProposalSourceProperties/TemplatePropertiesReadonlyList.tsx
lib/databases/proposalsSource/updateBoardProperties.ts

Remove archived proposal columns for proposal source board

---

components/common/form/FormField.tsx
components/common/form/hooks/formFieldSchema.ts

Op form field validation for proposal publish button

---

lib/metrics/mixpanel/opEvents.ts
pages/[domain]/proposals/index.tsx
pages/[domain]/rewards/index.tsx

Track proposals and rewards page view op events

---

@connect-shared/hooks/usePageView.ts
@connect-shared/lib/mixpanel/trackEventActionSchema.ts

fix casing of mixpanel properties

---

scripts/optimism/moveBackToLastEvaluation.ts

Added script to move back to last evaluation for proposal

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx

Dont depend on total reviews for approval

---

scripts/game7/export_game7.ts

add script to export data for game7

---

pages/api/google/code.ts

Fix tracking op google successful login event

---

components/common/SpaceAccessGate/SpaceAccessGate.tsx

[### WHAT
](https://discord.com/channels/894960387743698944/1266043391347527782/1266043391347527782)

hide summon token gate

---

components/common/form/FormFieldAnswers.tsx
components/proposals/hooks/useProposalFormAnswers.ts

Fixed proposal form field comments not working

---

__e2e__/po/formField.po.ts
__e2e__/proposals/proposalFinalStep.spec.ts
__e2e__/proposals/structuredProposalFormFieldComment.spec.ts
components/common/form/FormFieldAnswerComment.tsx

Added e2e test for proposal form field comment

---

lib/proposals/concealProposalSteps.ts

Fixed proposal hidden step results

---

scripts/exportData/restoreFromBackup2.ts

add another restoration script

---

components/common/CharmEditor/components/table/ui/createPopUp.tsx
theme/darkMode.ts

attempt to fix flashing of colors in table

---

lib/databases/proposalsSource/getCardProperties.ts

Fixed proposal publish date filter not working

---

.dockerignore
.github/workflows/test_and_deploy.yml
Dockerfile
scripts/migrations/2024_08_02_migrateProposalPublicPermissions.ts

Setup docker

---

.github/actions/build/action.yml
apps/connect/public/test.js

test swjs in staging

---

.github/workflows/test_and_deploy_connect.yml

uses a matrix to deploy all 3 apps using the same yml

simplify deployment yml for connect apps

---

.github/workflows/test_and_deploy_connect.yml
apps/connect/next.config.mjs
apps/sunnyawards/next.config.js

fix relations when deploying connect

---

components/settings/invites/components/InviteLinks/components/InviteLinksTable.tsx
components/settings/invites/components/PublicInvitesList.tsx

hide copy link in admin settings

---

__integration-tests__/server/pages/api/invites/index.spec.ts
lib/invites/__tests__/getSpaceInviteLinks.spec.ts
lib/invites/getSpaceInviteLinks.ts
pages/api/invites/index.ts

hide invite codes from frontend for non-admins

---

lib/proposals/createDraftProposal.ts
pages/[domain]/proposals/new.tsx

better handling when a template has no workflow

---

components/signing/hooks/useDocusign.tsx
pages/[domain]/proposals/new.tsx
pages/api/docusign/accounts.ts
pages/api/pages/[id]/threads.ts
pages/api/proposals/[id]/form/answers.ts

this makes our warning logs extremely noisy

dont throw an error when non-admin requests docusign templates

---

.github/actions/build_docker_image/action.yml
.github/workflows/deploy_staging.yml
.github/workflows/destroy_staging.yml
.github/workflows/test_and_deploy.yml
.github/workflows/test_and_deploy_connect.yml

use short length of github sha for docker imgtag

---

.github/workflows/test_and_deploy_connect.yml

Without debugging enabled (see Run Connect E2E tests):
https://github.com/charmverse/app.charmverse.io/actions/runs/10306910522/job/28531084135
With debugging:
https://github.com/charmverse/app.charmverse.io/pull/4391

enable logging e2e app in debug mode

---

lib/profile/getSummonProfile.ts
lib/summon/verifyMembership.ts

do not request from summon if we dont have a tenant api url

---

.github/workflows/test_and_deploy.yml
charmClient/apis/credentialsApi.ts
charmClient/hooks/charms.ts
charmClient/hooks/helpers.ts

fix requests with arrays in the payload

---

@connect-shared/lib/grants/getGrants.ts
apps/connect/app/grants/page.tsx
apps/connect/components/grants/GrantsList.tsx

Fixed connect grants pagination

---

apps/connect-api/src/api/session/login-with-farcaster.ts
apps/connect/Dockerfile

copy over files necessary for connect api

---

lib/credentials/__tests__/mapProjectToOptimism.spec.ts
lib/credentials/mapProjectToOptimism.ts

Fix the Gitcoin OP mapping

---

.ebstalk.apps.env/farcaster.env
apps/farcaster/components/product-updates/ProductUpdatesComposerAction.tsx

Fixed farcaster app embed url & baseUrl

---

apps/farcaster/app/api/product-updates/frames/[id]/route.ts
apps/farcaster/lib/productUpdates/getProductUpdatesFrame.ts

Fetch same project frames

---

components/common/ProjectForm/components/FieldAnswers.tsx
components/common/ProjectForm/components/Optimism/OptimismProjectForm.tsx
components/common/ProjectForm/components/ProjectField/FieldsEditor.tsx
components/common/form/fields/MultiTextInputField.tsx

fix saving inputs on proposal form

---

apps/farcaster/app/api/product-updates/frames/[id]/route.ts
apps/farcaster/lib/productUpdates/getProductUpdatesFrame.ts

Fixed frame button order and pages

---

components/common/CharmEditor/components/mention/mention.specs.ts
lib/prosemirror/markdown/__tests__/generateMarkdown.spec.ts
lib/prosemirror/markdown/generateMarkdown.ts

Fixed a bug with mention suggest marks

Fix markdown export

---

docker-compose.yml

Enable sunny awards logging

---

lib/prosemirror/markdown/generateMarkdown.ts

Remove serialiser override

---

components/common/DatabaseEditor/store/cards.ts
lib/proposals/createDefaultProposal.ts
lib/proposals/createProposal.ts

Fixed published at sort for proposals table and source board

---

@connect-shared/components/ProjectShareItem.tsx
@connect-shared/components/common/MultiTextInputField.tsx
apps/sunnyawards/__e2e__/createProject.spec.ts
apps/sunnyawards/app/layout.tsx
apps/sunnyawards/components/common/Footer.tsx
apps/sunnyawards/components/projects/components/SearchFarcasterUser.tsx
apps/sunnyawards/components/projects/components/ShareProjectToWarpcastButton.tsx
apps/sunnyawards/lib/projects/form.ts
apps/sunnyawards/theme/colors.ts
apps/sunnyawards/theme/index.d.ts
apps/sunnyawards/theme/theme.tsx

Improvements:
- website validation + helper text
- fix farcaster share
- farcaster default images
- sunny black bg

Sunny improvements

---

apps/sunnyawards/__e2e__/createProject.spec.ts
apps/sunnyawards/components/projects/components/AddProjectMembersForm.tsx
apps/sunnyawards/components/projects/components/ProjectForm.tsx
apps/sunnyawards/components/projects/components/SearchFarcasterUser.tsx
apps/sunnyawards/components/projects/new/CreateProjectPage.tsx
apps/sunnyawards/theme/theme.tsx

Reorganization:
- All fields in one place
- Form labels color: light gold

Sunnys - Create Project reorganization

---

components/_app/components/UserOnboardingDialog.tsx

Fix the onboarding dialog

---

scripts/optimism/exportMilestoneCompletionStatus.ts

Add script for exporting milestone completion status

---

.github/workflows/test_and_deploy_connect.yml
@connect-shared/lib/attestations/agoraApi.ts
@connect-shared/lib/attestations/storeProjectMetadataAndPublishOptimismAttestation.ts
apps/sunnyawards/components/projects/components/AddProjectMembersForm.tsx
apps/sunnyawards/components/projects/components/ProjectForm.tsx
apps/sunnyawards/components/projects/edit/EditProjectPage.tsx
apps/sunnyawards/components/projects/new/CreateProjectPage.tsx
pages/api/optimism/projects/index.ts

fix sunnyawards error

---

.ebstalk.apps.env/sunnyawards.env

Added domain env var for sunnyawards

---

apps/sunnyawards/components/welcome/ExtraDetails.tsx
apps/sunnyawards/lib/profile/form.ts

Two things:
- require user to enter an email when selecting 'send notifications' on welcome screen
- add link to Terms of Service

Fixes to Welcome onboarding form in Sunny

---

apps/sunnyawards/components/projects/components/ProjectForm.tsx
apps/sunnyawards/lib/projects/form.ts

add groups of categories for sunny awards

---

apps/sunnyawards/components/projects/components/ProjectForm.tsx
apps/sunnyawards/lib/projects/form.ts

Reverts charmverse/app.charmverse.io#4442

Revert "add groups of categories for sunny awards"

---

@connect-shared/lib/mixpanel/trackEventActionSchema.ts
apps/sunnyawards/components/projects/[id]/share/components/TwitterShareButton.tsx
scripts/migrations/2024_08_16_splitCategory.ts

add more mixpanel events to sunny

---

@connect-shared/lib/attestations/storeProjectMetadataAndPublishOptimismAttestation.ts
apps/sunnyawards/app/projects/new/page.tsx
apps/sunnyawards/components/projects/new/CreateProjectPage.tsx
apps/sunnyawards/components/projects/new/ImportOptimismProject.tsx
apps/sunnyawards/lib/projects/createProjectAction.ts
apps/sunnyawards/lib/projects/fetchUnimportedOptimismProjectsAction.ts
apps/sunnyawards/lib/projects/schema.ts
lib/credentials/__tests__/mapProjectToGitcoin.spec.ts
lib/credentials/mapProjectToOptimism.ts

Allows importing projects into the form

Add way to import OP projects

---

@connect-shared/components/common/MultiTextInputField.tsx
@connect-shared/lib/aws/uploadToken.ts
apps/connect/components/home/HomePage.tsx
apps/sunnyawards/components/common/WarpcastLogin/WarpcastLogin.tsx
apps/sunnyawards/components/projects/components/SearchFarcasterUser.tsx
apps/sunnyawards/lib/projects/schema.ts
components/common/form/SearchFarcasterUser.tsx

- allow searching farcaster w/2 characters, like "mo"
- remove duplicate website error
- fix filename logic when uploading to s3

Small last minute bug fixes for sunny awards forms

---

@connect-shared/components/ProjectShareItem.tsx
apps/sunnyawards/app/p/[path]/page.tsx

Fixes:
- twitter/facebook og image
- change text length to be on 2 rows + delete avatar

Fix og image

---

apps/sunnyawards/app/layout.tsx
apps/sunnyawards/app/manifest.ts
apps/sunnyawards/app/p/[path]/page.tsx
apps/sunnyawards/components/common/Header/Header.tsx
apps/sunnyawards/components/home/HomePage.tsx
apps/sunnyawards/components/profile/components/ProjectsList.tsx
apps/sunnyawards/components/projects/[id]/components/JoinTheSunnysBanner.tsx
apps/sunnyawards/components/projects/[id]/components/ProjectShareButton.tsx
apps/sunnyawards/components/projects/[id]/share/ShareProjectPage.tsx
apps/sunnyawards/components/projects/[id]/share/components/TwitterShareButton.tsx
apps/sunnyawards/components/projects/[id]/share/components/WarpcastShareButton.tsx
apps/sunnyawards/components/projects/components/ProjectForm.tsx
apps/sunnyawards/lib/mailer/sendProjectConfirmationEmail.ts
apps/sunnyawards/lib/mailer/templates/ProjectConfirmation.tsx

copy updates for Sunny Awards

---

apps/connect/Dockerfile

test sunny deploy

---

scripts/makeAllProposalsPublic.ts

Script for making all proposals public

---

@connect-shared/components/ProjectShareItem.tsx

fix word wrapping

---

apps/sunnyawards/components/home/HomePage.tsx
apps/sunnyawards/components/projects/[id]/share/ShareProjectPage.tsx
apps/sunnyawards/components/projects/components/ProjectForm.tsx
apps/sunnyawards/lib/projects/schema.ts

copy changes requested by OP for sunny awards

---

lib/farcaster/__tests__/ensureFarcasterUserExists.spec.ts

Don't delete test users

---

.ebstalk.apps.env/sunnyawards.env
scripts/fixProjectMembers.ts

Add script for project members

---

.github/actions/build/action.yml
.github/actions/build_app/action.yml
.github/actions/install/action.yml
.github/workflows/deploy_connect.yml
.github/workflows/deploy_farcaster.yml
.github/workflows/deploy_sunnyawards.yml
.github/workflows/destroy_staging.yml
.github/workflows/test_and_deploy.yml
.github/workflows/test_new_core_pkg.yml
apps/sunnyawards/components/projects/[id]/ProjectDetailsPage.tsx

fix cache key for app builds

---

lib/credentials/reputation/constants.ts
lib/credentials/reputation/issueUserIdentifier.ts
lib/credentials/reputation/storeCharmverseProjectMetadata.ts

Post all charmverse credentials to matching chains

Fix credentials chains

---

@connect-shared/lib/projects/getRecentProjectsWithMembers.ts
apps/sunnyawards/lib/projects/createProjectAction.ts
apps/sunnyawards/lib/projects/editProjectAction.ts
lib/farcaster/loginWithFarcaster.ts

- only show projects created from sunny awards
- more logging

some small fixes for sunny awards

---

apps/sunnyawards/lib/projects/schema.ts

Only validate contract string

---

components/common/ProjectForm/components/Optimism/OptimismProjectSelector.tsx
components/login/components/FarcasterModal.tsx
lib/farcaster/__tests__/connectWithFarcaster.spec.ts
lib/farcaster/__tests__/loginWithFarcaster.spec.ts
lib/farcaster/connectFarcaster.ts

Chris posted this bug while trying to add his farcaster to another account

Return an error when connecting to Farcaster if another user already connected

---

@connect-shared/lib/projects/createProject.ts
@connect-shared/lib/projects/editProject.ts
@connect-shared/lib/projects/findProject.ts
@connect-shared/lib/projects/projectSchema.ts
apps/sunnyawards/components/projects/components/ProjectForm.tsx
apps/sunnyawards/components/projects/edit/EditProjectPage.tsx
apps/sunnyawards/components/projects/new/CreateProjectPage.tsx
apps/sunnyawards/lib/mailer/templates/ProjectConfirmation.tsx
apps/sunnyawards/lib/projects/__tests__/createConnectProject.spec.ts
apps/sunnyawards/lib/projects/schema.ts
lib/credentials/__tests__/mapProjectToGitcoin.spec.ts
lib/farcaster/ensureFarcasterUserExists.ts
package.json

Add extra details for Sunnyawards category

---

@connect-shared/lib/projects/createProject.ts
@connect-shared/lib/projects/editProject.ts
@connect-shared/lib/projects/projectSchema.ts

fix type validation

---

apps/sunnyawards/lib/projects/schema.ts

make some fields optional on farcaster profiles

---

apps/sunnyawards/components/profile/ProfilePage.tsx
apps/sunnyawards/components/profile/[username]/ProfileDetailsPage.tsx

Change labels in profile page

---

.cdk/bin/app.ts
.github/workflows/deploy_farcaster.yml
.github/workflows/deploy_scoutgame.yml
.github/workflows/deploy_sunnyawards.yml

I first created a Certificate in AWS: https://us-east-1.console.aws.amazon.com/acm/home?region=us-east-1#/certificates/b901f27e-5a33-4dea-b4fb-39308a580423

update SSL for scout game

---

apps/sunnyawards/components/projects/new/CreateProjectPage.tsx

Add in typo edge case

---

.github/workflows/destroy_staging.yml

upgrade delete env action

---

lib/proposals/workflows/__tests__/syncProposalPermissionsWithWorkflowPermissions.spec.ts
lib/proposals/workflows/syncProposalPermissionsWithWorkflowPermissions.ts
scripts/addRubricEvaluationStep.ts

Script to add rubric evaluation

---

apps/sunnyawards/lib/projects/createProjectAction.ts
apps/sunnyawards/lib/projects/editProjectAction.ts

Pause CharmVerse attestations

---

.ebstalk.apps.env/sunnyawards.env
apps/sunnyawards/lib/projects/createProjectAction.ts
apps/sunnyawards/lib/projects/editProjectAction.ts
lib/blockchain/getCurrentGasPrice.ts
lib/blockchain/walletClient.ts
lib/credentials/attestOnchain.ts

Call EAS contract directly so we can control gas usage

Optimise EAS gas costs

---

components/settings/space/SpaceSettings.tsx

Requested by Chris on behalf of Eth Foundation

Allow 2-letter space domains

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/EvaluationStepSettings.tsx
components/proposals/ProposalsPage.tsx
components/proposals/components/UserProposalsTables/ActionableProposalsTable.tsx
components/proposals/components/UserProposalsTables/ProposalsTable.tsx
lib/proposals/__tests__/getUserProposals.spec.ts
lib/proposals/concealProposalSteps.ts
lib/proposals/getUserProposals.ts

1. Hide private evaluation details
2. Show a modal if a proposal is currently unviewable
3. Include appeal reviewers and approvers in actionable group

Fixed my work tab for proposals

---

components/[pageId]/DatabasePage/DatabasePage.tsx
components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
components/common/DatabaseEditor/components/__snapshots__/centerPanel.spec.tsx.snap
components/common/DatabaseEditor/components/centerPanel.spec.tsx
components/common/DatabaseEditor/components/centerPanel.tsx
components/common/DatabaseEditor/components/table/__snapshots__/table.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/tableRow.spec.tsx.snap
components/common/DatabaseEditor/components/table/table.spec.tsx
components/common/DatabaseEditor/components/table/table.tsx
components/common/DatabaseEditor/components/table/tableGroup.tsx
components/common/DatabaseEditor/components/table/tableRow.tsx
components/common/DatabaseEditor/components/table/tableRows.tsx
components/proposals/ProposalsPage.tsx
components/rewards/RewardsPage.tsx
pages/[domain]/index.tsx

[Card](https://app.charmverse.io/charmverse/cmd-click-right-click-open-new-tab-proposals-from-proposal-list-129493023591712)

Table row open button link

---

components/[pageId]/DatabasePage/DatabasePage.tsx
components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
components/common/DatabaseEditor/components/__snapshots__/centerPanel.spec.tsx.snap
components/common/DatabaseEditor/components/centerPanel.spec.tsx
components/common/DatabaseEditor/components/centerPanel.tsx
components/common/DatabaseEditor/components/table/__snapshots__/table.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/tableRow.spec.tsx.snap
components/common/DatabaseEditor/components/table/table.spec.tsx
components/common/DatabaseEditor/components/table/table.tsx
components/common/DatabaseEditor/components/table/tableGroup.tsx
components/common/DatabaseEditor/components/table/tableRow.tsx
components/common/DatabaseEditor/components/table/tableRows.tsx
components/proposals/ProposalsPage.tsx
components/rewards/RewardsPage.tsx
pages/[domain]/index.tsx

This reverts commit 6ad2062a3e4a20428e2106ef73019de51efe7f42.

Revert "Table row open button link (#4516)"

---

components/[pageId]/DatabasePage/DatabasePage.tsx
components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
components/common/DatabaseEditor/components/__snapshots__/centerPanel.spec.tsx.snap
components/common/DatabaseEditor/components/centerPanel.spec.tsx
components/common/DatabaseEditor/components/centerPanel.tsx
components/common/DatabaseEditor/components/table/__snapshots__/table.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/tableRow.spec.tsx.snap
components/common/DatabaseEditor/components/table/table.spec.tsx
components/common/DatabaseEditor/components/table/table.tsx
components/common/DatabaseEditor/components/table/tableGroup.tsx
components/common/DatabaseEditor/components/table/tableRow.tsx
components/common/DatabaseEditor/components/table/tableRows.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx
components/proposals/ProposalsPage.tsx
components/rewards/RewardsPage.tsx
pages/[domain]/index.tsx

Fixed issue for rewards table links

Table open button link

---

.eslintrc.json
@connect-shared/components/layout/AppProviders.tsx
esbuild.config.ts
packages/charmeditor/src/buildSchema.ts
packages/charmeditor/src/extensions/listItem/listItemPlugins.ts
tsconfig.json

fix main webapp build

---

pages/authenticate/index.tsx

[Card](https://app.charmverse.io/charmverse/user-receive-space-invite-sign-up-with-email-does-not-get-sent-to-space-6972231060051293)

Fix email login redirect to invite page

---

components/proposals/ProposalsPage.tsx
components/proposals/components/ProposalsReviewersTable/ProposalsReviewersTable.tsx
components/proposals/components/ProposalsReviewersTable/ReviewerProposalsTable.tsx
components/proposals/components/UserProposalsTables/ActionableProposalsTable.tsx
components/proposals/components/UserProposalsTables/ProposalsTable.tsx
components/proposals/components/UserProposalsTables/UserProposalsTables.tsx
lib/proposals/__tests__/getProposalsReviewers.spec.ts
lib/proposals/getProposalsReviewers.ts
lib/proposals/getUserProposals.ts
pages/api/spaces/[id]/proposals/reviewers/export.ts

Proposals table reviewers tab improvements

---

apps/sunnyawards/components/common/Modal/Modal.tsx

Fix modal padding

---

components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx
components/rewards/RewardsPage.tsx

[Card](https://app.charmverse.io/charmverse/allow-projects-to-update-their-milestones-directly-from-inside-of-their-passed-proposals-4112176299427426)

Show published proposal rewards in modal view

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/EvaluationStepSettings.tsx

[Card](https://app.charmverse.io/charmverse/make-appealers-editable-762672905477509)

Allow editing proposals reviewer appealers by admins

---

components/_app/components/UserOnboardingDialog.tsx
components/members/hooks/useRequiredMemberProperties.ts
components/settings/space/components/PrimaryMemberIdentity.tsx

[Card](https://app.charmverse.io/charmverse/add-farcaster-as-a-primary-identity-option-517228836023135)

Farcaster primary member identity option

---

.github/workflows/deploy_scoutgame.yml
.github/workflows/deploy_sunnyawards.yml
.github/workflows/deploy_waitlist.yml
.github/workflows/test_and_deploy.yml
docker-compose.yml

The eslint step was hanging in CI, i believe on created sw.js files. so this just make sure we only lint typescript files

do not eslint js files

---

.github/workflows/deploy_comingsoon.yml
.github/workflows/deploy_scoutgame.yml

test coming soon staging

---

components/common/DatabaseEditor/components/table/tableRow.scss
components/proposals/components/UserProposalsTables/ActionableProposalsTable.tsx
components/proposals/components/UserProposalsTables/ProposalsTable.tsx

clean up for My Work page

---

components/settings/roles/components/MemberActions.tsx

There are already conditions in place to prevent demoting or removing an admin when there is only one left in the space.
[Discussion](https://discord.com/channels/894960387743698944/1281598789299339294)

Fixed removing member from space

---

.github/workflows/deploy_ceramic.yml
.github/workflows/deploy_farcaster.yml
.github/workflows/deploy_webapp.yml
.github/workflows/deploy_websockets.yml
docker-compose.yml

Add AWS credentials to deploy and fix build cache key for webapp

---

apps/sunnyawards/__e2e__/createProject.spec.ts
apps/sunnyawards/__e2e__/viewProject.spec.ts
apps/sunnyawards/components/profile/ProfilePage.tsx
apps/sunnyawards/components/profile/components/ProjectsList.tsx
apps/sunnyawards/components/projects/[id]/ProjectDetailsPage.tsx
apps/sunnyawards/lib/projects/createProjectAction.ts
apps/sunnyawards/middleware.ts

Suspend Sunny awards submissions

---

.cdk/ProductionStack.ts
.cdk/StagingStack.ts
.cdk/bin/app.ts
.cdk/config.ts
.github/actions/build/action.yml
docker-compose.yml

Simplify config for cdk

---

apps/waitlist/components/frame/JoinWaitlistFrame.tsx
apps/waitlist/components/frame/LevelChangedFrame.tsx
apps/waitlist/components/frame/WaitlistCurrentScoreFrame.tsx
apps/waitlist/components/frame/WaitlistJoinedFrame.tsx
apps/waitlist/lib/frame/actionButtons.ts

Fix the frame titles

---

apps/waitlist/lib/scoring/__tests__/refreshUserScore.spec.ts
apps/waitlist/lib/scoring/refreshUserScore.ts

Account for github when calculating score

---

components/common/SpaceAccessGate/SpaceAccessGate.tsx
components/common/SpaceAccessGate/components/TokenGate/TokenGateContent.tsx

fix layout of multiple token gates

---

apps/scoutgamecron/src/__tests__/healthCheck.spec.ts
apps/scoutgamecron/src/worker.ts

bring back health check to cron

---

apps/scoutgame/lib/farcaster/config.ts
apps/waitlist/components/common/WarpcastLogin/WarpcastLogin.tsx

use correct domains for sign-in with farcaster

---

.github/workflows/destroy_staging.yml

use correct api token when  staging cleanup

---

apps/waitlist/app/api/frame/[fid]/actions/goto-builders/route.ts
apps/waitlist/app/api/frame/[fid]/actions/goto-score/route.ts
apps/waitlist/app/api/frame/[fid]/actions/share/route.ts
apps/waitlist/app/api/frame/[fid]/waitlist/route.ts
apps/waitlist/lib/mixpanel/trackEventActionSchema.ts
apps/waitlist/lib/mixpanel/trackWaitlistMixpanelEvent.ts
apps/waitlist/lib/session/loginAction.ts
apps/waitlist/lib/waitlistSlots/joinWaitlist.ts
apps/waitlist/lib/waitlistSlots/joinWaitlistAction.ts
lib/farcaster/messaging/getApprovedSigner.ts
lib/farcaster/messaging/writeToFarcaster.ts

Better analytics for join_waitlist

---

lib/farcaster/validateFrameInteraction.ts

Better error handling when frame validation fails

---

lib/middleware/onError.ts
scripts/optimism/retroPGF/v5/data.ts
scripts/optimism/retroPGF/v5/exportStatus.ts
scripts/optimism/retroPGF/v5/utils.ts
scripts/query.ts

Op exports

---

apps/scoutgame/next.config.mjs
apps/waitlist/next.config.js

update next to use CDN at runtime too

---

scripts/optimism/retroPGF/v5/importProjects.ts

fix query to check for farcaster users

---

apps/scoutgamecron/src/tasks/processPullRequests/__tests__/processClosedPullRequest.spec.ts

Removed reference to github client in sg cron test file

---

apps/scoutgame/lib/session/loginWithFarcasterAction.ts
apps/scoutgame/lib/session/requireWaitlistUser.ts

only users from the waitlist can sign in

---

scripts/exportData/exportDraftProposals.ts

save script to export draft proposals

---

apps/scoutgame/app/(general)/welcome/page.tsx
apps/scoutgame/app/api/connect-github/callback/route.ts
apps/scoutgame/app/profile/page.tsx
apps/scoutgame/app/welcome/how-it-works/page.tsx
apps/scoutgame/lib/users/saveOnboardedAction.ts
apps/scoutgame/lib/users/saveTermsOfServiceAction.ts
package.json

updates to scout user model

---

lib/proposals/updateProposalEvaluation.ts

dont update evaluation result when updating settings

---

apps/scoutgamecron/src/tasks/processPullRequests/__tests__/processMergedPullRequest.spec.ts
apps/scoutgamecron/src/tasks/processPullRequests/processMergedPullRequest.ts

fix broken test

---

components/common/CharmEditor/components/table/TableCellMenuPlugin.ts
components/common/CharmEditor/components/table/ui/createPopUp.tsx

Looks like it was removed on accident https://github.com/charmverse/app.charmverse.io/commit/ddf2327872c7d7424d9fc1cf26665ba2ca3426ca#diff-9fca7ac393d5102af5d696cdabe64ac4c2d19ba06a96cd4b63a30af692386920L109

fix pencil icon not appearing in table component

---

__e2e__/charmEditor/inlineComments.spec.ts
components/[pageId]/EditorPage/EditorPage.tsx
components/common/PageLayout/PageLayout.tsx
components/common/PageLayout/components/AnnouncementBanner.tsx
scripts/query.ts

add banner to join waitlist

---

apps/scoutgame/components/common/Header/components/HeaderMessage.tsx
apps/scoutgame/components/layout/AppProviders.tsx
apps/scoutgame/components/scout/components/SearchBuildersInput.tsx
apps/scoutgame/components/welcome/builder/BuilderWelcomePage.tsx

Removed async component inside use client

---

lib/proposals/getProposalsReviewers.ts

include appeal reviews for Reviewer Status table

---

apps/scoutgamecron/src/tasks/processPullRequests/getPullRequests.ts
apps/scoutgamecron/src/tasks/processPullRequests/processMergedPullRequest.ts

fix method to process pull requests

---

apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfile.tsx
apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardNftDisplay.tsx
apps/scoutgame/components/profile/components/BuilderProfile/BuilderProfile.tsx
apps/scoutgamecron/src/scripts/seeder/generateBuilder.ts
apps/scoutgamecron/src/scripts/seeder/generateNftPurchaseEvents.ts
apps/scoutgamecron/src/scripts/seeder/generateSeedData.ts

Show fallback image if no builder nft exist

---

.ebstalk.apps.env/scoutgame.env

Add scoutgame wallet env

---

apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCard.tsx
apps/scoutgame/components/common/Gallery/BuildersGallery.tsx
apps/scoutgame/components/nft/NFTPurchase.tsx
apps/scoutgame/components/scout/ScoutPage.tsx
apps/scoutgame/components/scout/components/ScoutPageBuildersGallery.tsx
apps/scoutgamecron/src/scripts/seeder/seedWithRealCharmverseGithubData.ts
apps/scoutgamecron/src/tasks/processPullRequests/index.ts
packages/scoutgame/src/__tests__/getBuildersLeaderboard.spec.ts

Dont error out nft purchase

---

apps/scoutgame/components/nft/NFTPurchase.tsx

Add comment

---

apps/scoutgame/components/common/Header/Header.tsx

Add info link to header

---

apps/scoutgame/lib/builderNFTs/mintNftAction.ts

fix nft mint points activity

---

packages/scoutgame/src/builderNfts/createBuilderNft.ts
packages/scoutgame/src/builderNfts/uploadArtwork.ts
packages/scoutgame/src/scripts/uploadNFTArtwork.ts

update s3 location for nft artwork

---

apps/scoutgame/lib/builders/__tests__/getSortedBuilders.spec.ts
packages/scoutgame/src/testing/database.ts

Flaky test fix: remove delete cleanup from scoutgame test

---

.github/actions/deploy_production/action.yml
.github/workflows/deploy_scoutgame.yml
apps/scoutgame/app/global-error.tsx
apps/scoutgame/components/common/WalletLogin/WalletLogin.tsx
apps/scoutgame/components/common/WarpcastLogin/WarpcastLogin.tsx
apps/scoutgame/components/nft/NFTPurchase.tsx
components/common/RouteGuard.tsx
pages/[domain]/[pageId].tsx
pages/[domain]/index.tsx

attempt to fix datadog browser logs

---

apps/scoutgame/components/common/NotificationRequest.tsx
apps/scoutgame/components/common/SiteNavigation.tsx

fix error in Safari

---

apps/scoutgame/components/common/Card/BuilderCard/BuilderCard.tsx
apps/scoutgame/components/common/ScoutButton/ScoutButton.tsx
apps/scoutgame/components/home/components/LeaderboardTable.tsx
apps/scoutgame/components/nft/NFTPurchase.tsx
apps/scoutgame/components/nft/NFTPurchaseDialog.tsx
apps/scoutgame/lib/builders/getLeaderboard.ts

Uses the modal popup from BuilderCard

fix scout buttons on home page

---

.cdk/ProductionStack.ts
.cdk/StagingStack.ts

Cursor AI was really sweet here - i asked it to set one policy and then it suggested a few more i hadn't yet known about

add rolling deploys to CDK

---

apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx
apps/scoutgame/components/[username]/components/PublicScoutProfile/PublicScoutProfileContainer.tsx
apps/scoutgame/components/profile/components/BuilderProfile/BuilderProfile.tsx
apps/scoutgame/components/profile/components/PointsClaimScreen/PointsClaimScreen.tsx
apps/scoutgame/components/profile/components/ScoutProfile/ScoutProfile.tsx

[Card](https://app.charmverse.io/charmverse/empty-state-copy-517742290974162)

Scoutgame empty state placeholder

---

apps/scoutgame/__e2e__/welcomePage.spec.ts
apps/scoutgame/app/(info)/welcome/spam-policy/page.tsx
apps/scoutgame/app/api/connect-github/callback/route.ts
apps/scoutgame/app/api/connect-github/get-link/route.ts
apps/scoutgame/components/common/JoinGithubButton.tsx
apps/scoutgame/components/welcome/builder/BuilderWelcomePage.tsx
apps/scoutgame/components/welcome/builder/components/SkipBuilderStepButton.tsx
apps/scoutgame/components/welcome/how-it-works/HowItWorksPage.tsx
apps/scoutgame/components/welcome/spam-policy/SpamPolicyPage.tsx
apps/waitlist/lib/scoring/constants.ts

Show spam policy page after github connect

---

apps/scoutgamecron/src/scripts/seeder/generateBuilder.ts
apps/scoutgamecron/src/scripts/seeder/generateGithubRepos.ts

made it so it can be run again without clearing your DB, and images work without changing the path

make seed script more robust

---

apps/scoutgamecron/cron.yml

Fix cron definition

---

apps/scoutgame/components/[username]/PublicProfileTabsMenu.tsx
apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx
apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderStats.tsx
apps/scoutgame/components/[username]/components/PublicScoutProfile/PublicScoutProfileContainer.tsx
apps/scoutgame/components/[username]/components/PublicScoutProfile/PublicScoutProfileStats.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCard.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardNftDisplay.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardStats.tsx
apps/scoutgame/components/common/Carousel/Carousel.tsx
apps/scoutgame/components/common/Gallery/BuildersGallery.tsx
apps/scoutgame/components/common/Gallery/ScoutsGallery.tsx
apps/scoutgame/components/common/Icons.tsx
apps/scoutgame/components/common/Profile/UserProfile.tsx
apps/scoutgame/components/common/Tabs/TabsMenu.tsx
apps/scoutgame/components/home/components/BuildersCarousel/BuildersCarousel.tsx
apps/scoutgame/components/home/components/BuildersCarousel/TodaysHotBuildersCarousel.tsx
apps/scoutgame/components/profile/components/BuilderProfile/BuilderActivitiesList.tsx
apps/scoutgame/components/profile/components/BuilderProfile/BuilderProfile.tsx
apps/scoutgame/components/profile/components/BuilderProfile/BuilderStats.tsx
apps/scoutgame/components/profile/components/ProfileStats.tsx
apps/scoutgame/components/profile/components/ScoutProfile/ScoutProfile.tsx
apps/scoutgame/components/scout/ScoutPage.tsx
apps/scoutgame/components/scout/components/BuildersGalleryContainer.tsx
apps/scoutgame/components/scout/components/ScoutPageBuildersGallery.tsx

Homepage, scout and profile page UI improvements

---

.ebstalk.apps.env/scoutgamecron.env
apps/scoutgamecron/src/tasks/processNftMints/index.ts
packages/onchain/src/waitForDecentTransactionSettlement.ts

add decent api key to cron

---

apps/scoutgamecron/src/tasks/processPullRequests/index.ts
package.json

gives us a way to stop reading from repos but retain past events
This relies on https://github.com/charmverse/core/pull/365

ignore deleted repos

---

apps/scoutgame/app/api/session/refresh/route.ts
apps/scoutgame/lib/farcaster/findOrCreateFarcasterUser.ts
apps/scoutgame/package.json
apps/scoutgamecron/package.json
apps/scoutgamecron/src/scripts/createBuilders.ts
apps/scoutgamecron/src/scripts/createScouts.ts
packages/farcaster/package.json
packages/farcaster/src/getFarcasterUserById.ts
packages/farcaster/src/getFarcasterUserByUsername.ts
packages/farcaster/src/interfaces.ts
packages/farcaster/tsconfig.json

Use neynar api to fetch farcaster profile on sg login

---

apps/scoutgame/components/[username]/PublicProfilePage.tsx
apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfile.tsx
apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx
apps/scoutgame/components/[username]/components/PublicScoutProfile/PublicScoutProfile.tsx
apps/scoutgame/components/[username]/components/PublicScoutProfile/PublicScoutProfileContainer.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardStats.tsx
apps/scoutgame/components/common/Tabs/TabsMenu.tsx
apps/scoutgame/components/home/components/HomePageTable/components/LeaderboardTable.tsx
apps/scoutgame/components/scout/components/BuildersGalleryContainer.tsx
apps/scoutgame/components/scout/components/ScoutPageBuildersGallery.tsx
apps/scoutgame/lib/builders/getLeaderboard.ts
apps/scoutgame/lib/builders/getSortedBuilders.ts
apps/scoutgame/lib/builders/getTodaysHotBuilders.ts
apps/scoutgame/lib/builders/interfaces.ts
apps/scoutgame/lib/scouts/getScoutedBuilders.ts

UI cleanup for scouts

---

apps/scoutgamecron/src/tasks/processPullRequests/__tests__/processMergedPullRequest.spec.ts
apps/scoutgamecron/src/tasks/processPullRequests/processMergedPullRequest.ts

Check that PRs were not created on the same day

---

apps/scoutgame/lib/builders/getTodaysHotBuilders.ts
apps/scoutgamecron/src/scripts/fixArtwork.ts
packages/scoutgame/src/builderNfts/generateNftImage.tsx

Fixed builder nft artwork

---

.env.test.local.example
apps/scoutgame/__e2e__/homePage.spec.ts
apps/scoutgame/__e2e__/po/HomePage.po.ts
apps/scoutgame/app/layout.tsx
apps/scoutgame/components/common/NFTPurchaseForm/NFTPurchaseDialog.tsx
apps/scoutgame/components/common/ScoutButton/ScoutButton.tsx
apps/scoutgame/components/common/Tabs/TabsMenu.tsx
apps/scoutgame/components/common/WalletLogin/WagmiProvider.tsx
apps/scoutgame/components/common/WalletLogin/wagmiConfig.ts
apps/scoutgame/components/home/components/HomePageTable/components/ActivityTable.tsx
apps/scoutgame/components/home/components/HomePageTable/components/LeaderboardTable.tsx
apps/scoutgame/components/home/components/HomePageTable/components/TopBuildersTable.tsx
apps/scoutgame/components/home/components/HomePageTable/components/TopScoutsTable.tsx
apps/scoutgame/components/layout/AppProviders.tsx

Add tests for home page + put wagmi at top of layout

---

apps/scoutgame/components/scout/components/ScoutPageBuildersGallery.tsx
apps/scoutgame/lib/builders/__tests__/getSortedBuilders.spec.ts
apps/scoutgame/lib/builders/getSortedBuilders.ts

show all builders on Scout page, and swap hot and top algo

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
apps/scoutgame/lib/builderNFTs/saveDecentTransactionAction.ts
packages/scoutgame/src/builderNfts/handlePendingTransaction.ts

Fix same chain transaction handling

---

packages/scoutgame/src/builderNfts/handlePendingTransaction.ts

Add handle pending tx

---

apps/scoutgame/components/[username]/PublicProfilePage.tsx
apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx
apps/scoutgame/components/[username]/components/PublicScoutProfile/PublicScoutProfileContainer.tsx

Removed back button

---

apps/scoutgamecron/src/tasks/processNftMints/index.ts

Prevent duplicate processing

---

.ebstalk.apps.env/scoutgame.env

Use scoutgame client id in env

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx

log errors from decent sdk

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
apps/scoutgame/components/home/components/HomePageTable/components/TopBuildersTable.tsx

Make scout point payment secondary and fix bug in leaderboard table

---

apps/scoutgame/app/api/connect-github/callback/route.ts

better logic when connecting github for existing users

---

apps/scoutgamecron/src/tasks/processNftMints/index.ts
packages/scoutgame/src/builderNfts/handlePendingTransaction.ts
packages/scoutgame/src/builderNfts/mintNFT.ts
packages/scoutgame/src/refreshUserStats.ts

Fix payment bugs

---

apps/scoutgame/app/(general)/u/[username]/page.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCard.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardNftDisplay.tsx
apps/scoutgame/components/common/NFTPurchaseDialog/components/NumberField.tsx
apps/scoutgame/components/home/components/BuildersCarousel/BuildersCarousel.tsx
apps/scoutgame/components/home/components/HomePageTable/components/TopBuildersTable.tsx
apps/scoutgame/hooks/useMediaScreens.ts
apps/scoutgame/lib/users/getUserByPath.ts
apps/scoutgame/theme/index.d.ts
apps/scoutgame/theme/theme.tsx

Fixes and improvements
- Add metadata for farcaster share
- add a new breakpoint for small phone screens and make cards smaller for those resolutions
- fix table username url sending to wrong url
- fix mui warning for a prop that does't exist in html

SG improvements

---

packages/farcaster/src/getFarcasterUserById.ts
packages/scoutgame/src/scripts/importRepos.ts
packages/scoutgame/src/scripts/importScouts.ts

add scripts to import scouts and repos into Scout Game

---

apps/scoutgame/components/[username]/components/PublicScoutProfile/PublicScoutProfileStats.tsx

Empty values for public scout stats

---

.cdk/ProductionStack.ts
.ebstalk.apps.env/scoutgamecron.env
apps/scoutgamecron/src/scripts/processPullRequests.ts
apps/scoutgamecron/src/tasks/processGemsPayout/index.ts
apps/scoutgamecron/src/tasks/processPullRequests/getPullRequests.ts
apps/scoutgamecron/src/tasks/processPullRequests/gqlClient.ts
apps/scoutgamecron/src/tasks/processPullRequests/index.ts
apps/scoutgamecron/src/worker.ts
packages/scoutgame/src/builderNfts/clients/builderContractAdminWriteClient.ts
packages/scoutgame/src/builderNfts/getScoutGameNftAdminWallet.ts
packages/scoutgame/src/builderNfts/mintNFT.ts
scripts/query.ts

- Add missing env var for minting NFTs
- Better logging in Pull requests and tracking time to run tasks
- Extend the timeout used by Beanstalk before the cron task gets retried.

Improvements to SG Cron

---

apps/scoutgame/lib/builders/getBuilderActivities.ts
apps/scoutgame/lib/builders/getTodaysHotBuilders.ts
apps/scoutgame/lib/scouts/getScoutStats.ts
apps/scoutgame/lib/scouts/getScoutedBuilders.ts
packages/scoutgame/src/builderNfts/mintNFT.ts

[Post](https://discord.com/channels/894960387743698944/1291101673443426396)

Fixed builder nfts sold stats

---

.github/workflows/deploy_ceramic.yml
.github/workflows/deploy_cron.yml
.github/workflows/deploy_farcaster.yml
.github/workflows/deploy_scoutgamecron.yml
.github/workflows/deploy_waitlist.yml
.github/workflows/deploy_websockets.yml
apps/scoutgamecron/src/scripts/seeder/generateGithubRepos.ts
apps/scoutgamecron/src/scripts/seeder/seedWithRealCharmverseGithubData.ts
apps/scoutgamecron/src/tasks/processPullRequests/__tests__/processMergedPullRequest.spec.ts
packages/scoutgame/src/testing/database.ts

fix typos for new github model

---

packages/scoutgame/src/bonus.ts
packages/scoutgame/src/scripts/importRepos.ts

update bonus list for celo

---

apps/scoutgame/components/home/components/BuildersCarousel/BuildersCarousel.tsx

Fixed home page crash with back button

---

apps/scoutgame/components/profile/components/BuilderProfile/BuilderActivitiesList.tsx
apps/scoutgame/lib/builders/getBuilderActivities.ts
apps/scoutgamecron/src/scripts/seeder/generateNftPurchaseEvents.ts

SG: Builder activity table links

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
packages/scoutgame/src/builderNfts/handlePendingTransaction.ts
packages/scoutgame/src/builderNfts/mintNFT.ts

When switching chains, the button would be disabled for a long time without any info while fetching decent tx. Added a loading state for this case

More informational buy button

---

apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfile.tsx
apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx
apps/scoutgame/components/home/HomePage.tsx
apps/scoutgame/components/home/components/HomePageTable/HomePageTable.tsx
apps/scoutgame/components/profile/components/BuilderProfile/BuilderProfile.tsx
apps/scoutgame/lib/builders/__tests__/getBuilderActivities.spec.ts
apps/scoutgame/lib/builders/getBuilderActivities.ts
apps/scoutgame/lib/builders/getLeaderboard.ts
apps/scoutgame/lib/builders/getTopBuilders.ts
apps/scoutgame/lib/scouts/getTopScouts.ts

We could add infinte scroll when necessary. For now i just limit to 200

show entire leaderboards and activity but scrollable

---

apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx
apps/scoutgame/components/home/HomePage.tsx
apps/scoutgame/components/profile/components/BuilderProfile/BuilderActivitiesList.tsx
apps/scoutgame/components/profile/components/BuilderProfile/BuilderProfile.tsx
apps/scoutgame/lib/builders/getBuilderActivities.ts

show commits in activity

---

apps/scoutgame/components/common/Header/components/HeaderMessage.tsx
packages/scoutgame/src/dates.ts

update current season

---

apps/scoutgame/components/common/Header/Header.tsx
apps/scoutgame/components/common/SiteNavigation.tsx

add info nav for Info pages

---

apps/scoutgame/components/notifications/components/NotificationRow.tsx
packages/scoutgame/src/notifications/getNotifications.ts
scripts/rewardBuilders.ts

add script to reward builders

---

apps/scoutgame/app/api/connect-github/callback/route.ts
apps/scoutgame/middleware.ts

fix oauth for github

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/ChainSelector/chains.ts
apps/scoutgame/components/common/NFTPurchaseDialog/components/ERC20Approve.tsx
apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
apps/scoutgame/components/common/NFTPurchaseDialog/hooks/useGetERC20Allowance.tsx
apps/scoutgame/components/common/NFTPurchaseDialog/hooks/useUpdateERC20Allowance.tsx
packages/scoutgame/src/builderNfts/usdcContractApiClient.ts

Erc20 purchase allowances

---

apps/scoutgame/scripts/onboardScouts.ts
scripts/optimism/metrics.ts

Add script for onboarding scouts

---

apps/scoutgame/lib/session/__tests__/authorizeUserByLaunchDate.spec.ts
apps/scoutgame/lib/session/authorizeUserByLaunchDate.ts
apps/scoutgame/scripts/query.ts
packages/scoutgame/src/waitlist/scoring/constants.ts

Fix waitlist login

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
apps/scoutgame/lib/builderNFTs/saveDecentTransactionAction.ts
packages/scoutgame/src/builderNfts/handlePendingTransaction.ts

Trying to figure out how a user purchased an NFT but it wasn't recorded in our system

add some more logging around NFT purchases

---

apps/scoutgame/components/welcome/builder/components/ExtraDetailsForm.tsx

add link to Terms of Service

---

apps/scoutgame/lib/builderNFTs/purchaseWithPointsAction.ts

reload profile after purchasing nft with points

---

apps/scoutgame/components/common/NFTPurchaseDialog/NFTPurchaseDialog.tsx
apps/scoutgame/components/common/ScoutButton/ScoutButton.tsx

reset modal state when closing rainbowkit modal

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
apps/scoutgamecron/src/scripts/seeder/generateBuilder.ts
apps/scoutgamecron/src/scripts/seeder/generateGithubRepos.ts
packages/scoutgame/src/bonus.ts

[Discussions](https://discord.com/channels/894960387743698944/1293012208720019588)
[Discussion](https://discord.com/channels/894960387743698944/1293006229505048660)

Fix: Scoutgame nft quantity selection issues

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/ProposalNotesLink.tsx

Hide reviewer notes proposal link

---

apps/scoutgamecron/src/scripts/createBuilder.ts
apps/scoutgamecron/src/scripts/createScouts.ts

add script to add a builder to the ecosystem

---

components/common/CharmEditor/components/callout/components/Callout.tsx

[Card](https://app.charmverse.io/charmverse/not-able-to-change-emoji-in-callout-box-26355508537533723)

Fixed callout emoji picker not getting triggered

---

components/proposals/components/UserProposalsTables/ActionableProposalsTable.tsx
components/proposals/components/UserProposalsTables/ProposalsTable.tsx

My work proposals view new tab link support

---

components/common/DatabaseEditor/components/properties/UserAndRoleSelect.tsx
components/common/UserDisplay.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx

Anonymize proposal review step reviewers in public view

---

apps/scoutgame/components/common/WarpcastLogin/FarcasterModal.tsx
apps/scoutgame/components/common/WarpcastLogin/WarpcastLoginButton.tsx

Slight Warpcast login ux improvement

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
apps/scoutgame/components/common/NFTPurchaseDialog/hooks/useDecentTransaction.tsx

Fix the payments

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/ERC20Approve.tsx
apps/scoutgame/components/common/NFTPurchaseDialog/hooks/useUpdateERC20Allowance.tsx
apps/scoutgame/components/common/WalletLogin/wagmiConfig.ts

Fix USDC on base and add chain switching

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/ChainSelector/chains.ts
apps/scoutgame/components/common/NFTPurchaseDialog/components/ERC20Approve.tsx

Avoids edge case where amount to pay moves slightly

Add 2% margin on ERC20 allowance

---

apps/scoutgame/components/common/Card/BuilderCard/BuilderCard.tsx
apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
apps/scoutgame/components/common/ScoutButton/ScoutButton.tsx
apps/scoutgame/lib/builderNFTs/purchaseWithPointsAction.ts
packages/scoutgame/src/builderNfts/__tests__/utils.spec.ts
packages/scoutgame/src/builderNfts/utils.ts

remove 50% discount for points and only display points

---

packages/scoutgame/src/bonus.ts

[Discussion](https://discord.com/channels/894960387743698944/1295192046319042601)

Removed cv repo from bonus partner

---

apps/scoutgame/components/notifications/components/NotificationRow.tsx
apps/scoutgame/components/profile/components/PointsClaimScreen/PointsClaimButton.tsx
apps/scoutgame/components/profile/components/PointsClaimScreen/PointsClaimScreen.tsx

[Discussion](https://discord.com/channels/894960387743698944/1295192046319042601)

Show correct bonus partner in claim screen

---

.github/workflows/deploy_cron.yml
.github/workflows/deploy_scoutgame.yml
.github/workflows/deploy_scoutgamecron.yml
.github/workflows/deploy_sunnyawards.yml
.github/workflows/deploy_waitlist.yml
.github/workflows/deploy_webapp.yml
.github/workflows/deploy_websockets.yml
apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
apps/scoutgame/components/info/InfoPage.tsx
apps/scoutgamecron/src/scripts/query.ts

remove USDC price from nft purchase form

---

components/proposals/components/UserProposalsTables/ActionableProposalsTable.tsx
components/proposals/components/UserProposalsTables/ProposalsTable.tsx

[Discussion](https://discord.com/channels/894960387743698944/1294265952724062268)

UI fix for my work tab proposal tables

---

apps/scoutgamecron/cron.yml
apps/scoutgamecron/src/scripts/query.ts
apps/scoutgamecron/src/tasks/processNftMints/index.ts
packages/scoutgame/src/builderNfts/handlePendingTransaction.ts

only process nft transactions from this season

---

.github/actions/build_app/action.yml

include commits inside of packages folder for build

---

apps/scoutgame/components/profile/components/ScoutProfile/ScoutProfile.tsx
apps/scoutgame/lib/builders/interfaces.ts
apps/scoutgame/lib/scouts/getScoutedBuilders.ts

we were showing total NFT sold by all builders on your scout profile

fix number of NFTS purchased by a scout on their own profile

---

packages/scoutgame/src/builderNfts/mintNFT.ts
packages/scoutgame/src/builderNfts/utils.ts

round down when doing point calculations

---

apps/scoutgame/components/info/PartnerRewards/CeloPage.tsx
packages/scoutgame/src/bonus.ts

update the repos for celo

---

apps/scoutgame/components/[username]/components/PublicScoutProfile/PublicScoutProfileContainer.tsx
apps/scoutgame/components/[username]/components/PublicScoutProfile/PublicScoutProfileStats.tsx
apps/scoutgame/components/common/Gallery/BuildersGallery.tsx
apps/scoutgame/lib/builders/interfaces.ts
apps/scoutgame/lib/scouts/getScoutedBuilders.ts

[Card](https://app.charmverse.io/charmverse/fix-nft-counts-for-scout-profile-29919213251814325)

Add nft count on scouted by user page

---

apps/scoutgamecron/src/scripts/issuePoints.ts
apps/scoutgamecron/src/scripts/refreshPointsFromTransactionHistory.ts
apps/scoutgamecron/src/scripts/syncUserNFTsFromOnchainData.ts
apps/scoutgamecron/src/tasks/processGemsPayout/processScoutPointsPayout.ts
packages/scoutgame/src/builderNfts/getOnchainPurchaseEvents.ts
packages/scoutgame/src/points/__tests__/getPointStatsFromHistory.spec.ts
packages/scoutgame/src/points/__tests__/sendPoints.spec.ts
packages/scoutgame/src/points/getPointStatsFromHistory.ts
packages/scoutgame/src/points/refreshPointStatsFromHistory.ts
packages/scoutgame/src/points/sendPoints.ts
packages/scoutgame/src/points/updatePointsEarned.ts
packages/scoutgame/src/testing/database.ts

Add script to reconstruct points from transactions

---

package.json

fix install of viem

---

apps/scoutgame/lib/session/loginWithFarcasterAction.ts

swap the logic for invite code

---

scripts/optimism/retroPGF/v6/data.ts
scripts/optimism/retroPGF/v6/exportStatus.ts
scripts/optimism/retroPGF/v6/getTemplate.ts
scripts/optimism/retroPGF/v6/importProjects.ts
scripts/optimism/retroPGF/v6/importReviewers.ts
scripts/optimism/retroPGF/v6/updateProjects.ts
scripts/optimism/retroPGF/v6/utils.ts

add script to import retro v6 for op

---

components/common/form/fields/TextInputField.tsx

Cast values to string

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/ERC20Approve.tsx

remove approved checkbox in nft purchase

---

components/common/form/fields/TextInputField.tsx
scripts/exportForMoxie.ts
scripts/exportPRs.ts
scripts/importForMoxie.ts

Reverts charmverse/app.charmverse.io#4826

Fix ts error and add error log

---

.ebstalk.apps.env/scoutgamecron.env
apps/scoutgamecron/cron.yml
apps/scoutgamecron/src/tasks/alertLowWalletGasBalance/getWalletGasBalanceInUSD.ts
apps/scoutgamecron/src/tasks/alertLowWalletGasBalance/index.ts
apps/scoutgamecron/src/worker.ts

Alert on discord for low sg wallet gas balance

---

apps/scoutgame/lib/farcaster/findOrCreateFarcasterUser.ts
apps/scoutgame/lib/users/findOrCreateUser.ts
apps/scoutgame/scripts/onboardScouts.ts
apps/scoutgamecron/src/scripts/createScouts.ts

There's now a common task card for this script https://work.charmverse.fyi/work.charmverse.fyi/common-tasks-8113500801358333?viewId=fbba6a17-ddc2-4d81-aa15-b893db51a09a&cardId=e6ef9a98-d6d4-41be-b1cc-84a27c10647f

update onboarding scout script

---

scripts/migrations/2024_10_17_fixScoutScores.ts

add migration for fixing scout points

---

tsconfig.json

fix types for migration file

---

__e2e__/database/databaseProposalsAsSource.spec.ts
components/common/DatabaseEditor/components/__snapshots__/centerPanel.spec.tsx.snap
components/common/DatabaseEditor/components/__snapshots__/viewTitle.spec.tsx.snap
components/common/DatabaseEditor/components/calculations/__snapshots__/calculation.spec.tsx.snap
components/common/DatabaseEditor/components/gallery/__snapshots__/gallery.spec.tsx.snap
components/common/DatabaseEditor/components/gallery/__snapshots__/galleryCard.spec.tsx.snap
components/common/DatabaseEditor/components/kanban/__snapshots__/kanban.spec.tsx.snap
components/common/DatabaseEditor/components/kanban/__snapshots__/kanbanColumnHeader.spec.tsx.snap
components/common/DatabaseEditor/components/kanban/calculation/__snapshots__/kanbanOption.spec.tsx.snap
components/common/DatabaseEditor/components/properties/link/__snapshots__/link.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/table.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/tableGroupHeaderRow.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/tableHeader.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/tableHeaders.spec.tsx.snap
components/common/DatabaseEditor/components/table/__snapshots__/tableRow.spec.tsx.snap
components/common/DatabaseEditor/components/table/calculation/__snapshots__/calculationRow.spec.tsx.snap
components/common/DatabaseEditor/components/viewHeader/__snapshots__/newCardButton.spec.tsx.snap
components/common/DatabaseEditor/components/viewHeader/__snapshots__/viewHeader.spec.tsx.snap
components/common/DatabaseEditor/components/viewHeader/__snapshots__/viewHeaderSearch.spec.tsx.snap
components/proposals/components/ProposalStatusSelect.tsx
lib/databases/proposalDbProperties.ts
lib/proposals/getProposalEvaluationStatus.ts
lib/proposals/interfaces.ts

[Card](https://app.charmverse.io/charmverse/change-the-display-of-unpublished-in-proposals-table-2744070048023979)

Renamed unpublished and not issued for credentials status in proposal source db

---

lib/users/__tests__/mergeProfiles.spec.ts
lib/users/mergeProfiles.ts
scripts/mergeProfiles.ts

added common task card here https://work.charmverse.fyi/work.charmverse.fyi/common-tasks-8113500801358333?viewId=fbba6a17-ddc2-4d81-aa15-b893db51a09a&cardId=2e4a013a-f173-43cb-b5d2-69d60bbd2f58

add script to merge users

---

apps/scoutgamecron/src/scripts/deleteBuilderAndRedistributePoints.ts
apps/scoutgamecron/src/scripts/deleteScoutAndRedistributePoints.ts
apps/scoutgamecron/src/tasks/processGemsPayout/processScoutPointsPayout.ts
packages/scoutgame/src/points/getPointStatsFromHistory.ts

[Discussion](https://discord.com/channels/894960387743698944/1296810966360784937)

Delete builder and redistribute scout points script

---

apps/scoutgameadmin/components/repos/AddRepoButton/AddRepoModal.tsx
apps/scoutgameadmin/components/repos/DeleteRepoButton/DeleteRepoButton.tsx
apps/scoutgameadmin/components/repos/ReposDashboard.tsx
apps/scoutgameadmin/lib/repos/deleteRepo.ts
apps/scoutgameadmin/lib/repos/deleteRepoAction.ts
apps/scoutgameadmin/lib/repos/getRepos.ts

add abilite to delete repo

---

apps/scoutgamecron/src/scripts/seeder/generateGithubRepos.ts
packages/scoutgame/src/points/getPointStatsFromHistory.ts

Fixed getPointStatsFromHistory script

---

README.md

I fixed some minor typos in order to ensure a better understanding.

fix spelling README.md

---

apps/scoutgamecron/src/tasks/processGemsPayout/__tests__/processGemPayout.spec.ts
apps/scoutgamecron/src/tasks/processGemsPayout/index.ts
apps/scoutgamecron/src/tasks/processGemsPayout/processScoutPointsPayout.ts
packages/scoutgame/src/dates.ts
packages/scoutgame/src/testing/database.ts

last week, the job got run at the first hour of --this week--, so it had no one to payout yet. we should just look at the last week, i figure, but check it hasn't run yet. this gives us a window of 3 hrs to do the payuot

make sure gems payout gets run on monday

---

apps/scoutgame/components/common/WarpcastLogin/WarpcastLoginButton.tsx
apps/scoutgame/lib/builders/setupBuilderProfile.ts

[Discussion](https://discord.com/channels/894960387743698944/1296880168219967521)

Fixed scoutgame builder invite link

---

.ebstalk.apps.env/scoutgamecron.env

fix api key for mailgun in sg cron

---

@connect-shared/lib/session/config.ts
apps/scoutgame/app/api/login-dev/route.ts
apps/scoutgame/app/api/session/refresh/route.ts
apps/scoutgame/components/login/LoginPage.tsx
lib/session/getIronOptions.ts

use LAX cookie

---

lib/users/mergeProfiles.ts

add sanity check that primary user was not deleted when merging profiels

---

apps/scoutgame/__e2e__/onboarding.spec.ts
apps/scoutgame/__e2e__/profilePage.spec.ts
apps/scoutgame/app/(info)/welcome/page.tsx
apps/scoutgame/components/layout/UserProvider.tsx
apps/scoutgame/components/welcome/builder/components/ExtraDetailsForm.tsx
apps/scoutgame/playwright.config.ts
packages/scoutgame/src/testing/database.ts

require user to agree to terms

---

apps/scoutgame/__e2e__/onboarding.spec.ts
apps/scoutgame/components/welcome/builder/components/ExtraDetailsForm.tsx
apps/scoutgame/lib/users/termsOfServiceSchema.ts
packages/scoutgame/src/testing/database.ts

Require email

---

apps/scoutgame/components/common/ClientGlobals.tsx
apps/scoutgame/components/common/WelcomeModal.tsx
apps/scoutgame/components/welcome/how-it-works/HowItWorksContent.tsx
packages/utils/src/browser.ts

i hid it in test mode for now to not cause an issue w/the e2e tests. ideally i'd like to find a way where it is disabled by default but can be enabled for an individual test

Show 'how it works' to anon users

---

apps/scoutgame/components/common/WelcomeModal.tsx
apps/scoutgame/components/welcome/how-it-works/HowItWorksContent.tsx

highlight points

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/EvaluationStepSettingsModal.tsx

allow admins to save evaluation steps even if invalid

---

scripts/optimism/retroPGF/v6/data.ts
scripts/optimism/retroPGF/v6/exportStatus.ts
scripts/optimism/retroPGF/v6/updateProjects.ts
scripts/optimism/retroPGF/v6/utils.ts

update op reviewers

---

.ebstalk.apps.env/scoutgame.env
apps/scoutgame/lib/session/loginWithFarcasterAction.ts

allow other invite codes

---

packages/utils/src/fetch.ts
packages/utils/src/http.ts

add default timeout to http calls

---

apps/scoutgame/components/claim/ClaimPage.tsx
apps/scoutgame/components/claim/components/BuilderRewardsScreen/BuilderRewardsScreen.tsx
apps/scoutgame/components/claim/components/BuilderRewardsScreen/BuilderRewardsTable.tsx
apps/scoutgame/components/claim/components/BuilderRewardsScreen/BuilderRewardsTableContainer.tsx
apps/scoutgame/components/claim/components/PointsTable/PointsReceiptRewardRow.tsx
apps/scoutgame/components/claim/components/PointsTable/PointsTable.tsx
apps/scoutgame/components/claim/components/common/DividerRow.tsx
apps/scoutgame/components/claim/components/common/LoadingTable.tsx
apps/scoutgame/components/claim/components/common/StyledTable.tsx
apps/scoutgame/lib/builders/getBuilderRewards.ts
apps/scoutgame/lib/points/getPointsReceiptsRewards.ts
packages/scoutgame/src/dates.ts

Improved sg claim page UI

---

apps/scoutgame/components/common/Card/ScoutCard.tsx

[Card](https://app.charmverse.io/charmverse/sg-scout-names-go-beyond-the-box-1599089796442068)

Shrink scout card username

---

apps/scoutgamecron/src/scripts/createBuilder.ts

fix create builder script

---

.github/actions/deploy_staging/action.yml
.github/workflows/deploy_scoutgame.yml
.github/workflows/deploy_scoutgameadmin.yml

update build id

---

apps/scoutgame/components/scout/components/ScoutPageBuildersGallery.tsx
apps/scoutgame/lib/builders/getSortedBuildersAction.ts
apps/scoutgame/lib/builders/getTodaysHotBuilders.ts

update the top builders list

---

.github/workflows/deploy_scoutgame.yml

Fix sourcemaps

---

apps/scoutgameadmin/components/common/SiteNavigation.tsx
apps/scoutgameadmin/components/contract/ContractDashboard.tsx
apps/scoutgameadmin/lib/contract/getContractData.ts
packages/scoutgame/src/builderNfts/clients/builderNFTSeasonOneClient.ts

Cleanup the admin dashboard

---

apps/scoutgamecron/src/scripts/welcomeWaitlistTier.ts
packages/scoutgame/src/waitlist/welcomeToScoutgame.ts

Common tier notifications

---

apps/scoutgame/components/home/components/HomePageTable/components/ActivityTable.tsx
apps/scoutgame/components/profile/components/BuilderProfile/BuilderActivitiesList.tsx

[Card](https://app.charmverse.io/charmverse/update-activity-tables-9682091262921573)

Updated builder activities list table

---

components/common/PageLayout/PageLayout.tsx

Extra banner for expired subs

---

apps/waitlist/middleware.ts

redirect users to scoutgame.xyz from waitlist

---

apps/scoutgameadmin/components/contract/ContractDashboard.tsx
apps/scoutgameadmin/lib/contract/aggregateNftSalesData.ts
apps/scoutgameadmin/lib/contract/getContractData.ts
apps/scoutgamecron/src/scripts/seeder/generateSeedData.ts
apps/scoutgamecron/src/tasks/processGemsPayout/__tests__/processScoutPointsPayout.spec.ts
apps/scoutgamecron/src/tasks/processGemsPayout/index.ts
apps/scoutgamecron/src/tasks/processGemsPayout/processScoutPointsPayout.ts
packages/onchain/src/generateWallet.ts
packages/scoutgame/src/__tests__/dates.spec.ts
packages/scoutgame/src/builderNfts/__tests__/getCurrentWeekPointsAllocation.spec.ts
packages/scoutgame/src/builderNfts/getCurrentWeekPointsAllocation.ts
packages/scoutgame/src/dates.ts
packages/scoutgame/src/points/__tests__/calculatePoints.spec.ts
packages/scoutgame/src/points/calculatePoints.ts
packages/scoutgame/src/points/getPointsCountForWeekWithNormalisation.ts

Add scoutgame data and use dynamic points allocation

---

apps/scoutgame/components/common/Card/BuilderCard/BuilderCard.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardActivity/BuilderCardActivity.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardActivity/BuilderCardActivityTooltip.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardNftDisplay.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardStats.tsx
apps/scoutgame/lib/builders/getSortedBuilders.ts
apps/scoutgame/lib/builders/getTodaysHotBuilders.ts
apps/scoutgame/lib/builders/interfaces.ts
apps/scoutgame/lib/scouts/getScoutedBuilders.ts
apps/scoutgamecron/cron.yml
apps/scoutgamecron/src/scripts/prefillBuilderCardActivities.ts
apps/scoutgamecron/src/scripts/seeder/generateBuilder.ts
apps/scoutgamecron/src/scripts/seeder/generateBuilderEvents.ts
apps/scoutgamecron/src/scripts/seeder/generateSeedData.ts
apps/scoutgamecron/src/tasks/updateBuilderCardActivity/index.ts
apps/scoutgamecron/src/tasks/updateBuilderCardActivity/updateBuilderCardActivity.ts
apps/scoutgamecron/src/worker.ts
package.json

[Card](https://app.charmverse.io/charmverse/add-activity-visualization-overlay-to-builder-cards-11147744852296482)

Builder gems 7 contribution viz on card

---

packages/scoutgame/src/builderNfts/refreshBuilderNftPrice.ts

Add price refresh logging

---

apps/scoutgamecron/src/tasks/processBuilderActivity/__tests__/recordMergedPullRequest.spec.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/github/getRecentPullRequestsByUser.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/recordMergedPullRequest.ts
packages/scoutgame/src/testing/database.ts

[Card](https://work.charmverse.fyi/change-gem-scoring-20398238397759738)
Users can get 100 points only for merges in new repos and:
- if they didn't merge a PR in the last 7 days in a new repo
- if they didn't merge a PR in their own repo
Changes to the points system

New points attribution for new prs in new repos

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
apps/scoutgame/components/common/NFTPurchaseDialog/hooks/useDecentTransaction.tsx

use more friendly message when error from Decent

---

apps/scoutgameadmin/lib/contract/aggregateNftSalesData.ts

Remove hardcoding in admin

---

apps/scoutgamecron/src/tasks/processBuilderActivity/__tests__/getBuilderActivity.spec.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/getBuilderActivity.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/processBuilderActivity.ts

dont save new repos automatically from users

---

packages/scoutgame/src/points/getPointStatsFromHistory.ts
scripts/migrations/2024_10_17_fixScoutScores.ts

Fixed broken type issues

---

apps/scoutgame/app/api/health/route.ts
apps/scoutgame/components/common/WarpcastLogin/WarpcastLoginButton.tsx
apps/scoutgame/lib/blockchain/findOrCreateWalletUser.ts
apps/scoutgame/lib/farcaster/findOrCreateFarcasterUser.ts
apps/scoutgame/lib/users/findOrCreateUser.ts
apps/scoutgame/scripts/onboardScouts.ts

add select to user query skip-tests

---

apps/scoutgame/__e2e__/loginPage.spec.ts
apps/scoutgame/__e2e__/onboarding.spec.ts
apps/scoutgame/components/common/Header/Header.tsx

fix flaky e2e for login/onboarding

---

packages/farcaster/src/getFollowers.ts
tsconfig.json

Add method to retrieve Farcaster followers

---

apps/scoutgame/lib/builders/__tests__/getSortedBuilders.spec.ts
apps/scoutgame/lib/builders/getSortedBuilders.ts

always show a users current week rank

---

components/common/PageLayout/PageLayout.tsx

[Card](https://app.charmverse.io/charmverse/show-scout-game-marketing-banner-on-charmverse-2774960321764366)

Added banner on cv spaces for scoutgame

---

apps/scoutgameadmin/lib/session/getAdminUser.ts

Add scoutgamexyz fid 828888 to allowed admin dashboard users

---

apps/scoutgame/components/common/Card/BuilderCard/BuilderCardActivity/BuilderCardActivity.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardName.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardNftDisplay.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardStats.tsx
apps/scoutgame/components/common/Card/ScoutCard.tsx
apps/scoutgame/components/common/Profile/EditableUserProfile.tsx
apps/scoutgame/components/common/Profile/ProfileLinks.tsx
apps/scoutgame/hooks/useDynamicFontSize.ts

Fixed scoutgame card UI on small screen

---

apps/scoutgame/components/common/Card/BuilderCard/BuilderCardNftDisplay.tsx
apps/scoutgame/components/common/Card/BuilderCard/BuilderCardStats.tsx
apps/scoutgame/components/common/Profile/UserProfile.tsx
scripts/migrations/2024_10_31_migrateFarcasterUsername.ts

[Discussion](https://discord.com/channels/894960387743698944/1302992122026262610)

Fixed warpcast username issue

---

.ebstalk.apps.env/scoutgameadmin.env
apps/scoutgameadmin/components/users/UserActionButton/AddBuilderModal.tsx
apps/scoutgameadmin/components/users/UserActionButton/UserActionButton.tsx
apps/scoutgameadmin/components/users/UsersDashboard.tsx
apps/scoutgameadmin/lib/actions/revlidatePathAction.ts
apps/scoutgameadmin/lib/users/updateUser.ts
apps/scoutgameadmin/lib/users/updateUserAction.ts

Fix minting NFTs + allow rejecting a builder

---

apps/scoutgame/lib/builders/__tests__/getSortedBuilders.spec.ts
apps/scoutgame/lib/builders/getSortedBuilders.ts
apps/scoutgamecron/src/scripts/processBuilderActivity.ts

Make sure we look at the correct season when retrieving builder stats + test

---

apps/scoutgame/components/info/partner-rewards/OptimismSupersimPage.tsx

changes to supersim copy

---

apps/scoutgame/components/profile/components/BuilderProfile/BuilderProfile.tsx
apps/scoutgamecron/src/tasks/processBuilderActivity/recordClosedPullRequest.ts
packages/scoutgame/src/constants.ts
scripts/query.ts

Standardize the Appeal url

---

apps/scoutgame/lib/builders/getLeaderboard.ts
apps/scoutgame/lib/scouts/getTopScouts.ts
apps/scoutgame/scripts/query.ts

this was useful for some work with chris, not used in prod right now

Add a method to get top scouts by week

---

apps/scoutgamecron/src/tasks/resolveBalanceIssues/__tests__/resolveBalanceIssues.spec.ts
apps/scoutgamecron/src/tasks/resolveBalanceIssues/resolveBalanceIssues.ts

Mark the sent points as claimed

---

apps/scoutgame/components/common/Carousel/Carousel.tsx
apps/scoutgame/lib/builders/__tests__/getTodaysHotBuilders.spec.ts
apps/scoutgame/lib/builders/getTodaysHotBuilders.ts

[Card](https://app.charmverse.io/charmverse/hot-builder-automated-scrolling-686778878621773)

Autoplay hot builder carousel and updated hot builders query

---

apps/scoutgame/__e2e__/homePage.spec.ts
apps/scoutgame/app/(general)/layout.tsx
apps/scoutgame/components/[path]/PublicProfilePage.tsx
apps/scoutgame/components/home/HomePage.tsx
apps/scoutgame/components/home/components/HomePageTable/components/ActivityTable.tsx
apps/scoutgame/components/home/components/HomePageTable/components/CommonTableRow.tsx
apps/scoutgame/components/home/components/HomePageTable/components/LeaderboardTable.tsx
apps/scoutgame/components/home/components/HomePageTable/components/TopBuildersTable.tsx
apps/scoutgame/components/home/components/HomePageTable/components/TopScoutsTable.tsx
apps/scoutgame/components/scout/ScoutPage.tsx

[Card](https://app.charmverse.io/charmverse/homepage-scrolling-45966922568953517)

Scoutgame home scrollbar and fixed tabs

---

apps/scoutgame/components/common/WalletLogin/WalletLogin.tsx
apps/scoutgame/lib/blockchain/schema.ts
apps/scoutgame/lib/session/loginWithWalletAction.ts

Added invite code for wallet login

---

apps/scoutgame/components/home/HomePage.tsx

Fixed sg homepage scrollbar issue

---

apps/scoutgame/components/home/HomePage.tsx

Fixed sg homepage e2e tests

---

apps/scoutgame/__e2e__/infoPage.spec.ts
apps/scoutgame/__e2e__/po/HomePage.po.ts
apps/scoutgame/components/common/ScoutButton/ScoutButton.tsx
apps/scoutgame/components/home/components/TodaysHotBuildersCarousel/BuildersCarousel.tsx
apps/scoutgame/components/home/components/TodaysHotBuildersCarousel/PromoCard.tsx
apps/scoutgame/components/layout/Template.tsx
apps/scoutgame/hooks/usePageView.ts
apps/scoutgame/hooks/useTrackEvent.ts
apps/scoutgame/lib/mixpanel/trackEventAction.ts
apps/scoutgame/lib/mixpanel/trackEventActionSchema.ts
packages/mixpanel/src/interfaces.ts
packages/mixpanel/src/trackUserAction.ts

Track frontend activity

---

.ebstalk.apps.env/scoutgameadmin.env
apps/scoutgameadmin/app/api/partners/talent/route.ts
apps/scoutgameadmin/components/repos/components/HeaderActions.tsx
apps/scoutgameadmin/package.json
packages/farcaster/src/getFarcasterUserById.ts
packages/utils/src/http.ts

you can test by running `npm run scoutgameadmin:remote` against prod

add export for Talent builders

---

__e2e__/proposals/appealProposal.spec.ts

allow retrying the appeal test more often

---

apps/scoutgame/components/home/components/TodaysHotBuildersCarousel/BuildersCarousel.tsx
apps/scoutgame/components/home/components/TodaysHotBuildersCarousel/PromoCard.tsx

-insert the 2nd promo as the 6th card and fix link on "Learn More"

Fix promo cards

---

.ebstalk.apps.env/scoutgame.env
.ebstalk.apps.env/scoutgameadmin.env
.ebstalk.apps.env/scoutgamecron.env

Fix env var typo for scout protocol wallets

---

packages/scoutgameattestations/src/attestGemReceipts.ts

Fix github URL typos

---

apps/scoutgamecron/src/worker.ts

Add a comment so cron is redeployed

---

apps/scoutgame/lib/users/getUserByPath.ts

make sure to grab nft artwork from the correct season

---

@connect-shared/hooks/useS3UploadInput.ts
@connect-shared/lib/attestations/storeProjectMetadataAndPublishToGitcoin.ts
@connect-shared/package.json
apps/farcaster/package.json
apps/sunnyawards/Dockerfile
apps/sunnyawards/next-env.d.ts
apps/sunnyawards/package.json
apps/sunnyawards/tsconfig.json
tsconfig.json

Try sunny again

---

apps/cron/tsconfig.json
apps/farcaster/tsconfig.json
apps/scoutgame/tsconfig.json
apps/scoutgameadmin/tsconfig.json
apps/scoutgamecron/tsconfig.json
apps/scoutgametelegram/tsconfig.json
apps/sunnyawards/tsconfig.json
apps/waitlist/tsconfig.json
apps/websockets/tsconfig.json
tsconfig.base.json

After a few minutes, the IDE does not recognise types anymore. 
This PR fixes that.

Fix monorepo types

---

apps/scoutgame/components/home/components/HomePageTable/HomePageTable.tsx
apps/scoutgame/components/home/components/HomePageTable/components/HomeTabsMenu.tsx
apps/scoutgame/components/home/components/HomePageTable/components/LeaderboardTable.tsx
apps/scoutgame/components/home/components/HomePageTable/components/NewScoutsTable.tsx
apps/scoutgame/lib/scouts/getNewScouts.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/recordCommit.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/recordMergedPullRequest.ts
packages/scoutgame/src/dates.ts

Add New scouts table to home page

---

apps/scoutgamecron/esbuild.config.ts
packages/scoutgame/src/builderNfts/artwork/generateNftImage.tsx

fix scoutgame production build

---

apps/scoutgamecron/package.json
apps/scoutgamecron/src/__tests__/cronyml.spec.ts

Ensure all urls have a task in the worker file.

Add cron.yml test

---

apps/scoutgame/components/common/NFTPurchaseDialog/components/ERC20Approve.tsx
apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx

Refresh nft price by polling

---

.github/actions/install/action.yml

retry npm ci

---

.github/workflows/destroy_staging.yml

add telegram to staging cleanup

---

packages/scoutgame-ui/src/actions/claimPointsAction.ts

Generate claim screen before claiming

---

.cdk/ProductionStack.ts
.cdk/StagingStack.ts

Bring back lower threshold to production envs for downscaling

---

apps/scoutgame/components/home/components/HomePageTable/components/HomeTabsMenu.tsx
apps/scoutgame/components/home/components/HomePageTable/components/NewScoutsTable.tsx
packages/scoutgame-ui/src/components/common/Tabs/TabsMenu.tsx

fix layout of new scouts builder gems column

---

packages/scoutgame-ui/src/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
packages/scoutgame-ui/src/components/common/NFTPurchaseDialog/hooks/useDecentTransaction.tsx

refresh decent price when chasing amount to pay

---

apps/scoutgamecron/src/tasks/processBuilderActivity/__tests__/processBuilderActivity.spec.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/__tests__/recordMergedPullRequest.spec.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/github/getRecentMergedPullRequestsByUser.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/recordMergedPullRequest.ts

only look at merged PRs for a users first contribution

---

.github/actions/build_docker_image/action.yml
apps/scoutgame/components/home/components/HomePageTable/components/TopScoutsTable.tsx
apps/scoutgameadmin/components/repos/components/AddRepoButton/AddRepoModal.tsx

fix sg admin deploy

---

apps/sunnyawards/__e2e__/createProject.spec.ts
apps/sunnyawards/__e2e__/viewProject.spec.ts
apps/sunnyawards/components/projects/[id]/components/ProjectDetails.tsx
apps/sunnyawards/components/projects/[id]/share/components/TwitterShareButton.tsx
apps/sunnyawards/lib/projects/schema.ts
components/common/CharmEditor/components/tweet/TweetNodeView.tsx
components/common/CharmEditor/components/tweet/tweetSpec.ts
components/common/ProjectForm/components/Optimism/OptimismProjectDisplay.tsx
components/common/WorkflowSidebar/components/SocialShareLinksStep/SocialShareLink.tsx
components/login/components/Footer.tsx
components/members/components/MemberDirectoryTableView.tsx
components/members/components/MemberProfile/components/ProfileWidgets/components/LensProfileWidget.tsx
components/members/components/__tests__/MemberDirectoryGalleryView.spec.tsx
components/members/hooks/__tests__/useRequiredMemberProperties.spec.ts
components/settings/profile/components/SocialInputs.tsx
lib/credentials/__tests__/mapProjectToGitcoin.spec.ts
lib/credentials/__tests__/mapProjectToOptimism.spec.ts
lib/mailer/emails/templates/components/Footer.tsx
lib/users/__tests__/createUser.spec.ts
lib/utils/__tests__/strings.spec.ts
packages/scoutgame-ui/src/components/claim/components/PointsClaimScreen/PointsClaimModal/PointsClaimSocialShare.tsx
scripts/migrations/2024_04_05_generateOpGrantsSpaces.ts
scripts/optimism/getProjects.ts
scripts/optimism/getRound3Projects.ts
testing/mocks/spaceMember.ts

User can't embed twitter URLs with the new domain. Bug: https://work.charmverse.fyi/work.charmverse.fyi/tech-task-list-49366552253645923?viewId=50d940bb-fdbd-40ba-9816-616d6138a663&cardId=611f37ec-deb1-40c4-a194-b2aaa859b44c

update URL for twitter

---

apps/scoutgame/app/(general)/claim/page.tsx
packages/scoutgame-ui/src/actions/claimPointsAction.ts
packages/scoutgame-ui/src/actions/revalidateClaimPointsAction.ts
packages/scoutgame-ui/src/components/claim/ClaimPage.tsx
packages/scoutgame-ui/src/components/claim/components/PointsClaimScreen/PointsClaimModal/PointsClaimSocialShare.tsx
packages/scoutgame-ui/src/components/claim/components/PointsClaimScreen/PointsClaimScreen.tsx

Fixed claim screen copy issue

---

apps/scoutgame/app/(general)/points-claim/[path]/page.tsx
packages/scoutgame-ui/src/components/claim/components/PointsClaimScreen/PointsClaimModal/PointsClaimSocialShare.tsx
packages/scoutgame-ui/src/components/claim/components/PointsClaimScreen/PointsClaimScreen.tsx

Fixed x claim screen preview card

---

apps/scoutgame/lib/scouts/getNewScouts.ts

Fix code for new scouts

---

apps/scoutgamecron/src/tasks/processBuilderActivity/__tests__/recordClosedPullRequest.spec.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/recordClosedPullRequest.ts

dont send message to builder on github

---

.github/actions/build_docker_image/action.yml

fix version of docker build

---

docker-compose.yml

run prisma migrations when scout game is deployed instead of webapp

---

.github/actions/build_docker_image/action.yml
.github/actions/deploy_production/action.yml

Statically set the Sha length in CI to avoid breakages from updates

---

.cdk/ProductionStack.ts

have a minimum of 2 apps running in prod

---

.github/workflows/deploy_scoutgameadmin.yml
apps/scoutgameadmin/app/api/github/delete-strike/route.ts
apps/scoutgameadmin/app/api/github/user-stats/route.ts
apps/scoutgameadmin/app/api/users/route.ts
apps/scoutgameadmin/components/users/UsersDashboard.tsx
apps/scoutgameadmin/components/users/components/UserActions/BuilderReviewModal.tsx
apps/scoutgameadmin/components/users/components/UserActions/UserActionButton.tsx
apps/scoutgameadmin/hooks/api/github.ts
apps/scoutgameadmin/hooks/api/users.ts
apps/scoutgameadmin/jest.config.ts
apps/scoutgameadmin/lib/users/__tests__/getUsers.spec.ts
apps/scoutgameadmin/lib/users/getUsers.ts
apps/scoutgameadmin/package.json
package.json
packages/scoutgame/src/testing/database.ts
packages/scoutgame/src/testing/jest.teardown.ts
packages/utils/src/strings.ts

Allow un-suspending builder from admin

---

.github/workflows/deploy_scoutgameadmin.yml

i dunno how this passed CI before

run db for tests in acout game admin

---

apps/scoutgameadmin/app/api/github/user-stats/route.ts
scripts/rejectBuilders.ts

add a script to reject builders

---

apps/scoutgamecron/src/tasks/processBuilderActivity/__tests__/recordCommit.spec.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/__tests__/recordMergedPullRequest.spec.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/index.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/processBuilderActivity.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/recordCommit.ts
apps/scoutgamecron/src/tasks/processBuilderActivity/recordMergedPullRequest.ts

Ensure that no matter when a script is run, the week/season for a PR is relative to the PR data.

set week based on github data in the cron job

---

.ebstalk.apps.env/scoutgame.env
.ebstalk.apps.env/scoutgametelegram.env
apps/scoutgame/components/layout/Template.tsx
apps/scoutgametelegram/app/api/session/telegram-user/route.ts
apps/scoutgametelegram/app/template.tsx
apps/scoutgametelegram/components/friends/components/Info.tsx
packages/mixpanel/src/interfaces.ts
packages/mixpanel/src/trackUserAction.ts
packages/mixpanel/src/utils.ts
packages/scoutgame-ui/src/hooks/usePageView.ts

Add a platform value to all events triggered by our apps.
Details:
- Take the platform from an env var
- env var is being verified agains our db to see if the value is valid. If the value is not valid we log it and return 'unknown'

SG Telegram tracking

---

apps/scoutgame/components/home/components/HomePageTable/components/ActivityTable.tsx
apps/scoutgame/components/home/components/HomePageTable/components/LeaderboardTable.tsx
apps/scoutgame/components/home/components/HomePageTable/components/TopBuildersTable.tsx

clean up table headers on home page

---

apps/scoutgame/components/welcome/builder/components/ExtraDetailsForm.tsx
apps/scoutgametelegram/app/(general)/info/layout.tsx
apps/scoutgametelegram/app/(general)/layout.tsx
apps/scoutgametelegram/components/common/Header.tsx
apps/scoutgametelegram/components/friends/components/InviteButtons.tsx
apps/scoutgametelegram/components/scout/ScoutPageTable/components/TopBuildersTable.tsx
apps/scoutgametelegram/components/scout/ScoutPageTable/components/TopScoutsTable.tsx
apps/scoutgametelegram/lib/quests/getQuests.tsx
apps/scoutgametelegram/lib/scouts/getTopScouts.ts
packages/scoutgame-ui/src/components/[path]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx
packages/scoutgame-ui/src/components/[path]/components/PublicScoutProfile/PublicScoutProfileContainer.tsx
packages/scoutgame-ui/src/components/claim/components/BuilderRewardsScreen/BuilderRewardsScreen.tsx
packages/scoutgame-ui/src/components/common/Profile/EditableUserProfile/EditableBio.tsx
packages/scoutgame-ui/src/components/profile/components/BuilderProfile/BuilderProfile.tsx
packages/scoutgame-ui/src/components/profile/components/ScoutProfile/ScoutProfile.tsx
packages/scoutgame-ui/src/components/profile/components/UserProfileForm.tsx
packages/scoutgame-ui/src/theme/colors.ts

Scoutgame telegram polish

---

.ebstalk.apps.env/scoutgamecron.env
packages/scoutgame/src/builderNfts/__tests__/recordNftMint.spec.ts
packages/scoutgame/src/builderNfts/getOnchainPurchaseEvents.ts
scripts/migrations/2024_11_21_saveWallets.ts

Migration script to grab all user wallets

---

apps/scoutgame/app/(general)/points-claim/[path]/page.tsx
packages/mixpanel/src/utils.ts
packages/scoutgame-ui/src/actions/claimPointsAction.ts
packages/scoutgame-ui/src/actions/createUserClaimScreen.tsx
packages/scoutgame-ui/src/components/claim/components/PointsClaimScreen/PointsClaimModal/PointsClaimSocialShare.tsx
packages/scoutgame-ui/src/components/claim/components/PointsClaimScreen/PointsClaimScreen.tsx
packages/scoutgame/src/points/getClaimablePointsWithSources.ts

pass in the week to show for claims image

---

packages/scoutgame/src/users/findOrCreateFarcasterUser.ts

[Discussion](https://discord.com/channels/894960387743698944/1310966586458509394)

Generate path from farcaster username

---

scripts/getCharmVerseBuilders.ts

write a script to retrieve github from charmverse data

---

apps/scoutgametelegram/components/common/SiteNavigation.tsx
apps/scoutgametelegram/components/layout/StickyFooter.tsx
packages/scoutgame/src/session/getIronOptions.ts

This requires v 8 of the Bot API and i dont know how to enable it..
https://core.telegram.org/bots/webapps#recent-changes

Mobile footer

---

__e2e__/proposals/freeFormProposalTemplate.spec.ts
__e2e__/proposals/proposalEvaluations.spec.ts
__e2e__/proposals/voteOnProposal.spec.ts
components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/components/RubricAnswersForm.tsx
lib/proposals/__tests__/concealProposalSteps.spec.ts
lib/proposals/__tests__/mapDbProposalToProposal.spec.ts
lib/proposals/getProposal.ts
lib/proposals/interfaces.ts
lib/proposals/mapDbProposalToProposal.ts
lib/proposals/rubric/interfaces.ts
lib/templates/__tests__/importWorkspacePages.spec.ts
stories/ProposalsPage/Proposals.stories.tsx
stories/ProposalsPage/components/ProposalsPageStory.tsx
testing/mocks/proposal.ts

Fix proposals build

---

apps/scoutgame/components/home/LandingPage.tsx
packages/scoutgame-ui/src/components/claim/components/PointsClaimScreen/PointsClaimModal/PointsClaimSocialShare.tsx
packages/scoutgame-ui/src/components/common/Profile/EditableUserProfile/EditableName.tsx
packages/scoutgame-ui/src/components/common/Profile/EditableUserProfile/EditableUserProfile.tsx
packages/scoutgame-ui/src/components/common/Profile/ProfileLinks.tsx
packages/scoutgame-ui/src/components/common/Profile/ShareProfile.tsx
packages/scoutgame-ui/src/components/common/Profile/UserProfile.tsx

[Card](https://app.charmverse.io/cvt-scout-game/add-share-button-to-profile-page-16241046574251028)

Add Share button to profile page

---

packages/scoutgame-ui/src/providers/AppProviders.tsx
packages/scoutgame-ui/src/providers/LinkInterceptor.tsx

[Card](https://app.charmverse.io/cvt-scout-game/better-handling-of-external-links-in-telegram-23519699011459738)

Intercept external link click and navigate using tg api

---

package.json

update serwist/next lib for security purpos

---

apps/scoutgame/components/welcome/builder/components/ExtraDetailsForm.tsx
packages/scoutgame-ui/src/components/common/Profile/EditableUserProfile/EditableName.tsx
packages/scoutgame-ui/src/components/common/Profile/EditableUserProfile/EditableUserProfile.tsx
packages/scoutgame-ui/src/components/common/Profile/ShareProfile.tsx

Hide share profile icon onboarding and fixed origin url for share

---

apps/scoutgame/components/welcome/how-it-works/HowItWorksContent.tsx
apps/sunnyawards/components/projects/components/BlockchainSelect.tsx
packages/scoutgame-ui/src/components/common/NFTPurchaseDialog/components/ChainSelector/chains.ts

Fixed op logo url

---

apps/scoutgametelegram/app/(general)/scout/page.tsx
apps/scoutgametelegram/components/scout/ScoutPage.tsx

[Discussion](https://discord.com/channels/894960387743698944/1313518530104262718)
[Discussion](https://discord.com/channels/894960387743698944/1313520091664617503)

Fixed telegram layout

---

apps/scoutgametelegram/components/friends/components/InviteButtons.tsx
packages/mixpanel/src/interfaces.ts

scoutgametelegram updates:
- copy button tracking
- invite button tracking

Referral tracking update

---

apps/scoutgame/components/scout/ScoutPage.tsx

Footer was fixed yesterday but today seems it has a problem just on Scout page.

Fix sg footer for scout page

---

apps/scoutgame/__e2e__/claimPoints.spec.ts
apps/scoutgame/__e2e__/po/ClaimPage.po.ts
apps/scoutgame/__e2e__/test.ts
packages/scoutgame-ui/src/components/claim/components/PointsClaimScreen/PointsClaimModal/PointsClaimScoutScreen.tsx
packages/scoutgame-ui/src/components/claim/components/PointsClaimScreen/PointsClaimScreen.tsx

hide points claim share in some cases

---

scripts/getCharmVerseBuilders.ts

updates to exporting cv builders

---

scripts/sendTelegramPost.ts

Add script to send messages in telegram

---

packages/scoutgame-ui/src/providers/WagmiProvider.tsx

only deep link to metamask inside of webapp

---

.ebstalk.apps.env/scoutgame.env
.ebstalk.apps.env/scoutgametelegram.env
packages/mixpanel/src/utils.ts

fix platform to work on the client

---

packages/scoutgame/src/builders/approveBuilder.ts

dont import repos for new builders automatically

---

.github/actions/install/action.yml
.github/workflows/deploy_ceramic.yml
.github/workflows/deploy_cron.yml
.github/workflows/deploy_farcaster.yml
.github/workflows/deploy_scoutgame.yml
.github/workflows/deploy_scoutgamecron.yml
.github/workflows/deploy_scoutgametelegram.yml
.github/workflows/deploy_sunnyawards.yml
.github/workflows/deploy_webapp.yml
.github/workflows/deploy_websockets.yml
.github/workflows/test_new_core_pkg.yml

this pr also removes some old code for deploying new versions of core. that is all handled upstream now

typecheck more apps with core updates

---

apps/scoutgamecron/src/scripts/createBuilder.ts
apps/scoutgamecron/src/scripts/createBuilders.ts
apps/scoutgamecron/src/scripts/createScouts.ts
apps/scoutgamecron/src/scripts/seeder/seedWithRealCharmverseGithubData.ts

fix types for sg cron

---

apps/scoutgame/lib/builders/getLeaderboard.ts
apps/scoutgame/lib/builders/getPaginatedBuilders.ts
packages/scoutgame-ui/src/components/[path]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx
packages/scoutgame-ui/src/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx
packages/scoutgame-ui/src/components/common/NFTPurchaseDialog/components/SuccessView.tsx
packages/scoutgame/src/builders/getTodaysHotBuilders.ts
packages/scoutgame/src/builders/interfaces.ts
packages/scoutgame/src/scouts/getScoutedBuilders.ts
packages/scoutgame/src/social/getBuildersByFid.ts

[Card](https://app.charmverse.io/cvt-scout-game/share-after-buy-nft-2726174411611346)

Fixed share nft purchase screen

---

apps/scoutgame/components/scout/ScoutPage.tsx

Re enable starter pack

---

packages/scoutgame/src/builders/getTodaysHotBuilders.ts

Only display default builder nfts in hot builders

---

packages/scoutgame-ui/src/components/info/partner-rewards/CeloPage.tsx
packages/scoutgame-ui/src/components/info/partner-rewards/OptimismPage.tsx
packages/scoutgame-ui/src/components/info/partner-rewards/OptimismSupersimPage.tsx

update celo page

---

packages/scoutgame/src/builders/getBuilders.ts

remove starter pack nfts from builder search

---

packages/scoutgame/src/users/findOrCreateTelegramUser.ts
packages/scoutgame/src/users/findOrCreateWalletUser.ts

[Discussion](https://discord.com/channels/894960387743698944/1314651020915118120)

Fixed telegram login issue

---

packages/scoutgame-ui/src/components/common/Card/BuilderCard/BuilderCard.tsx
packages/scoutgame-ui/src/components/common/Gallery/BuildersGallery.tsx
packages/scoutgame-ui/src/components/common/ScoutButton/ScoutButton.tsx
packages/scoutgame-ui/src/components/profile/components/ScoutProfile/ScoutProfile.tsx
packages/scoutgame/src/scouts/getScoutedBuilders.ts

Hide the starter points amount when displayed on public profile

---

packages/mixpanel/src/interfaces.ts
packages/scoutgame/src/builderNfts/__tests__/recordNftMint.spec.ts
packages/scoutgame/src/builderNfts/recordNftMint.ts

add nft type to mixpanel events

---

packages/scoutgame-ui/src/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx

hide quantity for starter packs

---

apps/ceramic/esbuild.config.ts
apps/cron/esbuild.config.ts
apps/websockets/esbuild.config.ts
components/common/form/InputGeneratorText.tsx
pages/api/v1/webhooks/stripe/index.ts

chore: fix some comments

---

.ebstalk.apps.env/webapp.env

disable RUM for datadog

---

lib/google/loginWithMagicLink.ts
lib/projects/getProjectMemberCreateTransaction.ts
package.json

remove core dependency on nanoid

---

serverless.yml

v 4.5.3 seems to have broken our deploy

test serverless

---

lib/mailer/emails/emails.ts
lib/mailer/emails/templates/PlainTemplate.tsx
lib/mailer/mailer.ts
scripts/query.ts
scripts/sendPlainEmail.ts

add a way to send a plain email from script

---

lib/rewards/blocks/views.ts

Add due date to milestone table

---

lib/notifications/documents/createDocumentNotifications.ts

We want to send notifications only to reviewers from the current step of the proposal

Send notifications only to step reviewers

---

components/common/comments/Comment.tsx

Change reply button to blue

---

components/proposals/ProposalsPage.tsx

[Card](https://app.charmverse.io/scout-game/my-comments-in-my-work-section-4499120139800532)

My comments tab in proposal work

---

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/components/RubricAnswersForm.tsx

fix cached rubric answers

---

.github/workflows/deploy_webapp.yml

remove old websocket beanstalk service

---

scripts/syncWorkflowPermissions.ts

add script to sync workflow permissions

---

lib/metrics/postToDiscord.ts

stop sending events to discord

---

components/common/PageLayout/PageLayout.tsx

Dev token banner

---

lib/members/getMemberUsername.ts
lib/members/getSpaceMembers.ts
lib/telegram/interfaces.ts

fix lookup of telegram user name

---

components/common/PageLayout/PageLayout.tsx

update banner for scout game

---

apps/cron/src/tasks/chargeSpacesSubscription/task.ts
apps/webapp/components/settings/subscription/CreateSubscriptionInformation.tsx
apps/webapp/lib/spaces/createSpace.ts
apps/webapp/scripts/upgradeSpacesToGoldTier.ts
package.json
packages/lib/src/subscription/chargeSpaceSubscription.ts
packages/subscriptions/src/calculateSubscriptionCost.ts
packages/subscriptions/src/constants.ts
packages/subscriptions/src/getSubscriptionReceipts.ts

auto upgrade new spaces created to gold tier

---

apps/webapp/charmClient/hooks/subscriptions.ts
apps/webapp/components/settings/subscription/SubscriptionSettings.tsx
apps/webapp/components/settings/subscription/components/SendDevToSpaceForm.tsx
apps/webapp/components/settings/subscription/components/SpaceSubscriptionEvents.tsx
apps/webapp/components/settings/subscription/components/SubscriptionHeader.tsx
apps/webapp/components/settings/subscription/components/SubscriptionTiers.tsx
apps/webapp/components/settings/subscription/components/modals/DowngradeSubscriptionModal.tsx
apps/webapp/components/settings/subscription/components/modals/UpgradeSubscriptionModal.tsx
apps/webapp/components/settings/subscription/hooks/useDevTokenBalance.ts
apps/webapp/pages/api/spaces/[id]/subscriptions/status.ts
packages/lib/src/subscription/constants.ts
packages/subscriptions/src/constants.ts
packages/subscriptions/src/getExpiresAt.ts
packages/subscriptions/src/getSubscriptionStatus.ts

Warning banner when your plan will expire

---

apps/webapp/pages/api/spaces/[id]/subscriptions/cancel.ts
apps/webapp/pages/api/spaces/[id]/subscriptions/contribution.ts
apps/webapp/pages/api/spaces/[id]/subscriptions/downgrade.ts
apps/webapp/pages/api/spaces/[id]/subscriptions/reactivate.ts
apps/webapp/pages/api/spaces/[id]/subscriptions/upgrade.ts

add logs for changes to subscription

---

apps/webapp/components/common/PageLayout/PageLayout.tsx

new pricing model space banner

---

apps/webapp/scripts/sendPricingUpdatesEmail.ts
packages/lib/src/mailer/emails/emails.ts
packages/lib/src/mailer/emails/templates/PricingChangeTemplate.tsx
packages/lib/src/mailer/emails/templates/components/Button.tsx
packages/lib/src/mailer/emails/templates/components/Feedback.tsx
packages/lib/src/mailer/emails/templates/components/Footer.tsx
packages/lib/src/mailer/emails/templates/components/Header.tsx
packages/lib/src/mailer/emails/templates/components/Link.tsx
packages/lib/src/mailer/emails/templates/components/Text.tsx

Send pricing change email

---

packages/subscriptions/src/chargeSpaceSubscription.ts

apply payment discount for spaces

---

apps/webapp/components/common/PageLayout/components/BlocksExceededBanner.tsx

fix banner when space is readonly

---

packages/lib/src/permissions/spaces/saveRoleAndSpacePermissions.ts
packages/lib/src/proposals/createProposal.ts
packages/lib/src/rewards/createReward.ts

we were including 'assignedSubmitters' in rewards, which are userIds not roleIds. i made the logic more foolproof

fix check for archived roles

---

apps/webapp/charmClient/apis/tokenGateApi.ts
apps/webapp/charmClient/charmClient.ts
apps/webapp/charmClient/hooks/tokenGates.ts
apps/webapp/components/settings/invites/components/TokenGates/components/TokenGatesTableRow.tsx
apps/webapp/components/settings/proposals/SpaceProposalSettings.tsx
apps/webapp/components/settings/proposals/components/ProposalWorkflow.tsx
apps/webapp/components/settings/roles/components/RoleRow.tsx
apps/webapp/components/settings/subscription/SubscriptionSettings.tsx
apps/webapp/components/settings/subscription/components/ArchivedFeatures.tsx
apps/webapp/hooks/useTokenGateAccess.ts
apps/webapp/hooks/useWorkflowAccess.ts
apps/webapp/lib/spaces/createSpace.ts
apps/webapp/pages/api/roles/[id]/unarchive.ts
apps/webapp/pages/api/token-gates/[id]/unarchive.ts
apps/webapp/pages/api/token-gates/index.ts
packages/lib/src/proposals/workflows/__tests__/unarchiveWorkflowTemplate.spec.ts
packages/lib/src/proposals/workflows/unarchiveWorkflowTemplate.ts
packages/lib/src/roles/__tests__/unarchiveRole.spec.ts
packages/lib/src/roles/unarchiveRole.ts
packages/lib/src/token-gates/__tests__/unarchiveTokenGate.spec.ts
packages/lib/src/tokenGates/__tests__/unarchiveTokenGate.spec.ts
packages/lib/src/tokenGates/unarchiveTokenGate.ts
packages/subscriptions/src/featureRestrictions.ts
packages/testing/src/setupDatabase.ts

space features list

---

apps/webapp/charmClient/hooks/admin.ts
apps/webapp/components/admin/components/AdminSpacesTable.tsx
apps/webapp/pages/api/admin/spaces.ts
apps/webapp/pages/api/admin/token-balance.ts

allow editing space price

---

apps/webapp/lib/admin/users.ts

updated admin users list

---

apps/webapp/components/settings/subscription/SubscriptionSettings.tsx
apps/webapp/components/settings/subscription/components/modals/UpgradeSubscriptionModal.tsx
packages/spaces/src/getSpaceTokenBalance.ts
packages/subscriptions/src/getSubscriptionStatus.ts

Fixed subscription payment for overriden space amount

---

.ebstalk.apps.env/cron.env
.ebstalk.apps.env/webapp.env
apps/webapp/components/settings/invites/components/TokenGates/components/TokenGateModal/hooks/useTokensForm.tsx
packages/blockchain/src/connectors/chains.ts
packages/lib/src/blockchain/provider/ankr/client.ts
packages/lib/src/blockchain/provider/ankr/config.ts
packages/lib/src/blockchain/publicClient.ts

Fixed ankr api id and token gating
