charmverse/app.charmverse.io

components/editor/BangleEditor.tsx
It seems like the order of the specs is important... currently, hitting Return creates a code block. And if I remvoe code blocks, hitting Return creates an H1 tag. But it's fixed if I move them both to the end of the specs (maybe it just has to be after paragraph?).
=> fix code block creation on new lines

components/common/Emoji.tsx, components/editor/Editor.tsx, styles/index.css, theme/index.ts
We want to support emojis for pages like Notion does, this adds a component we can use that will apply the emoji font.
I also adjusted the font sizes for page title and Bangle editor to match Notion
=> add emoji next to page title

Dockerfile, package-lock.json
Not sure why but i started getting an error in Github Actions from Next.js after installing a new module and updating package-lock.json. I got it working by re-installing modules, but not sure what changed. Hopefully it doesn't come back!
Output looked like:
```
Run npm run build
> build
> next build
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
info  - Checking validity of types... …
```
=> update Node version in production

.github/workflows/test_and_deploy.yml, pages/[domain]/[pageId].tsx
Next.js warns us we are not caching our build, it should help speed up build times: https://github.com/vercel/next.js/blob/canary/errors/no-cache.md
=> Add Next.js cache to CI builds

components/editor/BangleEditor.tsx, components/editor/Image.tsx
I found the culprit: https://github.com/ProseMirror/prosemirror-dropcursor. This cursor is to show you where a component will be dropped if it is draggable. Bangle.dev enables this plugin all the time even if an element is not draggable. I don't think we support any draggable components at the moment? Just hiding it for now.
Also, no need to add a drop shadow on images.. I think that could mess up people's abilities to fully customize their content. They can always add a drop shadow themselves, or we could give them some options one day .. but i think by default we should leave it up to them, since a drop shadow might look ugly say if you have a transparent picture.
=> remove black bar on images and other components

.vscode/settings.json
When saving .ts or .tsx files in VScode, ESLint will automatically apply all fixes to that file
=> Setup automatic linter fixing on save for tsx and ts files in VSCode

components/bounties/BountyModal.tsx, components/common/Avatar.tsx, components/common/page-layout/CreateWorkspaceForm.tsx, components/common/page-layout/Sidebar.tsx, components/settings/ContributorRow.tsx, hooks/useContributors.ts, hooks/useUser.tsx, lib/users/getDisplayName.ts, models/User.ts, models/index.ts, pages/[domain]/settings/account.tsx, pages/[domain]/settings/contributors.tsx, seedData.ts
We decided that allowing people to enter a custom username could be misleading - they could put in someone else's wallet address or ENS for example. In the near-term future, we should pick up ENS name, and make our avatars should be more unique because plain wallet addresses are hard to remember.
=> remove username from user model

.gitignore, .vscode/launch.json
Currently the Chrome debugger starts with a new profile each time you run it, but it's a pain to reinstall the Metamask extension each time. One option is to set the user directory to "false" and it will use your personal profile, but with this update we save it inside `.vscode` so that it just remembers what you did the last time, and we only have to install Metamask once.
https://stackoverflow.com/questions/51725854/run-vscode-chrome-debugger-with-its-extensions
=> remember extensions when using Chrome debugger

pages/[domain]/settings/contributors.tsx
hiding "Token Gates" and "Invite LInks" for now since they are just placeholders
=> hide token gates and invite links until we actually have them

components/common/page-layout/Sidebar.tsx, components/signup/SignupForm.tsx, hooks/useENSName.ts, hooks/useUser.tsx, lib/users/getDisplayName.ts, models/User.ts
this might create some flickers where we use the account address while waiting for ENS lookup, but should be acceptable for now.
=> implement ENS name

components/databases/focalboard/src/components/viewHeader/newCardButton.tsx
I think I might be able to get this done if provided a bit more time but for now, as a quick fix, I've removed the button to add a template, as well as showing the existing templates. More importantly I noticed a major bug in our focal board API.
=> Removed adding template and showing list of templates

components/editor/BlockAligner.tsx, components/editor/ColumnLayout.tsx, components/editor/Image.tsx, components/editor/Resizer.tsx
1. Dropped column drop shadows
2. Images can be resize beyond the width of a column
3. Toggling dark/light theme doesn't reset image size
=> Fixed image resize issue on toggle dark/light modes

components/databases/focalboard/src/blocks/block.ts, components/databases/focalboard/src/blocks/charmBlock.ts, components/databases/focalboard/src/components/cardDetail/cardDetailContents.tsx, components/databases/focalboard/src/components/centerPanel.tsx, components/databases/focalboard/src/octoUtils.tsx, components/editor/CharmEditor.tsx, components/editor/Editor.tsx, theme/focalboard/focalboard.main.scss
This fix is to create a single "content block" of type: 'charm_text' for focalboard tasks. there might be a more elegant solution but it would require more changes outside the card details view
=> save content for focalboard blocks from charm editor

components/editor/@bangle.dev/react-emoji-suggest/EmojiSuggest.tsx, components/editor/@bangle.dev/react-emoji-suggest/emoji-suggest.ts, components/editor/@bangle.io/extensions/inline-command-palette/InlineCommandPalette.tsx, components/editor/@bangle.io/js-lib/inline-palette/inline-palette.ts, components/editor/@bangle.io/lib/ui-components/InlinePaletteRow/InlinePaletteRow.tsx, components/editor/@bangle.io/lib/ui-components/UniversalPalette/PaletteItem.tsx, components/editor/@bangle.io/lib/utils/utility.ts, components/editor/utility.ts
Two problems I fixed, tested in Chrome and Firefox:
- up/down arrows go in reverse direction if the command pallete opened above instead of below the cursor.
- even if the element you are keying down to is still in view, we were scrolling the parent each time.
- same issue was happening on the emoji container, and pressing up/down arrow would go diagonally up/down rather than straight up and  down
The bug stemmed from the fact our elements are embedded inside of a couple parent items (List, ListItem) so `parent` was actually a button, and not the scrolling container as it is on bangle.io.
=> fix up and down arrow key direction on command palette

components/editor/@bangle.dev/react-emoji-suggest/EmojiSuggest.tsx, components/editor/Editor.tsx
Show the page controls only on hover. Previously it was always shown.
=> Show page controls, icon and cover on hover

components/editor/Resizer.tsx
Previously when the image was resized to its maximum size it always got aligned to the left. Below are two screenshots of the same image before and after the commit
Before:
After:
=> Fixed image not being aligned center when resizing

components/editor/CharmEditor.tsx, components/editor/Editor.tsx, pages/[domain]/[pageId].tsx
This was nuts to fix. Tells me we are doing something wrong, maybe relying on both 'currentPage' and 'pages' in context is wrong.. I just tried to reduce the amount of places we were using the 'currentPage' value. `setState()` for example can either take the new value as input, or a function which then gives you access to the current value:
```
const { currentPage, setCurrentPage } = usePages();
function setPage (updates) {
// doesnt work
setCurrentPage({ ...currentPage, ...updates });
// works
setCurrentPage(_currentPage => { ..._currentPage, ...updates });
}
```
=> fix state messing with page properties

components/bounties_v2/BountyEditorForm.tsx, components/bounties_v2/BountyIntegration.tsx, components/common/Emoji.tsx, components/databases/focalboard/src/components/cardDetail/cardDetailContents.tsx, components/editor/CharmEditor.tsx, components/editor/Editor.tsx, components/editor/Page/PageBanner.tsx, components/editor/Placeholder.tsx, pages/_app.tsx, theme/@bangle.dev/styles.scss, theme/focalboard/focalboard.main.scss, theme/index.ts
Some cleanup items/bug fixes:
- Simplified CSS for page title and controls, reducing the need to set multiple 'top' offsets - now we just have an offset whether there's an icon set or not.
- made placeholder  its own component, and now it appears in the correct spot wherever it is used
- the text style cursor was disabled when looking at editor inside focalboard
=> small tweaks for bangle dev editor

components/common/Emoji.tsx, components/editor/Editor.tsx
I think you added the extra padding because the buttons were not accessible? adding overflow:hidden instead makes it so i can click on them again
=> fix overlapping of icon over buttons

charmClient.ts, components/common/RouteGuard.tsx, components/common/page-layout/Header.tsx, components/editor/Editor.tsx, components/editor/Page/PageTitle.tsx, models/Space.ts, pages/[domain]/[pageId].tsx, pages/api/public/pages/[pageId]/index.ts, pages/share/[pageId].tsx
Provides a toggle which admin users can enable.
If so, a publicly shareable link can be copied and sent to others.
=> Allow making pages public

components/common/page-layout/Header.tsx
Admins and collaborators can change a page between public and private
Toggle position default value now set on load
=> Page share fixes

components/_app/Web3ConnectionManager/components/WalletSelectorModal/utils/processConnectionError.ts
Currently it says 'an unknown error occurred' if you are signed out of metamask. I think checking for the error code is enough to guess it's metamask
=> better error from metamask

components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx, components/common/base-layout/PageWrapper.tsx, components/settings/TokenGates.tsx, components/settings/TokenGatesTable.tsx, next.config.js, pages/_app.tsx, theme/styles.scss
This was hard to track down.. In only our production build, the lit modal component was destroying our CSS styles. I realized the class definitions from @emotion/react were disappearing. I have a hunch thi sis because react-windows-select also uses @emotion and it was overriding our own. I added a cache for our Emotion styles with its own name (so the classes are all prefixed with "app" now). This seems to work on my laptop and hoping for the best in production!
Related issues:
https://github.com/JedWatson/react-select/issues/3309
https://github.com/emotion-js/emotion/issues/2210
=> Fix conflict between different @emotion instances

components/databases/DatabasePage.tsx, pages/[domain]/[pageId].tsx, pages/share/view/[sharedViewId].tsx
Revert to previous behaviour of letting focalboard load its view from the url query
=> Get viewId from the query, let DatabaseEditor access it from the query

connectors.ts
No idea why they were using the hex value in the source that I copied: https://github.com/agoraxyz/guild.xyz/blob/main/src/connectors.ts. Seems like an oversight and I'm guessing they don't really use that value
=> use correct type for chainIds in connects

components/common/page-layout/PageLayout.tsx, pages/share/[pageId].tsx
Fixes the bug in the screenshot of two scrollbars when sharing a page publicly:
=> fix scroll bars on public pages

components/common/page-layout/PageNavigation.tsx, components/common/page-layout/Sidebar.tsx, components/settings/Layout.tsx, pages/[domain]/settings/token-gates.tsx
Some users were not sure where to go to add users, and i wanted to highlight we have token gates. This also fixes the bug when clicking on Bounties in dev mode. We can use the extra space at the bottom of the sidebar for showing the network you're on, maybe allowing u to reconnect too
=> Put link to settings at top of sidebar like Notion

pages/_app.tsx, pages/_document.tsx
Fixes a warning when starting Next.js:
```
Warning: viewport meta tags should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-viewport-meta
```
=> more viewport meta tag to _app.tsx

components/common/page-layout/PageNavigation.tsx, components/common/page-layout/ShareButton.tsx, components/common/page-layout/Sidebar.tsx, components/editor/NestedPage.tsx, hooks/usePages.tsx, pages/[domain]/[pageId].tsx
Editor is still a bit slow but we should try to avoid array loops in general. Should probably move the rest of our data state to maps, but I think this is the one we use most commonly and that could impact editor speed.
I think this turned out to be a good change because it reduced the amount of code we needed to update a single page in various places
=> convert pages state to a map for performance

components/common/page-layout/PageNavigation.tsx, components/editor/@bangle.dev/tooltip/suggest-tooltip.ts, components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx, components/editor/CharmEditor.tsx, components/editor/Mention.tsx, components/editor/NestedPage.tsx, hooks/useNestedPage.ts
1. Type `/` to view the `Link to Page` option
2. Click on the option to view a list of all pages in the workspace
3. Click on any of the pages to see it get embedded in the editor
I tried to implement @motechFR suggestion to allow navigation via arrow key and select page on pressing enter and was almost close to completing it, but just couldn't seem to get it working. I've added that to the backlog as that's quite important for UX
=> Link to page using `/` shortcut

components/common/base-layout/getLayout.tsx, pages/index.tsx
There's a flash of the login page when you go to https://app.charmverse directly, that's because the redirect inside `useEffect()` is happening after the component mounts. The fix is to rely on a different value to trigger the login view which is set in the useEffect method
=> fix flash of login page on first load

components/databases/focalboard/src/components/gallery/galleryCard.tsx
this is based on my own local example, the image node was not nested inside a paragraph node. not sure if this was what the original user was seeing though
=> check for image nodes in charmeditor

lib/notion/importFromWorkspace.ts, pages/api/notion/callback.ts, pages/api/notion/import.ts
1. If the code is ill-formatted or if it has already been used, we show this error message to the user `Invalid code. Please try importing again`
2. If we face any issue importing a page/database we show
1. The page/database title
2. Page/database id
3. Trail of blocks (block_type, Position of the block in the parent)
Right now we fail the whole import process even if a single page/block fails importing. We need to handle that case better. We should continue importing and create an array of messages like the following to show the user which pages we failed to import and which block is the culprit. One approach we can take is by creating a representation of the whole workspace in memory before creating anything, that way error handling and reporting would be a whole lot easier than the …
=> Better error handling for notion import 

lib/log/logLevel.plugin.ts
I'm going to set LOG_LEVEL to 'debug' in production, this won't affect the browser but we'll be able to capture more logs on the server
=> allow overriding log level

components/common/RouteGuard.tsx, components/common/Snackbar.tsx, components/editor/FloatingMenu.tsx, components/editor/IFrameSelector.tsx, components/editor/ImageSelector.tsx, components/editor/NestedPage.tsx, pages/[domain]/settings/workspace.tsx
1. Removed local `Snackbar` to opt for a single global `Snackbar`
2. Close the snackbar using `setIsOpen` as soon as we change route
3. Test the following places where we used local snackbars
1. Select a text and see if the floating menu appears or not
2. Select a text and click on link format, see if a new floating menu appears or not
3. Iframe and image blocks
4. Create a child page `Insert Page` and click the right-most icon (to delete, duplicate and copy link)
5. Click on `Link to Page` and see if the dropdown appears or not
=> Removed unnecessary snackbars

seedData.ts
Fixes this video being too wide:
=> fix max width of introduction videos

components/common/CharmEditor/components/ResizableIframe.tsx
Youtube links (both regular and shared) failed to generate the embed link with timestamp. This PR fixed this [card](https://app.charmverse.io/charmverse/page-49366552253645923?cardId=a2bff99f-0595-4e0d-a71a-1bcda05ccb8a&viewId=d15c9b90-8918-44da-bbd8-db8712faa723)
=> Fixed parsing yt link with timestamp

components/common/PageLayout/components/Account/Account.tsx, components/common/PageLayout/components/Account/components/AccountModal/AccountModal.tsx, components/settings/roles/components/RoleRow.tsx
- limit the height of the list of members under roles to 5
- don't hide the modal immediately after connecting discord. I left in the 2.5 second timeout, but maybe we should just leave it alone. I tried unsuccessfully to remove query params in the URL without redrawing the whole page (and hiding the modal!)
- added member count to roles
- made the 'disconnect' button an outlined red. i think solid red looks pretty scary especially since we hide the modal automatically
=> User roles UI

components/common/form/InputSearchContributor.tsx
1. `multiple` prop was added to `InputSearchContributor`, which meant when we selected a value it was an array, and array's don't have `id` property.
2. We used to show the `Autocomplete` component even if the `contributors` list was empty. Initially it will be empty as its being fetched but once its fetched, the default values can be gathered, but by then MUI has already set the defaultValue (as undefined due to empty list) and changing it would trigger an error (MUI wont show the default value) as its being converted from an uncontrolled component (default value of undefined) to a controlled one (non undefined default value)
=> Removed multiple prop from InputSearchContributor component

pages/api/discord/callback.ts, pages/api/profile/index.ts, pages/api/session/login.ts
Alex can't log in, i believe it's because his cookie is too large. I think it's because we are writing the whole discord user profile to the cookie. It looks like we only really need to save the userId to the sessino, but i'm going to wait till i have more time to do that
=> strip out fields from user profile when saving the session cookie

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/ResizableIframe.tsx, components/common/CharmEditor/components/ResizableImage.tsx
1. Disable resizing images/videos/iframes in readonly mode (sharing)
2. Disable uploading or adding link for empty images/videos/iframes
3. Disable deleting images/videos/iframes (top right icon)
=> Disable editing images on readonly mode

components/common/PageLayout/components/PageNavigation.tsx
- There was an error from MUI because we were not passing a 'nodeId' property to the TreeItem used for board views. I also split it into its own component from PageTreeItem because they don't really need to share the same code.
```
Warning: Failed prop type: The prop `nodeId` is marked as required in `ForwardRef(TreeItem)`, but its value is `undefined`
```
- Also: highlight the view row when you're on the page (see screenshot)
=> fix error related to board page items in sidebar menu

components/common/CharmEditor/components/Mention.tsx, components/common/CharmEditor/components/Resizable/HorizontalResizer.tsx, theme/index.ts
1. Show the contributors and pages of a workspace in separate sections
2. Link to a page inline
(Pages could be large so we might have to add support for [Virtualized List](https://mui.com/material-ui/react-list/#virtualized-list))
=> Show pages and contributors list inside @ trigger

components/common/CharmEditor/CharmEditor.tsx, components/common/PageLayout/components/PageNavigation.tsx
We couldn't detect page content emptiness if there was a non-content node. See below (a page node). I encountered this while testing out the notion import
1. Correctly detect content emptiness for non-content nodes (mention, pages, cryptoPrice and so on)
2. Show the correct icon in the sidebar if the page is empty (couldn't detect correctly earlier)
=> Fixed not being able to detect content emptyness

components/common/CharmEditor/components/EmojiSuggest/EmojiSuggest.tsx
this must have never worked since i added the clickawaylistener component? but apparently it's smart enough to not close when a child component is clicked. i had to use react's portal component as well
=> fix emoji picker in charmeditor

components/common/PageLayout/components/PageNavigation.tsx
We shouldn't be allowing the user to change the focalboard view icons since they are static. This is a misleading UX. This PR:-
1. Removes showing the picker for focalboard views
2. Removes the hover style to let the user know its not clickable (at least nothing will happen if they click it)
=> Shouldn't show picker for focalboard views

.github/actions/build/action.yml, .github/actions/install/action.yml, .github/workflows/deploy_staging.yml, .github/workflows/test_and_deploy.yml
we could probably be even more greedy by hashing all the ts, scss, etc. files but that could also backfire if we forget to include something in the cache key. for now, i tihnk this just will speed up deployment since the 'build' step fires after test
=> Reuse next.js builds in CI

lib/browser.ts, lib/session/config.ts, pages/api/notion/callback.ts
it wasn't working because code in the browser would set a domain on the cookie, but the cookies from the server dont have an explicit domain. I removed the setting of domain, we don't have a need for that now. It could be useful if we want to support cross-domain cookies
=> Fix notion cookies

components/common/PageLayout/components/PageNavigation.tsx, components/common/PageLayout/components/Sidebar.tsx, pages/api/blocks/[id]/index.ts
Right now if we delete the focalboard page, all the card pages get moved to the root level of the navigation
=> Delete card pages and card blocks when deleting board

pages/api/blocks/[id]/index.ts
Turns out we only deleted blocks via their rootId. This works only when we delete the whole board, but not when deleting a single card. If I delete a card now only the card page and card block get deleted, the charm_text and comment blocks associated with it still remain.
**Strategy**
1. Retrieve all the blocks whose `rootId` or `parentId` is the same as the deleted block id
2. Delete all the blocks whose id is from 1 or whose `parentId` is from 1
=> Delete all child blocks of a block when deleting

components/common/BoardEditor/focalboard/src/components/sidebar/sidebarAddBoardMenu.tsx, components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/Mention.tsx, components/common/CharmEditor/components/nestedPage/components/NestedPagesList.tsx, components/common/CharmEditor/components/nestedPage/hooks/useNestedPage.ts, components/common/PageLayout/components/NewPageMenu.tsx, components/common/PageLayout/components/PageNavigation.tsx, components/common/PageLayout/components/Sidebar.tsx, hooks/usePages.tsx, lib/pages/addPage.ts, lib/pages/index.ts
Ideally we shouldn't need to update the sidebar at all while someone is typing on a page, but that's not possible today. I think it's another good reason to try and split the metadata/page tree from the actual page content..
3 major improvements made:
1) memoized a lot of the inputs to components in the sidebar
2) change nested page and mentions list to only render when they are actually open - this removes watchers on the pages context being triggered.
=> Optimize rendering of sidebar components

components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.scss, components/common/BoardEditor/focalboard/src/styles/main.scss, theme/focalboard/focalboard.main.scss
Bug fix: https://app.charmverse.io/charmverse/page-49366552253645923?cardId=bf1e756c-99cc-4dab-bac4-478b87cfd6e8&viewId=d15c9b90-8918-44da-bbd8-db8712faa723
Now:
=> add some padding around properties on kanban cards

components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.scss
This fixes a bug: https://app.charmverse.io/charmverse/page-49366552253645923?cardId=370458ce-83d1-4f52-aeb5-2fb06d2ba257&viewId=d15c9b90-8918-44da-bbd8-db8712faa723.
=> fix scrolling in focalboard cards

components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/BoardEditor/focalboard/src/components/dialog.scss
it now stretches across the page < 975px:
=> Fix focalboard modal CSS on mobile

components/[pageId]/BoardPage/BoardPage.tsx, components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButton.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx, components/common/CharmEditor/CharmEditor.tsx, components/common/PageLayout/PageLayout.tsx, components/common/PageLayout/components/AddNewCard.tsx, components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, components/common/PageLayout/components/PageNavigation/components/BoardViewTreeItem.tsx, components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx, components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx, components/common/PageLayout/components/PageTitle.tsx, components/common/PageLayout/components/Sidebar.tsx, pages/api/pages/[id]/index.ts
My approach was again to profile the React components while typing in the focalboard title input. most of it now looks like it's inside the MUI TreeView component. the only way we can get away w/o rendering all of that would be to separate the page content state from the page tree info, both of which we store in the PageProvider currently..
=> more optimizations

components/[pageId]/BoardPage/BoardPage.tsx, components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.tsx
Turns out we were calling the `debouncedPageUpdate` function even after the `cardDetail` component was unmounted. Added a ref to make sure we don't call it if the component has been unmounted.
=> Fixed card content being reset after closing it

package-lock.json, package.json
Updating to the latest version, which doesn't complain that react-dnd is an invalid version: https://github.com/TechStark/react-dnd-scrolling/issues/15. i don't expect and breaking changes
=> update react-dnd-scrolling lib

.github/actions/install/action.yml, package.json
The 'postinstall' script was in the wrong place in package.json, so it didn't get triggered! I have a feeling this happened while I was fixing a merge conflict.. after this, we should no longer have to run npx patch-package locally :)
=> fix script to run patch-package

lib/public-api/interfaces.ts, pages/api-docs.tsx
This ensures the Open API docs show in light mode only, and fixes a small bug on the Database Page
=> Fix API docs, enforce light mode in the API

components/bounties/components/BountyStatusBadge.tsx
Made updates to the bounty card in the bounties list:
- if the content on the amount row does not fit in a single line, it is displayed on two lines (wrapped)
- the currency ticker is displayed in the tooltip
=> Added amount ticker to tooltip, prevent row truncation

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/emojiSuggest/emojiSuggest.specs.ts, components/common/CharmEditor/components/table/table.ts
Prevent markdown export from blowing up
- Adds support for inline emojis
- Provides empty renderer function for tables
=> Review markdown

components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
Apparently, 'card.deletedAt' can be 0 sometimes, but it then appears on our UI. I wonder if there's a lint rule or something to prevent non-boolean types from being used in React templates
=> fix logic to not show "0" on focalboards

components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx, components/common/BoardEditor/focalboard/src/components/cardDialog.tsx, components/common/BoardEditor/focalboard/src/components/dialog.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButton.tsx, components/common/BoardEditor/focalboard/src/widgets/menu/menu.scss, components/common/BoardEditor/focalboard/src/widgets/menu/menu.tsx, components/common/BoardEditor/focalboard/src/widgets/menu/menuContext.ts, components/common/BoardEditor/focalboard/src/widgets/menu/subMenuOption.tsx, components/common/BoardEditor/focalboard/src/widgets/menuWrapper.tsx, components/common/BoardEditor/focalboard/src/widgets/valueSelector.tsx
This screenshot is an example of really bad UI:
The dropdowns are now embedded at document.body so nothing can crop them:
One downside to this I noticed is that if they go past the viewport, you can't get to content. What Notion does is auto- popups to fit inside the viewport. I want to leave that for another day / another PR
The placement of menus may be a little off, I didn't go thru and update 'position' everywhere.
=> Fix hidden menus in Focalboard

components/common/PageLayout/components/ShareButton/components/PagePermissions/PagePermissions.tsx, components/common/form/InputEnumToOptions.tsx
This PR is in response to an issue reported by a user who thought they couldn't change their permissions.
It displays a box when a permission level is hovered.
=> Show a visible box when the permission is hovered

components/common/PageLayout/PageLayout.tsx
Improvments for sidebar UX on mobile:
- the sidebar is collapsed by default
- when the sidebar is extended, it is full width
=> Improved sidebar UX for mobile

patches/lit-share-modal+0.1.84.patch, theme/lit-share-modal/lit-share-modal.scss
The ERC20 token dropdown select is broken according to Lit. They are going to fix it n the next 1-2 weeks by rewriting it. In the meantime, we just want to hide it.
I tried using CSS to hide it, but  there's no way to only target the correct elements.
=> Lit modal fix (temporary)

next.config.js
Alex has said a few times that he's had to hard-refresh the page to get updates, using Chrome. This is hard to reproduce but it looks like Next.js uses ETags to tell browsers when to refresh the page. Perhaps the Etags are not always updated properly - by removing them, we force the browser to always load the first page. With Etags, I get a 304 Status code after the first load, without them, it's a 200 each time (re-download the page). I believe this only affects the first request and not our other static assets.
https://stackoverflow.com/questions/69838808/next-js-is-caching-my-server-side-pages-how-to-disable-that
=> remove etags to force page reloading

pages/api/spaces/index.ts
The workspace update was throwing a 500 when editing just after it was created. The reason was that the pages were also sent in the PUT request.
=> Prevent pages from being returned on workspace creation

components/bounties/components/BountyEditorForm.tsx, components/common/CharmEditor/CharmEditor.tsx
1. Disabled inline comment for bounty charmeditor (for some reason we missed this)
2. Fixed the width of bounty charmeditor to take parents width
=> Bounty charmeditor

components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx, components/common/PageLayout/components/Sidebar/Sidebar.tsx
Scroll to the current page in the page navigation for a long list. Currently, we keep the scroll bar at the top which leads to a suboptimal UX. The user has to manually scroll to get to the page.
=> Scroll to the correct item in page navigation

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/Paragraph.tsx
The toggle layout broke when we made global style changes to the editor for inline comments. I am using position: absolute instead.. let me know if there's issues
=> fix styles for toggle input

components/common/PageLayout/components/ShareButton/ShareButton.tsx, components/common/PageLayout/components/ShareButton/components/PagePermissions/PagePermissions.tsx, components/common/form/InputEnumToOptions.tsx
Related card: https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=ae01f13c-f888-405b-aa18-eb94ba4e800e
The layout for permissions breaks when the option is logn (see loom). I replaced the custom ui with standard MUI select and some CSS:
https://www.loom.com/share/d085c99689424177988848bbbd814df0
new UI:
=> improve UI for permissions border

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/disclosure/commands.ts, components/common/CharmEditor/components/disclosure/disclosure.ts, components/common/CharmEditor/components/quote/components/Quote.tsx, theme/@bangle.dev/styles.scss
- fixes an issue that space bar would toggle the summary open and close
- fixes a layout issue when header is more than one line, so the indent carries down
=> Fix toggling for Firefox

components/[pageId]/DocumentPage/DocumentPage.tsx, hooks/usePages.tsx
There's a bug introduced recently where adding a page brings back stale data from pages. This update makes it so that the setter `setPages` updates the original cache from SWR, which in turn updates the object map returned from usePages()
=> Fix: keeping our page cache up-to-date

components/common/CharmEditor/components/@bangle.dev/react/NodeViewWrapper.tsx
Not 100% sure why, but when deleting a paragraph content inside a list item, it crashes the editor. This is serious because the user can't undo. Another fix would be to not use "span" as the contentDOM for Paragraph tags, but this seems less intrusive.
=> fix bug deleting a node

components/common/Loader.tsx, components/common/PageLayout/components/ShareButton/components/PagePermissions/AddPagePermissionsForm.tsx
Fixes an issue where multiple permissions were added at once but not inherited
We now send new permissions from a client-side orchestrated queue to ensure deterministic behaviour.
=> Multi role user permission inheritance

components/profile/components/ProfileLayout.tsx, components/profile/integrations/IntegrationsPage.tsx, components/profile/integrations/components/DiscordProvider.tsx, components/profile/integrations/components/IdentityProviders.tsx, components/profile/tasks/GnosisTasksList.tsx, components/profile/tasks/IntegrationCard.tsx, components/profile/tasks/TasksPage.tsx, lib/discord/constants.ts, lib/gnosis/gnosis.importSafes.ts, lib/gnosis/gnosis.ts, pages/api/discord/callback.ts
- de-dupe gnosis safes for users that have more than one wallet in control of a safe
- use purple color for discord icon on Integrations page
- better layout for Integrations
- most of this PR turned into a refactor of Discord connect. I split it up from the main page and we're now using cookies instead of the URL - I left the URL alone because some components are still using it. Please check it works on your end!
New layout:
=> Small tweaks to Personal Nexus and integrations

components/common/CharmEditor/components/nestedPage/hooks/useNestedPage.ts, hooks/usePages.tsx
Still getting the hang of state in React... I assumed the "closures" are being regenerated so we'd be fine, but apparently not. I even removed all the debounce logic, but the only thing that works is to capture a ref to the original pages state.
https://dmitripavlutin.com/react-hooks-stale-closures/
=> fix stale cache of pages

components/common/Modal/Modal.tsx, components/common/Modal/SuccessModal.tsx
This reverts a change to the Modal component from the profile section. It causes the success modal used on token gates to stretch full width:
@AndreiMitrea can you let me know which modal relied on this update?
=> fix widths of modals

adapters/litProtocol/hooks/useLitProtocol.tsx, pages/_app.tsx
Lit protocol creates a ton of open connections when it loads. By removing global context for lit protocol, we'll only create the client in the components that need it get loaded. I tested by creating and testing a token gate in workspace settings
=> dont enable lit protocol globally

components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx, pages/api/blocks/[id]/index.ts
Client and server-side validation for not allowing the user to delete the last view of a page. A board page is completely unusable without at least a single view and a blank screen will be shown in that case.
=> Prevent deleting the last view of a board page

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/callout/components/Callout.tsx
Better UX for callout emoji (using twemoji and IconButton for hover styling). Fallback to regular emoji for Mac
=> Used twemoji for callout emoji

lib/gnosis/gnosis.tasks.ts, lib/gnosis/gnosis.ts, scripts/sendNotifications.ts
I can't find any documentation about rate limits for Gnosis, the error goes between "Service Unavailable" and "Service Temporarily Unavailable". This could be Alchemy but I feel like it's Gnosis... anyway i added a try/catch so a single exception won't fail everything else.
There's also no documentation about the different types of responses I can get, AFAIK. They have some types on their swagger ui but it doesn't go into enough detail.
I want to keep looking for rate limit docs, may need to find their Discord channel or whatever :/
=> Fix: too many requests to gnosis safe and handle more types of transactions

package-lock.json, package.json
Just want to keep updating next.js. They've been working on 12.1.7 for a while so I assume this should be pretty stable.
changelog: https://github.com/vercel/next.js/releases/tag/v12.1.6
=> update next to 12.1.6

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/iframe/IFrameSelector.tsx, components/common/CharmEditor/components/iframe/IframeComponent.tsx, components/common/CharmEditor/components/iframe/iframe.ts, components/common/CharmEditor/components/iframe/index.ts, components/common/CharmEditor/components/inlinePalette/useEditorItems.tsx, components/common/PopperPopup.tsx, lib/embed/extractEmbedLink.ts
- group iframe embed code for CharmEditor into one folder
- fix default video width of 400px to be full-width (this feels more intuitive to me, but also mirrors notion)
- have video/iframe input appear by default
- removed the paragraph component wrapper around iframe and video embeds when inserting into the doc...  @Devorein is there any reason to keep them wrapped by p tags?
=> reorganize iframe component for charm editor

components/common/CharmEditor/components/iframe/IFrameSelector.tsx, components/common/PopperPopup.tsx
Opening the popper-popup for IframeSelect is fine but everytime I navigate to a page (that has a cover) it opens it up, I reckon it does the same in all the places we are using `PopperPopup` component, added an `autoOpen` prop to disable this by default
=> autoOpen prop for PopperPopup component

.github/actions/install/action.yml
The builds have started failing when doing npm ci if we don't have a cache of node_modules. Using v16.14 seems to work fine. 16.15 was released 7 days ago and includes a new version of npm, which I think may be the culprit.
=> pin the version of node in github ci for now

charmClient.ts, components/bounties/BountyList.tsx, components/bounties/[bountyId]/components_v3/BountySubmissions.tsx, components/common/BoardEditor/focalboard/src/store/cards.ts, hooks/useBounties.tsx
This fixes some bugs due to stale bounty state. To reproduce one example:
1. Create a few bounties
2. Edit one bounty's status by creating a submission
3. Go back to bounties page: there is only one bounty (the bounty we edited).
We had a similar issue with usePages where we were reading the context value directly, but it turns out to be the initial state, so when the method gets calle,d 'bounties' is still an empty array.
=> fix access to bounties state

components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
Fixes for incorrect page ordering on drag and drop.
Some scenarios fixed by this PR that can be reproduced in production:
1. Dragging as child page
1.1 Make sure there are at least 2 pages in the workspace.
1.2 Drag one as the child page of the other.
1.3 Notice the console error:  _Uncaught Invariant Violation: Expected to find a valid target. targetId=_
2. Order shuffle for new pages
https://www.loom.com/share/d4f085548c9b42318d8705672ca00f8f
2.1 Create a new workspace.
2.2 Add 5 new pages.
2.3 Click randomly on the screen.
2.4 Notice the order changes.
3. Three is a problem
3.1 Create a new workspace.
3.2 Create two pages and a board.
3.3 Drag the second page above the first page.
3.4 Drag the board in between the two pages.
3.5 Notice the board is put first.
=> Fix for incorrect page ordering

components/profile/components/PoapSection.tsx
This PR contains a fix for a scenario in which the POAPs are not displayed.
STR
1. Go to the nexus profile.
2. Notice existing poap(s).
3. Copy the public profile URL.
4. Go to that page in the same tab.
5. Notice the poap(s).
6. Click on the name in the top right corner.
7. Click on the My public Profile link.
8. Notice the missing poap(s).
=> Fix for not displayed poaps

charmClient.ts, components/[pageId]/EditorPage/EditorPage.tsx, components/common/CharmEditor/CharmEditor.tsx, components/common/PageLayout/PageLayout.tsx, components/common/PageLayout/components/Account/Account.tsx, components/common/PageLayout/components/CurrentPageFavicon.tsx, components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/PageTitleWithBreadcrumbs.tsx, components/share/PublicPage.tsx, hooks/usePages.tsx, hooks/useSpaces.tsx, lib/middleware/errors.ts, pages/[domain]/[pageId].tsx, pages/api/public/pages/[pageId]/index.ts, pages/api/spaces/[id]/pages.ts, pages/share/[pageId].tsx, pages/share/view/[sharedViewId].tsx
This was trickier than it looked because I had to make sure all the context loads properly, including with SWR refreshes. The flow now looks like this:
1) the PublicPage component determines what space and page we're looking at by calling getPublicPage(). This  api call now supports a path as well as a pageId.
2) usePages() is used to grab the rest of the pages. It depends on useSpace(), but that depends on the /domain URL. So I updated usePages() to check for the /share/[pageId] route and in that case, just assume it's the first workspace available (since we only load one for public pages).
=> Add breadcrumbs for public page

charmClient.ts, components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx, components/common/PageLayout/components/ShareButton/ShareButton.tsx, components/common/PageLayout/components/ShareButton/components/PagePermissions/PagePermissions.tsx, components/common/PageLayout/components/ShareButton/components/ShareToWeb.tsx, hooks/usePages.tsx, pages/api/permissions/index.ts, pages/api/spaces/[id]/pages.ts
The fix was to remove teh call to 'refreshPage' inside of usePAges but it required a number of other changes which led to some nice cleanup.. thanks @motechFR
=> Simplify loading of permissions and fix for loading context for public pages

.github/workflows/test_and_deploy.yml, lib/utilities/__tests__/strings.spec.ts, lib/utilities/strings.ts, package.json
my update to the URL stuff doesn't remove cardId when closing a card in focalboard. Added some tests :)
Also, by adding `--watch`, running `npm run test:server` now only runs against tests/files that changed. It somehow can tell when I change a file what tests are running against it...
=> add test and fix: properly update the URL when closing cards

components/common/BoardEditor/focalboard/src/cardFilter.test.ts, components/common/BoardEditor/focalboard/src/components/blockIconSelector.test.tsx, components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.test.tsx, components/common/BoardEditor/focalboard/src/components/cardDetail/comment.test.tsx, components/common/BoardEditor/focalboard/src/components/cardDialog.test.tsx, components/common/BoardEditor/focalboard/src/components/centerPanel.test.tsx, components/common/BoardEditor/focalboard/src/components/gallery/gallery.test.tsx, components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.test.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanban.test.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.test.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanbanColumnHeader.test.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanbanHiddenColumnItem.test.tsx, components/common/BoardEditor/focalboard/src/components/topBar.test.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/emptyCardButton.test.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/filterComponent.test.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.test.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/filterValue.test.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButtonTemplateItem.test.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderActionsMenu.test.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderGroupByMenu.test.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderPropertiesMenu.test.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderSortMenu.test.tsx, components/common/BoardEditor/focalboard/src/components/viewTitle.test.tsx
removes annoying typescript errors, and i think is required if we actually want to run these tests :P
=> replace deprecated use of mocked from ts-jest

components/settings/roles/RoleSettings.tsx, components/settings/roles/hooks/useImportDiscordRoles.ts
Discord roles import logic was previously written inside `RoleSettings`, while it doesn't introduce any bug it's not a good practice. Now the whole logic is located inside a local hook, making it much easier to reuse and reason about.
=> Moved discord roles import logic inside a hook

jest.config.ts, lib/deepdao/__tests__/getAggregatedData.spec.ts, lib/deepdao/getAggregatedData.ts, lib/spaces/__tests__/getSpacesCount.spec.ts, lib/spaces/getSpacesCount.ts
Previously we only counted the number of daos you are part of in deepdao, but now we add the charmverse workspaces you are part of with that data
=> Include the number of charmverse spaces with deepdao communities 

components/common/PageLayout/components/Account/Account.tsx, components/nexus/MentionedTasksList.tsx, components/nexus/TasksPage.tsx, components/nexus/hooks/useTasks.ts
1. Show the total number of unattended tasks you have beside your avatar on the top right
2. Used `useSWRImmutable` to fetch tasks as fetching gnosis tasks can take a long time
3. Update the tasks state right after viewing the mentioned tasks (when you navigate to the mentioned tasks tab in your nexus we mark all the mentions as "seen", now since it will impact how many tasks is shown, I had to update the tasks state)
=> Show notifications badge beside avatar on top right

components/common/PageLayout/components/Account/Account.tsx, components/nexus/components/SnoozeButton.tsx, models/User.ts, pages/api/profile/index.ts
1. Skip counting snoozed multisig tasks when counting your notifications
2. After adding a snooze/removing snooze for multisig tasks we update the users state to show a live update of the notifications count
=> Skip snoozed multisig tasks in notifications count 

components/common/ImageSelector/ImageSelector.tsx, components/common/MultiTabs.tsx
Right now if after clicking on **Choose an image** and uploading an image, the UX is extremely confusing. The user has no idea whether its uploading or not. The button is not disabled so they can upload again, or switch tabs. This PR does the following things:-
1. Show an upload message for the upload button text while the image is being uploaded
2. DIsable the tabs so that one can't switch to pasting a link
3. DIsable the upload button while its uploading
4. Show a spinner beside the upload message
=> Better upload image ux with loading message and spinner

components/[pageId]/DocumentPage/components/PageTitleInput.tsx
This solution is pretty simple for now: just don't sync backend changes with the title when the user has it in focus. Tested by using Firefox to throttle the network.
First I tried adding a trigger in Postgres to bump a document version on update, and then only updating the view when the version is more recent, but it didn't solve the issue: because we're waiting for Postgres to give us the new version, but the client has more recent changes. I would like to see how we will solve this for CharmEditor before coming up with a final solution.
=> Immutable page title while focused

lib/bounties/__tests__/rollupBountyStatus.spec.ts, lib/bounties/rollupBountyStatus.ts, lib/bounties/updateBountySettings.ts, pages/api/bounties/[id]/index.ts
Fixes an issue whereby updating a bounty suggestion triggered rollup to open status
Ensures fields for suggestion are not dropped if update coming from an admin
=> Bounty submissions rollup fix

components/bounties/components/BountyStatusBadge.tsx, components/common/TokenLogo.tsx, components/common/form/InputSearchCrypto.tsx, components/settings/payment-methods/PaymentMethods.tsx, components/settings/payment-methods/components/PaymentMethodList.tsx, connectors.ts, lib/tokens/tokenData.ts
This PR adds a default icon (the chain logo) for all tokens. I think it's better than leaving a whitespace... also mirrors what you see on Etherscan.
I also fixed a bug wehre when you select a custom token in InputSearchCrypto, we show the token address rather than the token name. I think that the code for this component could be simplified further, but saving for another day..
=> Payment icons

lib/discord/loginByDiscord.ts, lib/session/config.ts, lib/users/createUser.ts, lib/users/getUser.ts, models/User.ts, pages/api/profile/favorites.ts, pages/api/profile/index.ts, pages/api/session/login.ts
I noticed Alex was seeing the "Favorites" label in his sidebar with no pages underneath. I don't know if this was his case, but I know it is a bug - that we don't check which favorites have been deleted. Once the page is deleted after 30 days, it should be cleared, but this check helps until that happens. 
Currently what it looks like:
To test: add a page to your favorites and delete it. Reload the site.
=> only include favorites of pages not deleted

components/common/CharmEditor/components/Paragraph.tsx
This fixes a bug where I can't use the "down arrow" in CharmEditor in Firefox. I believe this has something to do with the native cursor in contenteditable wanting to select an element with position: absolute. If I remove that CSS property, the cursor works again and goes to the next line. After lots of debugging, wrapping it in an element with contenteditable='false' also seems to work!
=> fix cursor in firefox

components/common/CharmEditor/components/Paragraph.tsx
Fixes a warning I saw in dev mode, but the icons are working:
Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.
=> suppress warning about contenteditable

lib/pages/server/duplicatePage.ts
Fixes a call we forgot to revert when removing parentPage relationship
=> Fix parent page call in the duplicatePage method

__integration-tests__/server/pages/api/email-templates/index.spec.ts, package-lock.json, package.json
looks like we never had mjml declraed as a dependency, but we are supposed to according to the react-mjml docs. It was working because it was somehow listed in package-lock.json until I upgrade Prisma.  I think I used a more recent version of npm (v8.11) which cleaned out undeclared dependencies like mjml :/
I Found that I can trigger the error by vising https://app.charmverse.io/api/email-templates, so added a test on that endpoint
=> Error fix for emails: 'mjml not found'

components/common/BoardEditor/focalboard/src/components/gallery/gallery.scss, components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.scss, components/common/BoardEditor/focalboard/src/components/viewTitle.scss, components/common/BoardEditor/focalboard/src/components/viewTitle.tsx
On mobile, you can scroll the focalboard view left and right  even though it's just whitespace. I figured out it was the title input being 500+ pixels wide was stretching the page. I don't know why it is that wide by default, but setting it to 100% fixes the problem. I found that normally it has a "100% width" when it's a child of CardDetail, so I figure this is a safe update.
=> fix extra space on focalboard in mobile view

components/[pageId]/DocumentPage/components/BountyProperties.tsx, pages/api/bounties/[id]/permissions.ts
We don't want to take 'admin' status into account when letting someone apply to a bounty. I think this is the only place I actually need to change?
I'm not sure what we've discussed thus far, but maybe we can just remove the admin override to bounty permissions since they already have the ability to delete the page itself.
=> remove admin bypass when viewing permission for a bounty

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/@bangle.dev/base-components/code-block.ts, components/common/CharmEditor/components/@bangle.dev/base-components/image.ts, components/common/CharmEditor/components/ResizableImage.tsx, components/common/CharmEditor/components/ResizablePDF.tsx, components/common/CharmEditor/components/columnLayout/columnLayout.tsx, components/common/CharmEditor/components/emojiSuggest/emojiSuggest.specs.ts, components/common/CharmEditor/components/iframe/IframeComponent.tsx, components/common/CharmEditor/components/iframe/iframe.ts, components/common/CharmEditor/components/mention/mention.specs.ts, components/common/CharmEditor/components/nestedPage/nestedPage.specs.ts, components/common/CharmEditor/components/paragraph/index.ts, components/common/CharmEditor/components/quote/quote.ts, lib/browser.ts, theme/@bangle.dev/styles.scss, theme/cssVariables.ts
It turns out I can still drag elements with draggable: false. According to the docs it means: "Determines whether nodes of this type can be dragged without being selected. Defaults to false." So I'm not actually sure what that means
=> Fix select multiple lines

components/[pageId]/DocumentPage/components/CreateVoteBox.tsx, components/common/CharmEditor/components/inlineVote/components/InlineVoteSubmenu.tsx, components/common/PageLayout/PageLayout.tsx, components/common/PageLayout/components/Header/Header.tsx, components/votes/components/CreateVoteModal.tsx, hooks/useVotes.tsx
I noticed I couldn't save a new vote when looking at a card view inside of focalboard. It's because the pageId was 'null' inside the hook - it doesn't seem to get upated when the URL changes.
I also moved the call to useVotes for `createVote` into the modal component because all the parents were having to do the same logic.
=> fix saving votes from inside a card

components/integrations/components/DiscordProvider.tsx, pages/api/discord/importRoles.ts
Some considerations
1. Fetching all users that have their discord account connected to charmverse for a specific space could cause some bottleneck if there are lots of them. Should we be careful about that or is that something we can skip for now?
2. How to handle the case when failing to fetch an individual user? When the import is done should there be a message that says failed to import/connect `X` users?
3. Right now as soon as you authorize your server the import starts and you are redirected to where you came from (settings/roles), and we show a loader underneath the `Roles` section indicating that roles are being imported. Should that be more prominent via a modal that says `Discord roles import is in progress. Please wait...`?
=> Fetch individual discord user when importing roles

components/share/PublicPage.tsx
At the moment, this is what I understand:
- The page view components PublicPage and EditorPage should only use `router.query` to determine the current page, they set currentPageId but do not read it
- currentPageId is used by components in CharmEditor (and we should be able to now remove the check for 'cardId' in the URL), and maybe other places but I did not investigate.
I think going forward it would be good to try and get rid of needing to use a global state for the current page id.. or make it something we only use for CharmEditor?
=> show popups in public mode of boards

components/common/CharmEditor/components/inlineComment/inlineComment.plugins.tsx
This PR aims to fix the case where multiple comment count decoration is being shown for a single comment spanning across multiple nodes. This is a numbered list where I created a comment by dragging across all the lines. It should create a single comment decoration for the first node but instead creates it for all of them
**Current**
**FIx**
=> Show single comment count for multi line paragraphs

components/common/BoardEditor/focalboard/src/components/properties/user/user.tsx, components/common/UserDisplay.tsx
=> UI Tweak: add spacing and smaller avatar in focalboard

components/common/HexagonalAvatarMask.tsx
the SVG was causing an extra 10 px or so of whitespace, causing scrollbars to appear on every page:
=> fix extra margin on pages caused by hexagon svg

lib/pages/__tests__/mapPageTree.spec.ts, lib/pages/interfaces.ts, lib/pages/mapPageTree.ts, lib/pages/modifyChildPages.ts, lib/pages/server/__tests__/resolvePageTree_v2.spec.ts, lib/pages/server/resolvePageTree.ts, testing/generate-stubs.ts
Fixes the issue where we were getting "Cannot read properties of undefined (reading 'parentId')" we were getting on page deletion related endpoints
=> Fix the parentId of null error

package-lock.json, package.json
I don't think that we'll get DB tracing for free ( I think we have to set up a library called OpenTelemetry), but this version is at least a requirement to set it up: https://www.prisma.io/docs/concepts/components/prisma-client/opentelemetry-tracing
=> upgrade prisma to support db tracing

components/profile/components/UserPathModal.tsx
The edit mode input of user profile was not showing the /u/ prefix, which led to confusion about which url a user mentioned they were having trouble editing
**Before**
**After**
=> Add /u/ prefix in edit mode of user profile link

components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/CharmEditor/CharmEditor.tsx, hooks/usePageActionDisplay.tsx
I think I helped originally hide this on mobile because it would pop up automatically and hide the content at first. This allows users to open the comment sidebar from the context menu.
=> Enable viewing votes and comments on mobile

components/[pageId]/DocumentPage/components/PageTitleInput.tsx, components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
I may have missed some places, I intentionally left alone text inputs for new content where the user probably does want to type (like adding a row to a database).
Places fixed:
- the comments input when opening a database card
- the page title input
=> disable auto-focus on touch screen devices because it pops the keyboard

components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx, components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx, components/common/PageLayout/components/Sidebar/Sidebar.tsx, components/settings/roles/components/RoleMemberRow.tsx
On IOS, if CSS triggers a change to the the opacity/display of a pseudo-element or child element, then it treats the first click as a hover event instead, requiring user to click the link twice. This update disables the hover effect and just displays the "..." all the time when possible (discussed w/Chris).
Here's more info: https://css-tricks.com/annoying-mobile-double-tap-link-issue/
=> fix double-click behavior on ios browsers for hover events

components/votes/components/NewProposalButton.tsx
Usability fixes for permissions
- Disable create proposal button if new page creation is disabled
- TODO: Don't allow admin override in editing proposal content (They can still delete a proposal and toggle it public)
=> Disable new proposals button if user cannot create pages

__integration-tests__/server/pages/api/pages/[id]/index.spec.ts, components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx, components/bounties/components/BountiesKanbanView.tsx, components/common/PageDialog/hooks/usePageDialog.tsx, components/share/PublicPage.tsx, pages/api/pages/[id]/index.ts
I needed to add the 'PageDialogProvider' around the public page component. The methods from `usePageDialog()` just silently fail without it (the methods values are no-ops). We could just put it inside _app so it's always there, but I didn't because it relies on Comments and Votes providers which are added in PageLayout.tsx, and I'd have to move those into _app as well.
=> fix popup modal for public pages

.ebextensions/00_env_vars.config, docker-compose.yml
adding COMPOSE_PROFILE env variable and specified profiles of which service to run when running a specific profile. This should allow us to easily turn on/off datadog agent
=> turning off datadog agent using compose profile

components/common/CharmEditor/components/mention/components/Mention.tsx, components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx, components/common/Link.tsx, components/common/PageLayout/components/PageIcon.tsx
Tested with Nested pages and Mentions, using custom icon and default page svg icons:
After fix:
This was before (the mentioned page on the first line is vertically offset):
=> fix styling for nested pages and mentioned pages

components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx
Steps to reproduce:
1. Click on page icon on left sidebar
2. Once the emoji picker opens up click anywhere outside of it
3. You will be redirected to that page
corresponding [Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=8bacf788-2899-4d78-b56f-b65b526300b1)
=> Fixed clicking outside emoji picker redirecting to page

lib/users/createUser.ts
Turned out `shortenHex` method does not use regular three dots `...` but `…` (U+2026) horizontal ellipsis character
=> Fix replacing dots with hyphen in user path

background/tasks/sendNotifications/sendNotifications.ts
please double-check my logic. If/when we start sending notifications out based on user timezone or preference, we'd want to make sure that we query for userId as well I think? This should not have any major effect today... (and wouldn't be the cause of Chris's issue getting duplicates)
=> include userId when looking for sent notifications

background/tasks/deleteArchivedPages/task.ts, background/tasks/sendNotifications/task.ts
Dunno if this was a mistake... but here's the doc on diff between count and gauge
https://docs.datadoghq.com/metrics/types/?tab=count
Gauge should be like, temperature, a measurement of a condition that exists between executions of a job. 
In this case, you're submitting the number of items you've processed after each cronjob. If you were to record, say, the total number of pages that the system has deleted since the dawn of time, then this can be a gauge.
=> converting the cronjob metrics to count

__integration-tests__/server/pages/api/pages/index.spec.ts, __integration-tests__/server/pages/api/proposals/from-template.spec.ts, __integration-tests__/server/pages/api/votes/[id]/index.spec.ts, __integration-tests__/server/pages/api/votes/index.spec.ts, components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx, components/common/PageLayout/components/Header/Header.tsx, components/votes/components/NewProposalButton.tsx, lib/permissions/meta/__tests__/getTemplateExplanation.spec.ts, lib/permissions/pages/available-page-permissions.class.ts, lib/permissions/pages/page-permission-mapping.ts, lib/permissions/spaces/mapping.ts, lib/votes/__tests__/deleteVote.spec.ts, lib/votes/__tests__/updateVote.spec.ts, lib/votes/deleteVote.ts, lib/votes/updateVote.ts, pages/api/pages/index.ts, pages/api/proposals/from-template.ts, pages/api/votes/[id]/index.ts, pages/api/votes/index.ts, prisma/migrations/20220922184953_add_create_poll_operation/migration.sql, prisma/schema.prisma
This PR moves the use of space permission "createVote" to be used for the creation of proposals
It adds a "create poll" ability at the page permission level so that inline poll creation depends on your access level to that page
For proposals, only proposal editors can create polls
=> Rationalise permissions

scripts/seedTestPages.ts, testing/__tests__/generateBoard.spec.ts, testing/generate-board-stub.ts, testing/generate-page-stub.ts, testing/setupDatabase.ts
This pull request allows us to generate an arbitrary number of pages with actual page content inside a space.
We can also generate X amount of boards each containing X amount of cards.
This will come in very handy for performance testing.
To use this, run one of the 3 scripts in scripts/seedTestPages.ts
Nifty feature, you can pass a "nestedPercent" parameter to the seedTestPages fn so that X percent of pages have a parent page.
=> Seed pages

lib/proposal/createProposal.ts, lib/proposal/syncProposalPermissions.ts
Removes extraneous call to prisma when new proposals are created
=> Remove unneeded prisma pages call by adding isNew flag

components/[pageId]/BoardPage/BoardPage.tsx, lib/browser.ts, lib/utilities/strings.ts
This PR resolves a bug where navigating using browser front / back history to a board page  where the card had been opened would cause a fatal error preventing navigation.
The source issue was due to wrongly setting the browser history in a non Next.js compliant format
=> Allow navigating backwards

lib/session/config.ts, pages/api/discord/callback.ts, pages/api/profile/index.ts, pages/api/session/login.ts
We only need to know the user id from the session state. I'd rename req.session.user.id to req.session.userId but that would invalidate all existing sessions, I think, and i'd rather not support two formats...
Storing and using other user data on the session has presented two separate issues int he past:
1) the session is not updated (we'd ideally re-query the user on every request)
2) the data from relational tables was so large we couldn't set the cookie, and users could not log in
=> More explicitly store only user id in session cookies

components/common/PageDialog/PageDialog.tsx
We can't use window.location for page link as this will just link to the main page you're on
=> fix page link when copying from modal

components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.tsx
For some reason, the a wrapped link with a prevent default & react-dnd library & Firefox don't go well with each other.
The onDrag works but onDrop does not.
I am making the assumption from what I've read in the issues column in react-dnd library, that onDrop is not working because the of the preventDefault.
This seems to be an issue just for Firefox.
=> Fix Firefox drag and drop for kanban card

components/common/TemplatesMenu/TemplatesMenu.tsx
Fix annoying warnings spamming console, related to templates menu list
=> Fix templates menu warnings

components/[pageId]/DocumentPage/components/BountyProperties/BountyProperties.tsx
TextField from MUI has an internal state to show the user his input when writing numbers in the input.
That means we don't need to handle a state that shows the value. Just need to show the first value the user sees when he opens the modal.
=> Remove 0 from the start of max submissions

components/common/BoardEditor/focalboard/src/components/calendar/fullCalendar.tsx
Upon further investigation I uncovered this error: `Please import the top-level fullcalendar lib before attempting to import a plugin`.. This was a regression from the lint PR to sort imports
=> fix calendar views not appearing

charmClient/charmClient.ts, components/settings/contributors/InviteLinks/InviteLinks.tsx, components/settings/contributors/InviteLinks/InviteLinksTable.tsx, lib/invites/updateTokenGateRoles.ts, pages/api/invites/[id]/index.ts, pages/api/invites/[id]/roles.ts, pages/api/invites/index.ts, prisma/migrations/20221007084158_invite_links_role/migration.sql, prisma/schema.prisma
This PR allows us to assign roles to private links, just like we do for token gates. You can select the roles that you want to assign, and when any user joins the workspace via that invite link they will automatically get assigned those roles.
=> Support assigned user roles on private invite links

lib/proposal/__tests__/getProposalTasks.spec.ts, lib/proposal/__tests__/getProposalTasksFromWorkspaceEvents.spec.ts, lib/proposal/__tests__/syncProposalPermissions.spec.ts, lib/proposal/getProposalTasks.ts, testing/setupDatabase.ts
I noticed that a new proposal event was showing up at the very bottom of my tasks. After reading the code, I figured out it's because we were never matching workspace events to the proposals, which are used for sorting.
One change I introduced is that we require at least one workspace event for proposals to appear. I think since we create an event whenver a proposal is created, this is good enough. Proposals prior to ~September won't appear, but they never had an event to trigger them anyway. We could backfill with 'created proposal' events but I don't think anyone but CharmVerse people would notice.
=> fix datetimes for proposal tasks

components/settings/invites/components/InviteLinks/InviteLinks.tsx, components/settings/invites/components/TokenGates/TokenGates.tsx
Fix for a console warning from React:
Warning: React does not recognize the `anchorEl` prop on a DOM element.
Looks like it is not a good idea to spread all the bindPopover props on a mui Modal. It also includes anchorEl and the Modal does not accept that prop.
=> Small fix - invites modal

components/common/TokenGateForm/JoinDynamicSpaceForm.tsx
Previously when the autocomplete textinput was out of focus, it was cleared. Thus the user had to write the workspace name again, which lead to suboptimal ux
=> Stop clearing input in join space autocomplete

components/proposals/components/ProposalStepper.tsx
This was requested by product team. Tooltips help users understand the flow even if they can't jump to a particular step
=> make tooltips always visible in proposal stepper

components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSidebar.tsx, components/common/BoardEditor/focalboard/src/store/boards.ts
For some reason, ClickAwayListener is causing the CenterPanel component to re-render all the time. We can fix this by disabling the mouseEvent that gets triggered, and I wonder if there's something going on w/CenterPanel that we could also fix..
=> disable click listener on sidebar when its invisible

components/common/BoardEditor/focalboard/src/components/viewHeader/newCardButton.tsx, components/votes/components/NewProposalButton.tsx, theme/index.ts
Using MUI styles for the button UX: https://mui.com/material-ui/api/button-group/
=> Make entire area of new proposal button clickable

pages/[domain]/[pageId].tsx
I think at some point we stopped returning 'deletedAt' pages into usePages() context, and this broke the single-page view of a deleted page (it would just appear white). I am not sure why we checked for pageId in the first place, but the EditorPage component can handle missing pages (404) already.
=> enable deleted page to be viewed

theme/lit-protocol/lit-protocol.scss
=> fix background of lit protocol dropdown in dark mode

pages/[domain]/index.tsx
The bug is that if you're on /<domain>/members, then go back to just /<domain>, we won't send you back to /members and we just send you to the first page in the workspace.
And out of scope, but it seems odd we have to maintain a whitelist at all. This was broken for /proposals too without anyone knowing.
=> include /members and /proposals pages as default redirect page

__integration-tests__/server/pages/api/notion/import.spec.ts, components/common/Button.tsx, components/settings/workspace/ImportNotionWorkspace.tsx, lib/middleware/requireSpaceMembership.ts, pages/api/notion/import.ts
Security feature requested by a user in Discord.
This PR also adds a new 'disabledTooltip' prop to the Button component, which makes it easy to add a message. This adds the Tooltip component to all our buttons, if there's a performance issue we could optimize it later.
=> Disable notion import for non-admins

components/common/Button.tsx
This addresses some funny UI when wrapping buttons w/a span tag, for exmaple with ButtonGroup:
It also addresses a warning from the tooltip when disabledTooltip is undefined and disabled = true
=> dont always wrap buttons in a tooltip

adapters/redis/redisClient.ts
I'm still getting lots of connection errors. This PR fixes that:
```
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379
Redis Client Error Error: connect ECONNREFUSED ::1:6379 …
```
=> dont create redis client if redis_uri is not set

lib/users/mergeUserDiscordAccounts.ts, pages/api/discord/connect.ts, pages/api/email-templates/index.ts, pages/api/spaces/[id]/members/index.ts, prisma/migrations/20221025120519_user_deleted_at_field/migration.sql, prisma/schema.prisma
Worked on this ticket: https://app.charmverse.io/charmverse/page-09977184042575171
The issue was that if a user previously created an account using discord oauth and would try to sync their discord with another account, they were prompted with an error.
This features allows to merge the two accounts in a non-blocking flow.
I had to create a migration to add the `deletedAt` field on the `User` table, I'm using it to soft delete the old user account.
=> Feat - better discord account association

components/[pageId]/EditorPage/EditorPage.tsx, components/common/PageLayout/components/Header/Header.tsx, components/common/PageLayout/components/Header/components/EditingModeToggle.tsx
Fixes two cases:
- when de-registering the EditorPage component, we would set editMode to null. I don't fully understand why 'editMode' would be still defined in EditorPage, but setting it again seems to fix it back to the correct state. I could reproduce this 50% of the time with Next.js hot-reloading.
- we get the 'default' page permissions at first and we set mode to Viewing. Because mode is set, we never update it to Editing. I just added a wait for the pages to be loaded
=> fix toggle for edit mode disappearing

.eslintrc.json, components/WebSocketTester.tsx, components/[pageId]/DocumentPage/components/BountyProperties/components/MissingPagePermissions.tsx, components/common/CharmEditor/components/iframe/IFrameSelector.tsx, components/common/CharmEditor/components/inlineComment/inlineComment.components.tsx, components/common/ImageSelector/ImageSelector.tsx, components/common/PageLayout/components/SearchInWorkspaceModal.tsx, components/common/PdfSelector/PdfSelector.tsx, components/members/components/MemberDirectoryProperties/MemberPropertySelectInput.tsx, components/proposals/components/ProposalStepper.tsx, components/settings/roles/components/RoleRow.tsx, components/settings/roles/components/SpacePermissions/components/DefaultPagePermissions.tsx, components/settings/roles/components/SpacePermissions/components/PermissionConfigurationMode.tsx, components/settings/workspace/ImportNotionWorkspace.tsx
For some reason our eslint setup did not warn about missing `key` prop for children arrays. This is one of basic good react practises so I think it is worth to add it.
This pr adds eslint rule + fixes all the places where keys were missing.
=> Fix react key property

components/integrations/components/IdentityProviders.tsx, pages/api/discord/connect.ts, pages/api/telegram/connect.ts
Stop overriding username and avatar on connecting with telegram or discord.
=> Stop overriding identity type, username and avatar on other integrations

pages/api/permissions/index.ts
The default timeout is 5 seconds. I tested on our workspace and it is almost taking 5 seconds to respond, and sometimes erroring out so I want to try extending that timeout.
=> increase timeout for page permissions

background/tasks/sendNotifications/sendNotifications.ts, lib/discussion/__tests__/getDiscussionTasks.spec.ts, lib/discussion/getDiscussionTasks.ts, scripts/sendNotifications.ts
Found the issue:
If a comment had more then 1 blockNode because of the for loop it was doubled in the comments array.
Also if the prisma transactions fails, the email will not be sent.
Added a test to be sure if the code changes in the future not to forget about this.
=> Fix duplicate comments

lib/metrics/mixpanel/utilsSignup.ts
Removes a leftover parser for signup campaign. Since the clients set this value as-is, we don't need extra parsing
=> Send through signup campaign

components/common/PageLayout/components/Sidebar/Sidebar.tsx
Change sidebar from "Settings & Members" to "Settings" since we already have Member Directory and Invite Members on the Sidebar.
=> Update Sidebar.tsx to remove Members from Settings & Members

components/members/components/AddMemberPropertyButton.tsx, components/members/components/MemberDirectoryProperties/MemberPropertiesSidebar.tsx, components/members/components/MemberDirectoryProperties/MemberPropertyItem.tsx, components/members/components/MemberDirectoryProperties/MemberPropertyVisibility.tsx, hooks/useMemberPropertyValues.ts, lib/members/constants.ts, lib/members/deleteMemberProperty.ts, lib/members/generateDefaultPropertiesInput.ts, lib/members/updateMemberPropertyVisibility.ts
having a single map for all member types prevents duplication of configs, and makes the checks faster since we aren't constantly looking for matches in a list
=> update member properties config

components/common/BoardEditor/focalboard/src/components/properties/dateRange/dateRange.scss, components/common/BoardEditor/focalboard/src/components/table/table.scss
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=44c79006-57dd-4e78-808f-b21ae0323b8c&cardId=4c086e40-ceab-4ea5-be8e-9184b2edf64f
=> fix: make date editable from table view

components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyApplicantTableRow.tsx, components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyPaymentButton.tsx, components/bounties/components/MultiPaymentModal.tsx, hooks/useGnosisPayment.ts, hooks/useMultiBountyPayment.ts, lib/payment-methods/defaultPaymentMethods.ts
I noticed the transaction URL is invalid, but not sure if it's because that I was using Goerli testnet: https://goerli.etherscan.io/tx/0x4439dc2f8f12b73a7bad020100605c701e8f0ae85ba4c1191f7c11b8e682738c. The transaction was executed on my gnosis safe fine. Gnosis also was unable to 'decode' the transaction, so I am not 100% confident in how I did it.
References:
- how to send a POAP thru Gnosis
https://ethereum.stackexchange.com/questions/138352/transfer-poap-erc-721-out-of-gnosis-safe-via-sdk
- how to use ethers to generate a call to a contract method
https://github.com/ethers-io/ethers.js/issues/478
=> Allow non-native tokens thru Gnosis safe

background/tasks/sendNotifications/sendNotifications.ts
The problem was that when I was sending the emails I didn't register the notification in the userNotifications table.
=> Fix bounty sending emails all the time

components/bounties/components/MultiPaymentButton.tsx, components/bounties/components/MultiPaymentModal.tsx, hooks/useGnosisPayment.ts, hooks/useMultiBountyPayment.ts
An error is occurring inside the MultiPaymentModal component after a payment is made:
https://www.loom.com/share/83dad81337584e38a0ed02d6bd53080e
This fix addresses two issues:
1) we were creating a map of transactions based on 'applicationId'. I think it was somehow out of sync the the state of bounties, and so when we looked up the transaction, it was undefined
2) I noticed we were assuming the first gnosis safe in the payment button's onPaymentSuccess handler, which also is run/used when you pay from a single bounty. This is now fixed
=> Fix for Gnosis safes + bounties

components/profile/components/SpacesMemberDetails/components/SpaceDetailsAccordion.tsx
This PR handles three lightweight tasks.
[Replace N/A in Gallery View by not showing the property at all](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=c93d339d-ce33-4d49-b3e9-57e3ab946f03)
[Change N/A in Member Directory to " - " in table](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=846cdc45-b984-49cc-9b12-9b176e47eab6)
[Do not show N/A fields on a users profile](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=58684028-28f9-469b-8373-0eb2ab9eda07)
=> Handle N/A and empty fields for member directory

components/nexus/components/NexusSidebar.tsx
I applied a fix for hiding the scrollbar in the sidebar that was not being used in the Nexus page (I needed to apply the same fix to a higher-level  component). The CSS hides the scrollbar, but the area is still scrollable/swipable.
See loom: https://www.loom.com/share/b62191ca98274e2bb37dbed3f0cabb65
=> hide scrollbar on nexus sidebar

components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.scss, components/common/BoardEditor/focalboard/src/components/kanban/kanban.tsx, components/common/BoardEditor/focalboard/src/components/kanban/kanbanCard.scss, components/common/BoardEditor/focalboard/src/components/table/tableRow.scss, next.base.js, package-lock.json, package.json
We were forced to double click links to navigate elsewhere to the app inside iOS.
The specific issue came from a component inside Kanban.tsx that was preventing click events being propagated
=> Fix double click issue on iOS

lib/members/createMemberPropertyPermission.ts, prisma/schema.prisma, scripts/addJoinDateMemberDirectoryProperty.ts, scripts/reorderMemberDirectoryProperties.ts, scripts/updateBioProperty.ts
- Be more explicit about first member property
- Rename an array in our schema to 'memberProperties'. This doesn't affect the DB
=> Fix script to add join date

components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, package-lock.json, package.json
Don't open dropdown if the page is a card
https://app.charmverse.io/charmverse/page-2438463783291298.
I also added the package.json name to not accidentally commit a name in package-lock.json
=> Keep tree closed when card is open

components/common/CharmEditor/components/iframe/IFrameSelector.tsx, components/common/CharmEditor/components/iframe/IframeComponent.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/embed.tsx, package-lock.json, package.json
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=44c79006-57dd-4e78-808f-b21ae0323b8c&cardId=bd01584a-09f2-45e3-a887-0b00538940f2
Material UI does not have a Figma Icon. I used Feather icons via [React Icons](https://react-icons.github.io/react-icons).
=> Sshrayber figma

lib/gnosis/gnosis.ts
Now that wallets are stored in lowercase, we need to convert to checksum when requesting them on Gnosis. the wallets on 'gnosis safes' are in their checksum format, so we shouldn't need to mess with casing in that table.
I tested this with the example address, both the checksum and lowercase and get an error when requesting lowercase
=> convert user wallet address to checksum when querying gnosis

components/profile/components/SpacesMemberDetails/components/SpaceDetailsAccordion.tsx
here's the property JSON that had 'null' for value:
```
{
"memberPropertyId": "3af1d898-e8e5-45ab-a5df-247f1221997b",
"spaceId": "db74b5db-c1f2-4ac5-b5f7-28ee98a9075b",
"type": "multiselect",
"name": "test",
"value": null,
"options": [
{
"id": "17c40e3a-8742-47bb-8e87-406e7babcb30",
"name": "foo",
"color": "orange",
"index": 0
},
{
"id": "8a4b56f4-40c0-4914-9a00-ca54bc14e5b7",
"name": "bar",
"color": "blue",
"index": 1
},
{
"id": "73ca8f4c-962b-495f-b97f-0ab1148a8fdd",
"name": "yes",
"color": "turquoise",
"index": 2
}
],
"enabledViews": [
"gallery",
"table",
"profile"
]
}
```
=> fix check for member property on user profiles

components/common/ActionsMenu.tsx, components/common/BoardEditor/components/properties/SelectProperty/SelectProperty.tsx, components/common/BoardEditor/focalboard/src/widgets/menu/menu.scss, components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/BlockAligner.tsx, components/common/Emoji.tsx, components/common/Link.tsx, components/common/PrimaryButton.tsx, theme/focalboard/focalboard.main.scss
This might fix more issues with the iPhone. I noticed that nested pages use the Link component, and inside it has a hover CSS effect. I did a search for "&:hover" and added media queries to a lot more places.
It'd be nice if we found a solution that didn't require special queries on all hover effects!
=> add media query for link hover effects

components/common/form/fields/Select/SelectOptionItem.tsx
I made it so that the dots are always on top, even if they are overlapping... ideally, the dropdown should stretch itself based on content but i wanted Marek's input on how to do that...
=> allow editing long tags in multi-select

components/nexus/GnosisTasksList.tsx
Also fixes this bug where a 0 would display if no Gnosis safes were connected
=> Always show Gnosis even with 0 tasks

components/common/RouteGuard.tsx
'inherit' inherits the parent component's style, causing this span to have a 'block' display and which ultimately somehow prevented the scrollbar from appearing on the focalboard element with class 'full-page'. I think 'inline' should be safe, that is the original display rule for span tags
=> fix scrollbar css

components/common/CharmEditor/components/ResizableImage.tsx, components/common/CharmEditor/components/iframe/IframeComponent.tsx, components/common/CharmEditor/components/tweet/components/Tweet.tsx, components/common/ImageSelector/ImageSelector.tsx
I added a trash icon when u hover over Tweets, and also fixed it so that the delete action on other embeds removes the element completely, not just unset the source, which requires user to take a 2nd action to fully delete the embed
=> add a delete icon to Tweets and make deleting embeds easier

components/common/CharmEditor/components/@bangle.dev/tooltip/suggest-tooltip.ts, components/common/CharmEditor/components/emojiSuggest/emojiSuggest.plugins.ts
Sometimes when I'm on production and adding a comment either inline or in the comments list for cards, the entire editor blows up. In the dev console, I can see there's an error `e.getState(...) is undefined`. The code is minified, and I haven't been able to reproduce w/unminified code, but I downloaded the compiled code and think it is related to one of our prosemirror plugins trying to access state from a plugin key that is missing. For now, I'm attempting to fix the issue by checking that the return of getState() is not defined before accessing properties on it.
=> bug fix attempt: uncaught exception  while using inline charm editor

lib/guild-xyz/getGuildRoleIds.ts, lib/guild-xyz/server/updateGuildRolesForUser.ts, lib/websockets/documentEvents/documentEvents.ts
I'm looking into this error:
```
[guild.xyz]: Failed to import guild.xyz roles TypeError: Cannot read properties of undefined (reading 'map')
```
I checked all the code that happens inside the try/catch, and my only guess is that guild.xyz's api is sometimes not returning a field.
=> debugging guild.xyz api: check that roleids are returned

.github/workflows/test_and_deploy.yml
This reverts commit 89858ffed5d6c86b1ea7472fdf2848849299320e.
This commit contains the fix for client side Env Vars.
Websockets url temporarily commented out till we fix URL. (Will operate as it has been so far, single node, till then)
=> Fallback to default pages socket and enable UD

lib/prosemirror/__tests__/applyStepsToNode.spec.ts, lib/prosemirror/applyStepsToNode.ts, lib/websockets/documentEvents/documentEvents.ts, scripts/query.ts
I'm still trying to understand whath appened, but socker server started returning a 502 bad gateway and no one could load page content. 
This PR adds more logging, particularly userId so that i can see if issues are related to one person or not, it also adds a try/catch around the place that probably blew up the server so that doesn't happen again.
1) The most recent update was at 8am: https://github.com/charmverse/app.charmverse.io/pull/1324. This was just moving code around, nothing about the prosemirror schema should have changed.
2) Around 9:30am, I see a rapid increase (thousands) of logs saying "Ignore duplicate diff message from client"
3) Around 9:33-9:35am, I see about 20 errors "Error: Failed to apply step"
3) 9:35am - last log from websockets: "Argument where of type …
=> Make websockets more resiliant to errors

components/forum/components/ForumFilterList.tsx, components/forum/components/ForumFilterSelect.tsx
- add tooltip for disabled "Add category" button
- fix categories with back text in ff
- show 'all categories' in the mobile view selector
=> Category ui bug fixes

.env, lib/blockchain/provider/alchemy.ts
I was debugging Alchemy and noticed that their API has changed. "filters" is now "excludeFilters" when excluding spam from NFTs - it still seems to work, but not sure for how long: https://docs.alchemy.com/reference/getnfts.
I also fixed the env var name for Deep DAO. I changed it everywhere but in the default .env file.
=> update alchemy api and fix Deep Dao env var

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx
To reproduce the bug: highlight some tet in CharmEditor, create a comment. Now type some text in the comment input and try to highlight your comment. It crashes the page.
I think the issue is that the "inline palette" (aka slash command menu) is using a static plugin key. This broke the floating menu for inline comments. I removed the inline palette from comments (as well as text color) since it's unecessary.
I made another PR to pass the palette plugin key in dynamically: https://github.com/charmverse/app.charmverse.io/pull/1352
=> Fix floating menu in comments

components/common/CharmEditor/components/callout/callout.ts, components/common/CharmEditor/components/quote/quote.ts, components/common/CharmEditor/components/tabIndent.tsx
in order to carry attributes when copying prosemirror components, we have to make sure they are mapped in toDOM and parseDOM
=> copy emojis when copying callouts

components/common/CharmEditor/components/mention/components/MentionSuggest.tsx, lib/utilities/__tests__/strings.spec.ts, lib/utilities/strings.ts
Type "@(" into the charm editor to cause a crash. The "@" triggers the mention logic, and the "(" becomes invalid input to `String.match()`, the error is "SyntaxError: unterminated parenthetical".
=> sanitize inputs for mentions

components/common/CharmEditor/components/nft/NFTNodeView.tsx
The props for Opensea's embed are just confusing. even setting a 'width' triggers 'manual' orientation mode. And you can't actually set 'maxWidth' even though it is a prop on Typescript. I just found that this combination works well enough.
preview:
=> make opensea embed look decent inside of column

package-lock.json
running `npx tsc` locally for typechecking throws 5 typescript errors. Turned out npm lock was not updated correctly, and npm installed typescipt v4.7.4 instead of 4.9.4.
With this + `npm i` all errors are gone.
=> Fix typescript version

components/settings/roles/components/SpacePermissions/components/DefaultPagePermissions.tsx, lib/permissions/pages/page-permission-interfaces.ts, lib/spaces/__tests__/setSpaceDefaultPagePermission.spec.ts, lib/spaces/setSpaceDefaultPagePermission.ts
Prevents space page permissions preset from being proposal editor or custom
Also filters out proposal editor option in the page permissions UI
=> Remove proposal editor as an option in default page permission presets

theme/lit-protocol/lit-protocol.scss
Alex asked to remove this because the search is not very good
=> hide nft search inside of Lit modal

components/common/TokenGateForm/TokenGateForm.tsx
Fixes a small issue, where visiting a Token Gate form you can't pass through would give a mysterious "Verification Failed" message, which wasn't great UX
=> Don't show the error message since user already has visual feedback

charmClient/apis/blockchainApi.ts, components/profile/components/IdentityModal.tsx, components/profile/components/Integration.tsx, components/profile/components/UserDetails/UserDetails.tsx, hooks/useMembers.tsx, lib/blockchain/__tests__/refreshENSName.spec.ts, lib/blockchain/getENSName.ts, lib/blockchain/refreshENSName.ts, lib/session/config.ts, lib/users/__tests__/createUser.spec.ts, lib/users/__tests__/updateUsedIdentity.spec.ts, lib/users/createUser.ts, lib/users/updateUsedIdentity.ts, lib/utilities/__tests__/strings.spec.ts, lib/utilities/strings.ts, models/User.ts, pages/api/google/disconnect-account.ts, pages/api/nft/refresh-ensname.ts, pages/api/profile/add-wallets.ts, pages/api/profile/index.ts, pages/api/telegram/disconnect.ts, prisma/migrations/20221226132047_add_wallet_ensname/migration.sql, prisma/schema.prisma, scripts/updateUserIdentity.ts, testing/__tests__/generateStubs.spec.ts, testing/generate-stubs.ts
This PR adds some cleanup for ENS and identity selection
- User can trigger manual refresh of their wallet address, to fetch the ENS Name.
- We don't lookup ENS anymore when you switch identities, this removes the long delay when switching to wallet identity
- When adding a user wallet to an existing account, or creating a new account, we refresh their ENS
- We now always save the exact wallet address as username to the back-end. Responsibility for shortening the address is done in presentation layer (so we can always match the username to a wallet address they are allowed to have)
- Also added "secondary" username concept, so the selector modal shows more details as tooltip for each ID ( address for ENS name, email for Google, and username + discriminator number for Discord)
=> Persist ens

components/common/CharmEditor/components/Resizable/HorizontalResizer.tsx
According to Andy, videos used to auto-adjust their height when added to columns. I did change the component that handles youtube embeds when we added Mux from 'iframe' to 'video', but I checked that PR and it looks like I kept all the same logic... 
anyways, I tested this with image embeds as well which also uses Resizable component.
=> fix auto adjustment of height for embeds

pages/api/pages/import/[spaceId]/zipped.ts
I made some updates to make it work for the user zip that was shared with us: https://app.charmverse.io/charmverse/page-21850517986912954
- handles upload of larger zip files. `req.on('end')` was not working but I found a solution here: https://stackoverflow.com/questions/70084915/proxy-pass-multipart-in-nextjsalso-nodejs
- exclude the mirror files that MACOSX creates (these are present in the user's sample zip and were crashing the import, since the content included some weird characters. I found this SO post about the error: https://stackoverflow.com/questions/1347646/postgres-error-on-insert-error-invalid-byte-sequence-for-encoding-utf8-0x0). I wonder if there's a more robust approach than excluding files that start with "." :)
=> Improvements to markdown import

lib/discord/__tests__/disconnectDiscordAccount.spec.ts, lib/discord/disconnectDiscordAccount.ts, lib/google/__tests__/disconnectGoogleAccount.spec.ts, lib/google/connectGoogleAccount.ts, lib/google/disconnectGoogleAccount.ts, lib/users/__tests__/softDeleteUserWithoutConnectableIdentities.spec.ts, lib/users/mergeUserDiscordAccounts.ts, lib/users/softDeleteUserWithoutConnectableIdentities.ts
Deleting a user for an action they take which isn't 'delete my account' is a dangerous side-effect. It might be the cause of a recent issue we had with a user who could not log in (I think because he was marked 'deleted').
The original purpose of deletedAt is for when we need to delete a user that is not the one logged in. Instead of soft delete, the UI could just either prevent users from disconnecting too many accounts. If they somehow manage to get past that, it's not the end of the world to have no connected accounts, they can still connect another one.
This PR also adds the new 'softDelete' logic for discord auth
=> Dont delete user that's logged in

components/[pageId]/DocumentPage/components/CommentsSidebar.tsx, components/common/CharmEditor/CharmEditor.tsx
Users have been trained that comments are always sorted by position. Discord discussion: https://discord.com/channels/894960387743698944/1016422398964269076/1059582305770950756
Anyway, it's good to have less options + simpler UI and if people really want more features, they can ask for it :)
=> remove sort options on comments sidebar

charmClient/apis/iframelyApi.ts, components/common/CharmEditor/components/bookmark/BookmarkNodeView.tsx
This example does'nt return HTML and is not supported when you try it on iframely:
https://www.meti.go.jp/english/press/2022/0715_002.html
Iframely link: https://iframely.com/try?url=https://www.meti.go.jp/english/press/2022/0715_002.html
Good news is we still get metadata
=> show embeds when iframely cannot generate html

components/[pageId]/DocumentPage/components/BountyProperties/components/BountySignupButton.tsx, components/common/DiscordGate/hooks/useDiscordGate.ts, components/common/TokenGateForm/TokenGateForm.tsx, components/invite/InviteLinkPage.tsx, components/login/Login.tsx, components/nexus/components/NexusPageTitle.tsx, hooks/useUser.tsx, hooks/useWeb3AuthSig.tsx, pages/_app.tsx
Key change: Put useUser above instead of below the useWeb3AuthSig hook in the dependency hierarchy
If user switches to a wallet that has signed with CharmVerse before, switch accounts
If new wallet, logout user entirely
=> Simplify useUser and implement logout on wallet switch

components/common/CharmEditor/components/fiduswriter/state_plugins/collab_carets.ts, components/common/CharmEditor/components/floatingMenu/floatingMenu.plugins.ts, components/common/CharmEditor/components/rowActions/rowActions.ts
This brings back the call to the selection tooltip update, but checks the state from row-action before calling it...
Some inspiration came from https://github.com/ProseMirror/prosemirror/issues/587
=> Highlighting text with keyboard doesn't show floating menu v2

components/common/Emoji.tsx, lib/utilities/browser.ts
Use system font for iOS/iPhone but also change the CDN since Twitter dropped support: https://github.com/twitter/twemoji/issues/580
=> hot fix for icons in all safari os

components/common/BoardEditor/FocalBoardProvider.tsx, components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx, components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx, components/common/TreeItemContent.tsx
This is a cleanup of how we scroll to the correct page on first load. Will result in more accurate sidebar :)
- I think we can get rid of the local storage solution to remember the scroll position of sidebar - this was probably due to the page remounting all the time?
- I moved the scroll logic down and removed some DOM queries (these are really expensive compared to regular JS, and were running on every render!)
=> simplify logic to show menu item in sidebar

lib/middleware/onError.ts, lib/utilities/errors/errors.ts
now you can log (err.stack) in the `onError` middleware, for example, and see where in the code the error was thrown
=> extend Error class to include stack traces

components/common/BoardEditor/focalboard/src/components/dialog.tsx, components/common/PageActions.tsx, components/common/PageDialog/PageDialog.tsx
This PR relocates the close button to the right of the dialog, and actually shows it
=> Standardise the close button UI to the right on dialogs

hooks/useWeb3AuthSig.tsx
I think we've introduced a new Discord login bug:
1) connect a web3 account to CV. (Don't verify wallet).
2) connect to Discord/Google
You will see a flash of content and be logged in automatically. This doesn't seem to happen if you've verified your wallet though - I'm assuming based on the code, however, that we would log you into the other metamask wallet if we have it verified, which is also not what the user wants
=> try to fix log in thru discord

pages/[domain]/settings/workspace.tsx
When visitng the space settings directly, the `space` data is not available right away, resulting in a blank form at first:
=> make sure to load space data in settings page

components/common/CharmEditor/components/inlineComment/inlineComment.components.tsx
Also sets max-width so that the comment input doesn't fall off the screen (for some reason, 100% width doesn't work so I used 100vw)
=> focus comment input on mobile

hooks/useWebSocketClient.tsx
It doesn't appear that we were getting two connections w/the space-wide socket server (I would expect the 'connect' event to trigger twice) the way we were with the namespaced one for "/ceditor", but the call to .connect() is also unnecessary. 
In VS Code, when I hover over connect(), this is the example they give for its usage (where you set autoConnect: false):
=> dont call connect() when connecting to space sockets

__integration-tests__/server/pages/api/v1/spaces/index.spec.ts, lib/middleware/onError.ts, lib/public-api/createWorkspaceApi.ts, lib/public-api/interfaces.ts, pages/api-docs.tsx, pages/api/v1/spaces/index.ts, prisma/migrations/20230113193547_add_xpsengine_to_space/migration.sql, prisma/schema.prisma
We need to keep track of the unique id from Game7 (XPS Engine) when they create a workspace. The admin will also have a wallet address instead of a discord user id, which still needs to be supported but my thought was to update the api docs so they could see it
=> Xps engine - update to create a workspace 

components/common/RouteGuard.tsx, components/settings/workspace/ImportNotionWorkspace.tsx, lib/utilities/browser.ts, pages/_app.tsx, pages/_document.tsx
Based on trial-and-error, I think the errors are related to our usage of `router.isReady` to determine how to render components, which Next.js says not to do. I added this logic [12 months](https://github.com/charmverse/app.charmverse.io/commit/85bac433b4121e3fb87c87281e545acf444652f8#diff-a9827ce1be32c607c948881a89b99c592f752898f9c49e0dea0b7199eb151029R67) ago when I was first building the app, but it basically means we don't do any rendering on the server! My comment was about hiding components until the space is known, but all our components seem to handle it gracefully.
https://nextjs.org/docs/api-reference/next/router
> isReady: boolean - Whether the router fields are updated client-side and ready for use. Should only be used inside of useEffect methods and not for conditionally …
=> Fix hydration error when running Next in dev mode

components/common/RouteGuard.tsx, components/settings/workspace/ImportNotionWorkspace.tsx, lib/utilities/browser.ts, pages/_app.tsx, pages/_document.tsx
Right now, the SSR html we are serving doesn't look like anything. With this update, we get closer to being able to server pre-rendered pages to the user. The updates are based on MUI's example: https://github.com/mui/material-ui/tree/332081eb5e5e107d915e3c70f92e430dc364048f/examples/nextjs-with-typescript
=> Add emotion styles to SSR pages

components/common/UserDisplay.tsx, hooks/useLocalStorage.tsx
We aren't supposed to use the `window` object except inside a useEffect(), the useLocalStorage hook violates that rule, and it seems to be causing havoc in the sidebar right now: the default is set to "open", and the user can't change the state/close the sidebar
The good news is we don't really use this hook (!) so i'm not worried about other regressions
Bug report:  https://discord.com/channels/894960387743698944/1065339867971731537/1065339867971731537
=> dont pull in defaults for local storage until after the first render

components/common/PageLayout/PageLayout.tsx, components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, config/constants.ts, hooks/useFocalboardViews.tsx, hooks/useLocalStorage.tsx
Turns out, we can't rely on local storage to define UI preferences because it's not available for SSR. I removed a check on 'window', but now the sidebar is always open by default at first, even if it's supposed to be closed.
So this change doesn't render the sidbar/nav at all until the first render, which is unfortunate but we could fix using cookies and getServerSideProps
=> set sidebar state before page renders

background/cron.ts
Temporary disablewebhooks on prod - we have shared sqs queue for prod and staging, so we do not want prod to consume test webhooks from collabland test api
=> Disable webhooks prod

components/common/BoardEditor/focalboard/src/components/dialog.tsx, components/common/BoardEditor/focalboard/src/components/viewSidebar/viewSourceOptions.tsx, components/common/CharmEditor/components/PageList.tsx, components/common/PageActions.tsx
When the sideview opens now, I get a cursor floating out in the middle of nowhere - if I start typing, it appears to be focused on the CharmEditor! This fixes what I'm seeing in Firefox:
=> improve database search + CSS tweaks

lib/notion/NotionImporter/NotionImporter.ts
Since the standard notion client logger logs multiple lines, we can't parse them in Datadog. Fortunately, according to their doc we can define a custom one https://www.npmjs.com/package/@notionhq/client/v/0.4.7
=> use custom logger with Notion client

prisma/migrations/20230119234413_add_missing_indices/migration.sql, prisma/schema.prisma
just db cleanup. Ideally, every query we make is hitting an index. And indices on things like posts are an easy trade-off since they spend most of their time being read not written (which is more expensive with indices).
=> add missing indices

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/@bangle.dev/base-components/image.ts, components/common/CharmEditor/components/Resizable/HorizontalResizer.tsx, components/common/CharmEditor/components/Resizable/Resizable.tsx, components/common/CharmEditor/components/Resizable/VerticalResizer.tsx, components/common/CharmEditor/components/ResizableImage.tsx, components/common/CharmEditor/components/ResizablePDF.tsx, components/common/CharmEditor/components/common/MediaUrlInput.tsx, components/common/CharmEditor/components/fiduswriter/collab/doc.ts, components/common/CharmEditor/components/iframe/IframeComponent.tsx, components/common/CharmEditor/components/iframe/__tests__/utils.spec.ts, components/common/CharmEditor/components/iframe/iframe.ts, components/common/CharmEditor/components/iframe/iframeSpec.ts, components/common/CharmEditor/components/iframe/utils.ts, components/common/CharmEditor/components/inlinePalette/editorItems/database.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/media.tsx, components/common/CharmEditor/components/nodeView/nodeView.ts, components/common/CharmEditor/components/video/VideoNodeView.tsx, components/common/CharmEditor/components/video/video.ts, components/common/CharmEditor/specs/embeddedNodeSpec.ts, hooks/useLocalStorage.tsx, theme/@bangle.dev/styles.scss
- smoother resizing of sizes
- allow users to resize width of iframe
- smarter parsing for width/height attributes from pasted code
- add an "Embed" and "Link" tabs when inputting a iframe src, however we wanted to support embed codes no matter which tab you use - this is just a trick to educate users that they can use embed codes
=> CharmEditor Embed improvements

components/members/MemberDirectoryPage.tsx, components/members/components/MemberDirectoryGalleryView.tsx, components/members/components/MemberDirectoryProperties/MemberPropertiesSidebar.tsx, components/members/components/MemberDirectoryProperties/MemberPropertyItem.tsx, components/members/components/MemberDirectoryProperties/MemberPropertySidebarDetails.tsx, components/profile/components/UserDetails/SocialIcons.tsx, lib/members/constants.ts, prisma/migrations/20230124032856_add_social_member_type/migration.sql, prisma/schema.prisma, scripts/migrations/2023_01_23_addMemberProperties.ts
This change requires a db migration, which was tested locally. Until it is run on a space, the two icons will not be visible
=> add options to hide github and linkedin icons

components/common/CharmEditor/components/floatingMenu/FloatingMenu.tsx, components/common/CharmEditor/components/inlinePalette/components/InlineCommandPalette.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/advancedBlocks.tsx, components/common/CharmEditor/components/inlinePalette/editorItems/text.tsx, components/common/CharmEditor/components/inlinePalette/paletteItem.ts
User was trying to highlight text and select "Link to Page" but it doesn't do anything in this context:
We currently have "Link to Page", "Divider", "Table" etc which make no sense when you are trying to change the type of a highlighted piece of text. The Link to page in particular was confusing for one user who just wanted to use the normal link
=> Remove some block options from floating menu

components/common/PageLayout/components/Header/components/utils/databasePageOptions.ts
In a csv, if a column had uuid's, I was assuming that the filed was type person.
We need to import any uuid as type text, not person.
=> Fix text as a uuid import from csv

components/[pageId]/DatabasePage/DatabasePage.tsx, components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx, components/common/BoardEditor/focalboard/src/store/index.ts, components/common/BoardEditor/focalboard/src/store/initialLoad.ts, components/common/BoardEditor/focalboard/src/store/loadingState.ts, components/common/Button.tsx, components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx, components/common/PageLayout/components/PageNavigation/PageNavigation.tsx
This fixes a few bugs related to state not getting updated properly when navigating between boards.
Fixes:
- when navigating from a databsae that had a source to one that doesn't, we wouldn't show the 'select a source' menu
- when navigating from a db with no source to one that has a source, we would briefly show the 'select a source' menu, because activeView was not set until a useEffect got triggered. Instead, I try to grab the first one from the board views if there are any
- it was not possible to create a new view on a linked inline db. (we'd constantly reset the current view to the first available - removing this logic doesnt seem to break anything, tested w/google forms too)
- in the views tabs, fixed the underline / tab indicator that animates into the first position when loading …
=> reset view settings state when navigating between databases

components/members/components/MemberDirectoryProperties/MemberPropertySidebarDetails.tsx
https://github.com/react-dnd/react-dnd/issues/1608
In Webkit, if the draggable element has a child of larger width/height, the 'drag preview' will expand to the max width/height. In Member Properties, this makes it appear you are dragging multiple rows, but really the fix was to just have the collapsed section unmounted until it needs to be expanded.
=> fix drag and drop of rows

components/common/PageLayout/components/PageIcon.tsx
Forgot to handle case for bounty and proposal page (due to local space not having any)
=> Add linked page arrow for bounty and proposal page

components/common/RouteGuard.tsx, pages/api/discord/callback.ts
We were unable to redirect a user, because a returnUrl was set with Japanese characters:
```
/henkaku-ochakai/forum/post/visionについて_ld9xxajl
```
I considered encoding the returnUrl when it was set, but I think this solution handles more cases.
=> encode url for redirect

components/[pageId]/DatabasePage/DatabasePage.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewTabs.tsx, components/common/PageLayout/components/AddNewCard.tsx, components/common/PageLayout/components/NewPageMenu.tsx, components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx, lib/middleware/onError.ts, pages/api/blocks/index.ts
- user could not close 'edit view menu' when clicking on a view tab to edit it, unless they selected an item in the menu
- clicking 'add page' or page action menu on the sidebar no longer navigates you to that page after clicking it
- made the card appear reliably when creating a new one inside a database from the sidebar
- we were not sending socket events at all when inserting focalboard blocks! I tested this out -if I make a new database page in one tab, the other tab will see it in the sidebar but there will be no content until I reload the page.
=> Some more UI fixes with dropdowns:

components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/PageLayout/components/AddNewCard.tsx
definitely need some tests in this area, as it's easy to get confused between 'activeboard' and 'board', i could use suggestions for a better name too. `activeBoard` is the one related to the data source, `board` could be thought of an organizational board of views, which  is the data source for non-linked boards
=> fix adding card to linked db

__e2e__/po/spaceSettings.po.ts, __e2e__/updateSpace.spec.ts, __integration-tests__/server/pages/api/spaces/[id]/index.spec.ts, lib/spaces/__tests__/updateSpace.spec.ts, lib/spaces/updateSpace.ts, pages/[domain]/settings/space.tsx, pages/api/spaces/[id]/index.ts
This pull request makes updating a space in space settings more reliable
- Extracted updateSpace from API to a lib method which only updates name, domain and spaceImage (also stops us sending arbitrary data from req.body straight to Prisma)
- Ensured the API and lib are resilient against inputs with additional unexpected values
- Added an e2e test for changing the space settings form
=> Update space tests

components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx, components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
User was trying to paste a URL into the table of an embedded DB, and it would either paste in the page document outside the table or jsut delete the table :(
https://www.loom.com/share/e24f7ea63e1841a1a02e252e4f4046d0
=> prevent paste commands from escaping database

components/common/CharmEditor/components/nestedPage/components/NestedPagesList.tsx
we shouldn't show certain types of pages in the link to page dropdown, ie ones that are embedded
=> filter pages in link to page

components/common/MobileDialog/MobileDialog.tsx, components/common/MobileDialog/MobileDialogTitle.tsx, components/common/Modal/Modal.tsx, components/common/PageLayout/components/Sidebar/SidebarSubmenu.tsx, components/common/PageLayout/components/Sidebar/Workspaces.tsx
I will need  dialog that will be reusable on mobile for different kinds of content. I made this reusable component + connected it with our current `Modal` for easy use. I added `mobileDialog` prop to our `Modal` and you can enable mobile behavior and animation with a single prop. Added example use to create sapce modals.
Note that `Modal` will work as it was for bigger screens.
https://user-images.githubusercontent.com/5198394/215264159-b3e13419-bb67-4a2d-a054-ec1f90f519b5.mp4
This is how it would look like if you pass `title` as `Modal` prop:
=> Mobile dialog

next.config.js
There are 2 situations that can lead the user to a 404 page
1. The last visited page of a user is [domain]/settings/workspace
2. A user goes to  [domain]/settings/ and is being redirected to  [domain]/settings/workspace
=> fix redirection to workspace page

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/PageTitleInput.tsx, components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx, components/common/CharmEditor/components/fiduswriter/collab/doc.ts, components/common/CharmEditor/components/floatingMenu/Menu.tsx, components/forum/components/PostList/components/PostSummary.tsx, components/forum/components/PostPage/PostPage.tsx, theme/@bangle.dev/styles.scss
I introduced this bug when I added a selection to the doc when we got the first handshake with web sockets... basically, the selection type was "all" by default.
I was trying to remove some weirdness where blocks would be highlighted by default, but a better fix was to disable focus on read-only content, and also simplify the focusOnInit logic for documents. It looks like Notion never applies focus on the document by default, just the page title if anything. I'd like to revisit the decision to put smart logic for autoFocus (aka focusOnInit) inside ReactEditor in the future
=> Bug fix: document selected by default causes unexpected behavior

components/common/CharmEditor/CharmEditor.tsx, package.json
One of my PR's failed in `deploy` job due to incorrect automatic merging with main. `focusOnInit` prop was duplicated in `CharmEditor`. I've checked for any other type issues, but found none.
=> Removed duplicate props from charmeditor

charmClient/charmClient.ts, components/profile/components/UserPathModal.tsx, pages/api/profile/check-path-availability.ts
if you clear out the profile path input, we'd still request the backend to check for pages, but the value would be undefined
=> fix error when searching for undefined profile path

components/common/CharmEditor/components/bookmark/BookmarkNodeView.tsx
Links in iframely were not clickable. Turned out it was because integration was missing their embed.js script as stated in: https://iframely.com/docs/react#add-embed-js-script
=> FIx bookmarks iframes, load iframely script

components/common/CharmEditor/components/iframe/IframeComponent.tsx
https://discord.com/channels/894960387743698944/1071053289166221403
Fix embeds crash due to breaking rule of hooks. I really think we should consider turning on eslint for that at some point of time :D
=> Fix embeds crash

__integration-tests__/server/pages/api/pages/[id]/index.spec.ts, components/[pageId]/DocumentPage/components/PageHeader.tsx, components/common/BoardEditor/focalboard/src/components/viewTitle.tsx, pages/api/pages/[id]/index.ts
Applied better readonly to top level page icon as well as the description page
=> Prevent updates to title, header image or icon by people who dont have edit_content permission

__e2e__/forum/commentOnForumPost.spec.ts, __e2e__/forum/editPost.spec.ts, __e2e__/po/forumPost.po.ts, components/forum/components/ForumVote.tsx, components/forum/components/PostPage/PostPage.tsx, components/forum/components/PostPage/components/PostComment.tsx, components/forum/hooks/usePostPermissions.ts
We have an ongoing issue where CharmEditor readonly mode cannot be changed once the editor mounts. It needs to be remounted with a fresh state.
I've updated usePostPermissions hook to undefined initially, so we can know it's loading in consumer components.
In the post page, I then added a loading and error state.
=> Fix issue of post not being editable on initial page load

__e2e__/po/signup.po.ts, components/common/CharmEditor/components/markdownParser/ImportZippedMarkdown.tsx, components/common/CreateSpaceForm/CreateSpaceForm.tsx, components/common/CreateSpaceForm/SelectNewSpaceTemplate.tsx, components/common/CreateSpaceForm/TemplateOption.tsx, components/common/TokenGateForm/JoinDynamicSpaceForm.tsx, lib/metrics/mixpanel/interfaces/UserEvent.ts, lib/spaces/__tests__/createWorkspace.spec.ts, lib/spaces/config.ts, lib/spaces/createWorkspace.ts, lib/spaces/getAvailableDomainName.ts, lib/spaces/utils.ts, lib/spaces/validateDomainName.ts
It was bothering me that the buttons on the Create Space template were less emphasized than the labels, and 'join' was so prominent. I think once we find some colored icons, we could make the 'Join a space' button grey as well to stand out less, it's the least likely option to be used.
I also did some cleanup. I left the important config (the enum of possible templates) in lib, but display-related config doesn't really need to be there, we need custom react components, etc. too so I just consolidated it as part of the form template
Before:
After:
=> clean up space templates UI

pages/_app.tsx, pages/_document.tsx, theme/createEmotionCache.ts
This is the config for caching the stylesheets gnerated by styled components. I'm not sure this is necessary.. but was looking at this code again for a performance bug, and one thing I noticed that I didn't copy from the original example I followed has the Document component (renders once no first page load) passing the cache to the App component (re-renders for every page). Seems useful https://github.com/mui/material-ui/tree/master/examples/nextjs
=> refine setup for emotion cache based on MUI

components/common/PageLayout/components/PageNavigation/PageNavigation.tsx, components/common/PageLayout/components/PageNavigation/components/TreeRoot.tsx
I noticed this in dev:
We are just passing this 'mutatePage' prop straight to the MUI 'TreeView' component, I think this was also just leftover from some refactor :)
=> remove mutatePage prop that is not valid but not used

theme/index.ts
The issue is IconButton is making emojis appear faded out when inside IconButton.
I see this effect even on MUI's website: https://mui.com/material-ui/react-button/ if you look at the first example under "Icon Button". Seems like an odd choice, and we sometimes use 'color=secondary' on the button that's wrapped which has a similar effect
=> use inherited color for default iconButton color

components/common/Modal/SettingsDialog.tsx
@mattcasey Last step of fixing space modal!
I noticed Members were still out of sync, but roles were fine. Upon further research, I understood.
The members depends on a global context. So even though we were setting useSpaceId locally, the useMembers hook was bound to global context and reading from global space.
I readded it below CurrentSpace and it works now.
Below are the global providers. MembersProvider is only provider it made sense to add, but please do double check.
For hooks which just return results (like useRoles) no work needed, they'll pick up the closest provided context.
=> Show correct members

components/nexus/BountyTasksList.tsx, components/nexus/DiscussionTasksList.tsx, components/nexus/ForumTasksList.tsx, components/nexus/ProposalTasksList.tsx, components/nexus/VoteTasksList.tsx
Clicking on a page link inside the Settings modal should close the modal. That way, the user will see the page he landed on.
=> Close dialog for vote

components/common/BoardEditor/focalboard/src/components/dialog.scss
We show the card before content is loaded, and it usually jumps full height once it is loaded. I think it's a better experience if we just use a fixed height. I also made the dialog be full height in mobile.
https://www.loom.com/share/354dbcbb67704b65864b7cee330218c0
=> Open cards full-height to avoid layout jumping

components/common/CharmEditor/components/ResizableImage.tsx
The error turned out to be some code in the image component that tries to upload binary image sources. In this case, it was an svg url which doesn't have binary data to convert. I was able to reproduce by copying the same content that Chris had mentioned:
=> Fix error when pasting SVG

components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetail.scss, components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx, components/common/BoardEditor/focalboard/src/widgets/TextInput.tsx, theme/focalboard/focalboard.main.scss
Previous issues
1. Didn't show ellipsis for long property names (only occurred in readonly mode)
2. Showed ellipsis for property values
Now (Note this is in read only mode)
=> Fix long property names and values

lib/spaces/interfaces.ts, lib/spaces/togglePublicBounties.ts
I removed the call to retrieve pages when updating bounties. Conceptually, it's nice, but it takes too long to resolve the whole page tree. I think it is extremely unlikely (knock on wood) that someone would be moving bounty cards around while someone else is toggling this setting in a way that would break permissions.
=> fix toggle for public bounties

__e2e__/po/settings/settings.po.ts, __e2e__/settings/notificationsRedirect.spec.ts, components/common/Modal/SettingsDialog.tsx, components/common/RouteGuard.tsx, components/nexus/TasksPage.tsx, hooks/useSettingsDialog.tsx, pages/nexus.tsx
we are still sending users to /nexus from notification emails:
```
const nexusDiscussionLink = `${charmverseUrl}/nexus?task=discussion`;
const nexusVoteLink = `${charmverseUrl}/nexus?task=vote`;
const nexusMultisigLink = `${charmverseUrl}/nexus?task=multisig`;
const nexusProposalLink = `${charmverseUrl}/nexus?task=proposal`;
const nexusBountyLink = `${charmverseUrl}/nexus?task=bounty`;
const nexusForumLink = `${charmverseUrl}/nexus?task=forum`;
```
This redirects user to open the settigns modal for now. I also did a little cleanup on the settings context while making it so i can pass in the default task tab
=> Fix nexus links

scripts/exportData/restoreFromBackup.ts
We had some blocks marked for deletion, but the pages not marked. User reported an issue that their databases were not appearing - so we can assume these boards and children should not have been deleted. i Was able to retrieve them from a snapshot taken before the deletion date.
The script is highly customized in what data it retrieves and uploads, but some of it can be reused if/when we need to retrieve data again.
=> save script used to export and restore data from a backup

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/EditorPage/EditorPage.tsx, components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/PageThread.tsx, components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx, components/common/PageLayout/components/Header/components/ShareButton/components/ShareToWeb.tsx, components/common/PageLayout/components/PageNavigation/components/PageTreeItem.tsx, components/common/PageLayout/components/TrashModal.tsx, hooks/usePages.tsx
While working on a page with access via my user role, I would see the "Access denied" error page briefly sometimes on page load. I traced it to the fact that userSpaceRole was undefined inside getPagePermissions(), which is being called inside of <EditorPage /> as soon as the page is loaded. If we just return null, than the components can choose to wait to display errors or whatnot until real permissions are defined.
Alternative solution could be that the EditorPage component should wait til user is loaded itself, but I feel like it's the responsibility of getPagePermissions() since it is retrieving the user internally.
=> set pagePermissions to null until user is loaded

components/settings/invites/components/TokenGates/TokenGates.tsx, lib/token-gates/daylight.ts
We've got a report from daylight that some of our abilities are duplicated. This pr fixes two issues:
1) Turned out you can click "done" on add token gate modal quickly, and it will create duplicated token gate in ou system. This is fixed by debouning button click
2) 1st point should fix duplicates in daylight, but to make it 100% sure I changed daylight create ability method (POST) to updasert ability (PUT) - this way ability will be updated rather than duplicated if we do anything wrong in the future.
=> Fix duplicating daylight abilities

components/integrations/components/IdentityProviders.tsx, components/login/WalletConnect.tsx, components/login/WalletSign.tsx, hooks/useDiscordConnection.tsx, pages/_app.tsx, pages/api/discord/callback.ts
There are still two issues with our wallet identity provider.
1. Wallet provider shows `Connect wallet` even though a wallet is already connected. Its due to `{account: undefined}` from `useWeb3React`. Since its undefined `storedAccount` is not updated from `null`. I was not able to figure out the reason though
2. "cancelled the wallet signature" error still shows up if a discord only user tries to connect their wallet that is already attached with another account (due to `Unique constraint failed on the fields: (`address`)`). We should lock the wallet after a user has logged out or show a better error message @mattcasey
=> Invalid token error on discord oauth

components/common/Link.tsx, components/common/Modal/SettingsDialog.tsx, components/common/PageLayout/components/Sidebar/Sidebar.tsx, components/common/PageLayout/components/Sidebar/SidebarButton.tsx
I brought over some more styles from the main sidebar, using the component for static links instead of the page tree nodes.
=> More cleanup for settings sidebar

components/[pageId]/DocumentPage/components/ProposalProperties.tsx
I think this rule was added for the admin when they set the next proposal status to vote active - but it is also active when any user is looking at a 'vote active' proposal so it can't be expanded while votes are active :P
=> fix collapsible proposal info

pages/_app.tsx
[Task item](https://app.charmverse.io/charmverse/page-13606663980167877?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565)
Looks like we were not cleaning up the current space id when we were going to a page with no current space from the path.
=> Fix visible icon in /u page

components/profile/components/UserDetails/UserDetails.tsx, lib/users/updateUsedIdentity.ts, lib/users/updateUserProfile.ts
Sometimes the username is too long or not shortened.
FE - Shorten the typography so it does not spill out.
BE- Found only one place where the username is not shortened + added a log for the future to check in datadog when exactly did a username update happened.
=> Fix long username

components/common/UserDisplay.tsx, lib/discussion/interfaces.ts, lib/forums/comments/interface.ts, lib/summon/addUserToSpace.ts, lib/summon/verifyMembership.ts, lib/users/hasNftAvatar.ts, pages/api/email-templates/index.ts, pages/api/summon/join-space.ts, prisma/migrations/20230228173525_add_user_xps_id/migration.sql, prisma/migrations/20230228180529_unique_xps_space/migration.sql, prisma/schema.prisma
We should have another table for XPS-related info, similar to what we do for Discord, Gmail, and wallets. But I'm waiting to work on the story for profiles so we know what we actually need, just want to get the token gating stuff working properly. In the meantime I'll just get the info by calling their api
=> add xps engine id to user table

components/proposals/components/ProposalsTable.tsx
Deleted proposals should not show in the UI
I noticed we got a page_meta_updated event when deleting a proposal, so just went with the updated deletedAt value for now (also avoids any manual mutations)
=> Dont show deleted proposals

components/common/CharmEditor/components/inlineComment/inlineComment.components.tsx
[Task item](https://app.charmverse.io/charmverse/page-8463429056408176?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565)
On pages, comments would crash because cardId was an empty string.
=> Fix threads error on certain pages

components/[pageId]/DatabasePage/DatabasePage.tsx
What's happening is a delay in updating the 'currentPage' defined in EditorPage based on URL, but there is logic in DatabasePage to add a viewId if none exists (and assuming we're on a board URL still).
=> Fix: sidebar navigation showing incorrect link when going from a databse to document page

.github/actions/build_docker_image/action.yml, .github/workflows/deploy_staging.yml, .github/workflows/destroy_staging.yml
Use the standard Amazon lib for CI process.
This reverts a hotfix we used when a buggy version was deployed.
We should make sure CI and staging deploy runs properly before merging this
=> Revert old hotfix

components/[pageId]/Comments/PageComments.tsx, components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/common/PageActionsMenu.tsx
1) pass down permissions instead of calling usePagePermissions at various levels. It seems like the way SWR's cache works is that it will use the previous response if one exsits, but it still makes another request to refresh the data anyway.
2) don't get page permissions for action menu until user opens it
As a user, you wouldn't notice anything because it doesn't affect page rendering, but it makes sense to me that this could be contributing to us running out of db connections
=> call page permissions less often

lib/aws/webhookSqs.ts
With SQS, if you delete the message it's gone forever. Instead, we should let the process retry and AWS will eventually send it to a dead letter queue which I added to AWS already, called "prd-webhook-collabland-dlq.fifo".
=> dont delete messages that fail from collabland

components/[pageId]/Comments/PageComments.tsx, components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
Page permissions are now loaded async. Once they load, the editor is re-mounted in editable state. This sort of thrashes the UI, but also triggers an error when the initial readonly flow tries to update the original view, which no longer exists:
=> wait until permissions are loaded to display CharmEditor in DocumentPage

components/common/BoardEditor/focalboard/src/store/cards.ts
Fixes a bug reported by user, where rows with empty number will appear at the top of the table, counted as if the value was "0"
I originally removed some return statements without really understanding the code: https://github.com/charmverse/app.charmverse.io/pull/393/files. It was actually designed so that no matter the sort, rows without a value would always appear at the bottom.
=> show values at bottom of table when undefined

lib/aws/webhookSqs.ts, lib/collabland/assignRolesCollabland.ts, lib/collabland/collablandClient.ts
Currently, we are "handling" all incoming messages even though our API was incorrect. This PR makes it so that the error can propagate. With SQS, we only want to remove a message from queue if it succeeds. SQS will re-send it a preset number of times and then put it in a dead letter queue so that we can debug and retry them manually later (and we can put an alarm on the size of this queue as well). The visibility timeout determines how often the message will appear as a available to consumers of the queue. (So if the time out is 30s, it will appear available again 30s after we first request it).
=> Dont let errors fail silently in collab worker

lib/users/prepopulateUserProfile.ts
Bug from Errors channel:
updateProfileAvatar() fails because the path of the image contains `?` symbol.
=> Fix save avatar failure

components/common/CharmEditor/components/iframe/iframe.ts
I think I had checked for html before we had teh check for iframe props. I don't think we need to be so cautious anymore. The case that is currently broken is pasting an iframe code with the URL encoded as a link:
=> fix iframe content paste when html is included

components/common/BoardEditor/focalboard/src/components/dialog.scss
this was just a leftover when we used to wait for content to load to stretch the modal accordingly.
=> static width for page dialog on mobile

components/profile/components/SocialInputs.tsx
Github names can include "-" which the regex doesn't match. I just tried to make it more relaxed by checking non-whitespace - we dont have to be so perfect imo
=> fix github regex

__integration-tests__/server/pages/api/bounties/index.spec.ts, components/bounties/BountiesPage.tsx, components/bounties/components/NewBountyButton.tsx, components/common/PageLayout/components/Sidebar/Sidebar.tsx, components/members/MemberDirectoryPage.tsx, components/proposals/ProposalsPage.tsx, hooks/useForumCategories.tsx, lib/permissions/forum/__tests__/computePostCategoryPermissions.spec.ts, lib/permissions/forum/__tests__/computePostPermissions.spec.ts, lib/permissions/forum/__tests__/filterAccessiblePostCategories.spec.ts, lib/permissions/forum/computePostCategoryPermissions.ts, lib/permissions/forum/computePostPermissions.ts, lib/permissions/forum/filterAccessiblePostCategories.ts, lib/permissions/proposals/__tests__/computeProposalCategoryPermissions.spec.ts, lib/permissions/proposals/computeProposalCategoryPermissions.ts, lib/permissions/proposals/computeProposalPermissions/__tests__/baseComputeProposalPermissions.spec.ts, lib/permissions/proposals/computeProposalPermissions/computeProposalPermissions.ts, lib/users/__tests__/hasAccessToSpace.spec.ts, lib/users/errors.ts, lib/users/hasAccessToSpace.ts, pages/[domain]/bounties/index.tsx, pages/_app.tsx, pages/api/bounties/index.ts
**Forums**
- Only show public forum categories to guest user
- Show forum link in sidebar if there is at least 1 public category (and the feature is enabled)
- Treat guests as members of public with regards to permissions (ie. read only, and only take into account public permissions for computing rights)
**Member Directory**
- Show error if user tries to navigate here
**Bounties**
- Prevent guest from creating bounties (they can still see public bounties)
**Proposals**
- Show error if user tries to navigate here
- Lock down proposal permissions for guest users (at most they can view individual public proposals, but not see the list)
=> Guest security improvements

components/common/BoardEditor/focalboard/src/components/properties/user/user.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/filterEntry.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.tsx, components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeaderSortMenu.tsx, components/common/BoardEditor/focalboard/src/widgets/menu/switchOption.tsx
+ Redone sort&filter dropdown
+ fix a warning in styled prop
To test: databases and inline databases & other types if exist
*The behaviour should be the same.
I just added mui because of the popover instead of a dropdown that can't be on top of an overflowed table
=> Fix sort&filter items in database

components/common/BoardEditor/focalboard/src/components/viewSidebar/GoogleDataSource/GoogleDataSource.tsx
Google said we dont follow sign-in guidelines. We do include the logo, so I think they didn't like that it says "Reconnect accounts" in our demo video - not telling the user they are signing in again with Google. Guidelines: https://developers.google.com/identity/branding-guidelines?hl=en#g+signin-social-scopes
https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=1a3c7596-6b8d-45d1-ad03-867b308932a8
=> follow guidelines for google sign-in

components/forum/components/PostList/PostList.tsx
https://app.charmverse.io/charmverse/page-46571373385070425
Issue was caused by refreshing data on focus
=> Do not refresh posts list when new posts banner is opened

lib/pages/server/__tests__/getAccessiblePages.spec.ts, lib/pages/server/getAccessiblePages.ts
I started using `<->` in the ts_query because it requires words to be in a certain order, but didn't realize they have to be adjacent as well. For example "Some <-> truths" will not match "Some simple truths," because "truths" does not immediately follow "some"
=> Hot fix to page search

lib/permissions/proposals/computeProposalPermissions/__tests__/computeProposalPermissions.spec.ts, lib/permissions/proposals/computeProposalPermissions/__tests__/policyStatusReviewedOnlyCreateVote.spec.ts, lib/permissions/proposals/computeProposalPermissions/policyStatusReviewedOnlyCreateVote.ts
Small fix, Admin can now edit proposal when in reviewed status (but not after). Confirmed with product team
=> Allow admin to edit proposal when it is in reviewed status

lib/token-gates/__tests__/verifyTokenGateMembership.spec.ts, lib/token-gates/verifyTokenGateMembership.ts, lib/token-gates/verifyUserTokenGateMemberships.ts
- enable removing users from spaces when token gates are not valid anymore
- additional method to check single user membership `verifyUserTokenGateMemberships` - @valentinludu  you can use it when disconnecting a wallet.
=> Enable removing users from spaces

components/common/BoardEditor/focalboard/src/components/properties/user/user.tsx, components/common/BoardEditor/focalboard/src/components/viewSidebar/viewPropertyOptions.tsx
=> Focalboard ui bug fixes

components/integrations/IntegrationsPage.tsx, components/integrations/components/MultiSigConnectCard.tsx, components/integrations/components/MultiSigList.tsx, components/nexus/GnosisTasksList/GnosisTasksList.tsx, hooks/useGnosisPayment.ts, lib/gnosis/gnosis.importSafes.ts
Gnosis issue reported by the user: https://discord.com/channels/894960387743698944/1092352184483581982
This pr:
- fixes retrieving user signature (user needs to sign tx manually with wallet)
- adds datadog logs in case of failure
- adds snackar with information if user does not have any safe to connect
- small refactor - just removed `default` export, moved one component to separate file
=> Fix gnosis integration + refactor

components/integrations/components/IdentityProviders.tsx
1. Show the full address of the user wallet before disconnecting.
2. Fixed a bug where if you had a connected account and the second was telegram, you could not disconnect telegram.
=> Improve the identity of the user

components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/BountyPaymentButton.tsx
User was ttrying to make a bounty payment but got "Could not detect your chain". It was just a matter of unlocking metamask, but error was not descriptive enough. 
I hope those little improvements will let us avoid situations like that in the future.
=> Update gnosis errors content

hooks/useUser.tsx
Currently when I log out, sometimes i see a lightning bolt appear for a minute as the view tries to catch up with the new state. This is an experiment to see if clearing the cache will make it better or worse. 
Something else we could try is redirecting the user to "/" immediately, instead of waiting for RouteGuard
=> clear cache when user logs out

components/common/CharmEditor/components/ResizablePDF.tsx, components/common/CharmEditor/components/iframe/IframeComponent.tsx, components/common/CharmEditor/components/iframe/iframe.ts, lib/notion/NotionImporter/NotionBlock.ts, lib/pdf/extractPdfEmbedLink.ts
=> Use pdf block when embedding pdf

components/common/CharmEditor/components/fiduswriter/fiduseditor.ts, lib/templates/importWorkspacePages.ts, lib/websockets/documentEvents/documentEvents.ts
Xandra lost an hour of work. It looks like she was opening a document mid-deploy of the socket service. I am having trouble figuring out the order of events still, but for now I want to propagate the error to the user so they know to reload the page. 
The error happens inside the RecreateTransform which is part of the merging plugin when the doc is validated (for when the server and client need to merge a lot of updates)
Luckily it hasn't happened too much in the past month (3-4 users): https://app.datadoghq.com/logs?query=%22Invalid%20content%20for%20node%20doc%22&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1678214069378&to_ts=1680806069378&live=true
=> Capture and alert user when an error occurs receving document updates

components/forum/components/PostDialog/PostDialog.tsx, components/forum/components/PostList/DraftPostList.tsx, components/forum/components/PostPage/PostPage.tsx
- we don't need to always close the drafts modal when a draft is deleted
- don't hide the modal when saving/updating a draft.
=> Fix UX when deleting drafts

components/integrations/components/NewIdentityModal.tsx, components/integrations/components/TelegramLoginIframe.tsx, db.ts, pages/api/telegram/connect.ts, prisma/migrations/20230412212824_update_telegram_id/migration.sql, prisma/schema.prisma
Some telegram Ids are larger than what "Int" supports (-2147483647 to 2147483647). BigInt will be plenty. For more info, see Integers on https://www.prisma.io/dataguide/postgresql/introduction-to-data-types#numbers-and-numeric-values
I ran this locally, with exsiting IDs and it seems to migrate fine. I do get a warning that if migration fails, this is the primary key of the table and it could cause problems
=> update DB column to support large telegram ids

pages/api/profile/remote.ts
I think instructions could be added to our Task Board:
1. run `npm run start:remote`
2. Visit http://localhost:3000/api/profile/remote?userid=
=> add endpoint to log in as another user

components/[pageId]/DocumentPage/components/PageTitleInput.tsx
multiline was removed in this PR: https://github.com/charmverse/app.charmverse.io/commit/470948e0bb591714736a4b578b06ca8bb8c40e71, not sure if it was an accident. Titles are currently cropped inside the card modal and you have to scroll the input to read it
=> support wrapping for page titles

components/common/PageLayout/components/Header/Header.tsx
Hiding on mobile seems unecessary, but 'full width' was hidden before. Notion also doesn't hide mobile
=> show font stylings on mobile

components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx
Fixes this issue:
I have a feeling it might be good to revisit the classes and styles we're using for card properties altogether
=> fix wrapping of card properties on mobile

components/common/PageLayout/components/Header/components/utils/databasePageOptions.ts
[Task item ](https://app.charmverse.io/charmverse/page-09990481564575848)
It was requested for the typeform implementation but I did it generally for any csv import.
What has changed:
If the csv rows have a column with the same name as the value I will delete that column and delete the property before it is created.
=> Improve csv import

components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
Revert back a change from this commit => https://github.com/charmverse/app.charmverse.io/pull/2080/files
Because it broke the view of data sources and now we can't see Google forms responses
=> Revert hiding linked db pages -> Fix: Show data sources dbs

components/_app/hooks/useSpaceGatesReevaluate.ts, components/common/SpaceAccessGate/SpaceAccessGate.tsx, components/common/SpaceAccessGate/components/TokenGate/hooks/useTokenGates.ts, hooks/useWeb3AuthSig.tsx, scripts/getPageHistory.ts
The change is that we will only respond to changes in the connected address if you logged in thru Metamask.
We've had a couple cases in the past including this one where we inadvertently log a user out at the wrong time. We can  simplify the logic by reducing the variables in play when we allow users to switch wallets.  
- assumes that the existence of wallet signature means a user logged in via wallet (we remove it when you log out). 
Flows that may no longer work:
- Log in thru Oauth, then connect thru Metamask expecting to be logged out and go to the login page
=> Simplify rules to switch web3 accounts

__e2e__/po/signup.po.ts, __e2e__/sessions/signup.spec.ts, __e2e__/utils/mocks.ts, __e2e__/utils/web3.ts, components/common/UserProfile/components/MemberPropertiesForm.tsx, hooks/useWeb3AuthSig.tsx, pages/join.tsx
I noticed that sometimes, when opening the member profile form or running the test locally, my console would show a  "maximum depth exceeded" error inside this component. With logging, I Could see that the useEffect() that watches `defaultValues` was being called over and over. My hypothesis is that the default array `[]` supplied for `properties` was causing the issue.
This must have broken in my update to simplify token gates, we were not picking up the signature from local storage because I was mixing up the casing of wallet address :/
=> Fix flaky e2e tests

components/common/CharmEditor/components/fiduswriter/ws.ts, lib/focalboard/cardFilter.ts, lib/websockets/documentEvents/documentEvents.ts
Long-polling is not a great experience for typing, and socket.io always starts with it by default. This might help reduce latency that people experience.
AFAICT, long-polling is just needed for really old versions of IE.
=> disable long-polling in sockets client + other cleanup

lib/lit-protocol-modal/reusableComponents/litInput/LitInput.jsx
Noticed a user's gates were not working due to an extra empty space at the end of the contract. This change affects all inputs in the modal, and you can no longer type with a space since it gets trimmed immediately, but all the inputs seem to require space-less input anyway
=> trim whitspace when entering inputs for token gate

components/common/CharmEditor/components/inlinePalette/inlinePalette.ts, components/common/CharmEditor/components/rowActions/RowActionsMenu.tsx, components/common/CharmEditor/components/rowActions/rowActions.ts, components/common/CharmEditor/utils.ts, theme/@bangle.dev/styles.scss
Feature: 
Known issues:
when you hover over the row actions and move your cursor up/down, you might expect for the row actions to follow This currently is not possible due to how we get the current node position from prosemirror. But I'd like to see if there's a workaround in the future
Testing:
I changed the algo a bit on how we find the hovered positions. So I tested Duplicate and Delete as well, particularly when the component is on the first row on a document.
=> allow users to insert new rows from action menu

components/common/CharmEditor/CharmEditor.tsx, components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx, components/common/CharmEditor/components/link/link.plugins.ts, components/common/CharmEditor/components/link/link.ts, components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx, scripts/blacklistSpace.ts
When working on custom domains, it includes my custom domain. I want it to just be a 'relative' link. I think this is better UX too since we pull up the correct page title.
=> When pasting a link to a page in CV, convert it to a page mention

lib/blockchain/provider/zora/getNFT.ts, lib/blockchain/updateTokenGateDetails.ts, lib/tokenGates/humanizeConditions.ts, lib/tokenGates/utils.ts
Fix:
- zora was not on the LIT_CHAINS list
- zora tokenId was sent as a number instead of a string. The ZDK was throwing an error.
- nft titles
=> Fix zora chain nft error and title display

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/DocumentPageProviders.tsx, components/[pageId]/DocumentPage/components/Sidebar/PageSidebar.tsx, components/[pageId]/DocumentPage/components/Sidebar/components/CommentsSidebar.tsx, components/[pageId]/DocumentPage/components/Sidebar/components/ProposalSidebar/ProposalSidebar.tsx, components/[pageId]/DocumentPage/hooks/useLastSidebarView.ts, components/[pageId]/DocumentPage/hooks/usePageSidebar.tsx, components/common/CharmEditor/CharmEditor.tsx, components/common/PageActions/components/DocumentPageActionList.tsx, components/common/PageLayout/components/Header/components/ToggleEvaluationButton.tsx, testing/customRender.tsx
What's supposed to happen is that we use local storage to open the sidebar when you get to full page. The current approach seems to overrides itself as you navigate between pages.
=> Fix opening evaluation sidebar

components/settings/account/hooks/useLensProfile.ts
This blew up when user.wallets is an empty array. was caught by e2e
=> fix code for lens profile

components/rewards/components/NewRewardButton.tsx, components/rewards/components/RewardProperties/RewardProperties.tsx, components/rewards/components/RewardProperties/RewardPropertiesForm.tsx, components/rewards/hooks/useNewReward.tsx, components/rewards/hooks/useRewards.tsx, components/settings/roles/components/RolePermissions/RolePermissions.tsx
- make all fields optional for reward templates
- fix: reward templates are appearing in the main board
[
](https://discord.com/channels/894960387743698944/1176944385678643301/1176944385678643301)
=> Fix and update reward templates

lib/utilities/file.ts
Remove slashes in filename when zipping files
This was causing exported databases to have some pages show as a subdirectory
=> Replace slashes in export filenames

components/common/Snackbar.tsx, hooks/useSnackbar.tsx, testing/customRender.tsx
Previously when the snackbar was about to close, we showed the initial state (info and empty message), which created a bad UX. Check out this loom recording, first portion is with the update, 2nd portion is what we have currently.
https://www.loom.com/share/d0ef1bb91ae641ee90c832bde7ef6870?sid=13b3008c-fdce-4761-bd9e-8997d3bfff41
=> Fixed snackbar close ux

components/common/BoardEditor/focalboard/src/components/viewSidebar/viewLayoutOptions.tsx, components/common/Menu.tsx, components/proposals/ProposalsPage.tsx, components/proposals/components/ProposalCategoriesList.tsx, components/proposals/components/ProposalViewOptions/components/ProposalCategoryContextMenu.tsx, components/rewards/components/NewRewardButton.tsx
1. Completely hide view option (...) if no user is logged in
2. Disable create new reward button without permission
3. Disable changing the "Open page in" option without being an admin
4. Hide proposal category options ellipsis until hover (just like forum categories)
[Discussion](https://discord.com/channels/894960387743698944/1016422398964269076/1178318289043214367)
=> Misc updates to public rewards and proposals view option

__integration-tests__/server/pages/api/public/pages/[pageId].spec.ts, lib/security/checkPageContent.ts
Ensure the document content check only runs if content exists
Generated page content was causing error to throw
=> Fix page content check

components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx, hooks/useCharmRouter.ts
I am not sure why this works! I was just looking at what React components are rendering during drag and drop on an inline db and noticed CenterPanel was rendering due to 'showCard' prop, so I added a useCallback around it. Now I can drag the event fine. I can't really explain it, but we should be memoizing it anyway
=> fix events not being able to be dragged on inline calendars

__e2e__/database/createAndEditDatabase.spec.ts, components/[pageId]/DatabasePage/DatabasePage.tsx, components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
1. Open the card based on the "Open page in" field of the current view
2. Remove `cardId` after closing card
=> Open card after creating and remove cardId from url after closing

components/common/CharmEditor/components/@bangle.dev/core/bangle-editor-state.ts, components/common/PageActions/components/DatabasePageActionList.tsx, lib/prosemirror/plugins/markdown/generateMarkdown.ts, pages/api/pages/[id]/export-database.ts
1. Fix the exported zip name. Previously it was `.zip.zip`
2. Pass an empty prosemirror document to `BangleEditorState` if there is no content, rather than passing an empty string, as otherwise it would try use dom methods (which are not present in node env) and throw error.
=> Handle exporting empty database pages without throwing error

components/common/PageDialog/PageDialog.tsx, components/rewards/components/RewardStatusBadge.tsx
- "Open as page" to applications inside dialog
- removed a case we don't use for RewardStatusBadge, which had an incorrect link to rewards
=> Rewards link

components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/proposals/components/ProposalProperties/components/ProposalRubricCriteriaInput.tsx
If proposal comes from a template, don't allow non admin to reorder criteria
Author was able to reorder criteria, which makes it more difficult for reviewers of multiple proposals using the same template
=> Prevent reordering flows from a template

components/_app/components/OnboardingEmailForm.tsx, components/_app/components/UserOnboardingDialog.tsx
1. Skip triggering the required member properties modal for guest members
2. Show tooltip for cv onboarding modal's disabled button
3. Add a loading state to disable the button while member properties are being updated
4. Fixed bug when modal doesn't close even after filling and saving required member properties
=> Improve UX + bugfix for required member properties

lib/mailer/emails/templates/components/Avatar.tsx
=> fix links to avatars in emails to not use s3 url

components/common/BoardEditor/components/cardProperties/CardDetailProperty.tsx, components/common/BoardEditor/focalboard/src/widgets/propertyMenu.tsx
[Card](https://app.charmverse.io/charmverse/delete-option-not-coming-up-from-block-handle-on-proposal-custom-property-6017166448466353)
=> Open card property menu on clicking handler

components/common/TokenGateModal/hooks/useTokenGateModalContext.tsx, components/settings/invites/components/TokenGates/TokenGates.tsx, lib/blockchain/updateLocksDetails.ts
Fix for refetching token gates after we create them.
Looks like mutate() from swr doesn't work.
=> Refetch tokengates after creation

charmClient/hooks/proposals.ts, components/common/BoardEditor/focalboard/src/components/kanban/kanbanColumn.tsx, components/proposals/ProposalPage/components/EvaluationSidebar/components/PassFailSidebar.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/components/CompleteFeedbackButton.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/components/GoBackButton.tsx, lib/proposal/clearEvaluationResult.ts, lib/proposal/submitEvaluationResult.ts, lib/proposal/updateProposalEvaluation.ts, pages/api/proposals/[id]/clear-result.ts, pages/api/proposals/[id]/evaluation.ts, pages/api/proposals/[id]/submit-result.ts
Reviewers could not submit result
The updateProposalstatus endpoint was checking for 'edit' permission. I broke out the logic to separate methods/endpoints to avoid conflicts like this in the future
=> fix apis to review and clear reviews for evaluations

lib/notifications/mailer/sendNotificationEmail.ts
Issue
In email, the "to" is the user who sent it instead of the one that received it.
=> Fix to name in email notification

components/[pageId]/DocumentPage/DocumentPage.tsx, lib/proposal/form/canAccessPrivateFields.ts, lib/proposal/form/getProposalFormAnswers.ts, pages/api/proposals/[id]/form/answers.ts, pages/api/spaces/[id]/proposals/blocks/index.ts
1. Custom proposal properties couldn't be created before on a standalone page view. They were working from the proposals table page. The solution was a missing context provider
2. Proposal form field answers are available even when no user is logged in via public proposals table or public proposal
=> Fixed adding custom proposal properties

components/settings/proposals/SpaceProposalSettings.tsx, lib/proposal/workflows/defaultWorkflows.ts
We are keeping Feedback for Vote-related flows, but it should not be included for rubrics and not as a default step when creating a workflow
=> remove feedback step as default

lib/tokenGates/evaluateEligibility.ts, lib/tokenGates/verifyTokenGateMembership.ts
Fix role id error - There were situations where we had only roleId.
Use Promise.allSettled to see all errors and prevent breaking on the first try.
=> Check all users for memberships

.github/workflows/deploy_staging.yml
Got a warning on recent build: https://github.com/charmverse/app.charmverse.io/actions/runs/7351818862
> The following actions uses node12 which is deprecated and will be forced to run on node16: bobheadxi/deployments@v0.5.2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
=> update github deployment action which runs on node 12

components/[pageId]/DocumentPage/DocumentPage.tsx, components/[pageId]/DocumentPage/DocumentPageProviders.tsx, components/proposals/ProposalsPageProviders.tsx, pages/[domain]/proposals/index.tsx, stories/ProposalsPage/ProposalsPageStory.tsx
User cannot add properties on the new proposal page, which uses NewProposalPage. Seems like the blocks provider belongs inside DocumentPageProviders
=> fix adding properties on proposals

components/common/form/fields/SelectField.tsx
When there's only one chip, the stack container collapses and you can't read the chip:
=> fix chips not expanding in seleect field

components/common/BoardEditor/utils/blockUtils.ts
I think the storedBored is being defined as readonly someplace, wasn't sure where though.. maybe swr?
=> cannot edit read only proposal block

lib/votes/__tests__/createVote.spec.ts, lib/votes/createVote.ts
Deduplicate vote creation
We can have multiple proposal votes as long as it's only 1 per evaluation
=> Fix vote creation logic so duplicates are assessed at evaluation level

__e2e__/proposals/proposalEvaluationCreation.spec.ts, __e2e__/proposals/proposalEvaluationTemplatesCreation.spec.ts, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/EvaluationStepSettings.tsx, components/proposals/ProposalPage/components/EvaluationSettingsSidebar/components/RubricCriteriaSettings.tsx
This adds default rubric criteria when creating a proposal.
It does not work when you change workflows in draft state, but that wasn't the primary request, and it's more difficult since updating workflow just syncs the backend and there's no clear event when to add a default empty value.
=> add default rubric criteria when setting up a new proposal

components/common/PageActions/components/DuplicatePageAction.tsx
per chris, users can copy/paste instead. The 'proper' way to do this, though, would be to update /new page with pageId and try to retrieve the inputs from the page
=> dont allow duplicating proposals

.github/workflows/test_new_core_pkg.yml
I noticed that we were spending 5 minutes each test rebuilding the app when testing core
=> save app build when testing chagnes in core

pages/api/spaces/[id]/pages.ts
This shaves off 1.5MB of data being transferred for the CharmVerse pages endpoint. That brings it from 12.77 to 11.25
=> remove null values from page meta

testing/generateBoardStub.ts
i thought i had included this in my original fix - we sort in the query but the extra cards were also using the same 'createdAT' as the original ones
=> fix flaky test

components/common/SpaceAccessGate/components/TokenGate/hooks/useTokenGates.ts
The issue was the user did not have an account, it skipped the verification and jumped to the page where the user did not have access.
=> Fix discord user trying to join a space through a token gate

components/[pageId]/DocumentPage/DocumentPage.tsx
I think this broke when i moved the page title outside the Charmeditor, which uses page id as its key. A really weird case to test - and it only would happen when the page you go to is older, because the page title udpates based on page updated date
=> fix page title not updating between pages

pages/api/events/index.ts
I noticed we logged "invalid track data" almost 300 times in the past week, and it's because no user id exists. I think it should be safe to create an id in this endpoint, wher normally we do it in api/profile. It's just probably a race condition
=> create anonymous user id when tracking if one has not been assigned yet

pages/api/v1/proposals/[proposalId]/index.ts, pages/api/v1/proposals/index.ts
Summon is using vote_active to know if a proposal is active right now. They're willing to updaet their client, we just need to decide what the new api could look like
=> temporarily bring back vote_active status for proposals in public api

components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx, components/proposals/ProposalPage/hooks/useNewProposal.tsx, lib/proposal/createProposal.ts
Authors are no longer mandatory when creating a template. If you do set them, then they will be included in the authors list when using a template.
The following query will clear out author inputs from existing templates, I checked and there are 286 in production:
```
await prisma.proposalAuthor.deleteMany({
where: {
proposal: {
page: {
type: 'proposal_template'
}
}
}
});
```
=> allow setting authors in proposal templates

docker-compose.yml
we are crashing around 4GB, best guess is that the max memory is not high enough. We're running on 16GB instances so 8GB shuld be fine to try
=> increase max old memory in production webapp

components/proposals/components/ProposalRewards/ProposalRewards.tsx, components/rewards/components/RewardStatusBadge.tsx
https://app.charmverse.io/charmverse/large-reward-number-in-proposal-breaks-formatting-4962506545590897
Before
After
=> Fix proposal reward property ui

lib/credentials/getAllUserCredentials.ts
If Ceramic is down, shouldn't affect EAS and vice-versa
=> Make loading more fault tolerant if ceramic is down

components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx, components/proposals/ProposalPage/components/TemplateSelect.tsx, components/rewards/components/NewInlineReward.tsx, components/rewards/components/NewRewardButton.tsx, components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
- allow unsetting reward template when it doesnt come from a proposal template
- we were not always pulling in template properties when you added a reward at first
- show "Empty" for empty template properties
=> Bug fixes for milestones

components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
I removed a useEffect which was overriding the Token default.. It looks like 'values' used to be optional, but now that it's required i don't think we need a useEffect anymore.
I tested with each type, opening the modal it shows the correct type.
=> dont override default reward type for new rewards

hooks/useSharedPage.ts
If a space has public proposals enabled, we still need to redirect them to login if they want to submit a proposal
=> redirect user to login when trying to creat ea proposal template

lib/rewards/getRewardTemplates.ts
Prevent reward templates marked for deletion as being returned
=> Filter out soft deleted reward templates

components/[pageId]/DocumentPage/components/RewardProperties.tsx, components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx, components/rewards/components/NewInlineReward.tsx, components/rewards/components/RewardProperties/RewardPropertiesForm.tsx, components/rewards/hooks/useRewards.tsx, stories/Rewards/Pages/NewRewardPage.stories.tsx
Reward type was not changing when selecting a different template. I also fixed updates - you can't even type in "Custom Reward" right now, because it is not beign debounced
=> better handle updates for  existing rewards

hooks/useRewardBlocks.tsx, pages/api/spaces/[id]/rewards/blocks/index.ts
If a user has no rewards, we were not requesting blocks from the DB at all. So anything they did would save but not appear when we requested teh blocks.
I also made it so we always allow access to the reward blocks of a space. I would have added another excpetion if you have public proposals, but this is just configuration and probably not a big deal.
=> always retrieve reward blocks

components/common/BoardEditor/components/properties/TagSelect/TagSelect.tsx
Fix empty multiselect in card details view
=> Fix empty tag not showing in details

connectors/chains.ts
The url https://safe-transaction-goerli.safe.global doesn't work anymore to get the users safes.
=> Remove goerli url for gnosis safe

components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/AttachRewardButton.tsx, components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx
I tried to add a reward to a proposal but it was telling me I needed to assign reviewers. I think checking for isProposalTemplate was added originally because we would make an exception and save them on the backend.
=> Fix for adding rewards to a proposal

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx
Fixes a bug where the rubric criteria details update in the sidebar before you click Save in the settings popup
=> deep clone evaluation steps when editing

lib/session/__tests__/getDefaultPageForSpace.spec.ts, lib/session/getDefaultPageForSpace.ts, pages/[domain]/index.tsx
Non logged in users ended up on space join page instead of login.
Update for non logged in user flow 
- if there is no public homepage return null instead of  redirect path
- in server side props fallback to original logic (return empty props) if redirect is null
- this will use route guard to redirect to login on the frontend
=> Fix non-logged in user redirect

lib/credentials/queriesAndMutations.ts
I am getting this locally when looking at member profile settings. It could also be a warning, but i just return an empty list instead to reduce noise. lemme know if u want a warning:
```
error: Error loading Charmverse Ceramic credentials for user 96cb5266-c546-4db8-8b3e-25551c118eb0 {
[next]   error: TypeError: Cannot read properties of undefined (reading 'toHexString')
[next]       at isHexable (/Users/matt/charmverse/app.charmverse.io/node_modules/@ethersproject/bytes/lib/index.js:9:21)
[next]       at hexlify (/Users/matt/charmverse/app.charmverse.io/node_modules/@ethersproject/bytes/lib/index.js:175:9)
[next]       at new SigningKey (/Users/matt/charmverse/app.charmverse.io/node_modules/@ethersproject/signing-key/lib/index.js:20:82)
[next]       at new Wallet …
```
=> dont throw an error if private key does not exist for credentials

background/cron.ts, background/tasks/updateSpacesMixpanelProfilesTask.ts, lib/metrics/mixpanel/updateMixpanelGroupProfiles.ts, lib/metrics/mixpanel/updateTrackGroupProfile.ts, scripts/updateMixpanelBlockCounts.ts
Update mixpanel space profiles with block counts  in a cron job. It uses mixpanel batch endpoint to update 1000 spaces at time
=> Update mixpanel space profiles with block counts

components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx
WHY
There can be significant delay waiting for pages to load, 100ms vs 1 second and Alex/Xandra asked if we could do something so that links to pages would show the titles faster. 
WHAT
I have a race between the requests to pages and getting a single page if pages have not loaded yet. Once they have loaded, we won't try to retrieve individual pages. Tested this by adding a timeout in the pages endpoint
=> optimize the loading of page links if usePages is not loaded yet

components/common/form/FormField.tsx, components/common/form/FormFieldsInput.tsx, components/common/form/fields/FieldTypeRenderer.tsx, components/common/form/fields/TextInputField.tsx
https://app.charmverse.io/charmverse/short-text-in-form-fields-should-wrap-4928057783714157
Added a way to simply override rows / maxRows in text field renderer. Setting them to undefined will default to multiline text input with 1 line by default
=> Wrapping text form fields

components/common/ContextMenu.tsx, components/common/PageLayout/components/LoggedOutButtons.tsx, components/settings/credentials/components/CredentialEventToggle.tsx, components/settings/credentials/components/CredentialTemplateDialog.tsx, components/settings/credentials/components/CredentialTemplateRow.tsx, components/settings/credentials/components/ProposalCredentialPreview.tsx, components/settings/space/components/SettingsItem.tsx, hooks/useSpaceFeatures.ts, lib/credentials/constants.ts, lib/credentials/issueProposalCredentialsIfNecessary.ts, lib/features/__tests__/getFeatureTitle.spec.ts, lib/features/getFeatureTitle.ts, lib/notifications/getNotificationMetadata.tsx
Fixes:
- add translation for "proposal" in credentials
- add translation when issuing credentials
- align the status labels we show in the UI as well as the backend
- add tests + correctly translate singular form of words, eg "grant" should be "grant" not "grants"
- refactor settings to use a common ContextMenu component
=> Bug fix for propoals words in Credentials

__integration-tests__/server/pages/api/v1/spaces/[spaceId]/members/index.spec.ts, charmClient/apis/publicProfileApi.ts, components/members/components/MemberProfile/components/ProfileWidgets/ProfileWidgets.tsx, lib/blockchain/provider/alchemy/client.ts, lib/profile/__tests__/getSummonProfile.spec.ts, lib/profile/getSummonProfile.ts, lib/summon/__tests__/syncSummonSpaceRoles.spec.ts, lib/summon/addUserToSpace.ts, lib/summon/api.ts, lib/summon/constants.ts, lib/summon/syncSummonSpaceRoles.ts, lib/summon/verifyMembership.ts, pages/api/public/profile/[userId]/summon.ts, pages/api/summon/join-space.ts, pages/api/v1/spaces/[spaceId]/members/index.ts, scripts/query.ts, testing/mocks/user.ts, testing/setupDatabase.ts
We shouldn't need a migration, at least right away. The cron sync job should retrieve and update spaceRoles automatically. I'll make another PR to remove xpsEngineId on user table later
=> use correct tenant urls and user ids for Summon API

components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/proposals/ProposalPage/components/ProposalProperties/ProposalPropertiesBase.tsx, components/proposals/ProposalPage/components/ProposalProperties/components/CustomPropertiesAdapter.tsx, components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts, components/proposals/ProposalPage/hooks/useNewProposal.tsx, components/proposals/hooks/useProposalsBoard.tsx, lib/proposal/interface.ts, lib/proposal/mapDbProposalToProposal.ts
**WHY**
Currently in prod, it just shows the unix epoch
**WHAT**
The 'createdAt' prop previously depended on a page existing in usePages(). The below screenshot is the correct version. 
Working on this  made me feel that it could be much simpler if we split out the states from useProposalsBoardAdapter(). For instance, the `card` export is only needed on individual pages -- and it felt hacky to have to pass in 'createdAt' for new proposals. And if we split out the board block, we would not need to retrieve all proposals and blocks on a single page.
=> Ensure created date has value on new proposals

components/common/form/FormFieldsInput.tsx, components/common/form/hooks/useFormFields.ts, components/proposals/ProposalPage/NewProposalPage.tsx
Once you edit a long text field, it suddenly becomes required even if it was optional. I think we just missed a rule in the yup config
Discord link: https://discord.com/channels/894960387743698944/1204993238470230037
=> fix required value for long test inputs

components/settings/proposals/components/EvaluationDialog.tsx, components/settings/proposals/components/EvaluationPermissions.tsx, components/settings/proposals/components/ProposalWorkflow.tsx
This way we can use 'move' permission to go back to draft state
=> only author can Move Back from first workflow step

components/common/CharmEditor/components/callout/components/Callout.tsx
=> fix broken layout for iframe embeds inside of callout

components/common/CharmEditor/components/BlockAligner.tsx
Some extra logic was added to hide if it's readOnly: https://github.com/charmverse/app.charmverse.io/commit/a9ca619bc7e525d21f7b131dd9fb097779678a31#diff-fcfabebfdfcdf3df1cd01702daa1cb76562c69c1877ad6df24664bf1afc1ac7fR74
But this hides File type components on public pages, and probably other components.
The BlockAligner element is too low-level IMO to have this type of logic.
=> Revert change to hide block aligner for readonly

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/RubricAnswersForm.tsx, components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx, components/rewards/components/RewardApplicationPage/components/RewardReviewerActions.tsx, components/rewards/components/RewardApplicationPage/components/RewardSubmissionInput.tsx, lib/rewards/getRewardType.ts, lib/rewards/interfaces.ts
Updated logic to consider 3 different reward types: When a reward type is "none", then `hasCustomReward` was false, but we were assuming it would be token.
=> consider None as reward type in UI components

components/common/CharmEditor/components/@bangle.dev/react/ReactEditor.tsx
not sure why this only happens on one page i found: https://app.charmverse.io/op-grants/optimism-grants-council-8323028890716944. somehow the nodeViews get set before editor.view, and it throws an error that EditorViewContext is not set. we should clean it up in a refactor on charmeditor so we dont have to check for editor.view..
=> fix context for node views

__integration-tests__/server/pages/api/spaces/rewards/blocks.spec.ts, components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx, components/rewards/hooks/useRewardsBoard.ts, lib/rewards/blocks/getBlocks.ts, lib/utilities/types.ts, pages/api/spaces/[id]/rewards/blocks/index.ts, testing/mocks/rewards.ts, testing/mocks/space.ts
I was grabbing the cardProperties from the fully-configured board which we export when updating the data. Apparently, we should not be storing the reward properties - they get added each time the board is loaded in the DB by getDefaultBoard.
I'm also just wondering if there could be a need to save reward card properties or not? And should we/do we use this approach for proposal-as-a-source? (I think every time we add a field we have to do a migration right now)
=> fix updating block so that we do not save reward properties

components/common/form/fields/FieldWrapper.tsx
=> fix width of charm editor input in form fields

__e2e__/po/document.po.ts, __e2e__/proposals/freeFormProposalTemplate.spec.ts, __integration-tests__/server/pages/api/proposals/templates/[id].spec.ts, charmClient/apis/proposalsApi.ts, charmClient/hooks/proposals.ts, components/[pageId]/DocumentPage/components/ProposalArchivedBanner.tsx, components/[pageId]/DocumentPage/components/ProposalProperties.tsx, components/common/CharmEditor/components/linkedPage/components/LinkedPagesList.tsx, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/EvaluationStepSettingsModal.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx, components/proposals/ProposalPage/components/TemplateSelect.tsx, components/proposals/components/NewProposalButton.tsx, components/proposals/hooks/useProposalTemplates.tsx, lib/proposal/__tests__/getProposal.spec.ts, lib/proposal/__tests__/getProposalTemplate.spec.ts, lib/proposal/__tests__/getProposalTemplates.spec.ts, lib/proposal/getProposal.ts, lib/proposal/getProposalTemplate.ts, lib/proposal/getProposalTemplates.ts, lib/proposal/getProposals.ts, lib/proposal/interface.ts, lib/proposal/mapDbProposalToProposal.ts, pages/api/proposals/templates/[id].ts, pages/api/spaces/[id]/proposal-templates.ts, stories/lib/mockData.ts
Given that we get all the forms and evaluation information currently, we're grabbing an enormous amount of data for spaces like OP that have 10-15 proposal templates (1 MB in size!)
=> Cleanup: only send meta data forward for proposal templates

components/common/SpaceAccessGate/components/TokenGate/hooks/useTokenGates.ts
If a user is loggedin with anything other then wallet and have an old signature stored, they can see the eligibility but can't join.
=> Request signature before joining a space

lib/spaces/customConditionJoinSpace.ts, pages/[domain]/proposals/new.tsx
Bug: currently, when using a custom domain I get redirected to /join?domain=work.charmverse.fyi. We are not finding the space for some reason, but I was able to simplify this and am going to reuse the logic from pages/[domain]/index.ts.
=> fix space lookup when creating a proposal

components/rewards/components/RewardProperties/RewardPropertiesForm.tsx, lib/proposals/createRewardsForProposal.ts, pages/api/proposals/[id]/rewards.ts
Somehow, we ended up with roleIds inside of assignedSubmitters in a pending reward on proposals. This seems to be possible if you change the application type as an admin, but not sure if thats actually what happened
=> fix attribution of submitters

components/common/BoardEditor/focalboard/src/components/kanban/kanban.tsx
[Card](https://app.charmverse.io/charmverse/confirmation-is-blocking-me-from-dragging-cards-to-other-columns-when-sort-is-enabled-04500755241082732)
=> Show sort warning when dragging between same column

lib/blockchain/provider/ankr/client.ts, lib/blockchain/updateTokenGateDetails.ts
After moving fron Ankr to Alchemy, Hats Protocol token gate was erroring because tokenId was too big and it couldn't be a number
=> Fix Hats Protocol Ankr error on polygon

hooks/useFavoritePages.ts
What: "Favorites" appears in the sidebar even when it's empty.
Why: if you have favorites in any space, then the list of favorite page ids is non-empty
Things to test: re-ordering favorites from different spaces still works
=> Bug fix: filter out favorite page ids that dont exist in a space

lib/focalboard/generateCsv.ts, pages/api/pages/[id]/export-database.ts
When exporting CSV, the rows are filtered by the active view, but the markdown was only filtered by pages that are accessible to you.
=> filter out markdown files based on view filter

components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/form/FormFieldAnswers.tsx, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/ProposalFormFieldAnswers.tsx, stories/FormFields/FormFields.stories.tsx
Before, we had "FormFieldsInput" and "FormFieldsEditor" and they sound too similar, since you are "inputting" form fields inside the editor too
=> rename FormFieldsInput to more clear FormFielAnswers

__e2e__/proposals/joinSpaceViaProposals.spec.ts, charmClient/hooks/pages.ts, components/[pageId]/DocumentPage/components/PageParentChip.tsx, components/common/BoardEditor/focalboard/src/components/centerPanel.tsx, components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx, components/common/PageDialog/PageDialog.tsx, components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx, components/common/PageLayout/components/Header/components/ShareButton/components/FreePagePermissions/FreeShareToWeb.tsx, components/common/PageLayout/components/Header/components/ShareButton/components/PaidPagePermissions/PaidPagePermissions.tsx, components/common/PageLayout/components/Header/components/ShareButton/components/common/ShareToWeb.tsx, components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx, lib/pages/interfaces.ts, pages/api/pages/[id]/index.ts
Fixes a failing e2e test. My recent update made it so that you can actually view proposal templates data even if you aren't in the space. What was happening is that the test id is "undefined" at first, until the proposal page meta loads. But I guess if the page loaded fast enough, then playwright would never see 'undefined'.
=> fix flaky e2e test

components/[pageId]/DatabasePage/DatabasePage.tsx, components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/BoardEditor/components/cardProperties/CardDetailProperty.tsx, components/common/BoardEditor/components/properties/PagesAutocomplete.tsx, components/common/BoardEditor/focalboard/src/components/cardDetail/cardDetailProperties.tsx, components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx, components/common/PageDialog/PageDialog.tsx, components/common/PageDialog/hooks/usePageDialog.tsx
1. Clicking on related cards inside a modal should open the clicked card in the same modal
2. Show clicked related card in a modal/new page for public databases
=> Show clicked related pages in modal

next.config.js
4MB is a lot, but these errors just create noise in our logs right now. I think its originally geared towards serveless endpoints anyway
=> silence errors about response size

lib/blockchain/provider/alchemy/client.ts
We need to get thumbnailUrl or originalUrl.
ENS was filtered out, but funny thing is that it didn't work because the contract needed to be lower case.
It should have been `n.contract.address.toLowerCase()`
=> Fix ens not showing

components/common/PageLayout/PageLayout.tsx
This should stop the user seeing "go to my space" from SharedPageLayout before user and spaces have finished loading
=> Add additional checks to prevent early render

.ebextensions_ceramic/06_cloudwatch_alarm.config
Infrastructure as Code alarm for the ceramic graphql env
=> Add cloudwatch alarm for ceramic

components/[pageId]/SharedPage/SharedPage.tsx, components/common/form/FormFieldAnswers.tsx, components/common/form/FormFieldsEditor.tsx, components/common/form/checkFormFieldErrors.ts, components/common/form/hooks/useFormFields.ts, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/ProposalFormFieldAnswers.tsx, lib/proposals/form/__tests__/upsertProposalFormFields.spec.ts, lib/proposals/form/upsertProposalFormFields.ts, lib/proposals/getProposalErrors.ts, pages/api/proposals/[id]/form/index.ts, stories/FormFields/FormFields.stories.tsx
- we were literally just filtering out form fields with no answers, assuming that meant they are 'private' *
- fixed layout for public version of documentpage with sidebars (the scrollbars were wrong in SharedPage.tsx)
- removed some very light, unecessary wrappers for FormFieldAnswers. It is now always "controlled". Previously, these wrappers had a bit more logic but we slowly removed it
- made it so we can call useFormFields and pass in fields after-the-fact. the form was depending on fields being defined from the git-go
* One thing we could do in the future is hide fields if they are private and you are not the viewer. I dont like how it was currently guessing in the frontend,. so its a larger change
=> show formfields even if no answer was found

components/common/form/FormFieldAnswers.tsx, components/common/form/fields/CharmEditorInputField.tsx, components/proposals/ProposalPage/NewProposalPage.tsx, components/proposals/ProposalPage/components/ProposalFormFieldAnswers.tsx
The "controlled" CharmEditor doesn't actually update if the content prop changes. So i introduced a race condition in my last update where the fields would be empty
=> dont load charm editor until field answers are loaded

components/common/PageDialog/PageDialog.tsx
We need to listen to page meta updates when showing a page in the dialog - otherwise adding icon, banner, etc. doesnt show up immediately
=> use page hook that updates metadata in real time

components/settings/roles/components/MemberActions.tsx
The logic is over 2 years old. I can't think of a technical reason not to let you remove the space creator from a space. We let you downgrade them from admin already
I added some extra logic to ensure there's always at least one admin in a space
=> allow removing the creator of a space

lib/credentials/connectors.ts, lib/credentials/external/getOnchainCredentials.ts, lib/credentials/external/schemas.ts, lib/credentials/schemas/deploySchema.ts, lib/credentials/schemas/index.ts
- Fixed a bug where we were filtering onchain credentials for CharmVerse schemas
- Added script for deploying to new chains
⚠️ Pending issue: Deploy fails on Arbitrum due to estimating gas
-- Option 1: Rerun the transaction with 1k USD in the wallet
-- Option 2: Fix the gas calculation
=> Fix displaying EAS credentials from charmverse and add script for deploying schemas

components/proposals/ProposalPage/NewProposalPage.tsx
The bug was that we were clearing out the form input's proposal id, which is used to load the template. I think a more proper fix might be to not use formInput.proposalTemplateId to load the template. I am able to remove the code that I did since you cannot select 'template' when adding proposals from the sidebar.
TODO: add e2e
=> fix duplicating proposal templates

charmClient/hooks/track.ts, components/[pageId]/EditorPage/EditorPage.tsx, components/[pageId]/SharedPage/SharedPage.tsx, components/common/PageDialog/PageDialog.tsx, components/forum/components/PostDialog/PostDialog.tsx, lib/metrics/mixpanel/interfaces/PageEvent.ts, lib/session/__tests__/getDefaultPageForSpace.spec.ts
In theory we shouldn't need to strip out the custom domain from the path, but there is a bug when looking at databases where the custom domain gets added to the URL. This pathname then breaks if you go visit app.charmverse.io:
=> strip out custom domain when tracking page views

lib/databases/cardFilter.ts
If card title was empty in the filter, it threw an error
=> Fix error on filter

pages/api/events/index.ts
Fix for error i saw. i'm not sure whats going on w/the input, we dont use "$eq" in the frontend:
=> protect track api if event is not a string

lib/credentials/apolloClientWithRedisCache.ts, lib/credentials/getGitcoinCredentialsByWallets.ts, lib/credentials/queriesAndMutations.ts
When ceramic fails, we just get an empty value for response. Not sure if there's a way to get better errors, or how to check if we can use it or not. This is my dev env
=> better handling of api errors

components/common/DatabaseEditor/components/propertyValueElement.tsx, lib/databases/createCardsFromProposals.ts, lib/databases/getCardPropertiesFromAnswers.ts, lib/databases/setDatabaseProposalProperties.ts, lib/databases/updateCardFormFieldPropertiesValue.ts, lib/databases/updateCardsFromProposals.ts
Two bugs:
- we were creating card properties for project profile form types, even tho we havent added support yet
- the value was an object { projectId: string }, but the default card property element assumes its a string. caused the page to blow up.
I am not sure whether it's possible to have the board automatically review properties that are no longer valid?
=> fix rendering of invalid strings in card properties

components/settings/space/components/SetupCustomDomain.tsx
Strip out the trailing period for the "Name" part of DNS records for validating custom domains. If you include a ".", then DNS registrars like Google will incorrectly apply the record with an additional period and it will not work as expected.
I'm just updating the frontend where users are copy/pasting in case these settings are used someplace else.
Fix for https://github.com/charmverse/app.charmverse.io/issues/3888
=> Strip the trailing period on DSN record names since providers usually do not expect it

__e2e__/charmEditor/rangeDeleteBlocks.spec.ts
https://github.com/charmverse/app.charmverse.io/actions/runs/8604066895/job/23577665135
Another alternative could be to not use e2e for this, but instead extract the logic we're using in the RowActions UI so it can be unit-tested
=> disable flaky e2e test

components/common/DatabaseEditor/store/views.ts
Two issues I fixed:
- it seems that we usually ignore board.fields.viewIds if it is empty. I think this field is empty until you choose to sort the views
- if the board block isn't loaded, we were not showing the views
So, this WAS working sometimes, for example if you had done something to load the database board block and had also sorted its views at some point in time.
=> fix views not appearing in the sidebar

hooks/useSpaces.tsx
To reproduce, try creating a new space and then visit Settings. The settings wouldn't appear because 'memberSpaces' had not been updated in the component. TUrned out we had useMemo'd the value in SpacesProvider and it wasn't updating when the user roles were changed.
And we would hide the space settigns if the space was not listed inside 'memberSpaces'
=> fix space settings not refreshing

.github/workflows/deploy_staging.yml, .github/workflows/destroy_staging.yml
When working on ceramic fixes, it's difficult to debug staging as concurrent pushes to staging by other developers block the deploy
This ensures ceramic staging only deploys if the tag is provided
=> Add conditional ceramic deploy tag for staging

lib/databases/cardFilter.ts
This code was added in a large refactor a year ago: https://github.com/charmverse/app.charmverse.io/commit/13ae5d2ba81e668edf6d4f495b62711077ee99d8. It seems unintuitive to include values that are empty when I'm looking for "is" or "starts with". This also doesn't match Notion UX
=> filter should not include empty values

components/common/DatabaseEditor/components/viewHeader/filterComponent.tsx, components/common/DatabaseEditor/components/viewHeader/filterEntry.tsx
Makes the filter input more responsive. Wait 100ms instead of 1000ms to update.
Text input would lose focus after the state updates. This was because a key was being generated that icnluded the input value. So the key would change every time state is updated.
=> Improve responsiveness when filtering database views

components/[pageId]/DocumentPage/hooks/usePageSidebar.tsx, components/common/CharmEditor/components/@bangle.dev/react/NodeViewWrapper.tsx, components/common/CharmEditor/components/@bangle.dev/react/node-view-helpers.tsx, components/common/CharmEditor/components/nestedPage/components/NestedPage.tsx
Another reason to move away from Bangle.dev @Devorein : it is written for React 16. Ever since React 18 implemented async updates, I had to hack it myself adding flushSync. This makes rendering the page very slow as we call that for each node view. I think this other lib might be a better approach, and it just exposes some hook sthat we can mostly replace the ones from Bangle.dev. Instead of rendering each node view one at a time, it renders them all at once I think: https://github.com/nytimes/react-prosemirror/tree/main
=> improve document performance

components/[pageId]/DocumentPage/DocumentPage.tsx, components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewards.tsx, components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx, theme/print.scss
I removed a rule (::before) which I think was used for the old bullet list styles, not sure what else it was used for. This seemed to be messing with the layout with our new bullets at least
=> fix printing for PDFs

theme/@bangle.dev/styles.scss
I noticed an extra set of bullet icons appearing in the left margin on someone's page. It's the first time i noticed it, but we don't need these styles anyway. the correct styles are defined in czi-list.scss and czi-indent.scss
Bullets still look fine in storybook:
=> remove extra bullet styles from bangle.dev

components/settings/integrations/components/Boto/BotoSettings.tsx, components/settings/integrations/components/CollabLand/CollabLandSettings.tsx, components/settings/integrations/components/Github/GithubSettings.tsx, components/settings/integrations/components/IntegrationContainer.tsx, components/settings/integrations/components/KYC/KYCSettings.tsx, components/settings/integrations/components/Snapshot/SnapshotSettings.tsx
Simplify and standardize the Integration settings for non-admins. They just don't get to expand the views, but they can see what has been connected. In the future we might add a summary
=> disable integration settings for non-admins

components/common/form/InputSearchMember.tsx
Card:
https://app.charmverse.io/charmverse/when-adding-a-person-to-a-card-property-it-doesnt-actually-remove-the-original-person-1513873279848057
The `value` state was not synced with the `defaultValue` state. Only after the user closes the dropdown the component was rerendered and the value was shown correctly.
Remove the `value` state, since we have the `defaultValue` which should be the same thing.
=> Fix user select property

components/common/form/hooks/useFormFields.ts, components/members/hooks/useRequiredMemberProperties.ts, components/rewards/components/RewardApplicationPage/components/RewardSubmissionInput.tsx, components/settings/profile/components/SocialInputs.tsx, components/settings/profile/components/UserDescription.tsx, components/settings/profile/components/UserDetailsForm.tsx, components/settings/projects/components/ProjectForm.tsx
Card:
https://app.charmverse.io/charmverse/edit-member-profile-cursor-jumps-to-end-of-text-everytime-you-make-an-edit-5293657149451723
Info:
- components were rerendering because of getValues() and cursor was jumping.
- as a best practice we should use watch() in a component and getValues() only inside functions when we need to get once the values.
- I changed it in all the places I saw it happening.
=> Fix forms values

components/common/DatabaseEditor/components/table/tableHeader.tsx, components/common/DatabaseEditor/store/cards.ts
React was not updating the component that was consuming the sorted cards.
The cards array was sorted and the original array was overwritten and that means no rerender.
Card:
https://app.charmverse.io/charmverse/sort-doesnt-work-on-databases-6821939509445178
=> Fix sort databases

components/common/DatabaseEditor/components/viewHeader/RelatedPagesSelect.tsx
Fix:
- TextField wasn't present and AutoComplete can't render without it
- Added types for Autocomplete 
Card: https://app.charmverse.io/charmverse/database-filter-relational-property-doesn-t-work-1421088646173554
=> Fix for filter database relation property

lib/notifications/cards/getCardNotifications.ts, lib/notifications/documents/getDocumentNotifications.ts, lib/notifications/forum/getForumNotifications.ts, lib/notifications/mailer/sendNotificationEmail.ts, lib/notifications/polls/getPollNotifications.ts, lib/notifications/proposals/getProposalNotifications.ts, lib/notifications/rewards/getRewardNotifications.ts
Issue:
- Users see Updates for pages that are deleted, don't exist anymore or they don't have access to the space anymore.
Fix:
- filter notifications that have a page or post relation, deletedAt is null and the user has a spaceRole
=> Filter notifications to be accessible for a user

components/common/DatabaseEditor/components/centerPanel.tsx, components/common/DatabaseEditor/components/kanban/kanban.tsx
Issue:
- Drag and drop in the same column is not working properly. The cardOrder is updated, but the cards positioning inside the group is not updated because it is not taking into consideration the cardOrder.
More info:
- before it was working because we were overriding the cards object when sorting. The cards should not be mutated, it should get the cardOrder array and sort it by that.
- this was the PR that fixed sorting but broke the cards order
https://github.com/charmverse/app.charmverse.io/pull/4059/files
Solution:
- Send sortedCards to the group
=> Fix card reordering

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluationContainer.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/RubricResults.tsx, package.json
We were displaying "Decline" when someone wanted to approve rubric criteria:
https://www.loom.com/share/e990952f059341f3a98c7becce6374c9?sid=caa4defc-cbe2-4fbe-ba12-7d8890ae3a7f
I did a bit of cleanup too. In general we should try not to write components that serve so many use cases, and instead compose them into what we need. for instance the component that rubric uses shouldn't include any appeal logic.
=> fix evaluation button

__integration-tests__/server/pages/api/proposals/evaluations/[id]/appeal/reset-review.spec.ts, __integration-tests__/server/pages/api/proposals/evaluations/[id]/appeal/submit-result.spec.ts, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluationContainer.tsx, components/settings/proposals/components/EvaluationDialog.tsx, lib/proposals/__tests__/goBackToStep.spec.ts, lib/proposals/__tests__/submitEvaluationAppealResult.spec.ts, lib/proposals/__tests__/submitEvaluationResult.spec.ts, lib/proposals/getProposal.ts, lib/proposals/goBackToStep.ts, lib/proposals/interfaces.ts, lib/proposals/mapDbProposalToProposal.ts, lib/proposals/submitEvaluationAppealResult.ts, lib/proposals/submitEvaluationResult.ts, package.json, pages/api/proposals/[id]/reset-review.ts, pages/api/proposals/[id]/submit-result.ts, pages/api/proposals/evaluations/[id]/appeal/reset-review.ts, pages/api/proposals/evaluations/[id]/appeal/submit-result.ts, scripts/migrations/2024_05_21_createProposalEvaluationAppealReviews.ts
1. We were using the `ProposalEvaluationReview` model previously with appeal: true, this PR makes the necessary changes to support a different table just for appeal reviews
=> Refactored proposal evaluation appeal reviews model

components/[pageId]/DocumentPage/components/PageTitleInput.tsx, components/_app/OpenGraphData.tsx, components/common/PageLayout/PageLayout.tsx, components/common/PageLayout/SharedPageLayout.tsx, components/common/PageLayout/components/CurrentPageFavicon.tsx, pages/[domain]/[pageId].tsx, pages/_document.tsx
This removes a redundant meta description tag, and also the default description in case that may be confusign Google crawler, making it think our pages are duplicate
=> Remove duplicat meta description tags

lib/google/__tests__/loginWithMagicLink.spec.ts, lib/google/loginWithMagicLink.ts
If a profile has been created using an email for notifications, we should pick it up when someone logs in via magic link
=> Connect notification email

lib/databases/proposalsSource/__tests__/updateBoardProperties.spec.ts, lib/databases/proposalsSource/updateBoardProperties.ts, scripts/migrations/2024_05_30_deleteRubricCriteriaTotalProperties.ts
* Previously we used to get rubrics from deleted proposal evaluations, now we skip them
=> Fixed proposal rubric criteria total score columns

components/common/DatabaseEditor/components/ViewFilterControl.tsx
Task:
https://app.charmverse.io/charmverse/database-filters-are-not-responsive-on-mobile-48855657842594336
Fix:
Let the user scroll left-right in the popover so he can access all the filters.
=> Fix: Database filters are not responsive on mobile

components/common/PageActions/utils/databasePageOptions.ts
Fix:
- empty string properties were created as dates instead of text properties
- strings with a number at the end were converted to dates instead of text properties e.g. "Season 1"
- All titles were transformed into Form Response
=> Fix csv import issues

components/common/DatabaseEditor/components/viewTitle.tsx
when navigating between databases, the description does not update immediately. You will see teh description of the previous page sometimes.
Bug on Discord: https://discord.com/channels/894960387743698944/1249742974196121610/1249742974196121610
=> reset view description whenever board changes

lib/mux/updateAllowedPlaybackDomains.ts, lib/spaces/updateSpaceCustomDomain.ts, scripts/mux.ts
i needed a way to update the list of referrers that did not throw an error. but i do want it to throw an error in Prod if we can't actually update the list for all domains
we were also not logging the error in prod
=> limit the number of domains sent to Mux

theme/index.ts
The grey text is hard to read. This chang erequested by Chris. This little setting took me a while to find!
=> remove translucent effect on disabled text

background/cron.ts, background/tasks/syncOptimismReviews.ts
This is a special request from OP, that the votes from one step should transfer to the next step. I am hoping that, by running every 15 minutes and since there r 5 reviewers in Full Review, we dont need to worry about marking the whole step completed
=> sync reviews for optimism evaluations

lib/notifications/proposals/createProposalNotifications.ts
[Card](https://app.charmverse.io/charmverse/verify-notifications-are-still-being-sent-when-a-proposal-has-hidden-steps-6495614505402232)
=> Send notification to authors for proposal passed/failed and rewards passed events in private evaluations

components/rewards/components/RewardProperties/CustomPropertiesAdapter.tsx, components/rewards/components/RewardProperties/RewardPropertiesForm.tsx
[Card](https://app.charmverse.io/charmverse/if-a-milestone-is-created-via-proposal-put-the-proposal-title-as-a-custom-property-5483940115308825)
=> Add proposal link as rewards table custom property

components/common/DatabaseEditor/components/kanban/KanbanGroupColumn.tsx, components/common/DatabaseEditor/components/kanban/kanban.tsx, components/common/DatabaseEditor/components/kanban/kanbanCard.tsx, components/common/PageActions/KanbanPageActionButton.tsx, components/common/PageActions/components/CopyPageLinkAction.tsx, components/common/PageActions/components/DatabaseRowActionsMenu.tsx, components/rewards/RewardsPage.tsx, components/rewards/hooks/useRewardsBoardAdapter.ts
[Card](https://app.charmverse.io/charmverse/reward-applicants-board-view-user-should-be-able-to-filter-by-custom-properties-9543093759683579)
=> Show and filter custom properties in reward applicants board view

components/[pageId]/DocumentPage/DocumentPageProviders.tsx, components/[pageId]/DocumentPage/DocumentPageWithSidebars.tsx, components/[pageId]/DocumentPage/hooks/usePageSidebar.tsx, components/common/PageLayout/PageLayout.tsx, components/rewards/NewRewardPage.tsx, components/rewards/components/RewardApplicationPage/RewardApplicationPage.tsx
The new logic does two basic things:
1) if workflow sidebar is open, don't show navigation sidebar
2) manually toggling navigation sidebar will close the workflow sidebar so that navigation can be seen
The goal is to show the user only one sidebar a time when looking at a proposal or reward. The left nav sidebar adds a lot of noise that takes away from the main content and the workflow sidebar. We wanted to emulate UX from Notion desktop screens where opening one sidebar collapses the other side (for example when opening pages on a database).
This was tricky to implement. At first I thought I'd use a useEffect inside PageLayout and add some dependency between the two sidebar states. But we don't know if a sidebar was toggled due to user action or just some logic.
=> collapse navigation bar if workflow sidebar is open

components/common/form/hooks/useFormFields.ts
In a cleanup of mine, I was changing how we use form state and incorrectly switched the logic for !isValid to isValid: https://github.com/charmverse/app.charmverse.io/pull/4052/files#diff-71448b12b7030b89c924058f05520978012032beef6f5fe18441cc7a7ca1522fR106
=> allow saving member onboarding form

components/common/DatabaseEditor/components/properties/UserSelect.tsx, components/common/form/InputSearchMember.tsx
This is a fix for cases like AddPermissionsPageForm which does not update the defaultValue when onChange handler is called. This input should maintain its own internal state of what is selected or else require a 'value' prop
Reverts charmverse/app.charmverse.io#4032 and also fixes original issue in a different way
=> Revert "Fix user select property"

.cdk/ProductionStack.ts, .cdk/StagingStack.ts
apps are running out of space when installing inside Docker.
eb-engine.log:
```
Pulling stg-sockets     ... extracting (42.7%)
Pulling stg-webapp      ... extracting (43.0%)
Pulling stg-sockets     ... extracting (43.0%)
Pulling stg-webapp      ... extracting (43.3%)
Pulling stg-sockets     ... extracting (43.3%)
Pulling stg-webapp      ... extracting (43.5%)
Pulling stg-sockets     ... extracting (43.5%)
Pulling stg-webapp      ... extracting (100.0%)
Pulling stg-sockets     ... extracting (100.0%)
ERROR: for stg-sockets  failed to register layer: Error processing tar file(exit status 1): mkdir /app/node_modules/@multiformats/multiaddr-to-uri/node_modules: no space left on device
ERROR: for stg-webapp  failed to register layer: Error processing tar file(exit status 1): mkdir …
```
=> increase root volume size for deploys

apps/connect-api/src/server.ts, lib/session/getIronOptions.ts
we used to do this, until Wix would clear all cookies. but now we don't use Wix and we need cross-subdomain cookies
People might get logged out of CharmVerse, i'm not really sure.. hopefully this new cookie just overrides the subdomain one. but shouldn't be a big deal TBH and now's a good time to try it instead of during the day in western hemisphere
=> set cross-subdomain cookies in production

apps/connect-api/src/server.ts, lib/session/getIronOptions.ts
My update last night broke logging in/out with custom domains. we'll need a better fix but not sure what that is yet. It would be easier if we can get the origin header on the request
=> Session domain setting

.github/workflows/test_and_deploy.yml, apps/connect-api/package.json, apps/connect/next.config.js, apps/connect/package.json, scripts/query.ts
This should speed up everyone since we're now building and uploading a Docker image while tests run. And further, the Connect app doesn't need to wait for other tests
I think the next big win would be to deploy smaller Docker images, or find a way to exclude source code / node modules
=> optimize test and deploy ci

components/[pageId]/DocumentPage/DocumentPage.tsx, components/rewards/NewRewardPage.tsx, components/rewards/components/RewardProperties/CustomPropertiesAdapter.tsx, components/rewards/hooks/useRewardsBoardAdapter.ts
it was showing up on reward templates. i figure lets not even show it unless there is a proposal/ this is actually a milestone
=> only show the application property on a reward if a link exists

components/common/form/fields/ProjectField/ProjectFieldAnswer.tsx, components/common/form/fields/ProjectField/ProjectForm.tsx, components/common/form/fields/ProjectField/useProjectUpdates.ts, lib/projects/constants.ts, lib/proposals/__tests__/validateProposalProject.spec.ts, lib/proposals/getProposalErrors.ts, lib/proposals/validateProposalProject.ts
I figured out if i just update the SWR cache for 'useGetProjects' then i dont have to refresh so much. One thing that is kind of concerning is that this data is only relevant to the proposal owner. But I think it should be fine, even if you're editing your own team member profile on someone else's proposal since that cache is only used when adding members or changing the project.
=> update the cache of projects when using project form

charmClient/hooks/projects.ts, components/common/form/fields/ProjectField/ProjectFieldAnswer.tsx, components/common/form/fields/ProjectField/ProjectForm.tsx, components/common/form/fields/ProjectField/useProjectUpdates.ts
This works because the project is always loaded in the form state from the proposal request, so we don't actually need to wait for the user's list of projects. That is only necessary to populate the dropdowns for selecting/adding projects and team members
=> allow anyone to view a project as part of a proposal

package.json
fixes issue that code is not linted on commit. the connecpt api may no longer be linted but seems like a different issue is needed for monorepos: https://github.com/lint-staged/lint-staged#how-to-use-lint-staged-in-a-multi-package-monorepo
at the moment, i'd rather bring back husky for the code we work on the most
=> fix linting for main app

components/common/PageActions/components/ForumPostActionList.tsx, pages/api/proposals/[id]/template.ts
Fixes bug: when template is required but empty by default, the "Publish" button does not know that a template is selected. One way to reproduce this is to 'convert from post' but could also just click "Create" without selecting a template.
Notes: navigating a way thereby getting SWR to update the page fixes the issue on its own
By broadcasting a websocket event we update the page state which is used to disable the Publish button
=> fix bug when selecting a template that is required

__e2e__/proposals/structuredProposalWithProject.spec.ts, components/common/form/FormField.tsx, components/common/form/fields/ProjectField/ProjectFieldAnswer.tsx, components/common/form/fields/ProjectField/ProjectFieldEditor.tsx, components/common/form/fields/ProjectField/ProjectForm.tsx, components/proposals/hooks/useProjectForm.ts, components/proposals/hooks/useProposalFormAnswers.ts, components/settings/projects/ProjectsSettings.tsx, components/settings/projects/components/FieldAnswers.tsx, components/settings/projects/components/FieldsEditor.tsx, components/settings/projects/components/ProjectForm.tsx, components/settings/projects/components/ProjectMemberFields.tsx, lib/projects/createProjectYupSchema.ts, lib/projects/formField.ts, lib/proposals/createDraftProposal.ts, lib/proposals/form/getProposalFormFields.ts, lib/proposals/getProposal.ts, lib/proposals/validateProposalProject.ts
The "defaultRequired" override on form inputs was causing unexpected behavior for me. There should be no need for low-level components to be "smart" or have special overrides if the form state at the top of heierarchy is set up correctly.
=> Simplify project form inputs - remove "defaultRequired"

components/common/SpaceAccessGate/components/TokenGate/TokenGateConditions.tsx, components/common/TokenGateModal/components/TokenGateTokens.tsx, components/common/TokenGateModal/components/TokenGateTokensFields.tsx, components/common/TokenGateModal/hooks/useTokensForm.tsx, components/common/TokenGateModal/utils/getTokensAccessControlConditions.ts, components/common/TokenGateModal/utils/utils.ts, lib/tokenGates/humanizeConditions.ts, lib/tokenGates/interfaces.ts, lib/tokenGates/validateTokenGateCondition.ts
Allow calling a custom contract method to check a wallet's balance. This enables one space to use their staking contract: https://sepolia.etherscan.io/address/0x55105f426126952ac6d9c2e7e72c7451318617d3#code
Form:
Preview:
=> add a new token gate option for contract method

components/settings/invites/components/TokenGates/components/TokenGateModal/components/TokenGateBlockchainSelect.tsx
I checked and all the token gate options that use TokenGateBlockchainSelect specify the chains they want, except for NFT and tokens, which we can use RPC urls for.
=> allow using other chains for token gating

components/common/PageLayout/PageLayout.tsx, components/common/PageLayout/SharedPageLayout.tsx
When using shared page layout for charmverse users that don't belong to a space, we should collapse the sidebar when proposal or rewards sidebar is open:
=> collapse sidebar in shared layout

lib/databases/proposalsSource/__tests__/getCardProperties.spec.ts, lib/proposals/rubric/__tests__/aggregateResults.spec.ts, lib/proposals/rubric/aggregateResults.ts
Update to the way we calculate for "proposalEvaluationAverage": https://github.com/charmverse/app.charmverse.io/blob/main/lib/databases/proposalsSource/getCardPropertiesFromRubric.ts#L105
We are supposed to sum all the scores and divide by number of users, not the number of scores.
=> change average calculation for rubrics

components/rewards/components/RewardAmount.tsx
I think this was a bug introduced in my cleanup PR: https://github.com/charmverse/app.charmverse.io/commit/010eb94948ead3786bbe3d38d754981ab1b8cd06
I just forgot to remove part of the old code
=> fix duplicate token label

@connect-shared/lib/projects/fetchProject.ts, apps/connect/app/page.tsx, apps/connect/components/projects/[id]/ProjectDetailsPage.tsx, apps/connect/components/projects/edit/EditProjectPage.tsx, apps/sunnyawards/app/page.tsx, apps/sunnyawards/components/projects/[id]/ProjectDetailsPage.tsx, lib/farcaster/loginWithFarcaster.ts
App was crashing because of some project members not having a farcaster id in the db.
Also, it was hard to debug production because of too many error messages like "Client Error: You are not logged in. Please try to login ". I removed the getCurrentUserAction and I just get the session since it is easier and doesn't throw an error.
The error mentioned above should be a warning for users that are taking an action and they are not logged in.
- fid can be undefined. Let's stop using assertions since they are getting in the way of finding the real issue
- when we just want to see that the user exists, let's use getSession() since it returns the user id
=> Fix app crashes without a farcaster id

lib/proposals/rubric/__tests__/upsertRubricCriteria.spec.ts, lib/proposals/rubric/upsertRubricCriteria.ts
When creating a proposal from a template, the criteria would be out of order
=> Retain rubric criteria order when using proposal templates

@connect-shared/lib/farcaster/fetchUserByFarcasterUsername.ts, apps/connect/components/common/FarcasterCard.tsx, apps/sunnyawards/components/common/FarcasterCard.tsx
- Get Farcaster user from db instead of an external api 
- Don't render a link if the member does not have a farcaster username
- [Card](https://app.charmverse.io/charmverse/use-user-path-for-u-pages-on-connect-app-instead-of-looking-up-farcaster-3513535065100033)
- The farcaster API can be down and our app could crash
- The page was crashing for non existing farcaster members
=> Farcaster user from db

apps/sunnyawards/lib/projects/createProjectAction.ts
The create project action was stopping the user flow of going to success page.
The error was inside thrown by storeProjectMetadataAndPublishGitcoinAttestation and it had the message:
Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ]
=> Fix Sunny project creation failure

.gitignore
Our gitignore was not actually excluding the .ebstalks folder correctly. This should enable searching for constants inside VS Code (which ignores things ignored by .gitignore), and also make it easier to add .env files in the future.
Found a solution on this SO post: https://stackoverflow.com/questions/5533050/gitignore-exclude-folder-but-include-specific-subfolder
=> fix gitignore for deployment .env folder

lib/databases/generateCsv.ts
I'm not sure how this wasn't broken already but i couldn't export a rubric proposal because the score is a number and hence doesn't have a "replace" method inside encodeText
If you can suggest a good place to add a test, I'll do it! The generateCSV seemed to use lots of builder api's and it wasn't clear where to add a rubric score.. do we have tests for rubrics in proposal-source i could copy from maybe?
=> fix generateCSV to support numeric values

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/EvaluationsSettings.tsx, lib/proposals/applyProposalTemplate.ts, lib/proposals/getProposalTemplates.ts
There is a proposal template where the page id and proposalId are not the same. Most of our code deals with this fine, but the template dropdown was assuming we are using proposalId, so it would not show the template as being selected. If someone 'fixed' the template and selected it by proposalId, it would break other things
=> make sure to use page id when applying templates

components/common/CharmEditor/components/heading.ts, components/common/CharmEditor/components/rowActions/RowActionsMenu.tsx, components/common/CharmEditor/components/tableOfContents/TableOfContents.tsx
Not sure when we crossed wires, but we need to use the 'slugified' version of headers for links to work, whereas it was expecting the heading number.
=> fix links to headings from table of contents

components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx, hooks/useWeb3Account.tsx
If you're not on a supported chain, when you try to log in it will log an error "No connected wallet detected. This is required to proceed." and not show the user anything. I did some tests and the sign-in works even if chain id is undefined. It seems to onyl be necessary for creating signatures that can be played on a specific network. For log in tho, we don't really care
I left the chainId in as input because it seems necessary for Gnosis + Wallet Connect to work, based on a comment inside the useEffect? But more info would be great
=> allow user to log in using any chain

hooks/useWeb3Account.tsx
Bug fix:
A user had logged in via Farcaster, but found that if they had a wallet connected already, then CV would log them out if they switched the wallet. So we had some logic that was only supposed to happen if you "logged in" with wallet, but our logic to determine your login method was flawed.
After talking w/Chris we just remove the feature that logs people out automatically by switching their wallet.
=> dont log out users automatically when switching web3 wallets

package.json
there's no change, just loss support in node 16.  https://github.com/nodejs/undici/discussions/3076
=> upgrade undici lib

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/EvaluationsReview.tsx, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/RubricEvaluation.tsx
Bug:
if a proposal is updated in a different view, it can reset the form of a reviewer submitting rubric evaluation
Solution:
There's really no need to refresh the answer state after being loaded, afaict, but we are getting them from the proposal which we do keep up-to-date. Also, for some reason the issue only happens if there was something changed in the proposal. It could just be changing the reviewer list on a different evaluation step
For now, i just made it so that we do not refresh the answers memo'd state. It's been a long time since this code was written, but i think that was the original intention
=> do not refresh rubric review any time the answers are refreshed

components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx, lib/forms/upsertProposalFormAnswers.ts, lib/forms/validateAnswers.ts, lib/proposals/getProposalErrors.ts, pages/api/proposals/[id]/publish.ts
we were filtering out form fields if there was no matchign answer, subverting the 'required' property. I'm not sure how users got past this in draft state though cuz the UI form was still correctly checking for answers
=> require all fields to be answered when publishing a proposal

apps/connect/app/page.tsx, apps/connect/middleware.ts, apps/sunnyawards/app/page.tsx, apps/sunnyawards/middleware.ts
Before: if you had an invalid user id in your session, it would keep trying to redirect you to /profile, which blows up cuz the user doesn't exist
After: we check that the user actually exists, and we only do redirect to /profile in one place (does'nt need to be in the middleware)
=> gracefully handle invalid user session cookie

.github/actions/build_app/action.yml, .github/workflows/deploy_farcaster.yml, .github/workflows/deploy_scoutgame.yml, .github/workflows/deploy_sunnyawards.yml, apps/farcaster/lib/postCreateCastMessage.ts
Uses git log instead of hashed files. Idea came from https://github.com/actions/runner/issues/1840#issuecomment-2094847172
=> test a faster way to generate cache keys for CI

apps/sunnyawards/lib/projects/createProjectAction.ts, apps/sunnyawards/lib/projects/editProjectAction.ts
If Gitcoin throws, it shouldn't bug application creation / editing
=> Add catching for the gitcoin attestations

components/settings/invites/components/TokenGates/components/TokenGateModal/hooks/useCollectablesForm.tsx, lib/blockchain/updateTokenGateDetails.ts, lib/utils/async.ts, lib/utils/numbers.ts
Issue: TokenId can be any string. If it's not a number the whole function crashes.
Fix:
- validate token id to be a bigint before the user saves his token gate
- Don't crash all the token gate list and show only the ones that are valid (by using allSettled)
=> Fix token gate crash

lib/farcaster/loginWithFarcaster.ts
User has a Charmverse user with a wallet and a fid. 
User tries to login with fid that is connected to the above user but it's different then the above fid.
Result: the API throws a prisma error since you can't create an farcasterUser if that user already has a farcasterUser.
Solution:
Ignore the above user and create another one with a farcasterUser.
=> Fix sunny farcaster login when user has multiple user accounts

lib/databases/__tests__/generateCsv.spec.ts, lib/databases/generateCsv.ts
Database csv export was broken because of multiline text card properties
Solution is to use csv-stringify
Future considerations:
Make the below function faster.
`getCardPropertiesFromProposals` function from lib/databases/proposalsSource/getCardProperties.ts file, takes 10 seconds locally to run.
To be more precise
```
const proposalPages = await prisma.page.findMany({
where: {
spaceId: space.id,
type: 'proposal',
proposal: {
archived: {
not: true
},
status: {
not: 'draft'
}
},
deletedAt: null
},
select: pageSelectObject
});
```
=> Fix db csv export

components/common/form/fields/TextInputField.tsx
=> fix blue links in disabled input

components/common/PageLayout/components/Sidebar/components/PageNavigation/PageNavigation.tsx, pages/api/optimism/projects/index.ts
The latest TreeView throws an error if any item id is not unique. This can happen when you have a favorate page that is also nested under another favorite page. I tried adding unique id's to all items but it doesn't seem to work right unless item.id is used... which can break a lot of assumptions so for now i am just filtering out duplicates :P
=> handle new error with TreeView

theme/index.ts
It seems to require moer fields to be defined if you want to use custom colors in the Button component
=> update colors to work with new MUI

.ebstalk.apps.env/scoutgame.env
Github wasn't working because the base url was missing in redirect uri. This should fix it
=> Add missing domain env var

apps/scoutgamecron/jest.config.ts, apps/scoutgamecron/package.json, apps/scoutgamecron/src/tasks/processPullRequests/__tests__/processClosedPullRequest.spec.ts, apps/scoutgamecron/src/tasks/processPullRequests/__tests__/processMergedPullRequest.spec.ts, apps/scoutgamecron/src/tasks/processPullRequests/getPullRequests.ts, apps/scoutgamecron/src/tasks/processPullRequests/getRecentPullRequestsByUser.ts, apps/scoutgamecron/src/tasks/processPullRequests/processClosedPullRequest.ts, apps/scoutgamecron/src/tasks/processPullRequests/processMergedPullRequest.ts, apps/scoutgamecron/src/testing/database.ts, apps/scoutgamecron/src/testing/generators.ts, apps/scoutgamecron/src/testing/numbers.ts, packages/scoutgame/src/utils.ts, scripts/exportGithubCommits.ts
- consider streaks across weeks, not just the active week
- we should show builder events based on the merge date, but calculate streaks based on the created date of the PR
=> Updates to Gem calculations

apps/scoutgame/app/api/connect-github/callback/route.ts, apps/scoutgame/app/api/session/refresh/route.ts, apps/scoutgame/lib/session/authorizeUserByLaunchDate.ts, apps/scoutgamecron/src/tasks/processPullRequests/index.ts, packages/scoutgame/src/scripts/uploadNFTArtwork.ts
I duno really how to test this, but we know that it's best to tell Prisma what fields you want or else it will complain when the DB schema is out of sync with its own.
=> use select on important queries to avoid db breakages

apps/scoutgame/lib/builders/getSortedBuilders.ts, apps/scoutgame/lib/builders/getTodaysHotBuilders.ts, apps/scoutgame/lib/builders/getTopBuilders.ts, packages/scoutgame/src/builderNfts/__tests__/registerBuilderNFT.spec.ts
Removing a new condition about contract address for builder NFTs, which broke some tests.. but there's a lot of places we have to look for NFT by season, it's much easier to just make sure we configure the seasons correctly. So i am removing the additional condition
This also fixes tests on registerNFt that were broken because they were trying to create a wallet client
=> Fix tests for scoutgame

apps/scoutgame/components/common/WalletLogin/WagmiProvider.tsx
The examples from Rainbowkit and Wagmi create config and query client outside of React components:
https://wagmi.sh/react/getting-started
https://www.rainbowkit.com/docs/installation
=> Fix page crash: dont use state to capture Wagmi config

apps/scoutgame/components/common/DynamicLoading.tsx, apps/scoutgame/components/common/ScoutButton/ScoutButton.tsx, apps/scoutgame/package.json, apps/scoutgame/tsconfig.json
This also fixes an issue when closing RainbowKit modal, you wouldn't be able to open it again because the ScoutButton's state was not being updated. (I really wish Rainbow kit offered event callbacks instead, which is why i'm using useEffect to watch for changes).
=> Show loading state while Rainbow kit loads

apps/scoutgame/components/common/WarpcastLogin/FarcasterModal.tsx, apps/scoutgame/components/common/WarpcastLogin/WarpcastLogin.tsx
throws an error because we don't have "farcaster.main" in our theme for SG. Aggred w/valentin there's no need to import the component from connect-shared, as we're gonna stop using that lib eventually
=> fix login via Warpcast on sg

lib/discord/collabland/verifyDiscordGateForSpace.ts
About a year ago, i added a condition for Collabland, trying to differentiate between spaces that had Discord via Game7 vs Collabland. But it was incorrect, and basically any collabland space that did not have a super api token would fail (but super api tokens are generated for Game7, so i think the logic was inverted)
https://github.com/charmverse/app.charmverse.io/pull/1794/files
=> fix collabland check

apps/scoutgamecron/package.json, apps/scoutgamecron/src/scripts/processPullRequests.ts, apps/scoutgamecron/src/tasks/processPullRequests/getPullRequests.ts, apps/scoutgamecron/src/tasks/processPullRequests/gqlClient.ts, apps/scoutgamecron/src/tasks/processPullRequests/index.ts
Basically, only process 100 repos at a time. Previously, we waited to retrieve all PRs before processing any and if we got rate limited, it would not save anything. But now we have 53k repos. The code's not beautiful, but we might be optimizing a lot in the next few days.
=> optimize saving github events

apps/scoutgame/lib/builders/getSortedBuilders.ts, apps/scoutgame/lib/builders/getTodaysHotBuilders.ts
We want to always show same gem counts to be consistent
=> retrieve gems collected from this week in the Scout page

apps/scoutgame/app/api/farcaster/user/route.ts, apps/scoutgame/components/common/NFTPurchaseDialog/NFTPurchaseDialog.tsx, apps/scoutgame/components/common/NFTPurchaseDialog/components/NFTPurchaseForm.tsx, apps/scoutgame/components/common/NFTPurchaseDialog/components/SuccessView.tsx, apps/scoutgame/components/common/ScoutButton/ScoutButton.tsx, apps/scoutgame/hooks/api/builders.ts, apps/scoutgame/hooks/api/farcaster.ts, apps/scoutgame/lib/builders/getLeaderboard.ts
- load the correct farcaster username when sending a cast
We could alternatively refresh the user's profile regularly, but in the future, not everyone is required to have farcaster and/or we may let u customize your username. in that case, we probably will need to retrieve your farcaster username anyway unless we start storing it someplace else
=> check the users farcaster profile before sending them a mention

apps/scoutgame/components/common/WarpcastLogin/WarpcastLoginButton.tsx
Sometimes the request to alchemy times out / fails to load, can't figure out why. I tested with a fake URL and Farcaster does retries, but the user just sees an ugly message. so now ask the user to try again
Discord: https://discord.com/channels/894960387743698944/1295166542056652842
=> ask user to try again if warpcast log in fails

components/[pageId]/DocumentPage/DocumentPage.tsx, components/common/form/FormFieldAnswers.tsx, stories/FormFields/FormFields.stories.tsx
if you're an admin, the field will not be disabled and we'll show u the input, which depends on the author being connected to the farcaster account
=> show op profile if you are not the author

components/common/Icons/VisibilityIcon.tsx, lib/databases/getSubtree.ts
I noticed that for public boards, we are sharing all the blocks even if you filtered them. This PR utilizes the logic for a "locked" board to reduce the data we return if you also just don't have edit permission.
=> filter hidden blocks and properties if you do not have edit access to a proposal source board

components/common/DatabaseEditor/components/properties/TagSelect/TagSelect.tsx, components/common/DatabaseEditor/components/properties/UserSelect.tsx, components/common/form/InputSearchMember.tsx
it seems that the onClose/onBLur handlers get called before the component can emit the updated values. I guess this was when we updated MUI. The proper fix is to probably not switch the components we are using when it is shown/hidden, but i dont want to work on that right now
=> Fix removing properties

apps/scoutgame/components/[username]/components/PublicBuilderProfile/PublicBuilderProfileContainer.tsx, apps/scoutgame/components/common/Card/BuilderCard/BuilderCard.tsx, apps/scoutgame/components/common/Card/BuilderCard/BuilderCardStats.tsx, apps/scoutgame/components/profile/components/ScoutProfile/ScoutProfile.tsx, apps/scoutgame/lib/builders/getSortedBuilders.ts, apps/scoutgame/lib/builders/getTodaysHotBuilders.ts, apps/scoutgame/lib/builders/interfaces.ts, apps/scoutgame/lib/scouts/getScoutedBuilders.ts
[Card](https://app.charmverse.io/charmverse/change-gems-to-rank-on-nft-3690089306098805)
[Card](https://app.charmverse.io/charmverse/not-a-bug-add-tool-tips-for-stats-2546042290770323)
1. Today's hot builder carousel
2. Scout page
3. Scouted builders section on public and user profile pages
=> Show builder rank in card stats

apps/scoutgame/__e2e__/claimPoints.spec.ts, apps/scoutgame/components/claim/components/PointsClaimScreen/PointsClaimButton.tsx, apps/scoutgame/components/claim/components/PointsClaimScreen/PointsClaimScreen.tsx, apps/scoutgame/components/common/Header/Header.tsx
This test fails very often when running locally against a production build. I believe this test was flaky because the modal always exists, it's just not visible until the callback is successful.
=> make claiming points less flaky

apps/scoutgame/__e2e__/po/Utilities.po.ts
if i run tests more than once, the nft test fails becaus the pending nft was not 'cleaned up' from before. the e2e don't clean up like jest does.. but i think its also good to just use random data. This would probably affect any retries that playwright attempts
=> ranodmize the transaction hash used in e2e

scripts/migrations/2024_10_29_moveWalletAddress.ts
The core PR fails because the walletAddress is still called in one place.
=> Hide ts error for walletAddress migration

apps/scoutgame/components/common/WalletLogin/WagmiProvider.tsx, apps/scoutgame/components/common/WalletLogin/WalletProvider.tsx, apps/scoutgame/components/common/WalletLogin/wagmiConfig.ts, apps/scoutgame/components/layout/AppProviders.tsx, apps/scoutgame/next.config.mjs
- prepare the wagmi provider server side by passing an initial state
- sometimes env() lib doesn't load fast enough and we don't want to block the render just because of that. We can use, only for this case, the env var from the server.
When going to a not found page, wagmi provider blows up because of an env var not found.
=> Fix wagmi SSR and projectId not found

apps/scoutgameadmin/components/users/UserActionButton/AddBuilderModal.tsx, apps/scoutgameadmin/components/users/UserActionButton/UserActionButton.tsx, apps/scoutgameadmin/components/users/UsersDashboard.tsx, apps/scoutgameadmin/lib/users/getUsers.ts
=> Add email to admin dashboard

apps/scoutgame/app/(info)/layout.tsx, apps/scoutgame/components/common/WalletLogin/WalletLogin.tsx, apps/scoutgame/components/common/WarpcastLogin/WarpcastLogin.tsx, apps/scoutgame/components/common/WarpcastLogin/WarpcastLoginButton.tsx, apps/scoutgame/components/welcome/how-it-works/HowItWorksContent.tsx
- adds drop shadow below 'join farcaster'
- do not show wallet button as loading on page load / when its just connecting to your wallet
- fix height/width issue on iOS - seems like a safari rendering bug but i was able to reproduce and confirm the changes are required
=> Ios layout

apps/scoutgamecron/src/tasks/processBuilderActivity/__tests__/recordMergedPullRequest.spec.ts, apps/scoutgamecron/src/tasks/processBuilderActivity/recordMergedPullRequest.ts
[Card](https://work.charmverse.fyi/when-de-duping-first-contributions-worth-100-points-look-at-the-merged-at-date-and-not-created-at-6164434120491211)
=> Fix points attribution for first pr in a repo

apps/scoutgame/lib/scouts/getNewScouts.ts
=> dont count banned builder gems in new scout rank

apps/scoutgameadmin/lib/session/getAdminUser.ts, apps/scoutgamecron/src/scripts/issuePoints.ts, packages/scoutgame/src/builderNfts/purchaseWithPointsAction.ts, packages/scoutgame/src/builderNfts/syncUserNFTsFromOnchainData.ts
By selecting the fields we avoid breaking a feature if prisma knows about a field that has not been yet added to the DB (eg migration has not run yet)
=> add select statements to places where we query the scout

charmClient/hooks/proposals.ts, components/proposals/hooks/useProposalFormAnswers.ts
the issue is we need to keep the SWR state up-to-date if it is going to be immutable
When the user returns to the proposal page, the form loads with the previous state even tho SWR would refresh itself.
=> fix proposal answers again

packages/mixpanel/src/trackUserAction.ts, packages/mixpanel/src/utils.ts, packages/scoutgame/src/mixpanel/trackEventAction.ts, packages/scoutgame/src/session/interfaces.ts
Track utm_params on events. Mixpanel automatically attributes this to the user as initial properties: https://docs.mixpanel.com/docs/tracking-methods/sdks/javascript#track-utm-tags
=> track utm params in mixpanel

lib/utils/__tests__/browser.spec.ts, lib/utils/browser.ts
Exmple case: page path is "evo-labs-home-wip-19377272787222233" and the space domain is "evo-labs". we need to make sure not to mess the page path
=> fix links for custom domain

components/common/DateTimePicker.tsx, components/common/comments/CommentForm.tsx, components/common/form/hooks/usePersistantFormValues.ts, components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/components/RubricAnswersForm.tsx
[Card](https://app.charmverse.io/charmverse/resizing-window-when-evaluating-grants-removes-all-your-evaluation-scores-and-comments-3052262544901101)
This PR improves and adds the possibility to:
- save rubic answers in session storage
And fixes:
- a prop object containing a "key" prop is being spread into JSX
- disabled prop of a button received a string instead of a boolean
- element can't have ref. Add a forwardRef to your component
(The fixes can be seen in each commit)
=> Rubric score persistance

lib/gnosis/gnosis.ts
=> allow gnosis wallets on multiple chains

apps/scoutgame/__e2e__/buyNft.spec.ts, packages/scoutgame-ui/src/components/common/ScoutButton/ScoutButton.tsx
i can see that the scout button is being clicked before it's even visible. but we may need to wait until the user has a change to be loaded
=> fix flaky e2e nft tests

apps/ceramic/package.json
trying to resolve a security vuln. these version bumps are just based on dependency updates and are not really api breaking
=> update ceramic libs

apps/scoutgame/components/home/LandingPage.tsx
Sticky footer was no visible on safari.
=> Fix sticky footer on safari

packages/scoutgame-ui/src/components/common/Carousel/Carousel.tsx
Can be tested only on iPhone.
Safari on macOS does not have this issue.
=> Fix carousels with 100% height on mobile

apps/scoutgametelegram/app/(general)/layout.tsx
Tested with ngrok locally...this overflow rule doesn't seem to be necessary, and removing it fixes the issue reported here:
https://discord.com/channels/894960387743698944/1315672159494078504
I tested each of the 4 main tabs and am able to still scroll them
FWIW I still don't know why it's only in Telegram Webview. The same thing doesn't happen inside Metamask webview or the regular iOS browser. It also didn't happen if i was using my local db that had no builders/data to show. I had to use production data. And It was hard to find documentation on what might be causing the issue, so i dont know the root cause.
=> fix scrollable div on telegram app

components/_app/components/ConnectedAccounts.tsx, components/settings/account/components/NewIdentityModal.tsx, components/settings/account/components/TelegramLoginIframe.tsx
=> Fixed telegram login issue

components/common/CharmEditor/components/listItem/commands.ts, lib/permissions/bounties/__tests__/computeBountyPermissions.spec.ts, packages/charmeditor/src/extensions/listItem/toggleList.ts
remove redundant words in comment
=> chore: remove redundant words in comment

components/common/PageLayout/PageLayout.tsx
=> Added scoutgame preseason 2 banner

lib/proposals/forms/__tests__/upsertProposalFormAnswers.spec.ts
adding 'createdAt' to the data model broke these tests that were asserting all the fields
=> fix answers test

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/RubricEvaluation.tsx
I believe this is why we see the error "Could not find criteria ..." sometimes. Today a user was showing us a related error: the proposal id 1d1fd249-736c-467e-8341-2070f0bcc38c has two rubric evaluation steps, the first one has 3 questions and the second has 2 questions. The frontend was sending the evaluation id of the first step, with an array of 3 answers but the 3rd result was empty, and the rubricCriteriaIds were from the second step. My theory is that the frontend loaded questions for the second step first. When the user opened questions from the first step, the answers were memoized and didn't update.
=> refresh proposal rubric answers when evaluation id changes

lib/notifications/documents/createDocumentNotifications.ts, lib/webhookPublisher/publisher.ts
=> Optimism proposal reviewer notifications

lib/notifications/proposals/createProposalNotifications.ts
The condition required private evaluations to be enabled, otherwise everyone in the space will get a notification.
This seems to have been wrong since the feature was added: https://github.com/charmverse/app.charmverse.io/commit/f3862154bb6060edc1ff229278462ce57bcd7dff#diff-133705a1ff46d0b4a6a049c073023360b8c818d0232c43217f3d32cac673c51eR272
=> only send appeal notifications to appeal reveiwers

components/[pageId]/DocumentPage/DocumentPage.tsx, components/proposals/ProposalPage/components/ProposalStickyFooter/ProposalStickyFooter.tsx
If the proposal is a draft user sees the publish button.
If the proposal has another state then draft, show the Save button.
=> Add a dummy save button to proposals

components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/RubricEvaluation/components/RubricAnswersForm.tsx
In prod I am seeing that we are sending more answers than are necessary for the evaluation  - 8 instead of 4, but there were 8 for a previous step, so I think this workaround is safe enough for now, but i think there is some issue where we are not updating state properly that could lead to other bugs.
=> Clean up answers for rubric forms

components/common/DatabaseEditor/components/table/tableHeader.tsx, lib/rewards/blocks/views.ts
=> show deleted properties for milestones

components/[pageId]/DocumentPage/DocumentPage.tsx, components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsTable.tsx, stories/ProposalsPage/ProposalRewards.stories.tsx
=> hide deleted properties in proposal milestones

__integration-tests__/server/pages/api/spaces/[id]/snapshot.spec.ts
This test relies on the snapshot service responding, which we should never do. I can't use jest mock to mock the snapshot lib because this is an integration test. Just disabling for now
=> disable snapshot test

apps/webapp/components/members/hooks/useRequiredMemberProperties.ts, apps/webapp/components/rewards/components/NewRewardButton.tsx, apps/webapp/lib/spaces/updateSpace.ts
The space form sends all fields to the backend, whether or not they appeared in the UI. 
Also, we don't need to care much if an admin sets a feature, it's more important to just disable the feature - that way when they upgrade/downgrade, it is automatically enabled.
=> allow updating space for non-gold tiers
